### PR TITLE
AP_RangeFinder: Add load .data section into PRU

### PR DESCRIPTION
**Pull request by mirkix**
I am working on a filter running inside the PRU. For that it is necessary to load the .data part into the PRU, too.

### CODE REVIEW

**Comment by magicrub** [comment]
What is this for? What filters are you working on?

**Comment by mirkix** [comment]
@magicrub Hi Tom, it is for the HC-SR04 driver running inside a [PRU](http://beagleboard.org/pru). I try to get the values of the HC-SR04 a little bit smoother.

**Comment by mirkix** [comment]
This PR change the [BBBmini](https://github.com/mirkix/BBBMINI) HC-SR04 driver only.

**Comment by lucasdemarchi** [comment]
@mirkix could you add that info to the commit message please?

**Comment by mirkix** [comment]
@lucasdemarchi Sure, done with #3529 .

**Pull request closed without merging**
