### PR TITLE
AP_GPS: Support UBX messages for dual UBLOX GPS setups.

### PR DESCRIPTION
**Pull request by andyp1per**
Add extra DOP information to UBX precision messages.
Fixes https://github.com/diydrones/ardupilot/issues/2591

### CODE REVIEW

**Comment by andyp1per** [comment]
So a couple of comments/questions:
 - I have done this for the regular UBX messages, but the same problem exists for the raw UBLOX    
   logging. Not sure whether we want to fix this or not.
 - The 4-char limitation on DF message types made it hard to pick new names for the second GPS.
   I eneded up using UBY1, UBY2, UBY3 but am open to other suggestions.

**Comment by tridge** [comment]
hi Andy,
I'm not totally sure what issue is being solved here. We already can log raw UBX messages for multiple ublox receivers, and we can differentiate them with the Instance field.
I'm guessing the problem is graphing tools? I'm normally quite sympathetic to having separate messages for each instance to keep graphing simple for users, but the UBX messages are really just debugging messages from when we were trying to work out what fields we would use to determine GPS accuracy. We've now settled on the position and velocity accuracy fields, so the UBX messages are now less important.
Rather than make this change I think we should consider redoing this UBX message logging completely, and consolidating it down to just the most useful fields, hopefully fitting it in one UBX message. Then use UBX1 for GPS1, UBX2 for GPS2 etc.

**Comment by andyp1per** [comment]
Yes, you are right - it's about graphing and being able to compare performance of different receivers. Your proposal sounds reasonable to me and I could probably cook something up. Questions:
 - How do we pick what values should be displayed? The ones that are constantly referred to on diydrones are noisePerMs and jamInd. Are there others? 
 - vDOP seems good to report since we report hdop, but maybe this should be done in the front end?
 - GPS and GPS2 have slightly different sets of values, why is this? Are these receiver specific?

**Comment by rmackay9** [comment]
I definitely agree that jamInd should be there.
As for which ones people want, you could email drones-discuss and see if anybody else has an opinion.  I would have thought that @jschall might have a view too.

**Comment by tridge** [comment]
Hi Andy,
GPS1 and GPS2 being different is a historical artifact from when I was experimenting with a home-brew RTK system. I think we should consolidate those.
I agree about asking on drones-discuss. If nobody responds then I'd say you get to pick the key ones :-)

**Comment by WickedShell** [comment]
I really think GPS and GPS2 need to merge to have the same content.

Might need input from @peterbarker but I'd like to consider passing dataflash a message object (same way we do now), with a 3 letter identifier and an instance number < 10 and have it automatically make GPS1/GPS2 etc. Could be used here, as well as with mag/imu messages as well. It's still more messages in total but it makes them more common in code without having more work to maintain them, and makes it easy for the ground tools to display them. (and works well for things like GPS that are meant to be easy to enable 3 at compile time (although in practice there are currently a couple of errors with trying to do 3).

Maybe I'm pointing out the obvious here, but hDop/vDop/Dop is determined solely by GPS satellite geometry, the only effect that a receiver has is if it can track more satellites to get a better geometry. It's worth knowing for how accurate the position report is, but its not a part of the receiver quality. This is simply my understanding (from wikipedia and some manuals), so if I'm wrong here please let me know. It is still worth knowing while you're flying though. Although we don't really use the vertical component much yet typically it'd be nice to start logging that now to get a better idea of it.

**Comment by andyp1per** [comment]
@tridge the consensus on drones-discuss is pretty much for all of the messages :-/ so we seem to be back to square one. The number of messages probably means they could be consolidated to two per GPS, but not one I think. So I'd like to propose my original fix, or a variant thereof, unless you have a better suggestion?

**Comment by WickedShell** [comment]
I'm not seeing the purpose of the ublox_instance field or ublox_instances? This is covered for you by state.instance, and you run a large risk of stopping to log the raw messages if your gps driver is ever reloaded (as nothing decrements the ublox_instances, and then you could still have a collision on the ublox_instance number). Unless you have a good reason not to state.instance should be trusted.

**Comment by WickedShell** [comment]
And actually as an addendum to the above you are now logging duplicate information. If you are going to split out the a GPS1_UBX and GPS2_UBX then the instance should be removed as now there is duplicate data.

**Comment by andyp1per** [comment]
The issue is that the instance field is not specific to UBLOX - it comes from the front-end. So you could have a UBLOX and non-UBLOX GPS but you only want to log UBX messages for the UBLOX one. So if instance 0 is non-UBLOX and instance 1 is UBLOX you still want the UBX1 messages to be logged for instance 1, so you need some notion of the "UBLOX instance" (0 in this case). There are other ways of doing this, but this seemed the cleanest.

**Comment by andyp1per** [comment]
Agreed about removing instance from the log message.

**Comment by WickedShell** [comment]
I'd actually say if your first Ublox GPS is GPS 2 then that should have the instance UBX2 stuff set for it. Thats exactly the behavior you want. It's more intuitive when reviewing logs that the instances all share common traits. Especially if you ever have to share the log with someone else who doesn't know the exact hardware setup.

The other point is that state.instance will always be correct, its very possible for your ublox_instance to become totally wrong quickly and to stop emitting any further UBX messages. As is I don't think it can go it because if the driver is ever reloaded then your logging is now incorrect, and if its reloaded again then it will stop logging.

**Comment by andyp1per** [comment]
That's fine with me. I guess I was trying to avoid a change in behaviour - but this is a change in behaviour anyway. I also was trying to make sure it worked if someone had 3 GPS's. Under this scheme we would have to add UBZ as well, maybe that's ok as well.
Not much point in working on it until @tridge or @rmackay9 indicate which way they want to go :)

**Comment by tridge** [comment]
I'm happy either way - I'll let Michael decide what he wants to do (as ublox maintainer)
Michael, mark this as reviewed once you are happy for it to go in

**Comment by WickedShell** [comment]
I'm good with it if we do away with the ublox_instance tracking stuff. We should only look at the state.instance for the logging. The tracking code would have really unpredictable behavior, and it would make more sense when reviewing the logs to look at that.

@andyp1per do you want to do the rework to remove the instance tracking and rebase or do you want me to do it?

I haven't tested it yet past reading through it, so once it's rebased I'l just give it a quick spin here, but I expect it should be fine.

**Comment by andyp1per** [comment]
I'm happy for you to do it if you have time - or I can do it when I get back from holiday. My GPS's are now on different frames so it's harder for me to test.

Andy

Sent from my iPhone

On 23 Aug 2015, at 9:47 am, WickedShell <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm good with it if we do away with the ublox_instance tracking stuff. We should only look at the state.instance for the logging. The tracking code would have really unpredictable behavior, and it would make more sense when reviewing the logs to look at that.

@andyp1per<https://github.com/andyp1per> do you want to do the rework to remove the instance tracking and rebase or do you want me to do it?

I haven't tested it yet past reading through it, so once it's rebased I'l just give it a quick spin here, but I expect it should be fine.

-

**Comment by WickedShell** [comment]
I'm still trying to get to this andy, I unfortunately don't have a second GPS with me until about a week from now, and I really want to test it with a second GPS, so my being able to rework and test it is on hold till then.

**Comment by andyp1per** [comment]
I'm back from holiday now and happy to have a look if you want. My 250mm Quad has no FC so I could easily pull the GPS off again to test.

**Comment by WickedShell** [comment]
I finally got this rebased, is #2826 The major changes are that it doesn't try to track which instance it is anymore and instead depends on state.instance which is far safer and more reliable. UBX3 is also gone in master in favor of GPA/GPA2.

@andyp1per Can you please review the changes I made and if you're good with them we can get it merged in. I'm closing this here to track it on the rebased PR (unless you want to then pull the changes in from my repo back into this PR).

**Comment by andyp1per** [comment]
Cool. And I saw the vdop addition as well which I think is good. Thanks for doing this!

**Pull request closed without merging**
