### PR TITLE
Compiler warnings

### PR DESCRIPTION
**Pull request by magicrub**
This brings the total compiler warnings from 1350 down to 800. Most of the commits are implementing AP_Math::is_equal() and AP_Math::is_zero(). I've added static functions in a new AP_Math class so it's obvious where we're calling from. the function "is_zero()" is a popular name.

### CODE REVIEW

**Comment by magicrub** [comment]
I have not yet run this in SITL to confirm nothing blows up

**Comment by magicrub** [comment]
fixing AP_Param.cpp and vector3.cpp will knock off another 100.

**Comment by magicrub** [comment]
down to 670

**Comment by magicrub** [comment]
down to 543

**Comment by magicrub** [comment]
down to 513, from here they get harder.

**Comment by magicrub** [comment]
Remaining Ardupilot warnings ~75:
- mavlink generated code
- several unused functions, I'm reluctant to nuke them
- many undeclared functions in the pde files
- a couple HAL callback pointer handling

PX4Firmware and PX4NuttX ~440

**Comment by WickedShell** [comment]
I'm pro nuke unused functions. They remain in the git history if someone needed them. But they aren't in use now, and as such they aren't necessarily kept up to date with any architectural changes, or in the reverse case can cause people to spend time in them that won't ever benefit anything in an actual build.

**Comment by magicrub** [comment]
Thanks, nuking is probably the best way forward.

Randy & Tridge,
I don't think I'll be able to work on this for the next few days so, if you
have time, can you(or anyone else) please sanity check this on SITL and
merge with master so we don't diverge too much? I reeeeeeally don't want to
handle merge conflicts on on this beast of a pull request.

**Comment by tridge** [comment]
pushed to master!
thanks so much for all your work on this Tom!

**Pull request closed without merging**
