### PR TITLE
AP_Compass: make all backends use milligauss as unit

### PR DESCRIPTION
**Pull request by guludo**
Hi guys, this PR is making all compass backends use milligauss as mag field unit in order to keep measurements consistent across different sensors and also to fix calibration issues.

This PR also fix some issues found in the code:
 - HMC5843:
   - Fix _calibrate() function
   - Fix scale factor
 - AK8963:
    - Fix where to apply sensitivity measurements: the commit message explain my reasons

I tested with the mag sensors we have here, namely HMC5883L and AK8963. After these changes and calibration through Mission Planner the reported mag field length was in accordance with my geography location for both compasses.

***I couldn't test for the other backends, so I'd be grateful if developers with other sensors could test it :)***

@rmackay9 could you take a look?

Thank you!

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by rmackay9** [comment]
I tested this on the bebop and the results were very good after I did a compass calibration using the MP.

The EKF compass variances were low and the mag field was a consistent 450 milligauss which is reasonably close to what my nearby Pixhawk reported (it reported 508).

**Comment by rmackay9** [comment]
I found during testing that the onboard compass calibration does not work reliably on the Bebop but I think this is unrelated to these changes.
To be more specific, I found that during the compass calibration the display on the MP's calibration would simply stop at 98%.  It didn't output the new offset and scaling values.

**Comment by jberaud** [comment]
I also tested on the bebop with success.

The normal calibration procedure works fine.

I haven't tested the onboard calibration but Randy, If you tell me how to
try that I'd be happy to help.

Julien

2015-10-11 9:35 GMT+02:00 Randy Mackay <notifications@github.com>:

**Comment by guludo** [comment]
@rmackay9 and @jberaud 
I just tested onboard calibration for HMC5843: the calibration was successful and the reported mag field was fine.

@jberaud you can use `magcal` command from mavproxy to use onboard compass calibration.

**Comment by rmackay9** [comment]
merged, thanks!!

**Pull request closed without merging**
