### PR TITLE
Change panic() to be a variadic function

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This allows us to use it like printf() so we can easily append more data to the error messages, like return values, extra messages, etc.

### CODE REVIEW

**Comment by tridge** [comment]
all looks good apart from the minor comments above

**Comment by lucasdemarchi** [comment]
Em 22/10/2015 18:44, "Andrew Tridgell" <notifications@github.com> escreveu:
>
> all looks good apart from the minor comments above

What about the prog_char_t? Can I go ahead and prepare a separate PR to
remove it and the _P() variants?

**Comment by tridge** [comment]
yes, I think we can get rid of prog_char_t now as a separate PR. Thanks!

**Comment by tridge** [comment]
btw, the tricky part of removing prog_char_t won't be the strings. I think it will be all the other progmem accessors, such as those in AP_Param, AP_Scheduler etc. I think we should probably do prog_char_t as one PR, but keep the progmem infrastrucure, then do separate PRs to remove the progmem infrastructure for each library, and finally when all those are done remove the progmem global handling
It is quite a lot of work, sorry!

**Comment by lucasdemarchi** [comment]
@tridge yep... lot of work, but I can do that :-).

For the content on this PR I opened another one to replace this in order not to lose the comments in the commits: #3072

**Comment by lucasdemarchi** [comment]
@tridge almost all of the removal: https://github.com/diydrones/ardupilot/pull/3082

**Pull request closed without merging**
