### PR TITLE
AC_WPNav: 3d waypoint navigation speed does not exceed _wp_speed_cms

### PR DESCRIPTION
**Pull request by jschall**
addresses #3020

### CODE REVIEW

**Comment by jschall** [comment]
@eliao what do you think?

**Comment by eliao** [comment]
Cable cam will soon use a different controller where this will no longer be an issue.  (Selfie will still use the old controller)

I can't think of a use case where someone wants ground speed instead of 3d speed.

**Comment by rmackay9** [comment]
@eliao, I think general users of Auto expect that do-set-speed defines a ground speed and that's also how it's defined in MAVLink.  Remember we also have a speed-up and a speed-down (although they can't be set through MAVLink).  I think it's confusing to have all those but then actually apply the horizontal speed to more than just the horizontal axis.

Anyway, sounds like it's not going to be an issue for Solo in any case.

**Comment by eliao** [comment]
@rmackay9  The status quo is pretty confusing.  How should a user achieve a 3d speed to a specified waypoint?

**Comment by R-Lefebvre** [comment]
I think if you need to achieve a 3D speed, it should be computed externally.  Or we add a different handling system. 

There are very many good reasons why 2D speed should be handled separately from climb rate.  Not the least of which is because climbing takes much more power than flying flat at a given speed.

**Comment by eliao** [comment]
@R-Lefebvre - we do compute it externally.  But there's no way to set it.  (besides the velocity or pos-vel controllers - but that means no decel to waypoint.  This is done by the new controller).

**Comment by jschall** [comment]
@eliao decel to waypoint with velocity or posvel should be accomplished in the companion computer. I think that's what Will is working on though.

@rmackay9 we might be able to deal with this by simply waiting until Solo implements some better controls.

**Comment by rmackay9** [comment]
I'm going to take @jschall's comment as meaning it's ok to close this.  Happy to re-open if I've misunderstood.

**Comment by eliao** [comment]
There is currently no plan to reimplement Selfie; which would be impacted by this.   cc @wsilva32 .

**Pull request closed without merging**
