### PR TITLE
Functor

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This is more a RFC than a proper pullreq because it has not been well tested. I changed rover and plane and at the same time let the current structure to support copter while it's not converted. I tested rover in sitl and build tested on x86_64 and APM2 for rover and plane.  Tests and build from others are greatly appreciated.

I split the patch for changing FastDelegate -> Functor so it's 1) there's no breakage in the middle and 2) it's possible to support non-converted vehicles. This second part has been the most boring one. I couldn't apply a final patch removing all the no unnecessary code. In the last 2 patches I show the numbers regarding the sizes for sitl and apm2.

Comments?

### CODE REVIEW

**Comment by tridge** [comment]
Hi Lucas, thanks for all your work on this!
I'm getting this in the px4-v2 build:
/home/tridge/project/UAV/APM/libraries/AP_HAL_PX4/Scheduler.cpp:258:35: error: no match for 'operator!=' in '((PX4::PX4Scheduler*)this)->PX4::PX4Scheduler::_timer_proc[i] != 0'

maybe we need a macro for declaring a NULL functor, and a macro for testing if a functor is NULL.?

**Comment by lucasdemarchi** [comment]
ahh... that's the problem then.  There's these commits "AP_HAL_AVR: Do not compare delegate to NULL".  IMO we should not be comparing to 0/NULL but rather using the bool() operator which is what these commits are doing.

The delegate stuff uses the != operator... but that actually needs an object which in the end I think it will need to construct it with the default constructor just to compare to the other object if they are the same.. As far as I saw in our code, we only need to know if it's "empty/NULL", not if it's != to another object. That's why I prefer the bool operator.

**Comment by tridge** [comment]
I've been working some more on this and fixed a few minor build issues. It has also been test flown by randy
see my functor-wip branch

**Comment by tridge** [comment]
after further testing I'm very happy with this change - I've pushed it to master
Many thanks for all your work on this Lucas!

**Comment by lucasdemarchi** [comment]
@tridge Nice and thanks for fixing up the leftovers!

**Pull request closed without merging**
