### PR TITLE
Add HAL_QURT and QFLIGHT Linux subtype

### PR DESCRIPTION
**Pull request by tridge**
This adds two new ports of ArduPilot, both to the same board but with very different approaches.
The board is the "Qualcomm Flight"
http://shop.intrinsyc.com/products/snapdragon-flight-dev-kit
The HAL_QURT port compiles ArduPilot for the Hexagon DSP chips on the board, with just a tiny shim on the ARM processors for UDP networking and storage.
The QFLIGHT HAL_Linux subtype runs ArduPilot on the ARM core, and runs a small sensor gathering library on the DSPs for sensors and UARTs.
Basic documentation for the two ports are here:
https://github.com/tridge/ardupilot/blob/hal-qurt/libraries/AP_HAL_QURT/README.md
https://github.com/tridge/ardupilot/blob/hal-qurt/libraries/AP_HAL_Linux/qflight/README.md

### CODE REVIEW

**Comment by magicrub** [comment]
Great work @tridge . Question about the DSP core: does it consume it all in
a single thread or can it run ArduPilot and still allocate serious
resources for video processing?

**Comment by tridge** [comment]
@magicrub with ArduPilot running dual-EKF we use about 25% of one DSP core. There are 3 DSP cores available. I expect video processing at the same time will be fine, especially as there is a separate GPU core as well.

**Comment by tridge** [comment]
I have re-worked the patches a bit to add some comments and remove some debug code
It should be easier to review now

**Comment by lucasdemarchi** [comment]
Hi @tridge, sorry for the delay... I was away during holidays. I did a quick look and have some comments only. We can fix them on top.

**Pull request merged**
