### PR TITLE
waf: update waf submodule to v1.8.18

### PR DESCRIPTION
**Pull request by guludo**
:-)

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Just an update or anything we need that was applied?

**Comment by guludo** [comment]
@lucasdemarchi the option `--clear-failed` for unit tests is in that release :-)

**Comment by lucasdemarchi** [comment]
Next time would be great to have this info in the commit message.

**Comment by guludo** [comment]
> Next time would be great to have this info in the commit message.

Why not already this time? :-)
I've just amended the commit.

**Comment by lucasdemarchi** [comment]
because it was already applied.

**Pull request closed without merging**
