### PR TITLE
Support BH HAT for ardupilot (rebased)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Rebase #3244 and split the commits for easy of review.

This contains the same code as before.

### CODE REVIEW

**Comment by onceme** [comment]
@lucasdemarchi

Thank you for rebasing these commits for me. Sorry I didn't know the rules well.
I have replied you about the fifo size in https://github.com/diydrones/ardupilot/pull/3244, please let me know your opinion.

Welcome any comment and thanks for that.

**Comment by lucasdemarchi** [comment]
@onceme please take a look on https://github.com/diydrones/ardupilot/pull/3299#issuecomment-162606205. I'll update this PR soon.

**Comment by onceme** [comment]
@lucasdemarchi

Thanks for the RCOutput_RGBLed, it works well. Please check [rcoutput-rgbled-for-bh.patch.txt](https://github.com/diydrones/ardupilot/files/55674/rcoutput-rgbled-for-bh.patch.txt) for adopting it to BH. The attached photo is the BH v0.2 just been produced;-)

img_1329

**Comment by lucasdemarchi** [comment]
> I have replied you about the fifo size in #3244, please let me know your opinion.

As per your comment in that PR:

> The original value is 3, as for BH, we should set this value as 5 at least. In actual fly, the remaining samples in FIFO would never pile up to 84, most of the time is 4, and 5 is the highest value I saw.

I'm turning it into 6, which makes more sense.

**Comment by lucasdemarchi** [comment]
@tridge this is reviewed. I'm only concerned with the change to RCInput_RPI, which may break navio and other rpi-based boards.  Could you give this commit a look and/or test on your navio? Otherwise I think it would be best 1) apply this PR, 2) move this specific commit to another PR and 3) use an Empty::RCInput or RCInput_UDP meanwhile.  Thoughts?

**Comment by lucasdemarchi** [comment]
Ohh... And this PR depends on #3299

**Comment by jberaud** [comment]
See my comment about the max number of samples in the mentioned PR #3339

**Comment by jberaud** [comment]
About the number of samples, I would add that more than 3ms of delay on the 1kHz timer kind of underlines a very bad real time behaviour. What info do you get from SCHED_DEBUG?

**Comment by tridge** [comment]
I've pushed to master.
I don't really like the LINUX_RC_INPUT_CHANNEL_INVALID code, as I think it is a misuse of the API, but I think we can fix this with a re-work of the RC handling that I have pending.
Nice to have another port in!

**Comment by onceme** [comment]
@tridge @lucasdemarchi

Thank you very much to accept our port.

Sorry for the LINUX_RC_INPUT_CHANNEL_INVALID, actually we also think it is ugly. However like this we wouldn't need to add new API for RCInput, and won't affect existing code by that time.

Other non-Linux boards can accept separate PWM pauses, we think Linux boards should be capable of doing this too. Could you share your idea about the "re-work of the RC handing"? or issue link? It will be our pleasure if we can give it a hand on this.

**Comment by tridge** [comment]
I needed to do something similar with DSM input for a different port (see hal-qurt branch in my tree)
I think we need to make some clearer APIs for allowing different types of RC input protocols, and these need to be exposed in the RCInput API. RC input can sometimes come in from strange sources, for example on one of my boards the same UART that handles PWM output also handes RC input (as a DSM serial stream).
I'm not actually really happy with the solution I used for my qurt board either, so I think we need to re-work it some more. I'll look at it again after the holidays

**Pull request closed without merging**
