### PR TITLE
RasPilot: Add dual-IMU support & ToneAlarm refactory

### PR DESCRIPTION
**Pull request by raspilot**
1. Add dual-IMU support. As I used to discuss at #2857 , LSM9DS0 has a same register map as LSM303D & L3GD20. So I added the code into LSM9DS0. In two weeks of testing, it works quite well.

2. ToneAlarm API refactory. Move the pwm codes to a seperated class.

By the way, I'm working on refactory the I/O MCU API. By now it's a try to add a iomcu instance. I have some work here: https://github.com/raspilot/ardupilot/tree/pr-raspilotio-refactoring. But still need some discussion about the best way to add a common I/O MCU API. Will write a issue soon.

Thanks for reviews!

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Hi @raspilot  thanks for the changes! I went through each commit to point some problems. We have some problems here mainly on how the changes were submitted. Some of the things I asked to be changed will require some more advanced git commands, but it's mainly a matter of using `git rebase -i` to adapt them. Let me know if you need help with that.

I'm adding a "need-rework" label so we know it's already reviewed but need some changes.

Last thing: when you are ready to send a new version, would be great not to send to the same branch with `push -f`, otherwise we will lose the comments above. Thanks.

**Comment by raspilot** [comment]
@lucasdemarchi Thanks for review. I will fix the issues. 
And I'm getting familiar with github.

**Comment by lucasdemarchi** [comment]
@raspilot do you want help with the rebase?

**Comment by magicrub** [comment]
still needs a rebase

**Comment by lucasdemarchi** [comment]
new version on #3730

**Pull request closed without merging**
