### PR TITLE
Enable Copter to use EKF2 via the AHRS library and improve EKF2

### PR DESCRIPTION
**Pull request by priseborough**
I'm not sure if this is the best work-around to enable use of EKF2 with Copter, but it offers a means of getting both copter, plane and rover to access the EKF's using the same library and eventually eliminate requirement for the AP_InertialNav library.

### CODE REVIEW

**Comment by tridge** [comment]
i've discussed this with Paul and he will apply some fixes

**Comment by priseborough** [comment]
I've pushed changes to address the peer review comments, namely:

Incorrect use of case statements that ignored fall-through behaviour and would have always used EKF2 for some outputs
Moved decision to use a zero origin if no origin set by the EKF up from the AHRS library to the InertialNav library where it was done previously
Modified the vertical position rate function to return a float rather than a reference to a float in line with coding convention.

**Comment by rmackay9** [comment]
I test flew this branch with both EKF1 and then again with EKF2 enabled and there were no surprises, I still have my copter.

**Comment by priseborough** [comment]
Randy's log data looks good. I've added some patches to improve behaviour when taking off from magnetic surfaces.

**Comment by priseborough** [comment]
This patch makes the tuning of the filter easier by grouping measurements (GPS, baro, magnetometer, etc) together at the nearest 20msec time interval for fusion. This means that the covariance prediction doesn't have to deal with products of very small numbers which was causing tuning problems. It does mean however that there is an increased probability that the filter will need to fuse multiple measurements on the same time step, so with both filters running we will need to watch out for frame over-runs.

**Comment by priseborough** [comment]
Branch has had a further three flight tests today, Second test went into a failsafe because EKF1 variances and health were being used by the Copter checks. This was rectified with some additional patches and test flown.

A patch has been added to enable in-flight tuning of the height fusion parameters if required. 

Variances for EKF2 have been lower than EKF1 for todays flights.

**Comment by tridge** [comment]
Hi Paul, the build is failing because of the comment termination in the comment header of NavEKF2_core::CovariancePrediction()

**Comment by priseborough** [comment]
I'll fix it up and push the fix later this morning

**Comment by rmackay9** [comment]
This branch doesn't compile by the way.  It's got a MagN undefined error.

**Comment by rmackay9** [comment]
Also I'm seeing this warning while compiling:  

%% libraries/AP_NavEKF2/AP_NavEKF2_Measurements.o
/mnt/hgfs/GitHub/rmackay9-ardupilot/libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp: In member function 'void NavEKF2_core::readIMUData()':
/mnt/hgfs/GitHub/rmackay9-ardupilot/libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp:303:49: warning: 'dtDelVel0' may be used uninitialized in this function [-Wmaybe-uninitialized]
         alpha = constrain_float(0.5f*(dtDelVel0 + dtDelVel1),0.0f,1.0f);
                                                 ^
/mnt/hgfs/GitHub/rmackay9-ardupilot/libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp:303:49: warning: 'dtDelVel1' may be used uninitialized in this function [-Wmaybe-uninitialized]

**Comment by priseborough** [comment]
I included  some patches from my wip branch by mistake. I've removed the offending patches.

I can't work out why the compiler warning. Both dtDelVel0 and dtDelVel1 are read fro the INS library at the top of that scope.

**Comment by OXINARF** [comment]
Made two comments inline. Also, there's a mixed use of IMU0/IMU1 and IMU1/IMU2 in the code comments.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
