### PR TITLE
All: New severities

### LINKED ISSUE #901: Mavlink status text sent with wrong severities
Over in QGroundControl land we just updated such that status text messages show up in different colors based on severity. When we did that we noticed that ArduPilot boards are pushing out what is thought to be low severity messages but come through as high severity alerts. The reason for this is in GCS_MAVLink.h there is a gcs_severity enum which is used to set status text mavlink message severity, when in fact the mavlink provided MAV_SEVERITY enum should be used (in common.h). If you look at the two, SEVERITY_LOW=1 maps to MAV_SEVERITY_ALERT which is the opposite of what is meant. Not sure why the mavlink enum isn't being used directly.

### PR DESCRIPTION
**Pull request by squilter**
Replaces #1414 
Fixes #901 

This one covers the whole project and applying these commits in the wrong order could mess things up.  So I have submitted only half of the commits here.  I will create a new PR with the rest once this is done.

Merge commit 9faa878 first!  The rest of the commits in this PR can then be applied in any order.

### CODE REVIEW

**Comment by magicrub** [comment]
Build errors due to partial PR commits is normal. It's when the end result doesn't build that we get worried.

**Comment by squilter** [comment]
Yes, but lots of people in different time zones need to approve the commits individually.  So if I just dumped the whole thing here, some might get merged days before others, thereby breaking something.

**Comment by magicrub** [comment]
I'm just saying that a partial pull request is allowed to be broken. It's
definitely a good idea to break up large PRs. Keep up the good work (in the
cave)!

**Comment by squilter** [comment]
Thanks!

**Comment by rmackay9** [comment]
I've talked with MichaelO an he's made the reasonable request that we not merge this until the autopilot version stuff goes in because that way it will be much easier for him to manage the two different severity values.
I've reviewed this PR including a short-test so it should go in quickly once the version is available to the GCSs.

**Comment by squilter** [comment]
Great.  I can easily redo the commits if there are any conflicts.  I can do the version stuff also, but first we need to agree on a protocol.  I posted to the TSC mailing list but haven't received a response yet.

**Comment by rmackay9** [comment]
merged, thanks!

So I guess next you'll make the same changes for Plane and libraries like AP_Arming?  I'm pretty sure you said that was your plan.

**Pull request closed without merging**
