### PR TITLE
waf: ardupilotwaf as a waf tool

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This series of patches makes ardupilotwaf be used as a Waf tool for wscript files.
Here go some advantages of this approach:
 - there is no need to import ardupilotwaf in every single wscript
 - it follows the same standard used by c and cxx tools (like bld.program, bld.stlib etc)
 - semantically, ap_program, ap_stlib, example etc are all build related methods, so it makes sense to bind them to the build context
 - from the wscripts' perspective, the code is cleaner, since ardupilotwaf, which is not specific to just build contexts, isn't *explictly* used

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
Semaphoreci finished first hehehe

**Comment by lucasdemarchi** [comment]
Ack. @cmarcelo ?

**Comment by lucasdemarchi** [comment]
Ack in the sense "I reviewed it quickly and I like it" :-)

**Comment by cmarcelo** [comment]
The time has arrived :-)

+1

Consider using the `ap_` prefix in all functions we are injecting, so use `ap_find_tests` instead of `find_tests`. It helps the future header to distinguish between things from waf and things from ardupilotwaf.

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
