### PR TITLE
ArduPlane: Log isFlying status

### PR DESCRIPTION
**Pull request by magicrub**
Log is_flying() status and its float probability in new STAT msg
and piggyback on MODE bitmask flag.

### CODE REVIEW

**Comment by gmorph** [comment]
Hi Tom.  Travis has been fixed and this isn't passing the travis build.  Can you have a look please?  Thanks.

**Comment by magicrub** [comment]
do you mean you'd like me to rebase so the travis fix is in effect on this
branch?

**Comment by gmorph** [comment]
This is a PR for master so this build is running against master with your changes in the PR and failing.  This isn't a Travis build on your branch thats failing.  If you want the PR put into master it needs to pass the Travis build.  Thanks.

**Comment by magicrub** [comment]
right, I figured it out. Sorry.

**Comment by magicrub** [comment]
there you go @gmorph :)

**Comment by magicrub** [comment]
Bump. I've been flying with this for a while. I'm happy to report that I have never see the is_flying() flag do anything unexpected. If anything I'd like to lower the low-pass filter on it so it reacts faster. It takes a good 5 seconds to switch from true to false on a landing and that seems a bit conservative. Anyhow, better to be more conservative than not so I'm not in any hurry to change it.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
