### PR TITLE
Precise camera trigger rebase

### PR DESCRIPTION
**Pull request by jmachuca77**
This is the rebase for PR #2383 
Please check the changes to the scheduler on all three projects (Plane, Copter, Rover) and check on Arducopter/log.cpp I added a macro for PLOG that was present on both plane and rover. 

I just rolled in the changes from the other PR, I have not had a chance to test this yet.

### CODE REVIEW

**Comment by WickedShell** [comment]
It came up in the dev call, but the DF message should include the current GPS altitude not just altitude. Altitude is feed with the system altitude which has baro errors associated.

**Comment by magicrub** [comment]
Does this replace https://github.com/diydrones/ardupilot/pull/2383 ?

**Comment by jmachuca77** [comment]
As Craig explained to me I think we will bring this in several steps, step 1 is to include this change as is. Then a couple of enhancements should be done, One  is to switch to an interrupt driven edge trigger, and the others are the enhancements as to what to log.

**Comment by WickedShell** [comment]
Without the logging there isn't much point for this, as its to enhance RTK
functionality, as I understand. But yeah the edge stuff will be needed
later.

**Comment by jmachuca77** [comment]
I have been doing a bit of investigation on the topic of the hotshoe signal. The hotshoe is only a contact closure switch. The previous PR assumed that the camera outputs a voltage on the hotshoe, that is incorrect you have to provide a voltage to the center pin and then read the contact closure, with this diagram:

89a9db6a-0d4c-11e5-8763-142d49c5e577

I get a very clean ~10ms signal:

screen shot 2016-01-14 at 11 23 50 am

I will check with other cameras if I get the same timing.

**Comment by tridge** [comment]
I have reworked this set of patches to be cleaner and use a 1kHz timer to check the pin:
https://github.com/tridge/ardupilot/commits/camera-trigger-pin
that should mean it is reliable with much shorter pin changes.
Jaime, can you test my changes on your setup?

**Comment by jmachuca77** [comment]
Hi Tridge, I tested this but Its not quite working, there are two messages that are logged to DF, the TRIG, and the CAM. 

I am expecting to have one TRIG message entry for every time I receive a Do_digicam_control message with the trigger request set. Currently thats not the case I am seeing less TRIG messages than expected. 

The CAM message I expect to have 1 per picture taken, this is not the case either, I am getting more CAM messages than expected. I don't think its a problem with reading the pin, I think the problem is that its being logged in multiple places.

I will look further into this and let you know what I find.

**Comment by tridge** [comment]
I've found the cause of the double CAM messages and I've also added a CAM_FEEDBACK_POL parameter to set the polarity of the trigger pin
Can you try it again? Just re-fetch my branch above

**Comment by magicrub** [comment]
Was the problem due to a double state change high to low (or vice versa) of
the gpio?

**Comment by jmachuca77** [comment]
Almost there! CAM message logging seems to be working now. I am getting exactly one entry per pulse from the hotshoe. If I trigger the camera without the hotshoe feedback I get no CAM message log entry. Yey!
The TRIG message logging is not working when triggered with the MAV_CMD_DO_DIGICAM_CONTROL message from the GCS, on a mission it works fine, from the GCS it is only working when using the Ardupilot specific DO_DIGICAM_CONTROL message.
It seems that when a MAV_CMD message is received it is forwarded to the camera library, but when a DO_DIGICAM_CONTROL message is received it si forwarded but also copter.log_picture() is called. I think we just need to add that line to line 1304 in GCS_Mavlink.cpp

**Comment by taedla01** [comment]
Hello everyone,

Sorry for not comment before ... I've been several months away from this world for personal reasons ... I hope to return soon to be online.

Glad to see that finally you will include this improvement in the official code. We took over a year doing professional works with this improvement. This saves the use of an RTK system because we always get accuracies lower than one meter(which is enough for works on large areas of land).

To everyone: as I have said in the original pull request, the key is to standarize the pulse that the hot shoe produces. You will find that from scracth, most common cameras will work without any modifications, but when you will enter with real professional cameras is necesary to standarize this pulse.

You can check the result of the use of this PR seeing this example in our BETA point cloud service:

http://pointbox.geobit.es/cloud?id=567446908d454c0d00e857f2

Jaime, contact me privately if you need help.

Regards from Spain,
Dario.

**Comment by jmachuca77** [comment]
@tridge I gave you push access to my fork in case you want to update this PR with your changes.

**Comment by jmachuca77** [comment]
I rebased the PR on tridge's branch. So this should now have your changes Tridge.

**Comment by iskess** [comment]
I have a set up where the Pixhawk triggers an Arduino board that fires a NEX-7 camera 3 times in rapid succession. In this case, will I see 1 CAM message and 3 TRIG messages? That would be fantastic.

**Comment by WickedShell** [comment]
IIRC it would be 1 TRIG 3 CAM but otherwise that's the idea of the patch.

Again just pointing out that GPS altitude needs to be logged or this
doesn't help RTK users at all.

**Comment by WickedShell** [comment]
I should restate that last bit, its not useless for the RTK users, it does
require them to put more effort into re associating the correct altitude.

**Comment by jmachuca77** [comment]
@WickedShell I think I can add that now that everything else seems to be working. What message would that be in? And I assume you want Altitude Above Mean Sea Level right? At least thats what I would use for photogrammetry.

**Comment by WickedShell** [comment]
@jmachuca77 Ideally both, definitely in the CAM message. And MSL seems correct to me, and what I expect to use based on my past mapping work.

**Comment by taedla01** [comment]
Hello everyone,

@WickedShell: 
When I wrote the original pull request #2383, you could select in Mission Planner what height did you want to use simply by changing CAM msg offsets. So yes, the imperative altitude that we have to take is the GPS height. 

Remember that GPS gives you ellipsoid altitude, not geoid, so GPS altitude is not AMSL height.
I'm not a surveyor and maybe that is wrong, but I bet it is so.

@jmachuca77:
Other data that must to be included are GPS accuracies, i.e. 2D and 3D accuracy with which the picture is georeferenced.  Currently several photogrammetry programs such as  PhotoScan use these data. This greatly improves processing time and simplifies the calculations for matching images.

Regrads from Spain,
Dario.

**Comment by WickedShell** [comment]
@taedla01 Valid point with heights, I normally just fix that with GCP's afterwards with the heights given in EGM96.

I've never seen any option allowing an import of per photo accuracy in Agisoft? I'm somewhat doubtful that it exists (although I'd love to be proved wrong). There is a global accuracy control but I've never seen any manner of way to say on a per photo what the accuracy is. I also don't see any way for us to get a good estimate on the aircraft what the actual accuracy is. (We've translated some distance post GPS solution, and I'd expect enough noise on the gyros etc that an eaxct estimate would be difficult). What kind of report on accuracy are you looking for?

**Comment by taedla01** [comment]
@WickedShell : What version of Agisoft Photoscan are you using? We (https://www.geobit.es/shop/) are the official dealers in Spain of Agisoft PhotoScan, so if you need help with the software, feel free to contact with us ;)

Since we develop our Universal Hot Shoe for work with this patch, we have been closely in contact with Agisoft for integrate individual image accuracies into software processes. So now, with last versions of Agisoft Photoscan, you can introduce the 3D GPS accuracies (or 2D accuracies if you want), for get best resolution and lower effort to processing your work.

Take a look (quick example):

photoscan load csv

photoscan see acc


Cheers,
Dario.

**Comment by WickedShell** [comment]
Clearly I need to pull the latest update :) I've been meaning to play with
it anyways but haven't gotten to it. While not looking to derail this to
much what does agisoft expect that accuracy to be? I'm assuming absolute 3D
positioning error in meters?

**Comment by taedla01** [comment]
@WickedShell: 
I am sorry, it is sunday (here 10:11 pm) and this type of answer is best for my partners than for me... GPSs are not my speciality :( But I think that yes, it is absolute 3D positioning errors in meters giveng by the GPS chip.

Good night from Spain,
Dario.

**Comment by WickedShell** [comment]
Offtopic: I was on agisoft 1.1.6 looks like lots of worthwhile changes.

On-topic: For that accuracy to be useful we would need the error in the position which is really related to the error of the EKF as the actual Log_Write_Camera is fed with the position from the EKF rather then the GPS position (which is desirable, at least pre RTK gps, and even post for platforms that high movement speed). Or are we comfortable (and you're tests show) that using the EKF position with the accuracy from the GPS is sufficient?

**Comment by tridge** [comment]
@jmachuca77 I have made the following changes and pushed to master:
* GPSAlt has been added to both CAM and TRIG messages
* implemented the CAM and TRIG messages in DataFlash using a common function
* made AP_Camera::control() return a bool for if a picture is taken
* a picture is considered taken in AP_Camera::control() only if shooting_cmd is 1
* log_picture() is called whenever AP_Camera::control() returns true. This fixes the lack of log message when called via MAVLink

That should fix all of the issues listed in this PR, so after doing some bench testing I have pushed to master. I would appreciate if you could also test. Thanks!

**Comment by tridge** [comment]
does anyone on this PR have time to work on the wiki docs for the new camera trigger support?

**Comment by taedla01** [comment]
Hello everyone,

@tridge 
What type of documentation is needed? I can test in on bench and then do a full spec review. In the original PR #2383 there is some more information about this feature. I can not try the most recent changes you have made, maybe the configuration of the feature is diferent now, relative to the original PR?
P.S. Can you change the references to me? My correct name is "Dario Andres Lindo" (first name + first surname + second surname) not "Dario Andres". I am thrilled to have contributed with something useful to ArduPilot project. lol!

Thanks for your effort!
Dario.

**Comment by iskess** [comment]
Id like learn more about how to tap the flash hot shoe signal. Where can I buy a low profile flash adapter for a NEX-7. I'm thinking I'll have to make a PCB.

**Comment by iskess** [comment]
Is there a mavlink message for TRIG so one can see on the GCS if the camera is actually firing. I hate flying a perfect hour long mission just to discover that the camera never triggered, or that the camera buffer filled up due to a tailwind and shots got missed. 

Actually it would be very nice to get a warning if the camera failed to meet the cam_trigg_dist command. If, for example the camera doesn't fire within xxx milliseconds of the trigger.

**Comment by taedla01** [comment]
Hello @iskess 

You can use MAVLINK_MSG_ID_CAMERA_FEEDBACK for receive information about camera status. For example, I have implemented a function in my Remzibi OSD wich I can see when camera is taking photos.


    case MAVLINK_MSG_ID_CAMERA_FEEDBACK:
      {
        osd_img_idx = mavlink_msg_camera_feedback_get_img_idx(msg);
      }
      break;
With camera in standby OSD shows this:

54fdcc9c-7412-11e4-808f-ae47ea7ff789


When camera shoots photos you can see this:

5a7f3570-7412-11e4-8d27-a37a7614190e

Regarding Hot Shoe... My friends from www.geobit.es will release soon a complete RTK solution for this feature. Of course, we will release separately a full Universal Hot Shoe for any cameras (Sony NEX-7 included), really at low cost and without any modification in your Hardware, just plug and play. Please stay tuned... ;)

Regards from Spain,
Dario

**Comment by jmachuca77** [comment]
@tridge , Ok, I am out of the office until tuesday, I will test this once I am back. Thanks Tridge

**Comment by terial** [comment]
**@taedla01** 

image

I am a surveyor and would like to confirm your thoughts, Typically ground elevations/orthometric heights are derived from the height above ellipsoid minus the geoid height... geoid heights can not be calculated but have to be measured and even at an elevation above sea level you can be below the ellipsoid (geoid height will be negative). Just like there are different ellipsoids (WGS84, GRS80, etc.) there are also different geoids that will affect your derived elevations from GPS.

If you or anyone else have any questions I am just getting into APM and would love to help in any way. I have access to survey equipment if it helps.

**Comment by magicrub** [comment]
closed per @tridge 's suggestion that this is done for ms accuracy, a new PR should be made for a us accurate one.

**Comment by jmachuca77** [comment]
Most of the changes done on this PR have already been added to master by Tridge with the following commits:
7e7027d82955fcfb4eb6dc81512a644ec54d4abf
48edb04414e40629551dca4a596a9787516e11ae
68470ff43ffbe4ee097e93abb0ca609cfa6d13c6
9c090184f8a53f9a5ff891e860e75cb63c8c7ae0
7a295e0c3695b0b2bb1f073ec7ce57d973e6704c
119703528e9f8221dcb68a7c3495634a75d857a9
f337057dea2dc09ca89818de9a8220fa0d9ad9ab
67b444b9e07bbd9e8ba38939881e1a8297056dab
1e651e8c4f61d40fb5544dd8e682e5865497ed0e
f90721f0cec38450c7c87a03b1386f9878bdce3c
2fd1904c9b41c027aca82218a140c44a8322e6ae

The only thing pending is changing the feedback pin reading to an interrupt if possible. And adjusting the altitude source on the log messages.

**Comment by Yups1337** [comment]
Great! 
How accurate is the logging of the gps time in the trigger msg? I think we need at least 1ms accuracy to get a position of 2cm when flying an 20m/s. This is a very important point to combine the trigger msg with a postprocessed gps RAW log.

**Comment by magicrub** [comment]
It's on the scale of a few Msec, an update in the future will make it on
the scale of a few Usec.

**Comment by WickedShell** [comment]
You will need to test it but since the GPS data is 5hz input (outside of a
few special cases) you will need interpolating with the imu's for better
data. I would be surprised to see 2cm's accuracy as that would be implying
near perfect accuracy on the GPS, and I don't think we handle the IMU data
nearly that well. You would need to try it, and I'd be interested to see
the results.

**Comment by Yups1337** [comment]
Yes, 2cm is maybe a bit optimistic, but it's the typical GPS-accuracy for GCP-based surveys.
The ublox M8T outputs RAWX with GPS and GLONASS at 10Hz, also the ublox 7P delivers 10Hz.

With 20m/s groundspeed we get a GPS Point every 2m. I think we can do a linear interpolation between to points without a significant error. Even 5cm oder 10cm precision would be a milestone in surveying without GCPs!

Of course i am willing to test the postprocessing of the GPS log. I hope somebody speeds up the GPS update rate in the plane software. Today i still wait for the hotshoe adapter. (for my NEX 5N)

**Comment by magicrub** [comment]
The AHRS/DCM/EKF system is always generating nice smooth GPS data at 50 to
400 Hz via IMU. That's sort of the point of it: to merge data together.

**Comment by Yups1337** [comment]
Yes, i don't think that we have any advantage with IMU-data in postprocessing...

3cm accuracy in flight with a 20Hz GPS L1/L2:
http://drone2gis.com/reporting-horizontal-errors-in-sfm-mapping/

**Comment by magicrub** [comment]
GPS with 20Hz is inventing data to work that fast. GPS is a very slow update, on the scale of 1Hz. Anything much higher than that is synthetically calculated internally. I would argue that a slower GPS with a faster IMU would give *MUCH* better results than a faster stand-alone GPS.

**Comment by meee1** [comment]
the time of flight for the signal is typicaly around 73 ms, the code modulation is transmitted at 1000hz, and 1024 bits long, giving accuracy per bit change of around 300m. it is posible to have accurate 20+hz gps, but that relies heavily on the reciever clock stability, and carrier phase, with an accuracy of sub 19cm

**Comment by Yups1337** [comment]
@meee1 @magicrub 
Thanks for clarification! So a 10Hz GPS update rate still makes sense with a ublox M8. 
But how can i enable the higher update rate in ArduPlane? Are there any code changes needed?

Do you see any chance to update the Missionplanner georef feature to work with a postprocessed RAW log from RTKLIB?

**Comment by magicrub** [comment]
1) These are questions for @WickedShell 
2) lets stop hijacking this closed thread and start a new one regarding faster GPS updates

**Comment by Yups1337** [comment]
Yes, you are right! 
Opened a new issue: 
https://github.com/diydrones/ardupilot/issues/3717

**Comment by Tietziano90** [comment]
Hey everyone,

I m just starting to get deeper into the programming and script using of the pixhawk. But the cam feedback is an update i really want to use. I already got an hot shoe adapter and i get the circuit closed when triggered. 

Can someone explain me how i can setup the Pixhawk to give me those camfeedback messages ?

(I have never implemented a script into the Arducopter FW, currently using V 3.3.3)

I already tried the explanations from the original issue but with no success! 

I would really appreciate your help!! Thank you in advance and best greetings from Munich

Michael

**Comment by verticalhorizons** [comment]
Really interesting following this development.

Instead of using flash trigger has anyone tried to use camera onboard speaker to get feedback from shutter sound?

I have an RX100M3 camera without hot shoe, the wiring to the internal speaker is easy enough to hack into, my plan was to use that to trigger feedback.

**Comment by R-Lefebvre** [comment]
Interesting concept, but I doubt the sound would be reliably audible with all the noise and vibration in a typical UAV?

**Comment by verticalhorizons** [comment]
You wouldn't need to hear it. Quite easy to take the wires from the speaker into an opto isolator and use that signal to trigger the pixhawk. 

As soon as this feature comes out for copter that is exactly what I will be doing.

**Comment by R-Lefebvre** [comment]
Ah, yes, OK, that makes sense if you're willing to hack the camera like that.

**Comment by verticalhorizons** [comment]
It's actually pretty easy, the wires are super easy to get to! 

In trying to get my head around how github works. Any idea how one finds the timescale for features to be rolled out? Just curious when this is likely to be available on copter.

**Comment by anestetico** [comment]
Anyone tested the CAM_FEEDBACK function with APM PLANE 3.7.1?
I have a big problem, tha AUX pin outputs 3.3V after the first camera trigger and stay on until disconnect lipo, the circuit I made is useless as the AUX pin should output anything, am I wrong?
Thank you
`CAM_DURATION,10
CAM_FEEDBACK_PIN,53
CAM_FEEDBACK_POL,1
CAM_MAX_ROLL,0
CAM_MIN_INTERVAL,0
CAM_RELAY_ON,1
CAM_SERVO_OFF,1100
CAM_SERVO_ON,1300
CAM_TRIGG_DIST,0
CAM_TRIGG_TYPE,1

RELAY_DEFAULT,0
RELAY_PIN,50
RELAY_PIN2,-1
RELAY_PIN3,-1
RELAY_PIN4,-1`

**Pull request closed without merging**
