### PR TITLE
Replay: set INS_GYRO_CAL to never to avoid losing samples

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
maybe a Replay::set_parameter() would be better? So we can set others as needed?

**Comment by peterbarker** [comment]
Doable.  Doable without cloning all of the code in LR_MsgHandler_PARM is a bit more difficult.

I currently plan on making the set_parameter call always work on the LogReader class - by putting in a dummy PARM handler until we get an FMT message for PARM.

**Comment by tridge** [comment]
ok, I'll pull in the existing patch and we can rework when we have time
pushed!

**Comment by peterbarker** [comment]
Here is a tree which passes a lambda function to LR_MsgHandler_PARM to allow it to set variables:

https://github.com/diydrones/ardupilot/compare/master...peterbarker:set-parameter-lambda

I'm not sure that deserves a PR considering (a) first use of Lambdas in ArduPilot? and (b) the min/max shenanigans.

**Comment by tridge** [comment]
hmm, thanks, I've never looked at lambdas in C++ before - I have too much baggage as a C coder. I think I'll skip this for now.

**Pull request closed without merging**
