### PR TITLE
HAL_Linux_Class: Fix the broken declare of "LinuxUtilRPI utilInstance…

### PR DESCRIPTION
**Pull request by raspilot**
…" at building raspilot.

### CODE REVIEW

**Comment by raspilot** [comment]
In a late commit the LinuxUtilRPI was added but not add build option for raspilot, which would cause the GPIOs from being initialized.

**Comment by lucasdemarchi** [comment]
@raspilot sorry, my bad. After seeing it was broken I fixed the build and added it to travis.  However I missed the variable declaration.  Thanks.

**Comment by lucasdemarchi** [comment]
related commits:
https://github.com/diydrones/ardupilot/commit/fc2a1d27b4398a51e9788ccf7b14eeb1c8e8d019
https://github.com/diydrones/ardupilot/commit/6cf1c5fdd669c5f86283775cefcd8593ef93b51b

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
