### PR TITLE
Support for IMU Heating

### PR DESCRIPTION
**Pull request by jberaud**
On the bebop, in order to keep the IMU at a constant temperature, a heating resistor is used.
This pull request adds the support for that by  reading the temperature on the MPU6000, and then controlling a pwm duty cycle with a simplistic PI algorithm.
HAL::Heat has been added.
Linux::Heat_Pwm has been added to control the pwm with sysfs.
The constructor takes the sysfs path, PI coeffs, target temperature and pwm period as params.
The only method is called from the IMU driver : set_imu_temperature

Tests : This has been flight tested quicky on the bebop to make sure that the temperature stays constant and doesn't go crazy.

Restrictions:
The bebop runs a 3.4.11 linux kernel. The sysfs interface has changed since, but should still be compatible if the correct file names are provided.

### CODE REVIEW

**Comment by tridge** [comment]
I should prefer just having this under hal.util, instead of a new heat class

**Comment by proficnc** [comment]
As this is also in the latest pixhawk 2 revision, I assume it will be in other boards as well.  It may make sense to be its own class.

**Comment by jberaud** [comment]
Rework done Tridge. Take the version you prefer (in case you agree that this should be a generic class).

**Comment by tridge** [comment]
I like the new structure better, thanks!
A few comments:
1) the perror() calls need fixing, as just printing an error on stderr doesn't stop the fd being used. We'll either need some way to disable the driver if it fails to open one of the sysfs paths, or use a panic(). Otherwise we'll try to just keep writing to fd -1 and sending errors to stderr.
2) I'd prefer asprintf() for creating the file paths, then free the result. That should be clearer as will also avoid a lot of wasted stack usage for large PATH_MAX. It also means we get error checking.
3) I'd prefer C++11 style initialisers for new code instead of having initialisers in the constructor
4) if _last_temp_update is a uint64 then you need to use micros64() not micros() or the subtraction won't work correctly on time wrap. Using millis() may make more sense in fact, as you don't need microsecond resolution
5) we don't really need return at the end of void function
6) we prefer curly braces on all if statements
7) for formatted write to a fd it is nicer to use dprintf() than using a separate snprintf and write (same for the write of "1")
Thanks!

**Comment by jberaud** [comment]
@zehortigoza 
"Restrictions:
The bebop runs a 3.4.11 linux kernel. The sysfs interface has changed since, but should still be compatible if the correct file names are provided."
That was what I meant by that.

**Comment by jberaud** [comment]
@tridge thanks for the review, I'll modify the patch according to your comments.

**Comment by jberaud** [comment]
> 3) I'd prefer C++11 style initialisers for new code instead of having initialisers in the constructor

I assume this means that the constant initializers have to be moved in the class declaration.

**Comment by jberaud** [comment]
@tridge Done.

**Comment by tridge** [comment]
applied, thanks Julien!

**Pull request closed without merging**
