### PR TITLE
AP_Notify: Add display support

### PR DESCRIPTION
**Pull request by mirkix**
* Add support for notify display.
* Enable notify display for [BBBMINI](https://github.com/mirkix/BBBMINI)
* See blog post http://diydrones.com/profiles/blogs/status-display-for-ardupilot . 
* Tested with [BBBMINI](https://github.com/mirkix/BBBMINI) SSD1306 I2C 400kHz.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Nice having this display! I never remember the color codes so have to resort to look in the GCS to know what's happening.

For me this is reviewed. Maybe @WickedShell wants to chime in regards the GPS changes.

**Comment by lucasdemarchi** [comment]
Oh... I forgot to say: the way we are including the headers in AP_Notify.h is not that good, because it will expose internal details to the other libraries (and trigger a complete rebuild when such headers change). However this is currently how the other notify objects are doing, so I'm not going to complain about your change. I'll send a separate PR to deal with it when this get merged (https://github.com/lucasdemarchi/ardupilot/tree/pr/ap-notify-headers)

**Comment by WickedShell** [comment]
GPS change looks innocuous to me. I admit I wasn't even sure what the AP_Notify library was used for :)

If you want some information that is GPS related (specifically multiple GPS units) but no one else can report while the vehicle is turned on you could report which GPS is being used as the primary instance, as that information is unavailable over MAVLink or any other real time feedback .mechanism.

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
