### PR TITLE
AP_Limits: Remove unused module

### PR DESCRIPTION
**Pull request by dgrat**
Module seems unused for years and doesn't compile, because the code is old.

### CODE REVIEW

**Comment by rmackay9** [comment]
Totally forgot about this library.  It was always a bit of a monster so happy to see it go.  I'll pull this in tomorrow once the checks have completed unless someone (Tridge or Lucas) beats me to it.

**Comment by dgrat** [comment]
What is actually the replacement of this old module? I am not up to date what was the original scope of the module and how it is solved today.

**Comment by lucasdemarchi** [comment]
@dgrat I'm surprised it's still there... I remember trying to nuke it at some point. Thanks for removing it.

There are still some references to it though, that I'm not sure how it should be handled:

```
ArduCopter/Parameters.h:        // 65: AP_Limits Library
ArduCopter/config.h:// AP_Limits Defaults
ArduCopter/config.h:// Enable/disable AP_Limits
Tools/ardupilotwaf/ardupilotwaf.py:    'AP_Limits',
Tools/autotest/apm_unit_tests/dev/arducopter_AP_Limits.py:    '''A scripted flight plan for testing AP_Limits'''
Tools/autotest/apm_unit_tests/dev/arducopter_AP_Limits.py:    print "# Setting AP_Limits parameters"
Tools/autotest/apm_unit_tests/dev/arducopter_AP_Limits.py:    print "# Listing AP_Limits parameters"
```

For example, the params in ArduCopter/Parameters.h -- can they be removed? @rmackay9, do you know?

**Comment by dgrat** [comment]
@lucasdemarchi 
I will remove them.

**Comment by dgrat** [comment]
I mean I could remove the  WAF links. AP_PARAM I don't know.

**Comment by dgrat** [comment]
Please check the parameters. Not sure whether it is okay to remove them. 
Nevertheless, it is time for them to sooner or later anyway :D

**Comment by rmackay9** [comment]
@dgrat, we can just leave the Copter parameter enums as they are.  they've all got a "deprecated" message beside them but we can't actually remove them from the enum even though it also says "- remove".  If we simply remove them the parameters below will shift up and they will actually move in eeprom which leads to corruption for people who were using the old location.  Eventually what we need to do is increase the parameter version number which will cause everybody to lose their parameters, then we can reorganise the locations.  We haven't done that in about 3 years but the day is coming!

**Comment by rmackay9** [comment]
merged, thanks!
I removed the copter changes but fixed the comments.

**Pull request closed without merging**
