### PR TITLE
waf: programs groups and build commands; update README-WAF

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

Here go the main contributions of this PR:
 - Introduce the concept of programs groups with the options `--programs-group'
 - Add build commands for each programs group
 - Update the README with the current status

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
@lucasdemarchi @cmarcelo Would you guys mind taking a look?

**Comment by lucasdemarchi** [comment]
@guludo I like it, but would name program_group, and not programs_group, programs_groups, etc. In the code, if you need the plural you can use program_group_list, program_group_array, or something like that. A typo there is way too easy to happen. Been there, done that :) - https://git.kernel.org/cgit/utils/kernel/kmod/kmod.git/commit/?id=a955f71f60954540f9ef59f081a0be02468af0e0

**Comment by guludo** [comment]
@lucasdemarchi hehe Ok, I'll change the names and do a forced push.

**Comment by guludo** [comment]
Ping: rename done.

**Comment by lucasdemarchi** [comment]
I fixed some typos: 1 in commit message and another in the code (there was still a PROGRAMS_GROUP in the help message). Applied.

**Pull request closed without merging**
