### PR TITLE
MAV_CMD_GET_HOME_POSITION returning incorrect result

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
There is another problem with this code in that it blindly sends the home position back to the GCS even though it may not have a valid home position yet. Not sure how to check for that. So couldn't fix. I can add that to this pull if someone tells me the check to make.

**Comment by rmackay9** [comment]
merged thanks!
As part of the merge I added the home-is-set check and also split the commit into a single commit for each vehicle (which is our regular practice).

**Comment by DonLakeFlyer** [comment]
@rmackay9 Question: Wondering if you've seen the PX4 Flight Stack calibration ui from QGroundControl? It's more much visual using a Cessna model to show the user orientations for things like accel cal and friends and how to rotate around the various orientations to get a good compass cal. Soon I'll switch it to a real 3d wireframe cessna model and really rotate it around on the screen so you can really see what to do. I re-wrote the PX4 flight stack firmware cal routines to support this more user friendly cal mechanism. I'm in the process of implementing setup screens for APM stack in QGC. I'd like to re-write the APM flight stack routines to also support this (I think better) calibration ui. In the process I'd keep the existing mechanism as well to keep MP and APMP running. Wanted to make sure APM folks would be ok with that before I put the effort into it.

Sorry, for polluting this pull with this question. Never really quite sure how to get hold of you APM folks.

**Comment by DonLakeFlyer** [comment]
> also split the commit into a single commit for each vehicle (which is our regular practice).

Didn't know that. Will do for my next ones.

**Comment by rmackay9** [comment]
@DonLakeFlyer, we have support for on-board compass calibration now in master and I hope that uses consistent messages with the PX4 stack.  I know that MP has support for that new method but I don't think it has any graphical user interface to go with it (the older method has rotating globes).  A vehicle frame view would be nice to have.

We can be reached through drones-discuss@googlegroups.com or our gitter channel.  https://gitter.im/diydrones/ardupilot

**Pull request closed without merging**
