### PR TITLE
Enables copy to clipboard from xterm shells. Useful to copy gdb output.

### PR DESCRIPTION
**Pull request by jmacgithu**
Needed at least for Xubuntu

### CODE REVIEW

**Comment by gmorph** [comment]
You have also added the -ls flag which will be ignored as the -e flag is already specified.  Are you able to update the request and remove the -ls flag please?
Thanks, Grant.

**Comment by jmacgithu** [comment]
Ok, done now

**Comment by gmorph** [comment]
Thanks!
I've tested this and it works fine.  All good to merge please.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
