### PR TITLE
Tools: add script to set up Arch Linux

### PR DESCRIPTION
**Pull request by squilter**
Ubuntu has failed me for the last time...

This script has all the dependencies to get the following things working:
- sitl
- make px4-v2
- make px4-v2-upload

AVR had some problems with mismatched versions.  The Arduino version in the package manager was too up-to-date and it broke support for `make apm2`.  I decided to just skip all AVR stuff.

### CODE REVIEW

**Comment by squilter** [comment]
Please hold off on this one until I look into AVR stuff again.

**Comment by lucasdemarchi** [comment]
What you really want for any AVR stuff is to install avr-gcc, not any arduino-related packages.

**Comment by lucasdemarchi** [comment]
> What you really want for any AVR stuff is to install avr-gcc, not any arduino-related packages.

turns out I forgot I had the arduino10 package installed. And that is only available on AUR.

**Comment by squilter** [comment]
Nevermind, I won't add it.  Arch doesn't have the right AVR compiler version in its repositories.

**Comment by squilter** [comment]
@lucasdemarchi The normal repositories only have avr-gcc v5.2.  We need 4.8.2.  The AUR had 4.8.1

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi The normal repositories only have avr-gcc v5.2. We need 4.8.2. The AUR had 4.8.1

I have avr-gcc 4.9.2 here, installed from the community repository. Nice to see they updated yesterday to 5.2.  Did you have any problem building with 5.2?

**Comment by squilter** [comment]
Yes, unfortunately I had lots of compile errors.

**Comment by lucasdemarchi** [comment]
> Yes, unfortunately I had lots of compile errors.

humn... I just built it here with gcc 5.2. Maybe it was related to arduino 1.0 vs 1.6 (from your other pr trying to support the new location for boards.txt)?  I have the arduino10 package installed from AUR here.

**Comment by squilter** [comment]
Hmm...

I might try that setup later.  Either way, the project only officially supports 4.8.2.  Would we really want to encourage people to use an unsupported compiler?

**Comment by lucasdemarchi** [comment]
> Would we really want to encourage people to use an unsupported compiler?

Not my call, at least not for AVR. For Linux targets I really like to support whatever the last version is available in distros.

**Comment by squilter** [comment]
The ARM compiler is the correct one, downloaded from the interwebs, not a repository.  Since we are dropping AVR soon (and since not many people use Arch), I think it's probably safe to just ignore AVR.

**Comment by lucasdemarchi** [comment]
I agree.

**Comment by lucasdemarchi** [comment]
@tridge maybe we can share some parts with the ubuntu script? Just not to have the packages here to bit rot.

**Comment by rmackay9** [comment]
merged, thanks!

**Pull request closed without merging**
