### PR TITLE
ADS-B msg bug: vert_velocity is supposed to be signed

### PR DESCRIPTION
**Pull request by magicrub**
bug was introduced when changing from floating point to fixed point format

associated PR: https://github.com/mavlink/mavlink/pull/481

### CODE REVIEW

**Comment by magicrub** [comment]
Bump. This is already merged and released in the latest mission planner beta. Pymavlink needs a version bump too.

**Comment by rmackay9** [comment]
by the way, normally we do the results of the generate as two separate commits.  one iwth the real functional changes, the other with the version update

**Comment by rmackay9** [comment]
merged, thanks.  The .xml changes should be made upstream as well.

**Comment by magicrub** [comment]
Here's the upstream PR https://github.com/mavlink/mavlink/pull/481

**Pull request closed without merging**
