### PR TITLE
Add NAV-DOP to get all DOP values, as Pdop is sent as Hdop currently

### PR DESCRIPTION
**Pull request by MacDev240**
Add vars for NAV-DOP ubx message x04, to obtain true Hdop value as current code pulls Pdop and sends as Hdop
new vars: h_dop, p_dop, and v_dop.

### CODE REVIEW

**Comment by MJBeaubien** [comment]
Was this ever resolved?

**Comment by squilter** [comment]
@MJBeaubien this was not resolved.  See #512 and #462

**Comment by MJBeaubien** [comment]
Hopefully this issue gets resolved soon...

**Comment by andyp1per** [comment]
Sorry, didn't see that you had done this. I have an up-to-date fix in https://github.com/diydrones/ardupilot/pull/2462

**Comment by rmackay9** [comment]
Sincere apologies for not merging this PR.  I've just merged in Andy Piper's change.
We're trying to do better getting PRs in faster so I hope you consider contributing again in the future!

**Pull request closed without merging**
