### PR TITLE
Always depart loiter WP towards next WP

### PR DESCRIPTION
**Pull request by magicrub**
This is only helpful for plane but available for all. When exiting a liter_turns, loiter_alt, or loiter_time there is now an optional cmd param field of heading required where when set to 1 yo must be +/- 10deg of the next waypoint before you are allowed to exit the loiter.

There needs to be a GCS change to added the bool label field 3 for loiter time/turns.

This fixes https://github.com/diydrones/ardupilot/issues/1906

### CODE REVIEW

**Comment by magicrub** [comment]
The bool flag is 1 for checking for heading, so you must enable it via param. I'm wondering if we should invert that so you have to set the flag to ignore heading and by default (0) it checks the heading.

**Comment by iskess** [comment]
I'm in favor of the heading alignment being default behavior as I feel this is what most operators would expect.

**Comment by magicrub** [comment]
I've removed the bool flag and now this behavior will be default so no GCS change is needed

**Comment by magicrub** [comment]
merged https://github.com/diydrones/ardupilot/commit/be3941efdfa39daf5307c185e3a37d2d338a756d

**Pull request closed without merging**
