### PR TITLE
waf: add most linux boards

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This PR adds most linux boards to the waf build system.

I couldn't test the build for `zynq` (also, I find it strange that it isn't in travis build). I tested the build for the other added boards locally.

I think feedback from the boards' maintainers is quite relevant for this PR.

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
@vmayoral 
@mirkix 
@staroselskii

**Comment by guludo** [comment]
@jberaud I'm supposing you're the maintainer for Bebop... Are you? :-)

**Comment by guludo** [comment]
@onceme I'm mentioning you here because I see that you added BH HAT to the other build system...

**Comment by jberaud** [comment]
@guludo I am. I will add that in the README.md if @lucasdemarchi @tridge @rmackay9 don't mind

**Comment by lucasdemarchi** [comment]
@jberaud yep, go ahead.

**Comment by jberaud** [comment]
@guludo great to have this PR it will ease lttng's integration

**Comment by vmayoral** [comment]
Good stuff! thanks @guludo!

**Comment by mirkix** [comment]
@guludo Just used waf to build bbbmini, works fine. Thanks.

**Comment by onceme** [comment]
@guludo Thank you. bhat build works fine. I can try again after your rework.

**Comment by jberaud** [comment]
@guludo Ok for bebop. Build works and arducopter runs fine. Thanks !

**Comment by guludo** [comment]
There's a new version. Closing this.

**Pull request closed without merging**
