### PR TITLE
RCMap Fix PR

### PR DESCRIPTION
**Pull request by R-Lefebvre**
Tested on Quadcopter in Stabilize, Acro, Alt Hold, Loiter and Stop modes.

### CODE REVIEW

**Comment by andyp1per** [comment]
Cool! Looks quite similar to my change - which means I think it's the right approach :)

**Comment by R-Lefebvre** [comment]
Thanks for reviewing it.  I'd like as many eyeballs on it as possible because it's a pretty big change any any errors could have a large effect.

**Comment by andyp1per** [comment]
Did you git grep for all remaining usages of rc3 etc? There was some mavlink SITL/HITL changes that I couldn't get my head around which aren't in your patch. Is it worth making the RCMAP parameter change I did to limit the mapping to channels 1-4 - I'm not convinced that trying to map throttle to channel 5 say would ever work?

**Comment by R-Lefebvre** [comment]
Actually, that's a really good point.  I notice that the comments for the RCMAP params say 1-8, but it really has to be 1-4 for copter.  I wonder if Plane can agree to that?

Not, I didn't do a grep, but did search through the main vehicle code and the libraries that I could think of.  There may be a few outliers still.

**Comment by R-Lefebvre** [comment]
Oh, and I did test this on a quadcopter, by moving the channels around on my Taranis, and it works.  I got about 2 flights in before I got a little cocky in acro and piled it into the ground.

**Comment by rmackay9** [comment]
merged!  thanks.

**Pull request closed without merging**
