### PR TITLE
ArduCopter: add support for simple digital pin.

### PR DESCRIPTION
**Pull request by taedla01**
For future developments, add support for simple digital pins on FMU rail
like ArduRover.

### CODE REVIEW

**Comment by gmorph** [comment]
We tend not to add code that we aren't going to use.  Is there any reason for adding this code now if its not going to be used?
Thanks, Grant.

**Comment by magicrub** [comment]
this is considered dead code and should be removed and/or not merged.

**Comment by rmackay9** [comment]
ok, closing for now at least.

**Comment by taedla01** [comment]
Hello everyone,

@rmackay9  Sorry... I did not known that was dead code... I saw this on current ArduRover code and thought that was being still used.

We are using this small piece of code for multiple uses:
1- With a switch input on pin 55, we can change flight batteries without the needed of turning off the plane. Pushing the switch, Pixhawk Enters on a "standby mode", activating a custom made capacitor circuit, giving power for at Least 40 seconds.
2- Connecting the logical level camera flash hot shoe pin to pin 54 gives (with other code changes) a best camera triggering flag. Reducing the CAM messages lag from 200ms to at Least 20-30ms.
3-With another switch we turn on/off the flight lights. 

Cheers,
Dario.

**Comment by magicrub** [comment]
It may not be dead in Rover, but you're adding the dead code in Plane/Copter since on those projects nothing is calling that function. If you are using the function on those platforms then feel free to submit that code too and it will no longer be considered dead code.

**Pull request closed without merging**
