### PR TITLE
Replay: handle df format changes - IMT vs IMU / GPS.HDop vs GPS.EPH etc

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
the GPS format changes have been reverted
can you rework this for just IMU/IMT ?
thanks!

**Comment by peterbarker** [comment]
Reworked just for the clock stuff.

**Comment by peterbarker** [comment]
Bump!

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
