### PR TITLE
Copter: soften takeoff

### PR DESCRIPTION
**Pull request by jschall**
This adds a takeoff acceleration (hard-coded) to soften takeoffs, and a minimum takeoff speed (also hard-coded) to ensure that liftoff happens promptly so that the vehicle doesn't interact with the ground for too long.

### CODE REVIEW

**Comment by jschall** [comment]
Not sure why this failed Travis - built for me.

**Comment by jschall** [comment]
Restarted Travis and it looks like it ended up passing.

**Comment by jschall** [comment]
Ping. Does not affect AUTO or GUIDED takeoff I think (might be a good thing to add!), does affect LOITER and ALT_HOLD takeoff which aren't used much outside of Solo. Makes them take off authoritatively but not terrifyingly, even when PILOT_VELZ_MAX and PILOT_ACCEL_Z are set very high.

**Comment by rmackay9** [comment]
merged, thanks!

**Comment by jschall** [comment]
It'd be cool at have a takeoff aux command now! Then DIY vehicles can take off like Solo.

**Pull request closed without merging**
