### PR TITLE
AP_InertialSensor: fixed default MPU6000 orientation for PXF

### PR DESCRIPTION
**Pull request by ahcorde**
Fixed default MPU6000 orientation for PXF

### CODE REVIEW

**Comment by tridge** [comment]
I have a couple of PXF boards but both have inoperable MPU6000 sensors. Where did you get your board? Is it from Erle Robotics?

**Comment by tridge** [comment]
ahh, I see that you're part of the ErleRobot organisation - you're working with Victor?

**Comment by ahcorde** [comment]
Hi @tridge ,

Yes, I'm one the software engineer of Erle Robotics.

**Comment by tridge** [comment]
pushed to master, thanks!
btw, it would be nice to enable both MPU6000 and MPU9250 on the PXF, but we need to cope with ones that have broken MPU6000.
We really need a runtime config file for the Linux port
Also, can you check the orientation of the AK8963 mag for the MPU9250 and MPU9255?

**Comment by ahcorde** [comment]
Here[1], you can find a log that contains the two accelerometers working at the same time (MPU6000 and MPU9250 on the PXF).

I have checked AK8963, but it seems that It doesn't work. I see the value changing but I think it's because of the IMUs. I can explain this: 

 1 ) I run ArduCopter and I check the value of the compass 
 2 ) Then I kill ArduCopter and I change the orientation of the board.
 3 ) The I launch again ArduCopter
 4 ) The value of the compass pointed to the North.  I have checked with a calibrate compass and the value is wrong.

I don't know exactly what is going on because AP_Compass_AK8963::accumulate(void) is empty. But I notice that you are using the publish_field in AP_Compass_AK8963::read()

[1] https://github.com/erlerobot/logs/blob/master/pxf/copter/29-12-2014/50.BIN
[2] https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Compass/AP_Compass_AK8963.cpp#L304

**Comment by vmayoral** [comment]
@tridge just made a [commit](https://github.com/erlerobot/ardupilot/commit/a5a72a8488a5f907bbd4c26196e0f1c33c9ed511) that addresses this matter. You should be able to `cherry-pick` it directly.

Have a look at [this log](https://github.com/erlerobot/logs/blob/master/pxf/brain/3.BIN) I just generated that has 1) the changes included in the commit mentioned above 2) MPU9255 3) MPU6000. 
Both IMUs provide pretty similar values and we've tested a flight with it and it looks quite good.

Supporting @ahcorde comments, it seems that the AK8963 is somehow wrong. We can clearly see values coming from the sensor but simply re-launching APM changes the orientation (every time).

**Pull request closed without merging**
