### PR TITLE
Add MPU9250 multiple instance support

### PR DESCRIPTION
**Pull request by mirkix**
This PR make it possible to use more than one MPU9250.  I already use this patch for dual MPU9250 IMU in my BBBMINI project.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
:+1:

**Comment by lucasdemarchi** [comment]
@mirkix if you have time and want to contribute another worthwhile change... this MPU9250 and AK8963 should be changed to use the AuxiliaryBus that MPU6000 is using.  Then then can profit of code sharing.

**Comment by lucasdemarchi** [comment]
@tridge looks like this got applied.

**Comment by tridge** [comment]
yes, I forgot to close it, thanks

**Pull request closed without merging**
