### PR TITLE
Add support for MinnowBoard Max (v2)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Second version of #2947 

Changes:
 - Remove the patch for rotation of HMC5883L. I'll send a separate PR for this one
 - Rebase, including the recent renames applied upstream
 - Make the uart device an argument to RCInput_UART's constructor as suggested by @jberaud

### CODE REVIEW

**Comment by tridge** [comment]
hi Lucas, I think it would be nice to make panic() be a varargs function with printf formatting
(I won't hold up merging this PR for that, but would be a nice cleanup)

**Comment by lucasdemarchi** [comment]
Indeed. I'll send a separate PR tomorrow

**Comment by tridge** [comment]
we should add minlure to the travis build in Tools/scripts/build_all_travis.sh

**Comment by tridge** [comment]
I've pushed to master, but I will leave this PR open for now to discuss the above minor issues.
In summary:
 * add varargs panic
 * make non-channel sysfs gpio read/write be fast by cacheing fd in a table
 * add minlure to travis

Thanks very much for the patches!

**Comment by lucasdemarchi** [comment]
@tridge thanks!

The panic() using varargs is in #3066 
I''ll take care of the others soon.

**Comment by tridge** [comment]
I'll close this now as the extra stuff is done or has a separate PR pending

**Comment by lucasdemarchi** [comment]
This one is still missing, but is on my todo list: "make non-channel sysfs gpio read/write be fast by cacheing fd in a table"... I know it will be faster, but I'd like to do a benchmark on this first.

**Comment by zehortigoza** [comment]
@lucasdemarchi Here your benchmarks:

Here with the current code:
```
   string "elapsed"
   array [
      dict entry(
         string "count"
         uint64 62380
      )
      dict entry(
         string "total"
         uint64 4223271397
      )
      dict entry(
         string "average"
         uint64 67701
      )
      dict entry(
         string "minimum"
         uint64 59152
      )
      dict entry(
         string "maximum"
         uint64 1180869
      )
      dict entry(
         string "variance"
         uint64 1331262830
      )
      dict entry(
         string "std-deviation"
         uint64 36486
      )
   ]
```
```
   string "elapsed"
   array [
      dict entry(
         string "count"
         uint64 521011
      )
      dict entry(
         string "total"
         uint64 34617186303
      )
      dict entry(
         string "average"
         uint64 66442
      )
      dict entry(
         string "minimum"
         uint64 59025
      )
      dict entry(
         string "maximum"
         uint64 1431152
      )
      dict entry(
         string "variance"
         uint64 893533176
      )
      dict entry(
         string "std-deviation"
         uint64 29892
      )
   ]
```

And now caching the file descriptor:
```
   string "elapsed"
   array [
      dict entry(
         string "count"
         uint64 91611
      )
      dict entry(
         string "total"
         uint64 3140214852
      )
      dict entry(
         string "average"
         uint64 34277
      )
      dict entry(
         string "minimum"
         uint64 29318
      )
      dict entry(
         string "maximum"
         uint64 1252268
      )
      dict entry(
         string "variance"
         uint64 517574212
      )
      dict entry(
         string "std-deviation"
         uint64 22750
      )
   ]
```
```
   string "elapsed"
   array [
      dict entry(
         string "count"
         uint64 503497
      )
      dict entry(
         string "total"
         uint64 17457082582
      )
      dict entry(
         string "average"
         uint64 34671
      )
      dict entry(
         string "minimum"
         uint64 29287
      )
      dict entry(
         string "maximum"
         uint64 1775476
      )
      dict entry(
         string "variance"
         uint64 863925629
      )
      dict entry(
         string "std-deviation"
         uint64 29393
      )
   ]
```

**Comment by lucasdemarchi** [comment]
@zehortigoza why do you have 2 groups for each elapsed?  DigitalSource_Sysfs already caches the fd. The one that doesn't cache fd is if you use hal.gpio->write() version. If you are measuring the right thing (the time of a single gpio write), then it looks worth. Half of the time, even if it's only ~30nsec of difference. Could you send the PR with the cache patch?  A table in the PR/commit-message with the timings would be greatly appreciated, too.

**Comment by zehortigoza** [comment]
@lucasdemarchi It is just 2 rounds of test of each elapsed.
What this is measuring is the time to change the DigitalSource mode, to output to/from input. Tridge was wondering about the performance on that https://github.com/diydrones/ardupilot/pull/3089#issuecomment-153554615

I can measure also the FD cache for GPIO write(), but on this case would be good have a hash table to store the file descriptors?

**Pull request closed without merging**
