### PR TITLE
Copter: Fix flighttermination capability

### PR DESCRIPTION
**Pull request by squilter**
The capability was successfully updated in mavlink/mavlink.

### CODE REVIEW

**Comment by rmackay9** [comment]
instead of updating the common.h I think the xml needs to be updated and then a generate.sh should be run.

**Comment by squilter** [comment]
I think there are probably a few changes between here and mavlink/mavlink.  Should I pull all changes and then regenerate?

**Comment by squilter** [comment]
Done.  I didn't pull changes from mavlink/mavlink's ardupilotmega.xml because it looked like the local one here might have been the one more recent one.  Not sure.  Either way, that should be synchronized across repos also.

**Comment by rmackay9** [comment]
merged, thanks!

**Comment by squilter** [comment]
cool

**Pull request closed without merging**
