### PR TITLE
ArduPlane: port INITIAL_MODE param from rover

### PR DESCRIPTION
**Pull request by magicrub**
added INITIAL_MODE which is the mode we boot up into. Default is MANUAL. This is useful when flying without a RX or if you have a RX that outputs zeros without a detected Txmtr. This is a port from rover.

### CODE REVIEW

**Comment by gmorph** [comment]
Reviewed and ready to go in.

**Comment by magicrub** [comment]
I've bench tested this on hardware and it works as expected, boots into whatever mode you told it to be. Also flown with it booting into MANUAL and STAB and AUTO.

**Comment by R-Lefebvre** [comment]
Cool, should we look at bringing this into Copter too?

**Comment by magicrub** [comment]
I don't see why not but I don't know the implications.

**Comment by magicrub** [comment]
I talked this over with @rmackay9 and he can't think of any use-case especially since copter requires a remotely triggered arm via RC TX or GCS. That means the ability to set a mode should be available at all times too.

**Comment by R-Lefebvre** [comment]
Hmm.  I thought this was actually to-do for us.  Even though the we *can* set the mode from the tablet, It might be best to default it to guided mode or something, so that we don't have people taking off in Stab or something by accident?  Not a big deal for me, I just thought it was already on our list for some reason.

**Comment by tridge** [comment]
applied, thanks Tom!

**Pull request closed without merging**
