### PR TITLE
Navio: SPIUARTDriver for Ublox, AK8963_MPU9250 compass, PCA9685 OE pin enable

### PR DESCRIPTION
**Pull request by Clouded**
We reworked SPIUARTDriver and MPU9250-AK8963 compass according to the points of the previous discussion. 

To sum up what has been done:

I went over the classes together with Georgii, ‘virtual’ keywords were removed where they were unnecessary. 
The unnecessary cast in Scheduler has been removed.
Semaphore in SPI UART driver was fixed.
The big commit for AP_Compass has been split in small ones per library and per vehicle.
A couple of register writes are disabled in MPU9250 if AK8963 is selected, because they prevent AK8963 from working properly. Comments about that were added in the code.
Writes in SPI Ublox were changed to 0xFF instead of 0x00 when there’s no data to write.

### CODE REVIEW

**Comment by tridge** [comment]
I've pushed part of this PR to master with some fixes, and left part of it out. You still need a bit more work to get your patch quality up. 
The fixes I put in are:
* made it build on all platforms. Please get into the habit of testing your patches using Tools/scripts/build_all.sh. Now that we use travis on master any future PRs will be auto-tested by Travis for buildability. This PR had quite a few pieces of code that broke the build on non-Linux platforms, including things like unconditionally including headers (such as stdio and cassert) that don't exist on all platforms.
* the move of the ringbuffer macros into AP_HAL conflicted with copies of those macros in the DataFlash library. When you move macros out of a cpp file and into a global header you are changing the scope of the macros, so you need to check for conflicts. I've created a AP_HAL/utility/RingBuffer.h to fix this.
* the "#if CONFIG_COMPASS" change in the mpu9250 driver didn't work, as CONFIG_COMPASS is only set in the top level vehicle code. You need to use HAL_COMPASS_DEFAULT in a library. 

I've left out the analog ADS1115 code completely as it is a bit of a mess (sorry!). It has functions in it that make no sense at all. For example Ch6() takes a list of channels to read, but ignores that argument and instead just reads all channels. Then there is a read() function that doesn't seem to be used at all (and behaves like Ch6?). There are probably other issues with it - I stopped reading when I saw those errors. Please go over that driver carefully before resubmitting.
That said, I'm really glad to see the NavIO port progressing so well!
I'll close this PR now. Can you open a new PR which fixes the above issues? Thanks!
Cheers, Tridge

**Comment by tridge** [comment]
oh, I also noticed that the default orientation for the AK8963 mag and it seems to be wrong. Can you check that too?

**Comment by Clouded** [comment]
Andrew, thank you very much!
We've just been discussing how cool Travis is:) 
Sorry for the mess in ADS, we are currently working on it.
Compass orientation was really wrong and has already been fixed, just didn't get in the pull request. 
We'll provide the new PR with fixes soon.

**Comment by Clouded** [comment]
The new PR with AK8963 fixes and some minor improvements is here - https://github.com/diydrones/ardupilot/pull/1744

**Pull request closed without merging**
