### PR TITLE
EKF2 - Improved use of GPS and range finder data for height

### PR DESCRIPTION
**Pull request by priseborough**
Adds the ability to specify use of GPS as the primary altitude source.
Improves timing accuracy of range finder measurements.
Improves protection against spikes when calculating the baro to GPS offset
Moves selection of altitude source into a separate function.
Uses sensor specific noise parameters when fusing height data from different sources.
Baro drift is learned during non-baro operation so reversion to baro can be made without height jumps.

The following combination were tested  in SITL Plane and SIM_BARO_GLITCH was adjusted by 50m to induce a timeout in the Baro to verify normal operation. The value of EK2_ALT_SOURCE was adjusted mid-flight to verify that the EKF could switch safely between Baro and GPS. A Baro offset was introduced during GPS operation and learning of the baro offset and correct application after switch back was confirmed.

EK2_ALT_SOURCE=0 (Baro option - verified switch to GPs and back again )
EK2_ALT_SOUCE = 1 (Range finder height - verified mode was ignored and continued to use Baro)
EK2_ALT_SOUCE = 2 (GPS option - verified switch to Baro and back again)

This following combinations were tested in Copter SITL

EK2_GPS_TYPE=0 and EK2_ALT_SOURCE=0 (GPS aiding, Baro height)
EK2_GPS_TYPE=0 and EK2_ALT_SOURCE=2 (GPS aiding and height)
EK2_GPS_TYPE=3 and EK2_ALT_SOURCE=0 (OF aiding, Baro height)
EK2_GPS_TYPE=3 and EK2_ALT_SOURCE=1 (OF aiding, RangeFinder height)

It has been flight tested in a copter with the following combinations

EK2_GPS_TYPE=0 and EK2_ALT_SOURCE=0 (GPS aiding, Baro height)
EK2_GPS_TYPE=3 and EK2_ALT_SOURCE=0 (OF aiding, Baro height)
EK2_GPS_TYPE=3 and EK2_ALT_SOURCE=1 (OF aiding, RangeFinder height)

Here are the GPS 3D position innovations from a high dynamics flight in a copter (3g peak manoeuvres) with 11 sats, no SBAS and receiver claimed vertical position accuracy of 1.6m. Pilot observations on this flight was that during high speed manoeuvring, the altitude hold was more consistent using GPS rather than Baro. 

use gps for height innovations

A subsequent low speed flight in a multi-path environment with 8 satellites and vertical position accuracy 2.1m of  showed that there was noticeably more height wander using GPS altitude than there was using Baro. 

gps vs baro height

This feature will definitely be of interest to users with higher grade GPS receivers operating where there is SBAS coverage.

### CODE REVIEW

**Comment by magicrub** [comment]
Paul,

This sounds really really good, thank you! How does ranegfinder come into
play for plane landing? Your patch is within lib EKF2 so I'm worried it's
applying the rangefinder data twice.

**Comment by priseborough** [comment]
The EKF (and EKF2) use range finder for:

1) Estimation of terrain height for use by the optical flow calculations (it also is output on the getHAGL() interface which currently is not published on the frontend.
2) As an alternative altitude reference when using optical flow

None of this should affect plane as plane doesn't operate in optical flow mode. If the EK2_ALT_SOUCE=1 option is selected and optical flow mode is not active, then the EKF ignores the request and continues to use Baro. This has been verified in SITL and bench testing.

**Comment by priseborough** [comment]
Flight results on an Iris with EK2_ALT_SOURCE = 2 were excellent, however the logs showed that the second IMU ran into difficulties, so the PR will be re-opened once the reason for this is understood.

**Comment by priseborough** [comment]
The problem was caused by attempting to use height fusion when GPs was available, but before the origin was set. This caused it to go without height measurements between gaining GPs lock and passing checks. Patches have been pushed to prevent this occurring.

**Comment by tridge** [comment]
Tom, we need to look at using the HAGL output of the EKF in plane for landing (and for auto generally?) instead of direct rangefinder data

**Comment by priseborough** [comment]
I have resisted the temptation to start adding more modes to this PR because i wanted to get a no-frills GPS mode in first, then start looking at smart ways of transitioning between modes based on sensor quality. 

One option is a hybrid mode that uses a combination of GPS and Baro that will reduce the height changes associated with Baro position and drift error, but also provide acceptable protection agains GPS glitches. It would run a small auxiliary EKF to fuse the baro and GPS data using the GPS receivers published vertical accuracy. The states would be GPS offset, Baro offset, height and height rate. The height state would be used as an input by the main EKF. The Baro observation error would have the ability to scale with filtered XY acceleration on Copters which is is a measure of dynamic pressure and proportional to Baro positional errors.

**Comment by priseborough** [comment]
I have completed flight testing of the EKF2 code with:

two flight on a 3DR quad using optical flow. one with baro and one with range finder.
two flights on a 3DR Iris+ using gps alt with dual EKF2 using IMU1,2
two flights on a 3DR Solo using baro alt using dual EKF2 for IMU1,3
two flights on a Skyhunter plane using gps alt - one with EKF and EKF2, and one with dual EKF2

Flights went well.

**Comment by priseborough** [comment]
Innovations from todays flight with the skyhunter plane:

vel innov
pos innov
mag innov
height innov

**Comment by priseborough** [comment]
Any issues with this PR?

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
