### PR TITLE
AP_ Compass backend/frontend separation

### PR DESCRIPTION
**Pull request by vmayoral**

### CODE REVIEW

**Comment by tridge** [comment]
Hi Victor, how are you running the script? You need to open a terminal and run it from there. You should run it from the ardupilot directory, like this:
  Tools/scripts/build_all.sh
Have you made any more progress on the compass split? I'd really like to get the frontend/backend separation in if we can

**Comment by vmayoral** [comment]
Thanks @tridge.

Just checked the branch and fixed a minor issue. The code compiles but we haven't tested it yet with a plane or a copter. 

@ahcorde is working on the LSM9D driver (https://github.com/ahcorde/ardupilot/commits/lsm9ds0-2files) and @enter-the-bot pushed support for the MPU9250 compass. As soon as we get the LSM9D we will test it.

@tridge feel free to take a look at our work in https://github.com/ahcorde/ardupilot/commits/lsm9ds0-2files and provide feedback.

**Comment by tridge** [comment]
hi Victor, it doesn't rebase on master and doesn't build for all platforms.
Are you still working on this PR? If you are then that is fine, if not then let me know and I'll work on finishing it off as I get time.
Cheers, Tridge

**Comment by vmayoral** [comment]
@tridge, spent some time rebasing the code and trying to make it compile with all the vehicles.

I do not know how i should proceed with `AntennaTracker` though. Let me know and I'll address it.
Regards

**Comment by vmayoral** [comment]
It seems there's also an issue with the PX4 compilation:
```
/home/travis/build/diydrones/ardupilot/libraries/AP_Compass/Compass.cpp:346:18: error: 'AP_Compass_PX4' has not been declared
```

**Comment by vmayoral** [comment]
It seems that the `AP_Compass_PX4` driver hasn't been ported to the back/front-end separation. I'll put some time on it tomorrow.

**Comment by tridge** [comment]
Thanks Victor. If you take it as far as you can, then when you are stuck push what you've done to the branch for this PR and I'll have a look. I am at a conference this week so I may be slow to respond.
Note that we now have frontend/backend split for AP_GPS, AP_Baro, AP_Rangfinder and AP_InertialSensor so those should provide you with some good examples of how to do the split. The AP_Baro was done quite recently and may be the best example to follow.

**Comment by tridge** [comment]
it looks like it is just the Replay build failing. I've pushed a fix for that here:
https://github.com/tridge/ardupilot/commits/erlerobot-ap-compass-separation
I think the travis build will pass with that fix. So next step is to check that it also works correctly on all boards!

**Comment by vmayoral** [comment]
Thanks @tridge! I plan to check it tomorrow with our boards.

**Comment by tridge** [comment]
One thing that could be improved is moving more of the common code into AP_Compass_Backend.cpp
For example, each driver has code that does rotations and fills in _compass._field[]. It would be better to have a _copy_to_frontend() function in AP_Compass_Backend, and make the _field variable be a private variable in Compass, but make AP_Compass_Backend a friend class of Compass. That would allow the removal of that common code, so each driver doesn't need to worry about the offset, rotation etc which is in common.
Have a look at _copy_to_frontend() in AP_Baro as an example.
The general principle is to make the sensor drivers for each magnetometer type be as simple as possible, and put the common code in the frontend or parent backend class.

**Comment by tridge** [comment]
this PR still needs a lot of work. It doesn't run at all on PX4, and mixes up frontend instance indexes with backend sensor indexes. I'll work on it when I get time.

**Comment by tridge** [comment]
I've finally had some time to work on this and I've pushed it to master
Note that I changed it so that PXF and NAVIO will try to load both hmc5883 and AK8963 drivers
Thanks for your work on this!

**Pull request closed without merging**
