### PR TITLE
Fix some warnings (v2)

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by guludo** [comment]
Looks good to me. There's just a suggestion for *future* improvements in ca0d4bf ("Filter: silence warning about unused function").

**Comment by lucasdemarchi** [comment]
previous comments: https://github.com/lucasdemarchi/ardupilot/commit/ca0d4bf23b59628f2a27eef65583f32090cce9e5

New version force pushed.

**Comment by guludo** [comment]
LGTM.

**Comment by lucasdemarchi** [comment]
Applied.

**Pull request closed without merging**
