### PR TITLE
Landing gear pr

### PR DESCRIPTION
**Pull request by R-Lefebvre**

### CODE REVIEW

**Comment by rmackay9** [comment]
It's looking pretty good.  If you could zap the relay feature I'll pull it into master.

**Comment by R-Lefebvre** [comment]
Those changes are done.

**Comment by R-Lefebvre** [comment]
Added auto-deploy function for Land, RTL and Auto modes.  Tested and works.

**Comment by rmackay9** [comment]
Merged, thanks!
I made some format fixes (spaces vs tabs) and moved the command_mode to become and enum.  In general we're trying to move to enums over #defines although there are still many places in the code where we haven't switched over.. still for new features we should use enums.

**Comment by R-Lefebvre** [comment]
Strange, I wonder why those tabs appear.  I have it set to spaces.  But I have also noticed that sometimes a blank line has a tabs/spaces hidden in it.

**Comment by rmackay9** [comment]
@R-Lefebvre, I think it's because you copied some of the lines above your code (as a basis for your change) and that existing code also has the formatting issue.  I.e. existing code has bad formatting, you copy-pasted part of it.

**Comment by R-Lefebvre** [comment]
It might be because I started with AP_Parachute and hacked it up.  Will try to be more careful.

**Comment by Thidsa** [comment]
Are this in the latest dev or will it be included when 3.3 go rc?
Loaded todays dev, but could only find the LGR_SERVO pwm values that seemed to relate to this

**Comment by R-Lefebvre** [comment]
This is currently in Master.

**Comment by Thidsa** [comment]
Ok. Thought the nightly(daily) builds came from master.

**Comment by R-Lefebvre** [comment]
They do.  What is it you're not seeing?

**Comment by Thidsa** [comment]
Wow, your answering fast :)
Well that i dont know. It ought to be more than just the 2 LGR pwm parameters. I may have missed something.  How do i choose which channel to connect the retracts to. Noticed in your files that one had to set 29 in ch 7 or 8. It was missing from the dropmenu in extended tuning. 29 was not mentioned in the  explaination in parameter list for the 2 LGR parameters either.

**Comment by R-Lefebvre** [comment]
Ok, so that is because MP only gets updated once the release is done.  If you set that function to 29 in the Advanced Parameter List it should just work.  Test safely before flying of course.

**Comment by Thidsa** [comment]
Ok great. Ill try it. Thanks

**Comment by furynick** [comment]
It's a great improvement but CH[9-16] can't be used for this (nor anything else I guess).
How can I setup 6 different flight modes (CH5), RTL (CH7), simple mode (CH8), chute (CH9?), landing gear (CH10?) and 3 axis gimbal (CH11-13?) with just 2 free channels (CH6 is dedicated for proportional uses) ??

**Pull request closed without merging**
