### PR TITLE
Different offsets and expected values for compasses

### PR DESCRIPTION
**Pull request by staroselskii**
Different magnetometers should use different parameters. The PR addresses the issue stated [here].(https://groups.google.com/forum/#!topic/drones-discuss/c9YeCOiq1KU).

### CODE REVIEW

**Comment by magicrub** [comment]
@enter-the-bot, how difficult would this be to port to Plane and/or Rover too?

**Comment by lucasdemarchi** [comment]
Nice. @guludo did something similar but for the INS while adding proper support for LSM9DS0 (https://github.com/diydrones/ardupilot/pull/2449).  The structure looks good to me.

**Comment by tridge** [comment]
I think this is a good change.
Randy, are you OK with this?

**Comment by rmackay9** [comment]
To be honest, I'm not a huge fan of this approach.  The pre-arm checks are meant to be a high level sanity check that the system is ok.  I think it's best to have those checks in the pre-arm check code itself.
This patch moves some of those "what is sane?" definitions down into the compass library and then duplicates them.  It seems this just makes it more difficult to understand what the sanity checks are.

**Comment by tridge** [comment]
Randy and I have discussed this, and we think adding new public interfaces that present milligauss as a float vector makes sense. So get_field_milligause() and get_offsets_milligauss().
Each compass backend sensor driver would need to provide a get_milligauss_scaling() function which would give the scaling factor between sensor units and milligauss.
We would then change consumers of the public compass interface to use the milligauss functions, but we would leave the application of the compass offsets in sensor units so we don't break existing users
This means we don't need the get_expected*() functions and get_max_offsets*() functions.

**Comment by ivereninov** [comment]
@tridge @rmackay9  May I suggest that we stick to SI units in the code? For magnetic field strength uT (micro Teslas) are proper units. Gauss is used in CGS. 

Another argument for uT is that they are 10 times smaller than mGa and users won't be getting 1000's in magnetometer calibration process and think that their offsets are unreasonably high (even though it is like comparing apples and oranges). They will be getting slightly lower readings than HMC reports now. (Normal field around Earth's surface is about 50uT).

It would be terrific if we can make all sensors report uT instead of bananas without making users to recalibrate their compasses. It will seriously help consistency and addition of new magnetometers in the future. It will also allow us to compare performance of different sensors.

Go SI!

**Comment by R-Lefebvre** [comment]
Agreed, we should use SI units.

**Comment by staroselskii** [comment]
@tridge @rmackay9 

Thanks for the feedback. I'm going to continue my work. It would be terrific to see these improvements in Copter 3.3.

I have a minor question, though. Not that long ago there was a need to recalibrate users' accelerometers in order to support new 3D method. How's that different from the issue at hand? 
It'd be awesome if we didn't have extra methods just to fix the inconsistency. I think, it'll bloat the interface. Is there any way we could just let ```get_magfield()``` return Teslas?

**Comment by staroselskii** [comment]
@tridge @rmackay9 

Isn't adding an additional method like ```get_field_milligauss()``` solely to fix this issue going to bloat the interface unduly and eventually make matters worse? 
Is making users to recalibrate compasses so different from recalibrating accelerometers? I'm missing something for sure.

I really don't want to add another ```ifdef``` for the compass on Navio. It seems like the wrong thing to desire.

**Comment by lucasdemarchi** [comment]
> We would then change consumers of the public compass interface to use the milligauss functions, but we would leave the application of the compass offsets in sensor units so we don't break existing users
> This means we don't need the get_expected() functions and get_max_offsets() functions.

@tridge could you elaborate on this?  How does sensor units make sense outside of the sensors themselves? What about their different sensitivity? It may need a bit more work here to achieve that, but we don't necessarily need to break users. Or am I missing something?

**Comment by rmackay9** [comment]
So the agreement on the call today was that it's ok to put this into master but we need to store the new milligaus or SI unit offsets in a new set of Vector3f parameters.  We can't just use the existing parameters because that would mean people wouldn't be notified that their compasses need to be calibrated.
Tridge and I also think we need to get in Jon's onboard compass calibration (hopefully) soon after this change goes into master so the calibration is easier for the users.

**Pull request closed without merging**
