### PR TITLE
Copter: Circular limits for pitch/roll axes

### PR DESCRIPTION
**Pull request by jolyboy**
This PR addresses the issues outlined in issue #1531

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
I've assigned myself to try and review the Tradheli portions of this.

**Comment by rmackay9** [comment]
@R-Lefebvre, ping!  I know we've all got a lot on, we should review or close down this PR though..

**Comment by R-Lefebvre** [comment]
Yep, absolutely.  This will conflict with fhedberg's structural changes unfortunately.  I had been wanting to get those in first, however, since they are very foundational.  Then this would have to be fixed.  I spoke with Jolyon a couple months ago and he was OK with fixing the inevitable merge conflicts.  But we're still waiting to get those fhedberg changes in.

**Comment by jolyboy** [comment]
Hi guys, as Rob said I'm happy to make any changes required. I'm back from
a long work trip in a couple of weeks, so hopefully the fhedburg changes
are in by then.

**Comment by R-Lefebvre** [comment]
fhedberg graciously did the work to rebase this, and it will be tested for inclusion in AC3.3-Heli:

https://github.com/R-Lefebvre/ardupilot/commits/Copter-3.3-Heli-RC13-WIP

**Comment by R-Lefebvre** [comment]
Closed due to this change being rebased and PR'd again here:

https://github.com/diydrones/ardupilot/pull/2970

**Pull request closed without merging**
