### PR TITLE
All: add smart-port support

### PR DESCRIPTION
**Pull request by multigcs**
smart-port telemetrie support

### CODE REVIEW

**Comment by gmorph** [comment]
Thanks very much for the pr Oliver.  I see there is a discussion going on between you and Matthais 
https://groups.google.com/d/msg/drones-discuss/rUXq93NUukM/S7NuUq2vMh8J
I'll wait until that discussion has come to a conclusion before putting this in.

**Comment by tridge** [comment]
the patch from Matthias is now in master. Can you test that code and then open a separate PR if there are any remaining issues? Thanks!

**Comment by leomeno** [comment]
Hello guys, thanks for the great work. Sorry for my uninformed comment here.. I'd like to test it but have not so much experience - I'd like to ask how to connect the Frsky smart-port telemetry to Pixhawk, do I need any converter (TTL/RS232?) and how to connect the 1-wire smart-port to TX and RX ? Can it be connected also using serial ports 4/5 or only 1/2 ?
Thank you very much.

**Comment by CodeChief** [comment]
The normal way I learnt to connect the X8R receiver is the Pixhawk RC port to the SBus port on the receiver. Then after seeing no RSSI I learnt it was necessary to connect a second servo cable between the Pixhawk SBus port and receiver Smart Port. Exactly what is this fix using because there is a similar patch for RSSI via SBUS "drops". If it is necessary to have a second cable to get full  telemetry then I guess this is the answer to the question, but then we don't need the RSSI over SBUS patch either  (one way for all makes sense). Please clarfy, I'm a newbie flyer but an experienced developer so I'm keen to help so long as it doesn't crash my new toy ☺

**Comment by CodeChief** [comment]
Correction I mean the second connection was between the analog RSSI port of the X8R and the SBUS of the Pixhawk. That's the only other horizontal port opposite SBUS on servo connector side of receiver.

Pixhawk <-> X8R
RC (Receiver) - SBUS
SB (SBUS) - RSSI

Very confusing because newbies think it would be simple like SBUS to SBUS.

Where is this going, how many connections/adapters do we really need if the code is designed to directly support the new FrSky X receivers?

I found that solution looking for why RSSI was missing from MinimOSD Extra.

**Comment by leomeno** [comment]
Hello CodeChief, SBUS from X8R really needs to be connected to RC port of Pixhawk, the RSSI signal from X8R, which is AFAIK PWM, not analog connects to SB port (virtual pin 103), SB means SBUS out port, which is not implemented yet, but serving as RSSI input (http://copter.ardupilot.com/wiki/common-analog-and-digital-pins-for-apm2-px4-and-pixhawk-2/).
But smart-port support is meant to utilize X8R's smart port to send telemetry data back to the radio transceiver..

**Comment by CodeChief** [comment]
OK thanks for the clarification, it's a completely different connector for the FrSky downlink then. I'll certainly be testing this. Like the idea of getting full integration on all connected devices. I'm putting together a newbie guide I'll share later once everything works. Really interested in all these protocols 8-)

**Comment by leomeno** [comment]
Hi
now i see updated wiki with connection description for s.port, thanks !
http://copter.ardupilot.com/wiki/common-frsky-telemetry/
Maybe worth to say that mentioned SPC cable is a plain diode as can be clearly seen and also can be read in some frsky docs.

**Pull request closed without merging**
