### PR TITLE
waf: standardize paths [v4]

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

this is the next version of #3472.

Diff is:
 - No more helper called `sketch`. It was a bad choice for a name. Just using `program`.
 - Option `destdir` renamed to `blddestdir` so that there's no confusion with installation option `destdir`.
 - Removed the `is_sketch` option and added the options `use_legacy_defines` and `program_name`.

@cmarcelo would you mind taking a look?

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
LGTM. I'll wait for @cmarcelo's feedback

**Comment by cmarcelo** [comment]
+1

But consider the comment :)

**Comment by lucasdemarchi** [comment]
@cmarcelo I like your sugestion... then we don't need to change how names are created. @guludo ?

**Comment by guludo** [comment]
> @cmarcelo I like your sugestion... then we don't need to change how names are created. @guludo ?

I like it too :-)

Let's just use the suffixes then, just like we do for the make wrapper:
`waf copter`
`waf plane`
`waf rover`

Do we have a consensus? :-)

**Comment by lucasdemarchi** [comment]
yes

**Comment by guludo** [comment]
@lucasdemarchi @cmarcelo 

Hi, I just added some commits for the build shortcuts. I could try fixing up the commits, but there were also changes required for the make wrapper to work properly (at *any* point in history :-)). So I decide to just go and add changes on top.

**Comment by cmarcelo** [comment]
+1

**Comment by lucasdemarchi** [comment]
> Just curious, do we need to support this case (I want to use a shortcut AND pass some extra targets)? Vs. simply overriding.

I think it could be used in future to create targets like copter-debug so we add some CPPFLAGS for example.

**Comment by cmarcelo** [comment]
> I think it could be used in future to create targets like copter-debug so we add some CPPFLAGS for example.

Sure. I'm not questioning having the function and having other shortcuts.

I'm wondering why preserving other _targets_ passed in the command line.

**Comment by lucasdemarchi** [comment]
> I'm wondering why preserving other targets passed in the command line.

ahh... ok.. targets. not sure it's useful, but doesn't hurt neither for now.

**Comment by lucasdemarchi** [comment]
I did some quick tests... works very nice, thanks. Applied.

**Comment by guludo** [comment]
> Just curious, do we need to support this case (I want to use a shortcut AND pass some extra targets)? Vs. simply overriding.

Yes, you can. :-)

**Comment by guludo** [comment]
>> Just curious, do we need to support this case (I want to use a shortcut AND pass some extra targets)? Vs. simply overriding.
>
> Yes, you can. :-)

Oops, I misread the question. Not sure if we needed. hehe

**Pull request closed without merging**
