### PR TITLE
Added ArduBoat

### PR DESCRIPTION
**Pull request by rotcehdnih**
Coped apmrover and renamed all strings to boat as a good fist step to moving away rover

### CODE REVIEW

**Comment by gmorph** [comment]
Hi Hector.  To date we have decided that separating Rover and Boat isn't necessary.  I was wondering if you had some thoughts as to why the split is necessary?  Do you have future software development plans that would necessitate this split?  The reason we DON'T want to split is code maintenance.  The boat and rover functionality is so similar at the moment there is no need for the overhead of having to maintain, build test an entirely new vehicle platform.

Looking forward to hearing from you.

Thanks, Grant.

**Comment by R-Lefebvre** [comment]
If this is just an issue with semantics (rover vs. boat) why not just change the name to "surface"?  That is typically what the RC hobby industry has used.

**Comment by rotcehdnih** [comment]
Fair call after thinking about it there is no real reason it would be needed at this time , i had idea's about submarine's and different sensors needed but this isn't the correct path.

**Comment by gmorph** [comment]
A submarine sounds awesome!  If your working on one we would love to see a post with pictures on it somewhere - maybe ArduBoat users group or Drones Discuss?
Thanks, Grant

**Pull request closed without merging**
