### PR TITLE
minlure: allow detecting internal and external compass

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

Mainly, this PR allows one to plug an HMC5883L external compass in minlure's I2C port so that she can configure arducopter to use it as primary instead of the internal one (HMC5883L through MPU6000).

Additionally, the example program is changed to output data from all the available compasses.

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@tridge remember we talked about the issue with the additional rotation on HMC5883L? This is the new attempt to fix it.  We had a successful flight test with the 3DR gps + compass module. Could you take another look?

**Comment by lucasdemarchi** [comment]
@vmayoral @staroselskii can you check if it continues to work for you with an external mag attached?

**Comment by lucasdemarchi** [comment]
@guludo this looks good to me. I'll let it here a couple more days to allow for testing.

**Comment by vmayoral** [comment]
@lucasdemarchi @guludo,
Tested the branch with a `ROTATION_ROLL_180` rotation. Looks good on Erle-Brain 2.

**Comment by lucasdemarchi** [comment]
@vmayoral did you have to add a rotation for it to work?  Or was it already the rotation for Erle-Brain 2?

**Comment by vmayoral** [comment]
@lucasdemarchi, we had to add the rotation  (about [here](https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Compass/AP_Compass_HMC5843.cpp#L472).)

**Comment by guludo** [comment]
@vmayoral, your link is pointing to master :-)

Btw, is the device set as external?

**Comment by vmayoral** [comment]
My bad. Thanks @guludo, updated.

> Btw, is the device set as external?

Commented https://github.com/guludo/ardupilot-1/blob/minlure-external-compasses/libraries/AP_Compass/Compass.cpp#L448 for the test but did not modify set it as external.

**Comment by guludo** [comment]
@vmayoral 

What if you set it as external? Will the additional rotation still be needed?
I think another possible thing that might contribute for the need of an additional rotation is when the HMC5583L rotation is done now. I changed to be applied before all the correction and publish methods, as it seems more correct.

**Comment by vmayoral** [comment]
@landerU can you give it a try and describe what you observe setting the "external" boolean?

**Comment by lucasdemarchi** [comment]
I applied the patches here that are changing the compass_test program to output multiple compasses

**Comment by lucasdemarchi** [comment]
@landerU any update on this?

**Comment by LanderU** [comment]
Sorry, tested. Works well.

**Comment by lucasdemarchi** [comment]
New version: #3792

**Pull request closed without merging**
