### PR TITLE
Remove most parts of AP_Progmem

### PR DESCRIPTION
**Pull request by lucasdemarchi**
The goal of this PR is to remove most of AP_Progmem. The only bits still here are the `pgm_read_*()` calls. I'll do them later if nobody goes ahead and finish the removal. 

If you try to review this through github UI or simply showing the commits you will have a hard time. With this command it's much easier to review:
`git show --word-diff-regex="[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+" --color-words=. <commit>`

Or you may be able to tell your preferred [T|G]UI to use these arguments to git-diff when displaying to commits. This way you can see why I split the commits the way I did: it's clear the "search and replace" throughout the codebase making it much easier to review.

I know this will cause some headache for people rebasing their branches. Thus I'm nominating myself to help on rebasing the branches (particularly pending PRs) when this goes in :-)

### CODE REVIEW

**Comment by magicrub** [comment]
is the (double) promotion still needed with this new print?

**Comment by lucasdemarchi** [comment]
@tridge i'm assigning this to you since you commented on the strategy to do this: https://github.com/diydrones/ardupilot/pull/3066#issuecomment-150367195

I shortcut a little bit and put everything in the same PR, except for the pgm_read_*() removal.

**Comment by lucasdemarchi** [comment]
@magicrub new print? I doesn't actually change any code with the exception of removing the indirections (and thus reducing 100 bytes on the binary size for PX4).

**Comment by tridge** [comment]
hi Lucas,
This looks good, but I'd like Jon and Sid to look at it. They are in the middle of a huge Solo merge at the moment, and I don't want them to give up on the merge because of this.
One option would be to remove all existing uses of PSTR() and PROGMEM, but leave the macros in for now to make merging easier, then remove the macros in a months time.
Jon and Sid, can you give your thoughts on this? Sid, could you see if rebasing your Solo branch on this is doable?

**Comment by lucasdemarchi** [comment]
@tridge this is why I removed PSTR and PROGMEM from users and only on the last commits I actually removed them from AP_Progmem.  I can rebase without the commit with the final removal if you prefer.

**Comment by jschall** [comment]
I don't think you should delay progress for us - we should be able to deal with rebasing. All we need to do is remove usages of PSTR and PROGMEM from our code?

**Comment by lucasdemarchi** [comment]
@jschall and all functions ending with _P() and those using prog_char_t. It's basically a search and replace like I did in this PR. Thanks.

**Comment by rmackay9** [comment]
I've checked with Jon and he says they will work around the merge conflicts so we're good to proceed.

**Comment by lucasdemarchi** [comment]
I just rebased the PR and added some more fixes to printf() in rover and things that entered in the repository meanwhile.

**Comment by rmackay9** [comment]
merged, thanks!

**Pull request closed without merging**
