### PR TITLE
GPS example

### PR DESCRIPTION
**Pull request by EShamaev**
Added comments to GPS example

### CODE REVIEW

**Comment by EShamaev** [comment]
Added AP_HAL::Storage example

**Comment by EShamaev** [comment]
How can build fail for comments? No code was changed. I think there is a different issue with building that you may have.

**Comment by magicrub** [comment]
Are you rebased onto master?

**Comment by EShamaev** [comment]
>> Are you rebased onto master
Not sure what you mean.

**Comment by magicrub** [comment]
Well it's passing now, must have been a glitch in the matrix.

**Comment by rmackay9** [comment]
merged, thanks!

**Pull request closed without merging**
