### PR TITLE
Add option to use GPS height for navigation

### PR DESCRIPTION
**Pull request by priseborough**
Use of GPs alt is selected by setting the EKF_ALT_SOURCE parameter to 2
Reverts to Baro if GPS times out.
Calculates and offset to be applied to Baro height to prevent height jumps when reverting, either due to to loss of GPS or changing the  parameter.
Baro height is used prior to setting the GPS origin

### CODE REVIEW

**Comment by ThorstenDP** [comment]
Thanks!

**Comment by jpkh** [comment]
I am not really sure if this is a good thing to do, I already proved on early dates of Arduplane and copter development that GPS height can be really bad on certain areas of the world. Just as example here in Thailand we measured over 200 meter changes on GPS altitude in less than 5 minutes of time. And it's not just single occasion, it's constantly drifting up and down. 
Sure close to allied airbases it is usually rather accurate but further you go worse it gets.

**Comment by ThorstenDP** [comment]
Hi Jani,
ok, this is problematic! The good thing with Paul's approach is that you can switch it off.
In Europe the GPS height - at least relative - seems to be (much) more stable compared to the baro. And over longer flights there can easily be offsets of 10+ meters, which might lead to dangerous situations regarding RTL. There are some discussions at drones-discuss:
https://groups.google.com/forum/#!topic/drones-discuss/xzUL7P9gNU0
https://groups.google.com/forum/#!topic/drones-discuss/idiv0aHJA-0
Cheers,
Thorsten

PS: maybe some warning should be reported to the GCS is the baro and the GPS alt differ > 10-15m

**Comment by priseborough** [comment]
The default parameter setting will use baro, so users have to opt in if they wish to use GPS alt.

Also we are getting some users that wish to integrate GPS units with RTK, dual band and other technologies that provide good height accuracy.

**Comment by magicrub** [comment]
@priseborough any thoughts on adding lidar support to this? In my application, I fly with Baro + lidar, and maybe GPS+lidar is helpful but lidar is a must and right now in plane it's just hacked in.

**Comment by BitMapping** [comment]
@magicrub I am wondering if LIDAR is a good idea here, because it is a relative - to the ground - altitude and thus I am not sure what will happen if you fly in an area with single trees or houses. LIDAR is perfect for measuring the distance to ground but not for navigating and keeping an altitude. Or am I mixing up something?

**Comment by magicrub** [comment]
@BitMapping That's a good point, I hope @priseborough handles that correctly when doing his optical flow+sonar integration. I'm just suggesting he do whatever he did with optical flow+sonar to apply it to lidar too or any generic rangefiner, especially since more people are using rangfinders than optical flow.

**Comment by magicrub** [comment]
@priseborough you may want to change the @ Values name from "Range Finder" to "Optical Flow" since this does not actually utilize a traditional rangefinder. (also, add 3: Rangefinder via https://github.com/diydrones/ardupilot/issues/2402)

// @Param: ALT_SOURCE
// @Description: This parameter controls which height sensor is used by the EKF. A value of will 0 cause it to always use baro altitude. A value of 1 will use the baro sensor, but switch to the range finder during optical flow navigation. A value of 2 will cause it to use GPS and switch to the baro sensor if GPS is not available.
// @Values: 0:Baro, 1:Range Finder, 2:GPS

**Comment by tridge** [comment]
hi Paul, after the discussions on the call yesterday I have rebased this patch here:
https://github.com/tridge/ardupilot/commits/priseborough-pr-enableGpsAltUse
can you check it over and see if you are happy with the rebase conflict resolution?

**Comment by tridge** [comment]
I also wonder if we should have a limit for how much the GPS and BARO are allowed to diverge. It would be quite possible to use this safely on a ublox I think if we stopped using the GPS if it diverged from the baro by more than 10m or so. That would allow it to ride our baro errors in corners, but revert to baro if GPS alt goes way off

**Comment by WickedShell** [comment]
Hard to say on that divergence, in some ways thats exactly why flying GPS altitude instead of baro altitude would be nice, is to handle drift over long flights. I've found flights with ~15 meters of error at the time of landing to be fairly common when flying past the 2.5 hour mark.

**Comment by tridge** [comment]
maybe we need a parameter for the maximum baro<->gps difference?

**Comment by Jman841** [comment]
+1. The whole point of using the GPS Altitude is to not have to worry about baro drift.

Maybe raise a warning in the GCS is there is a change over a certain amount?

Maybe if the change in altitude happens quickly with no change in pitch or attitude then it could be considered a glitch?

Maybe there could be a way for the operator to reset the baro altitude to the GCS altitude if they believe the GCS altitude is more correct than the Baro altitude? 

Especially if using an RTK GPS, I think the GPS altitude would be preferred over the baro.

**Comment by ThorstenDP** [comment]
I am not sure if reverting back is a good idea in all cases. I also found >10m difference within 45min and the GPS altitude was correct in all cases. But in environments with poor GPS reception it is another story. But in theses cases users should leave the setting to 0:Baro. I also like the idea of a warning in the GCS if there is a certain difference (>5m?) between GPS and baro altitude.

**Comment by priseborough** [comment]
If we do revert due to baro and GPS moving apart, it shouldn't be a snap back, it should start tracking a baro height that has a constant offset added to it so that there is no jump in EKF height at switchover, It should also go back to using GPS when the difference reduces below the threshold. 

The number of metres of difference required to revert to Baro should be a parameter so that setting it to zero disables the reversion. There are setups where using the Pixhawk Baro sensor will cause a crash, e.g. jets.

**Comment by meee1** [comment]
ive test flown this patch, logs are here http://vps.oborne.me/rtk/sept%20quad%209-9-2015/

**Pull request closed without merging**
