### PR TITLE
Fixes in Linux support

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Fixes to how the threads are spawn.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Not sure why CI is failing, it seems not to be related with the commit that failed... maybe removing the first commit, that's not really related to the rest will fix it.

**Comment by vmayoral** [comment]
makes sense. Thanks for putting time into this @lucasdemarchi.

**Comment by lucasdemarchi** [comment]
@tridge  do you want that the commits be separate in smaller pull reqs?

**Comment by magicrub** [comment]
That is always helpful.

Tridge has been traveling the past few weeks so he hasn't had time to look
at the recent Linux pull requests.

**Comment by lucasdemarchi** [comment]
Ok, so I'm closing this pull request. I just created several separate pullreqs for each issue and also fixed the build in travis.

**Pull request closed without merging**
