### PR TITLE
DataFlash_test:make it works with PX4 FMUv2

### PR DESCRIPTION
**Pull request by rentt**
I am new to APM code and still learning the examples of APM. The DataFlash_test app seems outdated and has compiling errors (make px4-v2). I have changed the code and made it work on PX4 FMUv2. I have not tested it on other platforms for I don't have the boards. Hope the developers can review the source and make it workable on other platforms.

PS: For such a case, is it right to open a pull request instead of reporting an issue?

### CODE REVIEW

**Comment by gmorph** [comment]
We can't include this PR as it explicitly breaks all other boardtypes except Pixhawk V2.  It need's to be fixed to work with all board types.

**Comment by proficnc** [comment]
Can you clarify? PX4-V2 or Pixhawk 2

Pixhawk 2 is the same as Pixhawk 1 from the point of view of compilation

**Comment by tridge** [comment]
looks good to me, but I'll assign to Peter as dataflash maintainer

**Comment by rentt** [comment]
I mean I have only tested on px4 FMUv2 board.

**Comment by peterbarker** [comment]
rentt,

  Thanks very much for getting this test working again!

  I'm happy for this code to be merged in.

  A couple of things, 'though.
 - you've lower-cased "DataFlash" -> dataflash as a member name.  AFAIK, thats good style - but it now doesn't match the rest of the code where we *do* use "DataFlash" as a variable name.  It's also code-churn.
  - we have the concept of "sitl" and "linux" builds ("make sitl" and "make linux").  These let us test things are in reasonable working shape quickly.  You didn't break them!  On the other hand, they weren't working, either.  I've taken the liberty of getting them working (a patch on top of your patch): https://github.com/diydrones/ardupilot/pull/2645

Thanks!

Peter

**Comment by rentt** [comment]
Peter, thanks for reminding me. I should have read the wiki more carefully.

**Comment by peterbarker** [comment]
This fix was pulled in as part of #2645 - thanks!

**Pull request closed without merging**
