### PR TITLE
Finish removal of FastDelegate

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Ohh... AntennaTracker hasn't been ported yet. this pull request will have to wait for that one.

**Comment by lucasdemarchi** [comment]
There wasn't much left on this pullreq after AntennaTracker was converted. I just left the 1 change above.
@magicrub what's the "ready" label?
@tridge  comments?

**Comment by magicrub** [comment]
It is from waffle.io that I am experimenting with. Disregard it.

**Comment by rmackay9** [comment]
merged, thanks!  (Tridge checked too and said "ok")

**Pull request closed without merging**
