### PR TITLE
GPS Glitch Detector

### PR DESCRIPTION
**Pull request by bugobliterator**
This PR solves the issue of erratic behaviour when there is momentary or long term GPS glitch during GPS aided flight modes. The patches included with this PR will make arducopter switch to non-GPS aided mode ALT_HOLD in which the copter will maintain its height with imprecise horizontal position, so user can takeover and take action to save from copter doing damage to itself or surrounding. There is addition of parameter "FS_GPS_GLITCH" which will enable/disable and determine the behaviour of copter in the case of gps glitch as reported by EKF.
Assigned to @rmackay9 for review.

### CODE REVIEW

**Comment by WickedShell** [comment]
I like the idea of FS_GLITCH_GPS and was about to open an issue for place
to do change to circle in that case. Guess I still need to make the issue.
Well look at what's here though.

**Comment by OXINARF** [comment]
My comments:

- this suffers the same problem that Solo had, you can enter RTL if GPS has a glitch: 3drobotics/ardupilot-solo#189
- I think that the change to ALT_HOLD should be configurable, for example to be able to LAND

Also I just noticed that when in RTL and a glitch happens it only changes to ALT_HOLD if it is in the landing phase, why is that?

**Comment by severinleuenberger** [comment]
Could this logic and new parameter FS_GLITCH_GPS be applied to arduplane as well? 
I think for arduplane the FS_GLITCH_GPS "enabled" should trigger a fixed wing plane in a auto-mission or RTL to switch to flight mode "loiter".

**Comment by WickedShell** [comment]
How about circle for plane? loiter needs GPS.

**Comment by severinleuenberger** [comment]
Yes,  i forgot about loiter needs GPS. Circle is ok, and better than switch to FBWB,  because at least there is no fly away.

**Comment by jschall** [comment]
Planes are different because they can dead-reckon on airspeed and they're not a hovering vehicle... I would agree with having an option to LAND.

**Comment by WickedShell** [comment]
You say they can dead reckon, but I've seen it in flight and its so far off
that you do not want to do that... It won't land anywhere near where you
would expect. That's been my experience any ways.

**Comment by severinleuenberger** [comment]
Planes should switch to circle when a GPS glitch is detected. Land is not an option. On circle,  the operator can takeover the aircraft. A steady mavlink message informing about the ongoing GPS glitch would help to recognize it as  operator

**Comment by rmackay9** [comment]
The handling of RTL is interesting.  It's basically treated as a pilot-controlled-GPS-mode (like Loiter) but then when the glitch triggers it doesn't actually do anything unless it's in the land-phase.
This means if fs_gps_glitch_type == FS_GPS_GLITCH_ENABLED_NON_AUTO and the glitch triggered just before the vehicle reached home the gps-glitch state would become true but it would still transfer into the land-phase using GPS.
It might make more sense to treat RTL like Auto and Guided.  If we're keen to split RTL so that the first stages are like Auto/Guided and the final landing stage is like Loiter then in gps_glitch_update() it should bail-out if g.fs_gps_glitch_type == FS_GPS_GLITCH_ENABLED_NON_AUTO if rtl is in one of it's earlier stages.

I hate to mention it but if you're going to split RTL's classification into bits, I think you'll need to split Auto-RTL as well.

**Comment by rmackay9** [comment]
Sorry to be so picky about all this, the GPS glitch protection is a really important feature so we really appreciate the contribution.

**Comment by magicrub** [comment]
For plane, RTL is a state that the aircraft is really only briefly in. It
sets home as a waypoint then flies in auto. There is almost no distinction
from RTL and AUTO.

**Comment by jschall** [comment]
Yes, leaving out RTL, POS_HOLD and DRIFT was a mistake.

**Comment by bugobliterator** [comment]
@jschall do you think this PR is relevant. If not can you close it?

**Comment by jschall** [comment]
This needs to be significantly reworked before it will be ready.

**Pull request closed without merging**
