### PR TITLE
waf: standardize paths

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

this PR addresses #3429 .

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
> With that, for example, the path 'build/linux/INS_generic.linux' becomes
> 'build/linux/libraries/AP_InertialSensor/examples/INS_generic/INS_generic'.

I don't like it much. It's way too long. I agree the `.o` objects should be in their own directory to avoid name conflicts. However I'd like to keep binaries as close to the build root as possible. How about having the vehicle binaries in `build/<board>/bin/` and tests in `build/<board>/tests/`?

**Comment by guludo** [comment]
@lucasdemarchi 

> How about having the vehicle binaries in build/<board>/bin/ and tests in build/<board>/tests/?

Well, I believe vehicles binaries won't have same names. However, for tests and benchmarks, if the binaries are placed directly into that folders, name conflicts are still possible.

Although I'm a bit uncomfortable with the idea of not having a unique standard for binary paths, I like the idea of having them close to the build root. So, here is my suggestion:
 1. We keep these patches, i.e., binaries are put into their "equivalent build directories".
 2. Then, we copy:
     - vehicle binaries to `build/<board>/bin/` (maybe `build/<board>/vehicles/`?)
     - test binaries to `build/<board>/tests/`
     - benchmark binaries to `build/<board>/benchmarks/`
 3. If there are name conflicts during (2), we either fail the build or raise a warning. I vote for the latter.

What do you think?

**Comment by lucasdemarchi** [comment]
I don't like it:
 - vehicle and hel binaries will end up installed in /usr/bin, so their names can't really conflict
 - tests and benchmarks should be named after what they are testing so shouldn't conflict as well. If in future they do, then we can revisit this decision. But this would also avoid giving bad names to tests :)

**Comment by guludo** [comment]
> vehicle and hel binaries will end up installed in /usr/bin, so their names can't really conflict

Yes, I said that before "Well, I believe vehicles binaries won't have same names."... What do you mean by "hel"?

> tests and benchmarks should be named after what they are testing so shouldn't conflict as well. If in future they do, then we can revisit this decision. But this would also avoid giving bad names to tests :)

If that's so, then we should fail the build if there are conflicts.

------------------------------

So let's:
 - remove (1)
 - change (2) so that they are not copied but built at those directories
 - and keep (3) with the choice of failing the build when there are conflicts

About (2), I like `build/<board>/vehicles/` better than `build/<board>/bin/` -  tests and benchmarks are also binaries :-) after all.

**Comment by lucasdemarchi** [comment]
Em 8 de jan de 2016 10:16 AM, "Gustavo José de Sousa" <
notifications@github.com> escreveu:
>>
>> vehicle and hel binaries will end up installed in /usr/bin, so their
names can't really conflict
>
> Yes, I said that before "Well, I believe vehicles binaries won't have
same names."... What do you mean by "hel"?

Should have been " helper".

>>
>> tests and benchmarks should be named after what they are testing so
shouldn't conflict as well. If in future they do, then we can revisit this
decision. But this would also avoid giving bad names to tests :)
>
> If that's so, then we should fail the build if there are conflicts.

We shouldn't need to do anything special for that. It should already fail
in this scenario

>
> ________________________________
>
> So let's:
>
> remove (1)
> change (2) so that they are not copied but built at those directories

Ack

> and keep (3) with the choice of failing the build when there are conflicts

See above

>
> About (2), I like build/<board>/vehicles/ better than build/<board>/bin/
- tests and benchmarks are also binaries :-) after all.

AntennaTracker is not a vehicle ;). bin/ is because of binary and because
the root build directory could have name conflicts with directories... Any
binary that we would end up installing would be put there. Just like they
will be in /usr/bin when you install them.

Tests and benchmarks could have their directories because they are "a
developer thing"... They don't end up installed later on.

**Comment by guludo** [comment]
@lucasdemarchi 

>> If that's so, then we should fail the build if there are conflicts.

> We shouldn't need to do anything special for that. It should already fail
in this scenario

It actually doesn't fail :-) It is maybe worth a patch to waf upstream. I'll ask Thomas if that's an intended behavior.

> AntennaTracker is not a vehicle ;). bin/ is because of binary and because
the root build directory could have name conflicts with directories... Any
binary that we would end up installing would be put there. Just like they
will be in /usr/bin when you install them.
> 
> Tests and benchmarks could have their directories because they are "a
developer thing"... They don't end up installed later on.

So, by following your logic, I see examples as a "developer thing" too. So they also should have a directory for them. Thus:
 - `bin`: for binaries to be shipped
 - `examples`
 - `tests`
 - `benchmarks`

Do you agree?

**Comment by guludo** [comment]
/me thinking it would be nicer if this discussion was done at https://github.com/diydrones/ardupilot/issues/3429 hehehe

**Comment by lucasdemarchi** [comment]
> bin: for binaries to be shipped
> examples
> tests
> benchmarks
>
> Do you agree?

Yes

**Comment by guludo** [comment]
As for the conflicts not failing the build, it looks like that is expected in waf. If you run with `-v` a warning is raised. I guess I'll try a patch to waf upstream...

**Comment by guludo** [comment]
New version. Closing this one.

**Pull request closed without merging**
