### PR TITLE
Copter: refactor RTL to compute full path on initialization, add RTL_CONE_SLOPE

### PR DESCRIPTION
**Pull request by jschall**
Here's a handy diagram of the intended behavior of RTL after these changes:

rtl behavior

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
Interesting.  I do like the concept in general.  There is some risk of crashing into trees if the pilot flies behind a tree very close to home.  This then becomes a "well don't do that" moment.  I think it would probably not affect me as I tend to fly in clear locations, but I'm sure some will be caught out.  On the other hand, I've had RTL's from very close to home in an open field, that first climb to 30m which is silly.  Until we have optical object detection, there's got to be a compromise.  I think this is reasonable.

**Comment by jschall** [comment]
You'd have to set the slope much lower than the default of 3 to hit a tree. It'd take a pretty contrived situation to manage that otherwise. Maybe a pole...

Anyway, it is what Solo uses and we're pretty happy with it.

**Comment by rmackay9** [comment]
merged, thanks!

**Comment by drtrigon** [comment]
From the picture provided I do not understand what happens within the cone.

E.g. if I arm, start, ascend 1m and switch to RTL?
Generally what happens when switch to RTL within the cone? Is it possible than it raises to RTL_ALT?

(The picture shows a ascend of 2.5m that I don't understand.)

**Pull request closed without merging**
