### PR TITLE
Add RCOutput using Linux PWM sysfs API

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by gmorph** [comment]
Lucas - are you able to review this please?  I've eyeballed it and it looks ok but its your call.
Thanks, Grant.

**Comment by lucasdemarchi** [comment]
@gmorph yep, will do it tomorrow

**Comment by raspilot** [comment]
Is there a way to use this on Raspberry Pi? I can find bcm2835_pwm module in kernel, but nothing in /sys/class/pwm after loading the module.

**Comment by lucasdemarchi** [comment]
@raspilot do you have CONFIG_PWM and CONFIG_PWM_SYSFS in you kernel? (check /proc/config.gz)

**Comment by raspilot** [comment]
@lucasdemarchi Thanks! I will try. It's great to unify the Linux HAL.

**Comment by jberaud** [comment]
Apart from that(us vs. ns), I would just like it to be compatible with the Bebop for different purposes and then I'll add the reviewed tag. I'll let Tridge comment on the stack vs. heap on file path allocation.

**Comment by zehortigoza** [comment]
I'm not squashing this 3 new patches now because we would lost the comments.

**Comment by lucasdemarchi** [comment]
Hi @zehortigoza 

I think there are still some minor changes. I'm marking this as "need-rework". Please send a v2 in another PR with these commits on top already squashed.

**Comment by zehortigoza** [comment]
New version https://github.com/diydrones/ardupilot/pull/3039
Thanks all

**Pull request closed without merging**
