### PR TITLE
Plane: Add glitch detection to rangefinder via baro comparison

### PR DESCRIPTION
**Pull request by magicrub**
added two new params for temporarily rejecting rangefinder data if it diverges too much from baro for a short time such as flying over trees
RNGFND_CORR_CM, 500    // @Description: Amount of allowable altitude error correction when compared to the barometer. Set to zero to always accept rangefinder data regardless of what the baro data is. This helps reject rangefinder data when crossing over objects such as trees

RNGFND_CORR_MS, 2000:    // @Description: Duration to reject rangefinder data when beyond ERROR_CM height. Once this time has expired then range finder height is accepted as-is. This is typical of baro drift

### CODE REVIEW

**Comment by magicrub** [comment]
@Tridge, please review this. I have not tested it I just want to see if the methodology looks good.

**Comment by rmackay9** [comment]
you know the EKF can do height about terrain estimation with the lidar.. We're not using it in copter yet but we plan to.  I think that might be a better place to have the glitch detection although it would require getting the above-terrain alt estimate from the ekf instead of directly from the sensor.

**Comment by magicrub** [comment]
Its not coming directly from the sensor now, it's being passed through this altitude file in plane. I wanted to do it in the rangefinder driver but it got complicated with having to access baro

**Comment by magicrub** [comment]
still a work in progress so closing for now

**Pull request closed without merging**
