### PR TITLE
Use pragma once

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This replaces all occurrences (that I could find with a tweaked grep) of the header guards with "#pragma once".  We've been doing this a lot in the last months, making the changes in the same patches that do other things.  Here I try to stop that by doing all at once.

Benefit is not having to invent the name for the macro and easier maintenance. It used to yield better compiler performance, but nowadays it's the same for both gcc and clang.

I was not sure if I would split this giant commit or use a "Global:" commit. I decided to split because some maintainers may want to hold this change so it doesn't conflict with their pending changes.

### CODE REVIEW

**Comment by guludo** [comment]
Nice PR. It looks good (I just scammed it though hehe).

I'm not sure if this change would conflict with that the other maintainers are doing. Anyway, I think we can apply this as-is.

**Comment by lucasdemarchi** [comment]
@guludo I don't want to interfere too much with work in progress by other devs/maintainers. So... I applied only the the patches for AP_HAL_Linux and some other parts we're currently refactoring.

**Comment by lucasdemarchi** [comment]
I rebased on top of master, that now contains some of the previous commits.

**Comment by lucasdemarchi** [comment]
I don't want to cause trouble for other people, but I don't want this PR to bit rot too much. @tridge @rmackay9 @magicrub could you give a look on this andt tell me if it is ok (even if part of the PR)?

**Comment by OXINARF** [comment]
@lucasdemarchi Have you missed something in rebase? px4-v4 is failing in SemaphoreCI (which isn't built in Travis).

**Comment by OXINARF** [comment]
@tridge This has been merged right?

**Comment by tridge** [comment]
yes, it has been merged

**Pull request closed without merging**
