### PR TITLE
add support for BBBMINI, simple ArduPilot DIY Cape for the BeagleBone Black

### PR DESCRIPTION
**Pull request by mirkix**
With this configuration (bbbmini) it is possible to use the BeagleBone Black as a Linux flight controller by just adding a MPU9250 / MS5611 breakout board to the BBB. This makes an inexpensive way to get a Linux flight controller.

At which point additional documentation should be placed about the bbbmini? Within ArduPilot, or in a separate repository?

### CODE REVIEW

**Comment by tridge** [comment]
thanks! I was hoping someone would do this. Are you willing to work on documentation for this, perhaps writing some wiki pages on how to wire it up, power it in an aircraft, configure it etc?

**Comment by tridge** [comment]
I've pushed this to master, thanks for putting it together!
Now we just need some docs, and perhaps a blog post?

**Comment by mirkix** [comment]
Yes sure, I can do this. Maybe the dev.ardupilot.com is the best place.

**Comment by tridge** [comment]
probably best to start with this page:
http://dev.ardupilot.com/wiki/building-for-beaglebone-black-on-linux/
(a lot of it is out of date or just plain wrong)

**Comment by mirkix** [comment]
Hello Andrew,

put first content to https://github.com/mirkix/BBBMINI, but there is a lot
to do. Will will try to get more content to the page soon.

How could I get access to the dev.ardupilot.com wiki?

Did you build the RT-Kernel as described here (
http://dev.ardupilot.com/wiki/building-for-beaglebone-black-on-linux/)? Is
the PRU issue still there with the RT-Kernel?

By the way, thanks to talk about BBBMINI at the LCA.

Best regards Mirko

2015-01-19 23:44 GMT+01:00 Andrew Tridgell <notifications@github.com>:

**Pull request closed without merging**
