### PR TITLE
waf: fix blddestdir  (v2)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
v2 of #3515

Changes:
 - use `bldnode.find_or_declare()` as suggested
 - split patch

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Just added one more commit to change the binary names as discussed previously.

**Comment by guludo** [comment]
@lucasdemarchi This looks good to me. I just think we should skip https://github.com/lucasdemarchi/ardupilot/commit/7c4bc69437fec4a77f147283dabcbc1910bd3cdc (	waf: use os.path.join() for joining paths), since waf considers '/' a common path separator.

**Comment by lucasdemarchi** [comment]
os.path.join() is common language in python to join paths.Even if it works in windows without it, it would be wise to correctly join the paths... Depending on the function you call it may or may not work. Example: imagine you are calling your own function that is not prepared for that.

**Comment by guludo** [comment]
> Example: imagine you are calling your own function that is not prepared for that.

If waf it isn't aware of your system's path separator, even using `os.path.join()` wouldn't fix the problem. That's because 'Node.Node`'s functions always split the path and it uses its own functions for it, so that '/' may be recognized across systems. Furthermore, the unix style is always the fallback for the split function, see https://github.com/waf-project/waf/blob/waf-1.8.18/waflib/Utils.py#L424-L432. On the other hand, waf uses `os.sep` for making the path into string again.

Thus, `target = os.path.join(blddestdir, program_name)` might actually break the build for platforms waf isn't aware of, whereas `target = blddestdir + '/' + program_name` might work fine.

**Comment by lucasdemarchi** [comment]
@guludo we don't plan to support platforms we don't know about. When we start to support them, python/waf must support them as well.  os.path.join() is even used inside waf:
https://waf.io/apidocs/_modules/waflib/Configure.html  (or `git grep os.path.join` in waf's submodule)

using os.path.join() improves both readability and crossplatform support

**Comment by guludo** [comment]
@lucasdemarchi 
I'm not against the general use of `os.path.join()`, I also do believe it's a good practice. What I'm trying to say is that I don't see real necessity for using it **with** `waflib.Node.Node` class, since in the end the paths it receives are split independently of the current system path separator.

Anyway, it doesn't hurt to use `os.path.join()` for paths passed to `Node`, but it's just pointless in my opinion. I would go without them, but I'll leave that decision to you.

In the case of applying the use of `os.path.join()`, in order to keep consistency, we should raise a GitHub issue so that eventually all path fragments are defined using `os.path.join()`.

Lastly:

> using os.path.join() improves both readability and crossplatform support

I agree about the readability, but I can't really agree with the second argument for the reasons I pointed above.

Well, let's apply this? :-)

**Comment by lucasdemarchi** [comment]
I reworded the commit message a little bit to make sure it doesn't mention it's a fix, but just an improve in readability.

Applied.

**Pull request closed without merging**
