### PR TITLE
Navio RCInput deinitialization

### PR DESCRIPTION
**Pull request by staroselskii**
The issue has already come up. There's no deinitialization mechanisms at the moment. As APM is rather software than firmware on Linux, there're some clean-up work that needs to be done. The signal handling framework might also be needed. 

RCInput driver for Navio does need that to stop DMA in case of an error.

### CODE REVIEW

**Comment by tridge** [comment]
there seems to be some build errors?

**Comment by staroselskii** [comment]
@tridge 

Sorry for that! I guess now everything should be fine.

**Comment by staroselskii** [comment]
@lucasdemarchi 

I've slightly updated the PR. The better solution might be moving the code to kernel as stated in the commit message but that's not feasible now.

**Comment by lucasdemarchi** [comment]
> I've slightly updated the PR. The better solution might be moving the code to kernel as stated in the commit message but that's not feasible now.

IMO the only reason to move to kernel side is that opening `/dev/mem` is something that works but a) doesn't scale and b) is the wrong thing to do in a well behaved binary from the security pov.

We can easily add the code to handle the KILL/TERM/etc signals and call all the destructors we need. Since this is the only place currently getting the signals, we can live with it for now. Removing the `exit()` like you did is already good enough.

**Comment by staroselskii** [comment]
@lucasdemarchi We consider the PR reviewed then?

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi We consider the PR reviewed then?

humn... looking now, you removed the exit but added a panic() that will basically do the same thing. I wonder how you guys are handling a start/stop/restart of the ardupilot program if it always exits with an error code.

**Comment by lucasdemarchi** [comment]
Anyway, you are fixing the de-initialization which already deserves being integrated.

**Comment by staroselskii** [comment]
@lucasdemarchi 

I'll be happy to listen to an advice, Lucas!

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
