### PR TITLE
Log mission changes to dataflash

### PR DESCRIPTION
**Pull request by magicrub**
When uploading a new mission, and the new mission has completed, write the new mission to dataflash so it can be seen when updates are done after boot.

Rover and Plane both dumped their mission on boot and Copter did not. Now all three work the same and log the mission on boot and on full mission changes.

There is no logging if you change a single item of a mission.

### CODE REVIEW

**Comment by gmorph** [comment]
I "hub'd" to this and its working fine.  Code is reviewed and fine.  I couldn't figure out how to get "New mission is empty" in the log file but that's probably just my testing approach.  All good to merge.
Thanks Tom!

**Comment by magicrub** [comment]
I actually didn't test mission size == 0, just assumed it would work. If you could not get it to work then I would wonder why. I can take it out and just always print "New Mission" instead, no big deal.

**Comment by magicrub** [comment]
@gmorph I updated the PR with new commits that remove the "is empty" messages

**Comment by tridge** [comment]
applied, thanks!
(I folded the fixups into the patches)

**Pull request closed without merging**
