### PR TITLE
min()/max() rework

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This changes the implementation of the min() and max() functions. The motivation for this was that defining them as macro conflicts with some C++ headers which we need for the threaded I2C work. I decided to send this earlier so to split the review.

It's basically composed of 2 parts: 1) use another name for these macros and 2) change the implementation to be a little bit better.  Specific commits contain more detail about the changes. Particularly the last commit shows some examples of callers that benefit from these new implementations.

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks ok to me but I think the "Rename min and max macxros.." commit should be broken up into a zillion commits affecting each vehicle and then each library.

**Comment by khancyr** [comment]
Hi,
 maybe it has already be asked but why not use inline function instead of macro? With function we should not have type problem (like in your examples)
I am not fan of templates but I think in that case that it is could be more readable that the new macros 
````
template <class T> const T& max (const T& a, const T& b) {
  return (a<b)?b:a;     
}
````

**Comment by dgrat** [comment]
i totally agree with @khancyr. Using macros is in general a bad idea in a c++ environment. The only exception are code replacements for certain architectures.

**Comment by lucasdemarchi** [comment]
@khancyr @dgrat I think it's very well explained in the last commit message. Quoting the relevant part:

```
It doesn't have type safety as
std::min and std::max, but adding type safety would mean to check case
by case what would be a reasonable type and add proper casts.
```

The problem is that a template function would require the same types for the arguments and return type (it's the whole point of type safety here). However in several places we mix uint8_t, uint16_t, int (and the implicit cast to int on literals), etc... We'd need to carefully inspect the 300 call sites in order to correctly introduce the function and do the casts as needed. And risk introducing a bug.  And yes, I tried doing that before going back to a better macro.

Since with this conversion we can include the relevant C++ headers, we could encourage the use of std::min() and std::max() for new code. But for old one, doing the conversion is too troublesome.

**Comment by lucasdemarchi** [comment]
@rmackay9 I think we had a agreed to have a waiver for cases like this. It's a search and replace in the codebase. What benefits does splitting the commits give us? IMO It's rather counterproductive since it's a) harder to review, b) breaks the build in the middle and c) adds a lot of noise to git history.

**Comment by magicrub** [comment]
>> ...we could encourage the use of std::min() and std::max() for new code.

That's not the way it works. This is setting a precedent that will be
copied in the future.

**Comment by khancyr** [comment]
@lucasdemarchi ,ok I understand your point ! thanks for the explanation !

**Comment by lucasdemarchi** [comment]
@magicrub well... there's nothing wrong in using MAX()/MIN(). It's even clearer now that's a macro version since we are using all caps.  My point against doing the conversion is in the explanation above: it's a huge work prone to introduce bugs. I tried that as a first step and it didn't work.

**Comment by dgrat** [comment]
@lucasdemarchi 
Actually, application of st::min or std::max would cause a compiler error in the mentioned scenarios. 
It is defined as min(T a, T b) and when you insert mismatching types you get a simple error.
I think a compiler error is good in this project, because it is not nice programming style to compare different types in 99% of cases. 
Nevertheless, the new macros could be also implemented by a simple template function. To shift macro definitions into functions has the advantage of namespaces which can be used. This is exactly the reason why you renamed the macros. It was a name conflict. I mean everyone noticed already that there are tons of macro related errors if you try to include any bigger third party library. The only way to solve this is to remove these macros entirely and not to rename them. Next time someone tries to include another library with a MIN/MAX function will cause the same behavior.

what is wrong on a function like

<template A, template B> min (A a, B b) 
{

}

**Comment by lucasdemarchi** [comment]
@dgrat I suggest you to try using such a function in place of min() and check by yourself the nightmare it is to fix all the places. Additionally since here you have different types there's no benefit over the macro.

**Comment by dgrat** [comment]
@lucasdemarchi 
Hi there. Actually this example below seems to compile (and work fine).

    template<typename A, typename B>
    auto max(const A &one, const B &two) -> decltype(one + two) {
        auto res = one > two ? one : two;
        return res;  
    }

    template<typename A, typename B>
    auto min(const A &one, const B &two) -> decltype(one + two) {
        auto res = one < two ? one : two;
        return res;  
    }

**Comment by lucasdemarchi** [comment]
@dgrat thanks. Much better than my tentative to use a template version on Friday. I'm puzzled decltype(one + two) is the same type of one of them.

However type safety would only be possible checking case by case. Technically this is equivalent to the macro with the benefit of not conflicting with libstc++ or other libraries.  I'm wondering if we should go with it all caps or still use the same name.

**Comment by dgrat** [comment]
@lucasdemarchi 
Actually i was a bit lazy, you can put "one > two ? one : two" instead of "one + two" into the decltype() directive. I just wanted to demonstrate the approach. Your caps are okay, because I plan to replace AP_Math anyway sooner or later and the name conflict is urgent and would be solved by CAPs.
Initially, I wanted to finish the work on the Eigen library much faster, but my work catched me. However, I started to rewrite my initial commit. 

Best, Daniel

**Comment by khancyr** [comment]
@dgrat good job !

**Comment by lucasdemarchi** [comment]
Updated the PR changing the macro to a function.

**Comment by kwikius** [comment]
Hi,

Good job,

I had to do all kinds oj junk to get min max to work with Ardupilot code:
This was to get it working with AP_Param types
https://github.com/kwikius/quan-trunk/blob/master/quan/min.hpp#L51

https://github.com/kwikius/ardupilot/blob/quantracker_master/libraries/AP_HAL_Quan/ap_param_archetype.hpp

regards
Andy

**Comment by khancyr** [comment]
@dgrat @lucasdemarchi , just to be sure : 
Lucas use 
````
template<typename A, typename B>
static inline auto MAX(const A &one, const B &two) -> decltype(one > two ? one : two) {
    return one > two ? one : two;
}
````
and Daniel proposed : 
````
template<typename A, typename B>
auto MAX(const A &one, const B &two) -> decltype(one + two) {
    auto res = one > two ? one : two;
    return res;  
}
````

Is there any differences other than allocation by doing  return one > two ? one : two; directly  ??

**Comment by kwikius** [comment]
The second version with is meant to optimise better Look up NRVO RVO etc for full details

MIN and MAX with -> delctype(...) return type etc seems to build fine for me without issue
regards
Andy

**Comment by lucasdemarchi** [comment]
@khancyr the return without the additional variable should be the same. I also checked the assembly output and yes, it's line by line the same for both clang and gcc. https://gist.github.com/lucasdemarchi/b887a1cb12c36200a1e3

**Comment by lucasdemarchi** [comment]
@kwikius not in this case, probably because the function is already inlined.

**Comment by khancyr** [comment]
@lucasdemarchi @kwikius , ok thanks. That was just to be sure . I am not really use to template and using auto everywhere. (nice habit to check assembly ! I need to try to do it too)

**Comment by kwikius** [comment]
Based on this I updated my library. It is much simpler than my original code.

https://github.com/kwikius/quan-trunk/blob/master/quan/min.hpp

As to the RVO optimisation, I believe  It used once upon a time to make a difference on user defined types  where they didnt perform as well as inbuilt types (int etc)  because of their unknown side effects in constructors etc, which therefore had to be allowed to run so you couldnt elide copies etc,  however much work was done on the problem and in later version of C++ the difference is much less.  Nevertheless the second version is preferable for me :)

Anyway all round a good thing. For various reasons min macro in particular was problematic so this is great :)

**Comment by magicrub** [comment]
minf() and maxf() should be removed too

**Comment by lucasdemarchi** [comment]
@magicrub minf() and maxf() expect the parameters to have the same type

**Comment by lucasdemarchi** [comment]
but... there are so few users that I think it's worth doing

**Comment by magicrub** [comment]
well, maxf() is only used twice in AP_NavEKF_core and max() is used 24
times. Minf() is never used at all. That's *almost* dead code.

**Comment by magicrub** [comment]
yeah, exactly.

**Comment by lucasdemarchi** [comment]
Pushed a new version, also replacing minf() and maxf() with the new function.

@khancyr your comment is in this old commit (clobbered by the push -f, so I'm adding a link here, https://github.com/lucasdemarchi/ardupilot/commit/6493def41d832e9ce31e5ded963d9276e0eff4e0)

I didn't agree with the cast and maintained the c-style one because other places in this same file is using c-style casts when calling MAX(). For the basic types there isn't any advantages, but we can discuss the casts in another PR, too.

**Comment by dgrat** [comment]
@lucasdemarchi 
Looks nice, If I would have rights I would set it to reviewed :D

**Comment by lucasdemarchi** [comment]
@dgrat as per your comment, setting the reviewed label :)

**Comment by lucasdemarchi** [comment]
@dgrat thanks.

**Comment by tridge** [comment]
looks good. It adds 100 bytes of flash space on Pixhawk, but that isn't terrible.
Randy, do you have time to flight test this with copter?

**Comment by rmackay9** [comment]
Yup, I'll give it a test flight.

**Comment by kwikius** [comment]
could try adding constexpr to it and see if it optimises a little better?

http://en.cppreference.com/w/cpp/language/constexpr

**Comment by khancyr** [comment]
@kwikius just try and I see no differences in assembly code .

**Comment by kwikius** [comment]
Only other thing I can think of to try to optimise it is to pass arguments by value rather than by reference

**Comment by magicrub** [comment]
All template values are <= the architecture bus width (32bits) so I don't
think that will help either.

**Comment by dgrat** [comment]
@magicrub 
And what about passing a struct? Actually, template function doesn't exist until it is instantiated somewhere. 
Their types are known at compile time. This is why the compiler can "generate" a correct function for the right case. 
This is why they behave like usual functions with all their rules. Consequently, a reference makes sense for bigger types like our vectors. 
In this case one could insert a type check (at compile time level), as all non int and non double types don't work here. 
Best, Daniel

**Comment by kwikius** [comment]
Well if they are 8 bit or 16 bit values it may pack them together in one register, but it may not make much differnence though it is sad that the code is bigger than for the macro version

**Comment by kwikius** [comment]
Anyway I will give it a go rather than talk about it :)

**Comment by magicrub** [comment]
>> "All template values are <= the architecture bus width (32bits) so I don't think that will help either."
>> "And what about passing a struct?"
@dgrat well yeah, if the variable is larger than the bus width then it's better to use a reference. I would be worried if we are using min/max on a struct or a vector because the operators < and > are not defined.

**Comment by kwikius** [comment]
Code size on my custom code reduced by 8 bytes of 395000 using pass by value.

**Comment by priseborough** [comment]
I flew this PR on a quad this morning with a PX2. No issues to report.

**Comment by tridge** [comment]
Thanks Paul!
pushed to master

**Pull request closed without merging**
