### PR TITLE
Dataflash over mavlink support

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by magicrub** [comment]
>>No description provided.

Please elaborate

**Comment by tridge** [comment]
it would be good to run DataFlash through the new astyle script

**Comment by tridge** [comment]
I've reviewed this and pushed to master. Thanks for all the great work Peter and Sid!
I think there are other cleanups we can do, but we can do those after this PR

**Comment by magicrub** [comment]
Yay!

**Pull request closed without merging**
