### PR TITLE
Explicit failsafe

### PR DESCRIPTION
**Pull request by hsteinhaus**
This PR is a rework of #966 . 

This change evaluates the rc status flags recently added to PX4Firmware to make the RC input handling more robust. RC channel values are double-buffered now and forwarded only if there is no condition that could lead to compromised channel values. 

Additonally, any RC input with channel_count < 5 is rejected, as such signals are obviously of no value for us.

### CODE REVIEW

**Comment by magicrub** [comment]
For a flying wing setup, only 4 channels are used. However, in my case, channel 5 is set to mode and the yaw channel is disconnected

**Comment by magicrub** [comment]
I agree @tridge , this line is quite odd and should change.
bool rc_updated = orb_check(_rc_sub, &rc_updated) == 0 && rc_updated;

**Comment by hsteinhaus** [comment]
Strange line: @magicrub, your are definitely right - already changed that in  https://github.com/hsteinhaus/ardupilot/commit/67d8abde8ceb042534132aaf64176e568cc48677

Regarding the no of channels: my intention is to make sure that only complete telegrams make it to the higher layers of code, after seeing some with only one or two channels, especially when using PPMSum. This made earlier version of ArduCopter to see 0 values (instead of 1000...2000) range, which has caused really bad faults. I don't know if the problem  still exists as the original PR is almost a year old now and I don't fly PPMSum receivers anymore.

Regarding the pass-through channels: I have to agree to @tridge that passing failsafe values provided by the receiver is very important, so some additional work might be required here before merging this PR.

**Comment by rmackay9** [comment]
How do people feel about closing this?  I've done a fair bit of looking at this today as part of merging/fixing a copter rc-override issue and I can't easily make the px4firmware produce a frame with only a few channels in it.  Of course it could be an intermittant issue but I haven't seen any support requests with this kind of problem in a long time (actually I never personally saw them but I hear RobL saw them).

copter rc-override PR: https://github.com/diydrones/ardupilot/pull/568

**Comment by rmackay9** [comment]
Ok, no feedback so I'll close this.  If there are objections we can reopen and take another look.

**Pull request closed without merging**
