### PR TITLE
Device interface (v2)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
v2 of #3496 

See the other PR for a detailed explanation on the aim of this PR.

Changes from v1:

  - Added test as requested by @khancyr 
  - Fixed macro issue as noticed by @OXINARF and @jberaud 
  - AP_Baro and AP_InertialSensor are fully converted now
  - Tested on minlure and erlebrain2 to cover most of the sensors. Some sensors are not present in any board, so no tests: BMP085, LSM9DS0 and L3G4200D
  - This now conflicts with #3467 (which makes use of LSM9DS0 for raspilot) and #3251 which enables FIFO on MPU9250. However with the changes in this PR it also makes it much easier to get those PR reworked on top - I'm willing to rebase them myselves when this gets in
  - @jberaud gave a quick test on Bebop on the previous version - new version not tested yet
  - Includes for the AP_InertialSensor were sanitized: see the individual commit - it was just too hard to keep changing the drivers and having to rebuild everything every single time

PX4 is not affected. Currently PX4 uses the Empty implementation of the new I2CDevice/SPIDevice.

I think once we get more tests done we are ready to merge this in and convert the remaining drivers later, so we can already start the thread part.

### CODE REVIEW

**Comment by dgrat** [comment]
Hi Lucas,
the commit looks nice, but is it feasible to replace the functor macros?

#define FUNCTOR_TYPEDEF(name, rettype, ...) \
    typedef Functor<rettype, ## __VA_ARGS__> name

#define FUNCTOR_DECLARE(name, rettype, ...) \
    Functor<rettype, ## __VA_ARGS__> name

#define FUNCTOR_BIND(obj, func, rettype, ...) \
    Functor<rettype, ## __VA_ARGS__>::bind<std::remove_reference<decltype(*obj)>::type, func>(obj)

#define FUNCTOR_BIND_MEMBER(func, rettype, ...) \
    Functor<rettype, ## __VA_ARGS__>::bind<std::remove_reference<decltype(*this)>::type, func>(this)

**Comment by lucasdemarchi** [comment]
> #define FUNCTOR_TYPEDEF(name, rettype, ...) \
> typedef Functor name

Are you saying to use template argument deduction? AFAIK this only works for functions, not classes.

**Comment by dgrat** [comment]
Was mainly asking, because I also don't know how one can improve such constructs. 
However, it would be nice if there is a nice way to get something like this out of the pre-compiler space.

**Comment by tridge** [comment]
hi Lucas, with px4 using the empty implemention, the old hal.i2c will still work, right? It is needed for the LightWare i2c driver

**Comment by tridge** [comment]
the std::nullptr_t code in OwnPtr.h breaks clang for qurt
I think we need a linux-clang target, so we can test building with clang without the qualcomm SDK

**Comment by lucasdemarchi** [comment]
> the std::nullptr_t code in OwnPtr.h breaks clang for qurt
I think we need a linux-clang target, so we can test building with clang without the qualcomm SDK

I don't think it's sufficient. It seems to be a problem with the toolchain, not clang in general. Clang does support nullptr_t, which is stdc++11. I'll think on a workaround.

**Comment by lucasdemarchi** [comment]
> hi Lucas, with px4 using the empty implemention, the old hal.i2c will still work, right? It is needed for the LightWare i2c driver

It will continue to work. That's why I was asking some time ago which internal drivers the PX4 actually uses. We need to add the implementation to the PX4 HAL before converting them.  Basically any driver that uses hal.i2c still works.

**Comment by jberaud** [comment]
Tested on Bebop without regressions. Apart some minor comments, I like this implementation which simplifies the sensor drivers. It really needed to be done. Thanks @lucasdemarchi

**Comment by lucasdemarchi** [comment]
> I think we need a linux-clang target, so we can test building with clang without the qualcomm SDK

btw a build with clang can be easily done by exporting CXX and CC during waf configure.

**Comment by lucasdemarchi** [comment]
@jberaud thanks a lot for the review.

@tridge  I'll update it and see if I can also test with qurt since it's the only one with a broken build after this PR. Their toolchain is a pain to install :-/ - I still didn't find all the blobs needed for that. I think the README.md should contain a link to where to download the toolchain.

**Comment by lucasdemarchi** [comment]
I made the changes pointed out by @jberaud. I'm opening a new PR with the new version so we don't lose the comments.

@tridge I could fix the nullptr_t thing (just a `typedef decltype(nullptr) nullptr_t` would suffice), but I guess it's broken in more places.  I tried hard to get the toolchain for qurt/qflight but all I was able to get was an old version (6.4.06) that doesn't even compile the master branch.

**Comment by lucasdemarchi** [comment]
New version in #3618

**Pull request closed without merging**
