### PR TITLE
Added a default astyle options file and a linux script to run it.

### PR DESCRIPTION
**Pull request by gmorph**

### CODE REVIEW

**Comment by tridge** [comment]
this formats functions with { on same line as function header, whereas in our code we tend to put { on new line.
Just try this on ArduPlane/*.cpp to see what I mean

**Comment by legonigel** [comment]
@gmorph I think changing the style to `style=stroustrup` should be what we want. Only break lines on function definitions.

**Comment by gmorph** [comment]
When I polled the dev's on Mumble today (Randy, Peter, Michael) they all wanted the { on the same line which is why I set it they way I did.  I don't mind either way - i just want consistency.  I'll ask again tomorrow I guess to see if everyone is happy with the change.
Yes - stroustrup style will meet that requirement.  @tridge if we use stroustrup then { will ONLY be on the new line for function headers.  For classes they will still be on the same line.  Is that ok?

**Comment by guludo** [comment]
We already have uncrustify config files in the tree. I think we should have only one style configuration: either this new one or the former. Having two different tools configuration produces inconsistency in my opinion.

**Comment by lucasdemarchi** [comment]
> When I polled the dev's on Mumble today (Randy, Peter, Michael) they all wanted the { on the same line which is why I set it they way I did. I don't mind either way - i just want consistency. I'll ask again tomorrow I guess to see if everyone is happy with the change.

The majority of the code uses { in a new line for functions and only functions. This is also what's in the current coding style guidelines.

**Comment by lucasdemarchi** [comment]
> We already have uncrustify config files in the tree. I think we should have only one style configuration: either this new one or the former. Having two different tools configuration produces inconsistency in my opinion.

We can remove uncrustify IMO if we reach a good configuration with astyle. But I don't like to ban having more than one. That's because none of them are perfect and some times having an alternative is a good thing.

For example, recently I made the switch uncrustify -> astyle -> clang-format. I could say clang-format is by far the best one: it can be easily [integrated in editors](http://clang.llvm.org/docs/ClangFormat.html) or used as a stand-alone tool. IMO its only deficiency is needing a .clang-format file root directory of the repository.

**Comment by lucasdemarchi** [comment]
> Yes - stroustrup style will meet that requirement. @tridge if we use stroustrup then { will ONLY be on the new line for function headers. For classes they will still be on the same line. Is that ok?

Yes, I think so.

**Comment by tridge** [comment]
> When I polled the dev's on Mumble today (Randy, Peter, Michael) they all wanted the { on the same line which is why I set it they way I did

I'm not sure they understood the question then. Nearly all the existing code in ArduCopter uses { on new line. I'd be surprised if Randy wants to change that

**Comment by gmorph** [comment]
I have updated the astylerc file with the suggestions.  I ran astyle in the vehicle directories both with defaults and using the astylerc file and gathered some simple stats using "git diff --stat"

ArduCopter:
With the new astylerc - 48 files changed, 2110 insertions(+), 1892 deletions(-)
astyle default - 46 files changed, 1893 insertions(+), 1756 deletions(-)

ArduPlane:
With the new astylerc - 24 files changed, 924 insertions(+), 807 deletions(-)
astyle default - 69 files changed, 2765 insertions(+), 2554 deletions(-)

APMRover2
With the new astylerc - 17 files changed, 1234 insertions(+), 1155 deletions(-)
astyle default - 17 files changed, 1159 insertions(+), 1115 deletions(-)

**Comment by lucasdemarchi** [comment]
Hi @gmorph 

Looks good now from a quick look in the resulting modifications. I added 2 more options:
```
unpad-paren
pad-header
```

The only obvious mistake I found was in designated initializers (look at `struct log_Precland pkt` in ArduCopter for example). Apparently astyle thought it was a label.

**Comment by gmorph** [comment]
Thanks for reviewing again Lucas.  I will add pad-header but I think I will leave unpad-paren out as sometimes people like to pad the if statements to make it more readable.
Thanks, Grant.

**Comment by lucasdemarchi** [comment]
@gmorph what do you mean by pad the if statements? Unpad paren actually works together with "pad-header" so we always get this result:
```
if (a) {
```

and not any of these:

```
if ( a) {
if(a) {
if (a){
if (a ){
```

**Comment by gmorph** [comment]
Hi Lucas.  I might be wrong but I understood from the doco that unpad-paren would turn this
if ( isFoo( ( a+2 ), b ) )
    bar ( a, b );
into this
if(isFoo((a+2), b))
    bar(a, b);
See how it removes the internal spacing of the brackets.  Again I really don't mind - I just thought it could annoy dev's who like to make their if statement internals very clear.  I'm happy to go with either if that's what the team wants.
Thanks, Grant.

**Comment by lucasdemarchi** [comment]
It would actually turn it into:
```if (isFoo((a+2), b)) {```

notice the spaces on the outside, but not in the inside.  I think there are very few places the spaces inside make it more readable that can be either exceptions or we just ignore. Take a look into the diff it generates... it's basically people forgetting spaces in the end.

**Comment by gmorph** [comment]
Lucas, I have added in unpad-paren.
Thanks, Grant.

**Comment by tridge** [comment]
that is now looking pretty good, thanks!
I've pushed to master

**Pull request closed without merging**
