### PR TITLE
waf: copter frame types

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This PR is enabling users to easily configure arducopter frame type.

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
@tridge This might interest you (I'm assuming that by what we've talked on one devcall).

In the future we could try to build all frames for just one configuration.

**Comment by lucasdemarchi** [comment]
Now I think it's difficult to know what a binary is. Maybe add a suffix to the binary name?  arducopter-tri, arducopter-quad?

**Comment by lucasdemarchi** [comment]
And it's not possible to build all the configuration types?  Suppose I want to create a linux package (.deb, .rpm, .tar.gz) with all possible configurations for the user. How would you do that since you would need to change the configuration every time?  We build different vehicles at once, why not building different frame types... ?

**Comment by lucasdemarchi** [comment]
I applied the first commit, that's somehow unrelated.

**Comment by guludo** [comment]
> And it's not possible to build all the configuration types? Suppose I want to create a linux package (.deb, .rpm, .tar.gz) with all possible configurations for the user. How would you do that since you would need to change the configuration every time? We build different vehicles at once, why not building different frame types... ?

@lucasdemarchi I intend to that, but I don't like the way we work around the problem of having different object files for the same source. I want to fix that before building all frame types at once.

**Comment by guludo** [comment]
> Now I think it's difficult to know what a binary is. Maybe add a suffix to the binary name? arducopter-tri, arducopter-quad?

That makes sense.

**Comment by guludo** [comment]
>> And it's not possible to build all the configuration types? Suppose I want to create a linux package (.deb, .rpm, .tar.gz) with all possible configurations for the user. How would you do that since you would need to change the configuration every time? We build different vehicles at once, why not building different frame types... ?

> @lucasdemarchi I intend to that, but I don't like the way we work around the problem of having different object files for the same source. I want to fix that before building all frame types at once.

Hm, after a look at the code, that problem seems to happen only for library sources. So I think it's easily possible. I'll replace this PR with one that builds for all frame types then...

Anyway, @lucasdemarchi do you think it's worth applying the recursion patches? I think it might become useless code

**Comment by lucasdemarchi** [comment]
> Anyway, @lucasdemarchi do you think it's worth applying the recursion patches? I think it might become useless code

No idea. Your call.

**Comment by guludo** [comment]
Closing this. Second version at #3796 .

**Pull request closed without merging**
