### PR TITLE
RPM Improvements

### PR DESCRIPTION
**Pull request by R-Lefebvre**
Add synthetic quality measurement, minimum RPM, filter, etc.

### CODE REVIEW

**Comment by rmackay9** [comment]
A few things:
1. instead of using the new word, "activated", I would use the pre-existing "enabled"
2. the signal_quality is calculated but is it actually used anywhere?  It seems like it's used in healthy() but healty() doesn't appeared to be called anywhere anymore, instead activated() is used.
3. I'm not qualified to say whether the method used to calculate signal quality is valid or not.  It might be good to check with the likes of Paul or Leonard.

**Comment by R-Lefebvre** [comment]
1. fair enough on the word enabled() that makes sense.  I'll make that change.

2. Signal quality may be used in the future by downstream subscribers of the data.  Right now, it is definitely logged so that users can get an idea of how well their sensor is working. I expect this could be a problematic sensor for some people.  It is also used for health reporting.  Downstream users will definitely use the health data.

3. I used a similar method to greatly improve the signal quality from sonar sensors two years ago, it worked very well but never got into master.  But always open to input.  Hopefully if they make a contribution, it can be merged in whenever that happens, instead of holding this up for it.

**Comment by R-Lefebvre** [comment]
I updated the commits to change activated() to enabled().

**Comment by tridge** [comment]
thanks Rob, applied!

**Pull request closed without merging**
