### PR TITLE
HAL_Linux for Bebop - pwm gpio and i2cdriver

### PR DESCRIPTION
**Pull request by jberaud**
Needed for the optical flow implementation on Bebop.
This has been moved out of [PR #3221](https://github.com/diydrones/ardupilot/pull/3221) 
I have implemented the changes asked by @lucasdemarchi

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@jberaud only one minor thing: https://github.com/lucasdemarchi/ardupilot/commit/a5e80d854e0a36a99308bce55a31416188f05e55

Let me know what you think. Review branch is here: https://github.com/lucasdemarchi/ardupilot/commits/review/pr-3238

**Comment by jberaud** [comment]
I am OK with your changes except that we still need to check that polarity_path is not null because else we'll try to free a NULL pointer on Bebop. Am I right?

**Comment by lucasdemarchi** [comment]
free(NULL) works just fine. My point is exactly that we never need such a `if (bla != NULL) free(bla)`.

Quoting the man page:

```
       The free() function frees the memory space pointed to by ptr, which must
       have  been  returned  by a previous call to malloc(), calloc(), or real‐
       loc().  Otherwise, or if free(ptr) has already been called before, unde‐
       fined behavior occurs.  If ptr is NULL, no operation is performed.
```

IMO the additional "if" only adds noise to the code.

**Comment by jberaud** [comment]
@lucasdemarchi Ok, then everything is fine for me. Thank you very much for the review. Do you want me to modify my PR, do you want to do the PR yourself?

**Comment by lucasdemarchi** [comment]
Just push -f here.

On Mon, Nov 30, 2015 at 11:51 AM, Julien BERAUD <notifications@github.com>
wrote:

> @lucasdemarchi <https://github.com/lucasdemarchi> Ok, then everything is
> fine for me. Thank you very much for the review. Do you want me to modify
> my PR, do you want to do the PR yourself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot/pull/3238#issuecomment-160633302>.
>



-- 
Lucas De Marchi

**Comment by jberaud** [comment]
I have added the conversion of my Heat driver to the new PWM_Sysfs api. I hope you don't mind.

**Comment by lucasdemarchi** [comment]
I'm actually glad you did :-)

**Comment by tridge** [comment]
applied.
I have also exposed do_transfer() on PX4. Thank you for using the same API!
We could now remove everything but do_transfer() from the per-boards HALs, and move the helper functions up into libraries/AP_HAL.
Lucas, what do you think?

**Comment by lucasdemarchi** [comment]
@tridge what exactly do you want to remove?

**Pull request closed without merging**
