### PR TITLE
Navio RCInput reimplemented.

### PR DESCRIPTION
**Pull request by staroselskii**
Navio port had been using pigpio library to handle RC input. As a result of this PR we're getting rid of that dependency.

### CODE REVIEW

**Comment by tridge** [comment]
Lucas, are you OK if I merge this now, and fix up the small issues later?

**Comment by dgrat** [comment]
I would also suggest to add NULL pointer checks and make the pointer arguments const.
This would be very cheap and avoid potential mistakes.

**Comment by lucasdemarchi** [comment]
> Lucas, are you OK if I merge this now, and fix up the small issues later?

yes

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
