### PR TITLE
Copter: Fix Ch6 Tuning when no RC Receiver on Boot.

### PR DESCRIPTION
**Pull request by R-Lefebvre**
Currently, Tuned Param will end up being Zero if no RC Receiver present on Boot-up.  This patch results in the Param remaining as the last saved number, which is *not* the last tuned param.

### CODE REVIEW

**Comment by rmackay9** [comment]
Merged the 1st and 3rd commits, thanks!
I skipped the 2nd one (non-functional change to gcs failsafe logic) because I think there is perhaps a subtle functional change in that the gcs failsafe-off event may not trigger in some cases.

**Comment by magicrub** [comment]
Agreed. Non-functional change implies no possible way the behavior changed
but this clearly does.

**Comment by R-Lefebvre** [comment]
OK, sorry about that.

**Comment by magicrub** [comment]
30 lashes for you! :)

**Pull request closed without merging**
