### PR TITLE
Dual motor support

### PR DESCRIPTION
**Pull request by AndWik**
I have a sea plane with two motors. One on each wing. In all situations, except one, they can run at the same setting but:
Before takeoff and after landing it is very difficult to navigate.

Add support for dual motors for Ground Steering or Always would be highly appreciated

Thanks
Anders

### CODE REVIEW

**Comment by magicrub** [comment]
This needs to be rebased onto master, since master has changed too much since you started your work.

"git rebase master"

**Comment by iskess** [comment]
Please see #1861 for a request for motor failure handling on a twin

**Comment by AndWik** [comment]
Hi 

 

Thanks for the info.

Maybe a future change as it looks.

 

Anders

**Comment by magicrub** [comment]
unable to merge, needs a rebase

**Pull request merged**
