### PR TITLE
Plane: Limit THR_MAX (and THR_MIN for reverse thrust) via max battery power

### PR DESCRIPTION
**Pull request by magicrub**
new param: BATT_WATT_MAX

Description: If battery wattage (voltage * current) exceeds this value then the system will reduce max throttle (THR_MAX, TKOFF_THR_MAX and THR_MIN for reverse thrust) to satisfy this limit. This helps limit high current to low C rated batteries regardless of battery voltage. The max throttle will slowly grow back to THR_MAX (or TKOFF_THR_MAX ) and THR_MIN if demanding the current max and under the watt max. Use 0 to disable.

When using this it allows you to set arbitrarily set THR_MAX high, I suggest 100. You can also set THR_MIN to -100 when using reverse thrust. This is because the throttle limit assumes a fixed thrust during flight. however, as the battery voltage drops the effective thrust from THR_MAX drops. The intent of THR_MAX is to not over-current your battery. This does that directly instead of indirectly.

### CODE REVIEW

**Comment by magicrub** [comment]
after additional test the data shows that the throttle attack was too slow so I've sped it up to be instant-ish. I left it as a separate commit so it can be changed/ignored if needed

**Comment by magicrub** [comment]
This is related, but different than http://copter.ardupilot.com/wiki/current-limiting-and-voltage-scaling/
which tries to maintain a constant thrust as voltage drops while this PR is more for low-c batteries on plane where you set THR_MAX to 100 and the controller will always allow max thrust within the saftey of the low-c battery as the voltage drops

**Comment by iskess** [comment]
Tom,
I'm thinking that TKOFF_THR_MAX should be exempt from BATT_WATT_MAX. Low C batteries can usually handle a burst of power safely, and takeoff is a short period where 1) a burst is most needed, and 2) the pack voltage is highest and most likely to be safe to output a burst. 
Even a 6s burst can launch my plane out of my hand to a safe altitude of at least 30m. One of the two primary reasons to create TKOFF_THR_MAX was to allow higher throttle just for takeoff (and abort). If we are now going to limit takeoff power with BATT_WATT_MAX, we would need to add "TKOFF_WATT_MAX" to maintain this feature. 

To provide a more concrete example, using 3S4P Li-ion cells, I want to limit them to 2C for their longevity. This equates to 24A, which is ~288W. This is a pretty marginal amount of power for takeoff. I would like to allow 3C = 36A = 432W for takeoff/abort, which should last less than 10s. 
Thank you.

**Comment by magicrub** [comment]
I've been flying on this for awhile, works OK but I ended up disabling it because I didn't like it but I can see others would like it a lot. I'll rebase on master soon to get this in v3.5.1

**Comment by magicrub** [comment]
merged via https://github.com/diydrones/ardupilot/commit/ed6aa4ed17e6d2d8386964375c7224d40467bd23 and https://github.com/diydrones/ardupilot/commit/035f3b16a1d2d4c4c1485f85eca2bd040e5ed389

Future TODO would be to change limiting scheme from a fast-decrement to a computed value for faster and more accurate response. The current scheme attacks fast which is OK but then when the release creeps up it attacks fast again causing a max throttle oscillation of about 5% (fast down, slow up triangle wave). Still much better than popping a low-C battery.

**Comment by lvale** [comment]
@magicrub Tom, was this parameter supposed to appear also in Copter ?

Using today's master build

screen shot 2016-04-16 at 15 10 23

**Comment by magicrub** [comment]
No, it should not be. My bad.

**Comment by magicrub** [comment]
To-do https://github.com/ArduPilot/ardupilot/issues/3913

**Pull request closed without merging**
