### PR TITLE
Enable SITL code to call an external ROS simulator for ArduPlane

### PR DESCRIPTION
**Pull request by Georacer**
sim_vehicle.sh code was modified to call the autotest/ROS/runsim.py file instead of the default autotest/jsbsim/runsim.py, when using the -e option. To my current knowledge -e option is not used in conjuction with any other simulator, so I decided to take advantage of it.
ROS/runsim.py uses roslaunch command to launch the last_letter simulator https://github.com/Georacer/last_letter, which should be cloned and compiled in the system.

GIT_Success.txt file was modified to depict the author's current state of mind.

The location LGAT (Former National Airport of Athens, now an unofficial model park) was added in the locations.txt file, since this is my base of operations and start for my missions.

### CODE REVIEW

**Comment by tridge** [comment]
Thanks for this! I've wanted more FDM backends and having ROS support is very nice.

**Comment by tridge** [comment]
applied, thanks!
The idea with -e was that you start the sim separately, then run sim_vehicle.sh with -e. It was rarely used though. I think we need another option to specify the sim type.
Really we need to rewrite sim_vehicle.sh in python - the script is getting really unwieldy now, and hard to modify.

**Comment by tridge** [comment]
btw, are you willing to do a howto page in the dev.ardupilot.com wiki for using the ROS sim backend?

**Comment by Georacer** [comment]
Thanks a lot for this, tridge! Maybe it is time I invested some time in passing arguments from the sim_vehicle file to the simulator.

A cool feature that could be implemented and would be useful to ardupilot is to start the simulation mid-flight and freeze the kinematics (not the dynamics) until the APM code initializes. Then a specific test could be executed. I'm not sure how the initialization altitude would behave, however.

I already have started documentation in my own simulator github page: https://github.com/Georacer/last_letter/blob/master/last_letter/doc/manual/ArduPlane_SITL.md
where I discuss initialization stuff and configuring the simulator.

I don't have a problem with doing a short page, but I'd rather not write duplicate documentation. Where should I turn to?

**Pull request closed without merging**
