### PR TITLE
PX4IO: sbus1_output

### PR DESCRIPTION
**Pull request by samsonact**
Provide a way to turn on the px4io sbus1_out. PX4Firmware now has pulled the upstream support for sbus1 output.

I'm flying this with the pending ArduPlane beta compiled with the current PX4Firmware version.

### CODE REVIEW

**Comment by gmorph** [comment]
We are looking into this one but want to enable it via a parameter.  We will get back to you shortly.

**Comment by tridge** [comment]
I've now implemented it as a parameter BRD_SBUS_OUT. If you set that parameter to 1 then SBUS output is enabled.
Can you test this please by testing the latest master builds? I don't have any SBUS servos. I have checked we get what looks like a SBUS signal on the SBUS connector using my logic analyser, but it would be nice to know it actually works :-)

**Comment by samsonact** [comment]
I've loaded the latest autobuild. Confirmed sbus off without parameter set (check that I'd removed custom start script). Turned parameter on and sbus is enabled after reboot.

I haven't flown yet with this image but manual mode tested fine on the bench.

**Comment by tridge** [comment]
thanks for testing!

**Pull request closed without merging**
