### PR TITLE
waf: addition of cmake tool [v2]

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This is the next version of #3632 with the fixes suggested.

Best,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
HEADSUP: I just added some commits fixing some issues I bumped into while doing some tests.

I'm not sure if those commits should be squashed to the commit adding the tool -- the messages describe the reasons for the changes/additions.

**Comment by guludo** [comment]
Note: there's also another issue, which I haven't found a good and straightforward way to fix it and it's not on my priorities now: `cmake_configure_task` should delete `CMakeCache.txt` if it's supposed to run. The reason is that if a variable is removed from `cmake_vars`, that is kept as the old value instead of the default one.

I'll create an issue regarding that when this PR gets applied.

**Comment by lucasdemarchi** [comment]
@guludo from what I understood this is still not ready for merge, right?

**Comment by guludo** [comment]
> @guludo from what I understood this is still not ready for merge, right?

@lucasdemarchi I just added a commit fixing that issue I mentioned earlier. I think it's good to go now.

**Comment by lucasdemarchi** [comment]
Applied.

There were some conflicts while rebasing. I think I got then right.. please take a look.

**Comment by guludo** [comment]
Looks good. Thanks!

**Pull request closed without merging**
