### PR TITLE
Copter: finish removal of OF_LOITER, add convenience function for looping through modes

### PR DESCRIPTION
**Pull request by jschall**
Need to loop through valid modes for one of Solo's functionalities - is_valid_flight_mode and FLIGHT_MODE_MAX are needed for that.

### CODE REVIEW

**Comment by rmackay9** [comment]
thanks for this.
It looks like is_valid_flight_mode function isn't used yet?  Normally we don't add code before it's used.

**Comment by jschall** [comment]
@rmackay9 it will be used on Solo

**Comment by rmackay9** [comment]
@jschall, so you'll be adding the other calls that make use of this new function to master or just maintaining it in the solo branches?

**Comment by jschall** [comment]
This iteration of the feature (determining a bitmask of armable modes) is probably going to stay solo-only as it uses a NAMED_VALUE_INT, but that feature is desirable and useful so i'd imagine it will likely be included in the prearm rework...

**Comment by rmackay9** [comment]
Ok, I merged the OF_LOITER patch but left out the unused is_valid_flight_mode for now.  Not trying to be annoying, it's just that we don't normally add code that's not being used.  When we start using it we can add it.  One way it could go in is if it's behind a #define for solo.

**Pull request closed without merging**
