### PR TITLE
Initial integration of the Eigen math library

### PR DESCRIPTION
**Pull request by dgrat**
It would be nice to start experimenting a little bit with an optimized library.
I added a small example and a very basic include dummy "AP_Eigen.h", 
which is including the most relavant headers from Eigen for matrix and vector arithmetic.

Best, Daniel

### CODE REVIEW

**Comment by tridge** [comment]
hi Daniel, for something like this I think we should use a git submodule. We would create our own clone of eigen and point the submodule at that repository.

**Comment by dgrat** [comment]
Hi Tridge,
if it is okay, I will create a repo with a forked branch of Eigen, parts of the AP_Math library and an Interface header which makes type conversions of the original AP_Math types easy. The stuff is saved by its own namespace. I think, if greater parts of AP_Math can be used still and new things will be written with Eigen, it might be easier. Or do you prefer a clean Eigen repo? I still got no answer.

**Comment by dgrat** [comment]
@tridge 
What do you think: https://github.com/dgrat/AP_Eigen

**Comment by lucasdemarchi** [comment]
Hi @dgrat, thanks for working on this. As said the other time you sent to the mailing list, I still don't agree with adding a wrapper library. If we add it I don't see we removing it anytime soon and we would have a half-converted codebase for a long time.

**Comment by tridge** [comment]
I can't really just if we should have a wrapper around eigen functions or not until I see how we would actually use this.
For the submodule, I think that if possible it should point to an unmodified clone of the upstream eigen git tree. We may then have wrappers in the libraries/AP_Math or possibly libraries/AP_Eigen if they are needed.
What I will be looking for is:
 * what impact this will have on the code. Will it make our current code easier or harder to develop and read?
 * what impact will it have on memory, flash and cpu usage? I am especially interested in memory and flash usage, as they are our two tightest resources at the moment
 * what new capabilities will it give us?
Adding Eigen isn't an end unto itself. We should only use it if it wins something. For example, if I saw it reducing flash size, reducing code complexity, making the code easier to read and reducing memory footprint for the maths intensive parts of our code then that would be good reasons to use it.
So please concentrate on demonstrating and testing those aspects of using eigen. Especially keep in mind that the stm32 only hardware accelerates single precision maths.
A PR like this that just adds the whole of the 4k files of the eigen tree (including the .hg mecurial meta-data!!) is not useful. The only part that is really useful is the AP_Eigen/examples, and that is not enough to convince me.
If instead you converted part of the complex compass calibration code in AP_Compass, or showed how we could replace the matrix maths in the accel calibration then that would interest me a lot more.
I would also like to know exactly how the memory handling will work. When I see lines of code like this:
 MatrixXd b(2,2)
in the example I immediately think "how is the memory being handled for that? Why are we using double precision? Is this going to fragment the heap? What are the default values in that matrix? How will this integrate with the hundreds of existing uses of our vector and matrix calls? Will this work with the vectors we use in AP_Param? 
Actually adopting eigen will take a lot of thought and a lot of coding.

**Comment by dgrat** [comment]
@tridge 
I think I will prepare some benchmarks and an example.
Additionally, I will compare loss of precision after vector rotations :)

Best, Daniel

**Pull request closed without merging**
