### PR TITLE
Copter 3.3.1-Heli RC1

### PR DESCRIPTION
**Pull request by R-Lefebvre**
PR to merge in changes for what should become Heli AC3.3.1 RC1

It appears some of Randy's recent commits to 3.3.1 are showing up, I'm not sure why.

### CODE REVIEW

**Comment by rmackay9** [comment]
Generally looks ok.  I'll try and complete the review tomorrow.

**Comment by rmackay9** [comment]
Rob's fixing up a couple of little things so just adding a label just for status tracking

**Comment by R-Lefebvre** [comment]
Branch is updated with requested fixes.
Removed Need-rework tag.

**Comment by rmackay9** [comment]
merged!

**Comment by fhedberg** [comment]
@R-Lefebvre @rmackay9 :clap:

**Pull request closed without merging**
