### PR TITLE
HAL_Linux: AP_BattMonitor add support

### PR DESCRIPTION
**Pull request by vmayoral**
Support for voltage measurement with the PXF

### CODE REVIEW

**Comment by tridge** [comment]
Hi Victor,
That Linux analog code has some serious issues. Among other things it just did a panic when it failed to read a pin (do you really want the plane to immediately crash if it can't read the battery voltage?!).
I've put together some basic fixes here:
  https://github.com/tridge/ardupilot/tree/pxf-analog-wip
but it still needs some more work. The voltage and current scaling isn't right. If you can have a look at it a bit more carefully that would be appreciated.
Cheers, Tridge

**Comment by vmayoral** [comment]
@tridge voltage tested and seems to work appropriately with the last fix. I'll save some time later in the week to test the current. Regards

**Comment by tridge** [comment]
thanks! I'll take a look

**Comment by vmayoral** [comment]
Voltage seems to work fine but i can't say the same for the current. I'm probably missing something.

**Comment by tridge** [comment]
let me know when current is working

**Comment by vmayoral** [comment]
@tridge please take a look at [this log](https://github.com/erlerobot/logs/blob/master/pxf/brain/3.BIN) where you'll see something like:

captura de pantalla 2015-03-16 a las 14 31 55

The voltage seems to be fine but i can't get to understand the current readings.

**Comment by khancyr** [comment]
Hi,

I use Erlebrain and current monitor works fines. In my case, I use Chinese power module and I need to set BATT_AMP_PERVOLT,92.58737183 . I follow wiki procedure for voltage and current sensing calibration. 

Here is an example log of current sensing again throttle . Current sensing is good and battery failsafe are correctly trigger.
currlog

As I said to Vmayoral, some commits are erasing some default values .
	AP_BattMonitor: Adjust constants to PXF
	HAL_Linux: PXF BattMonitor voltage fixes

So a reread may be needed.

**Comment by vmayoral** [comment]
Reworked at https://github.com/diydrones/ardupilot/pull/2722#issuecomment-132996183.

**Pull request closed without merging**
