### PR TITLE
Added RSSI_RC parameter

### PR DESCRIPTION
**Pull request by RealTadango**
Added RSSI_RC parameter to allow a RC channel to be used as the RSSI value. This makes the OpeLRSng RSSI Channel injection compatible en eliminates the need for a analoge filter.

### CODE REVIEW

**Comment by markab** [comment]
Is EzUHF PPM rssi supposed to work on the pixhawk sbus port (virtual 103) yet? I have been searching for days and still cant work out if it is supposed to work in the current version or not?

**Comment by readerror67** [comment]
Bump, would really like this feature.

**Comment by tridge** [comment]
I'm finally having a look at this, sorry for the long delay.
I think it would be best if we added a new AP_RSSI library, with a RSSI_TYPE parameter, and RSSI_CHAN, RSSI_RANGE etc. The vehicle code wouldn't then need to each implement the rssi logic

**Comment by tridge** [comment]
it looks like the work on PR#2731 will replace this, so I will close this one

**Pull request closed without merging**
