### PR TITLE
AP_Math

### PR DESCRIPTION
**Pull request by dgrat**
Replaced some functions in AP_Math with safer templates.
Removed unused functions and cleaned the header.
This is the follow up because AP_Eigen will not make it into AP.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
> This is the follow up because AP_Eigen will not make it into AP.

That's not actually what I said. I said AP_Eigen needs to be a shim to allow the use of Eigen instead of duplicating functions from AP_Math

**Comment by dgrat** [comment]
I wanted to start from scratch, because I really don't like AP_Math.
Everything is chaotic there. Dozens of definitions, macro collisions and dunplicated functions which are not even usefull in most cases.

**Comment by dgrat** [comment]
@lucasdemarchi 
I replaced all PI definitions.

**Comment by lucasdemarchi** [comment]
@dgrat Nice, thanks.

It would help people to review faster these PRs if you follow the coding style. Particularly the commits need to be broken up by directory. Sometimes when it's a single search and replace, it's ok to do a single commit with the commit message: "Global: replace XXX with YYY". But do the implementation in a separate commit. Don't squash multiple changes in a single commit. See http://dev.ardupilot.com/wiki/submitting-patches-back-to-master/ and http://dev.ardupilot.com/wiki/style-guide/

I'll try to review this soon without taking the coding style into account.

**Comment by dgrat** [comment]
@lucasdemarchi 
As you can imagine, the changes are hard to deconvolute, because most files contain multiple changes.
I splitted into two commits, one with the current implementation of AP_Math and one with the search and replace.
Despite the fact that there are a lot of files included, the changes are small and easy to understand. Just macro and function replacements. There are very few cases were I replaced function calls like is_zero with "val == 0" because the variables were integers and thus the functions call ineffiecient. 

ArduPlane size comparison: 
	   text    data     bss     dec     hex filename
	 898492    2836   57616  958944   ea1e0 /home/dgrat/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build/firmware.elf

		text    data     bss     dec     hex filename
	 896332    2836   57616  956784   e9970 /home/dgrat/ardu_master/modules/PX4Firmware/Build/px4fmu-v2_APM.build/firmware.elf

**Comment by dgrat** [comment]
@lucasdemarchi @tridge 
I rewrote all wrap_* (180, PI, ..) functions. They are neither fast or precise. The more the angle is above the bias the more they lose precision. Additionally, It will lead to a wrong result if you give them an int as parameter. I think it is dangerous to use this function. Basically the same for the other wrap functions. 
I would highly appriciate to test a replacement.. I mean honestly, it looks like a joke: 

    while (angle_in_radians > M_PI) angle_in_radians -= M_2_PI;
    while (angle_in_radians < -M_PI) angle_in_radians += M_2_PI;

**Comment by dgrat** [comment]
Additionally, I would also appreciate if functions like these could be removed: 
  bool        inverse(float x[], float y[], uint16_t dim);

They are used just in one class (Compass_Calib.), they are relatively complex and not safe.

**Comment by dgrat** [comment]
@lucasdemarchi 
After some testing, I think the functions are now all more or less safe (not dependent what type you insert).
Some funtions like the one below, I wanted to make auto. Unfortunately AP_Int/AP_Float types lead to an error at compile time.
A solution would be to make casts into scalar types before you insert them as function parameter instead to use these types as they are. I don't want to make a type check on the side of the library.  
Now I just make a float cast and thus fix the return type. 
Another problem is that ints get promoted to doubles and many people here used int as functions parameters everywhere in the code instead to use floats. 
Last thing I noticed is that M_PI is defined as double even on embedded environments which also results in warnings. I don't think it is worth to take care about this or to define new types just to reduce these warnings. 

template<class T>
float sq(const T &val) {
    return std::pow(static_cast<float>(val), 2);
}

template<class T, class... Params>
float sq(const T &first, const Params&... parameters) {
    return sq(first) + sq(parameters...);
}

**Comment by ricardotk** [comment]
@dgrat

It's great to see a new implementation for `AP_Math`, I think the old version was a little chaotic too. But I would suggest you to add benchmarks for the `AP_Math` functions. This way we'll have something to compare before and after your new implementation. What do you think about it?

Also, you said that you've gained some precision on some functions in your new implementation, such as `wrap_360()`. I didn't reviewed this function yet but just be careful to not use `double` instead of `float` (just a heads up because I already did this kind of mistake in the past hehe)

**Comment by dgrat** [comment]
To be honest, this commit changes only 500 lines of code and I will not split it into even smaller peaces. Mainly because per file on average just to names get changed. The new implementation of AP_Math is in a separate commit and I will not split it into thousand of mini commits because I lack time. 
I will also not do any benchmarks. I just suggest everyone to look at the old implementation of some functions.

**Comment by ricardotk** [comment]
I understand your lack of time, I think everyone lacks it as well, this is one of the reasons on why I asked you to split into various commits, it saves time for the ones who are reviewing or taking a loot into the AP_Math functions history in git. But I think you can do it after the decision of which parts will be included. :smile: 

The benchmarks would be good to prove some of the things you're trying to prove with this new implementation. But it's your call to do it or not. :dancers:

**Comment by dgrat** [comment]
I will not do benchmarks because for most functions nothing will change.
In case of the wrap functions my implementation will be faster, but I am simply not interested how much.

**Pull request closed without merging**
