### PR TITLE
Clean up the px4 targets a little

### PR DESCRIPTION
**Pull request by peterbarker**
Commits should probably all be squashed together.

### CODE REVIEW

**Comment by guludo** [comment]
I think 2619150 ("mk: correct manipulation of buttx makefiles") and 60281c1 ("mk: replace rm/cp idiom with cp -f") could be squashed.

I not sure if we really need the `-f` option for `cp` though. Is there any environment where `cp` fails if the destination already exists?

**Comment by peterbarker** [comment]
@guludo Typo fixed - oops!

As mentioned in the PR - they can probably all be squashed together.  The two patches you mention are explicitly separate because only the first patch was part of a discussion I had with @tridge this-afternoon on the subject.  Everything else was just stuff I couldn't leave alone :-)

I can't think of any good reason for having the -f - but given someone decided that the rm's were needed in the first place I decided it was safer to have them than not.

Ta!

**Comment by lucasdemarchi** [comment]
The -f for rm is needed because if the file doesn't exist it would fail and not continue the other commands. For cp, I don't think is needed neither.

In other makefile-based projects usually people use $(RM), $(CP), $(MKDIR_P), $(LN_S) and set these vars to the correct expansion on each platform/distro.

**Comment by lucasdemarchi** [comment]
Squashed and applied. I added one commit on top to change the `cp -f` to `cp`

**Comment by peterbarker** [comment]
@lucasdemarchi It wasn't the "-f" flag to rm I was referring to - it was the presence of the "rm" in the first place! :-)

Thanks!

**Pull request closed without merging**
