### PR TITLE
waf: px4 build!

### PR DESCRIPTION
**Pull request by guludo**
Hey guys,

This series of patches are for enabling Waf building for PX4 boards.

I tried to organize the commit by tools and topics. I'm sorry for so many commits. I thought about splitting into different PRs, but I wasn't sure if that was worth it. If the majority thinks that's necessary, I could do that.

I can issue `waf all` for px4-v1, px4-v2 and px4-v4. :-)

I can upload px4-v2 programs, but I haven't tried flying yet.

@tridge, I think your feedback is very important here, would you mind taking a look?

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
Hm... I'm using cmake 3.4 in my environment whereas both travis and semaphoreci have older versions that don't support `string(APPEND ...)`. I'll be looking into that..

**Comment by khancyr** [comment]
Humm and what about using a ppa ? 
https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x

**Comment by lucasdemarchi** [comment]
@khancyr I think we should update the cmake version only if/when PX4 build uses a newer one... because they are the main reason we care about the cmake version and having a different version will cause problems in the long run.

Looking at their build it seems like cmake >= 2.8 is supported.

Updating to 14.04 is out of the scope of this PR - I remember it was not as straightforward as just updating the version in the .travis.yml file.

**Comment by guludo** [comment]
Although CMakeLists.txt files says the minimum version required is 2.8, it actually needs to be 3.2 or higher because of the option USES_TERMINAL of `add_custom_target` directive.

**Comment by guludo** [comment]
So, I just did a force push on my branch because of the change I made on PX4Firmware removing the use of `string(APPEND ...)`. Btw, the PR is at https://github.com/diydrones/PX4Firmware/pull/53.

**Comment by lucasdemarchi** [comment]
@guludo thanks!

Applied.

**Comment by OXINARF** [comment]
@lucasdemarchi This is failing building in CI because they don't have CMake 3.2. Maybe you could try using the official installer (https://cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh)?

**Comment by lucasdemarchi** [comment]
@OXINARF saw it... I'm adding the same ppa as the PX4Firmware has

**Comment by lucasdemarchi** [comment]
@OXINARF just pushed to master the fix.

**Comment by OXINARF** [comment]
@lucasdemarchi You forgot to add the other ppa (ppa:george-edison55/cmake-3.x) for Trusty (which is used by SemaphoreCI)

**Comment by OXINARF** [comment]
@lucasdemarchi And by the way, I'm not sure if removing -qq flag from apt-get is a good idea because the log is already really big. I think until we don't use the Make build system it should be left with the flag.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (405/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:48374 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLl-000aYL-4M
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:37:26 +0100
Date: Mon, 14 Mar 2016 11:08:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457978899;
	bh=5TtrPlAu02jtK+U6+kvrJA7LogFYQCi+Wk5QiQMnOr4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=N/5MDFf3RkphPYaKGYu7SNzi026O5FvZf43I8a4OtQM9pp409IUzVe8cRj30R0RAj
	 8lQbdUU91vTEHB140MldMEkpI06/1AbekYApo74OEGrTC7ik/kG1H0lN+OAhphv8I2
	 Z7hUDu5Ki15F5VJrtGOKpjYFs1REVUO/t7J4Jesg=

**Pull request closed without merging**
