### PR TITLE
AP_Baro_MS5611: Suspend timer when init to prevent other SPI drivers grabbing the bus.

### PR DESCRIPTION
**Pull request by raspilot**
1. AP_Baro_MS5611: Suspend timer when init to prevent other SPI drivers grabbing the bus.
Sometimes there is a "PANIC: AP_Baro_MS56XX: failed to take serial semaphore for init" message when starting the program. Because spi is blocked by other drivers.

2. HAL_Linux_Class: Init spi before rcin & rcout, because raspilot rcin & rcout use spi.

### CODE REVIEW

**Comment by jberaud** [comment]
>-bool AP_SerialBus_SPI::sem_take_blocking() 
+bool AP_SerialBus_SPI::sem_take_blocking()


You should split whitespaces corrections in a separate commit for clarity purpose.

**Comment by jberaud** [comment]
Apart from that, Check for me.

**Comment by raspilot** [comment]
Sorry, I was not to correct the whitespaces on purpose. I'm using the Atom of Github as an editor. The software delete the whitespaces itself.

**Comment by lucasdemarchi** [comment]
@raspilot one way to split the changes is by using `git add -p` or `git add -i`. The you can select part of the changes to go into each commit. See the "-p" option in http://git-scm.com/docs/git-add or https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging

**Comment by magicrub** [comment]
SourceTree does that quite nicely in a GUI environment.

**Comment by raspilot** [comment]
@lucasdemarchi @magicrub Thanks very much! I'm going to try that.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
