### PR TITLE
build: allow -j on top level makefile

### PR DESCRIPTION
**Pull request by lucasdemarchi**
By using $(MAKE) variable we allow to pass down to the called makefile
the number of jobs we want to compile with. The flags are communicated
to the next level via MAKEFLAGS variable.

Reference:
https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html#Options_002fRecursion

### CODE REVIEW

**Comment by magicrub** [comment]
There was a problem with px4 builds using -j >1 but ardupilot flight stack
was OK. Has that been resolved?

**Comment by lucasdemarchi** [comment]
These are separate issues. In the current state of PX4Firmware it works with -j > 1. @tridge told me that in new versions (and before the switch to CMake) a fix I did some time ago (https://github.com/diydrones/PX4Firmware/commit/1623d181b791ed0dfc151db66c2ed41ffb1b9219) stopped working so will be reverted when we upgrade.

In this commit we are just allowing parallelism on the **top** makefile. For the linux case this means running in parallel all the time (the same that happens if you do `cd [ArduCopter|ArduPlane|...] && make -j8 <board>`). For PX4 if we need to serialize part of the build we do it internally.

**Comment by magicrub** [comment]
Great

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
