### PR TITLE
Add APM support for Erle-Brain 2

### PR DESCRIPTION
**Pull request by vmayoral**

### CODE REVIEW

**Comment by vmayoral** [comment]
@lucasdemarchi I've addressed your comments at #2874 except the integration of `AnalogIn` and `RCInput`. Since Erle-Brain 2 is already commercially available I'd like to give support as soon as possible. Could you please review it?

**Comment by lucasdemarchi** [comment]
@vmayoral I see very few changes from the previous PR. Particularly the code duplication for RCInput is bad. Could you explain why you need a different one? For example, there's a fix changing uintptr_t to uint32_t that should not be there... it's not actually fixing anything from what I can see (uintptr_t and uint32_t are the same thing on 32 bit platforms).

Lastly, please squash the last changes in the commits they are fixing. I'm not commenting on individual commits so you can push -f here.

**Comment by vmayoral** [comment]
Hi @lucasdemarchi,
Thanks for taking the time to review it again.

> there's a fix changing uintptr_t to uint32_t that should not be there... it's not actually fixing anything from what I can see (uintptr_t and uint32_t are the same thing on 32 bit platforms).
That's my bad yeah. Should be fixed now.

>Particularly the code duplication for RCInput is bad. Could you explain why you need a different one? 
I don't think we need a different one. I just preferred to do this in two steps because to me, it seems like it'll get accepted upstream faster. That said, i've done as you requested at RCInput and AnalogIn and merged Erle-Brain 2 and Navio implementations into one. As pointed out in the commits, there're relevant similarities also in the AnalogIn layer of Raspilot but since that requires a bit more of attention I'd prefer that to happen in a later pull request.

**Comment by Clouded** [comment]
I don't see anything RPi-specific in "AnalogIn_RPI". It would be better to name it Linux\I2C\ADS1115-something instead.

**Comment by vmayoral** [comment]
I'm ok with that. Thanks @Clouded. I'll rename it.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
