### PR TITLE
AP_Arming: add voltage and compass checks ahead of integration with Copter

### PR DESCRIPTION
**Pull request by rmackay9**
I'm sure the most controversial change is the removal of the prearm_failure_reason() if AHRS is unhealthy.  The failure-reason is not directly related to the AHRS health however.

The second most controversial change is probably the removal of the exclamation marks from the text strings sent to the GCS.

Also modified formatting.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Hi @rmackay9 

I added some comments to the individual files. I have no opinion on your controversial points :-)

**Comment by gmorph** [comment]
Reviewed - Looks fine to me.

**Comment by gmorph** [comment]
Tested in SITL with the joystick plugged in.  Rudder Armed and Disarmed the plane correctly.  Looks good.

**Comment by rmackay9** [comment]
Ok, I think I've incorporated everyone's requests and pushed to master, thanks!

**Pull request closed without merging**
