### PR TITLE
Copter: Restrict mode changes for TradHeli.

### PR DESCRIPTION
**Pull request by R-Lefebvre**

### CODE REVIEW

**Comment by rmackay9** [comment]
this seems to be failing travis because it's trying to build with a compiler that's not available anymore.  I suspect this will happen for any PRs against Copter-3.3 branch.

**Comment by R-Lefebvre** [comment]
Ok, so is there something I should do?  It compiles on my end.

**Comment by rmackay9** [comment]
@R-Lefebvre, no, I think it's ok.  I'll review in the next day or so.

**Comment by rmackay9** [comment]
merged, thanks!  sorry for taking so long.

Anything else you want in Copter-3.3.3-rc1?

**Pull request closed without merging**
