### PR TITLE
Compiler warnings

### PR DESCRIPTION
**Pull request by magicrub**
Fixes various compile warnings:
- float to double promotions
- float compare to constant (ie zero)
- unused template<double>

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm a little surprised that the "AP_Math:: compiler warnings" one requires the addition of the "detnxn" and other functions.  That's not a mistake though right?

**Comment by rmackay9** [comment]
For the last commit re "WGS84_A", I probably would have added a .0f to the end instead of making them an integer.  But what's there is what you intended?

**Comment by WickedShell** [comment]
@magicrub you can probably kill off this define as well I'm guessing:
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Common/AP_Common.h#L61

Also note line 55 in there has the GCC pragma for float-equals (commented out) if we are passing this arg elsewhere it can probably go as well.

**Comment by magicrub** [comment]
@rmackay9 the detnxn functions were giving warnings for not being declared. Where's the harm in declaring them?
@WickedShell  OMG that's a horrible define! That may actually be masking some warnings that should be fixed correctly. I was a little baffled by the 1e7 stuff showing up as floats, that's probably why!

**Comment by WickedShell** [comment]
To be fair I couldn't find a spot where it was ever used because of the IFDEF but still, that's something we shouldn't even allow...

**Comment by lucasdemarchi** [comment]
> I'm a little surprised that the "AP_Math:: compiler warnings" one requires the addition of the "detnxn" and other functions. That's not a mistake though right?

He's adding the declaration, not the definition of the functions... Although I think it should be in a separate commit.  I also like to copy and paste the warning message so it's clear what's being fixed, but that's just me.

**Comment by lucasdemarchi** [comment]
> @WickedShell OMG that's a horrible define! That may actually be masking some warnings that should be fixed correctly. I was a little baffled by the 1e7 stuff showing up as floats, that's probably why!

no... because it's not defined and as the comment says, it shouldn't be defined. I think @WickedShell said that it could be removed because it's **not** used, and shouldn't be.

**Comment by lucasdemarchi** [comment]
@magicrub I added some inline comments. In general I'm ok with the commits... some small suggestions and nitpicks only.

**Comment by magicrub** [comment]
implemented comments and rebased -i
- removed the (float)atof call due to stdlib not supplying it, but added it to the SITL ones.
- removed that wicked "#define float double" thing. That thing gives me nightmares!
- broke up AP_Math commit regarding separate commit for separate compile warnings
- removed the commit regarding the WGS84_A decimal place stuff. I'm not 100% that is computing the exact same result and I don't feel like testing it so we can just fix it some other time.

**Comment by rmackay9** [comment]
Merged all except these two which replace atof with strtof.  I think what's been done is ok but I'd like to hear lucas's opinion.
https://github.com/Airphrame/ardupilot/commit/7ff87ff171abf04de5e0df789c8c6e10e6f9a329
https://github.com/Airphrame/ardupilot/commit/df56a4466b0cd4852dce39e65aa047265287ea45

It's slightly bad behaviour to merge in only part of the PR but ..

**Comment by magicrub** [comment]
I don't mind the partial merge, Randy. Each commit was just chasing down a
sperate unrelated warning. The strtof changes were only in SITL comes where
it is fully supported. The ones where it is needed in an embedded
application I left as-is with the atof causing a warning.

**Comment by lucasdemarchi** [comment]
I'm ok with the changes to strtof(). Depending on the case we could implement a wrapper for safety reasons, but that would also apply to atof()

**Comment by lucasdemarchi** [comment]
and... by safety I mean:  unless we pass an endptr variable, there's no way to know if the conversion failed or was indeed 0. Example:

```c++
const char *s = "bla";
float f = strtof(s, nullptr);
```

`f` will 0. To fix this we actually should provide and `endptr` an compare to `s` in order to check if there was any conversion in place. It would also be good to check `errno` by ERANGE.

**Comment by rmackay9** [comment]
Ok, I've pushed the last two changes into master then, thanks!

**Pull request closed without merging**
