### PR TITLE
Parse parameter metadata as part of travis build [WIP]

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
First try at mechanism to parse parameter meta data as part of Travis build. This way parameter meta data breaks will be caught prior to merge.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Ok, so with the changes to travis.yml in this pull it does fail the build if the parameter meta data is bad. Issues:
- It runs twice, once for each item in the matrix. I'm not much of a travis person. I think I could move before_script: and it would only happen once. Not sure if that would still fail the build. Would that be a better way to do this? As it stands now, it adds a couple seconds more to the build process than it needs to.
- It leaves things like the apm.pdef.xml file in the root directory. Not sure if that will screw something else up later on.

**Comment by lucasdemarchi** [comment]
Looks good without the change to ArduCopter (was this intended to force a fail?)

**Comment by DonLakeFlyer** [comment]
Yes, this was intended to fail, so I could test. I'm going to try moving it to before_script to only run it twice and see what happens. Once I try that I'll put together a new pull which is correct.

**Comment by DonLakeFlyer** [comment]
Trying parsing in before_script to see how that works.

**Comment by DonLakeFlyer** [comment]
Ok, here are the two options:
1) Put the parameter parse test in before_script:. This will fail the build, but if parse fails the build stops immediately.
2) Put the parameter parse in build_script: This run the parse twice but continues the build so you can determine builds errors even if you have parse errors.

I think #2 is the better way to go.

I'm going to do a little more testing on this WIP pull then I'll put together a real pull.

**Comment by rmackay9** [comment]
@DonLakeFlyer, I agree #2 is better.

**Comment by DonLakeFlyer** [comment]
One last test run which is Option #2 with the parameter parse break removed. Should pass. If everything goes ok with this I'll close and make a real pull.

**Pull request closed without merging**
