### PR TITLE
Copter: Add AC_Booster for fast forward flight

### PR DESCRIPTION
**Pull request by fhedberg**
Adds support for lateral boosters used in fast forward flight with:

* AC_BoosterController: A booster controller that controls the booster backend. Takes pitch target as input and naively scales back the pitch and replacing the excess with lateral boost.
* AC_BoosterSimple: A simple booster backend that uses an AUX channel to drive an ESC, for example controlling an aft-mounted pusher propeller on a quad-copter.
* Copter: Adapted the applicable forward flight flight-modes to use the booster controller.

The approach of using pitch as a proxy for desired forward acceleration is naïve, but works decently in practice. Before we have more sophisticated merging of plane-like flight modes and navigation strategies, I think this is sufficient.

This pull-request has been flight tested using a quad-copter with an aft-mounted pusher propeller and on a compound helicopter using #1860.

### CODE REVIEW

**Comment by fhedberg** [comment]
@rmackay9 Any feedback on this? Biggest question-mark on my end is how to better translate accel_forward to desired boost in AC_PosControl::accel_to_lean_angles without using pitch as a proxy.

**Comment by rmackay9** [comment]
@fhedberg,
I spent some time reviewing this and it's nicely written.
Still, i'm very hesitant to merge it in because I don't think our code base it ready to accept the fundamental change in the assumption that the vehicle has a downward thrust vector.
Breaking this assumption means adding fixes in numerous places in the code which adds significant complexity.  It's perhaps manageable in these patches but it's sure to snowball if done more comprehensively.

Some of the changes required to handle it completely/comprehensively would be:
1. some manual flight modes modes (i.e. control_stabilize, control_althold) should be modified accept desired accerations from the pilot instead of lean angles.
2. a new desired-acceleration -> desired attitude class should be created with multiple implementations.  Multicopters would simply convert the desired acceleration to lean angles.  Booster-copters would use a different conversion which would result in a desired attitude+boost-level.
3. at least two different attitude controllers would be created.  The current attitude controller would remain and would accept the roll-pitch-yaw-throttle as it currently does.  A new alternative attitude controller would accept these plus a boost level.  These attitudes/boost would be converted to raw roll-pitch-yaw-thrust+boost values for the motors library.
4. the booster class should be integrated into a new quad-with-booster motors class which accepts the attitude+boost-level from the above attitude controller.  It should of course obey the armed state so the booster can't spin up with the vehicle is disarmed (the current patches don't absolutely protect against this).

5. similar to the manual flight modes mentioned above, the auto flight modes should be changed to produce desired accelerations instead of lean-angles.  In particular the position control library should have it's acceleration<->lean-angle code removed/replaced.

There are certainly many other places in the code where we assume lean-angle = acceleration that would need changing and other assumptions that I've overlooked.

There's some concern that the idea of a booster will not gain much traction because:
- it's not a "good" way to increase the vehicle's top speed or acceleration.  A regular quad with larger motors (equivalent to the increase in weight/power of the booster) will perform as well or better.
- yaw control is very weak a high speed when the vehicle is mostly flat.  As the speed increases it's likely the vehicle will lose control of it's yaw.

So we want to add support in ardupilot for hybrid vehicles but it's a big job and we need to be careful how we proceed.  I'm not sure we're ready for it and if we do it prematurely we're just going to add complexity which will make support more difficult and slow forward progress on the traditional multicopters.

**Comment by rmackay9** [comment]
In terms of the next steps, I'll have a chat with Tridge, Rob, Craig and some others about this and get their opinion as well.

**Comment by fhedberg** [comment]
@rmackay9 Thanks for the feedback.

I totally agree, especially now that I've gotten a better understanding of the codebase, that this is pretty far from the perfect solution and that a move an acceleration based world view is probably preferably. Implementing that however, is somewhat over my head (and time available).

I also don't really see the practical benefit of using pusher-props on regular multi-copters, but this PR was rather focused on providing forward thrust for compound helicopters using #1860, which brings us into the hybrid world as I also have wings with control-surfaces.

I'm not sure how @tiltrotor are progressing with their project, but I assume that moving to an desired-acceleration approach would be very beneficial for them as well.

Closing this for now.

**Pull request closed without merging**
