### PR TITLE
VideoIn: add benchmarks and improve performance of crop_8bpp() and yuyv_to_grey()

### PR DESCRIPTION
**Pull request by ricardotk**
This PR adds benchmarks using gbenchmark and improve performance of
crop_8bpp() and yuyv_to_grey().

### CODE REVIEW

**Comment by ricardotk** [comment]
@guludo would you mind taking a look?

**Comment by lucasdemarchi** [comment]
instead of going assembly, try enabling the compiler (via CXXFLAGS) to generate optimized instructions and compare to the ones without. For MinnowBoard Max that would be:
 `-march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2`

For ARM I think this would be: `-mfpu=neon -ffast-math`

**Comment by lucasdemarchi** [comment]
heheh... just found my blog post back when I was at university: http://www.politreco.com/2009/07/11/sharing-some-homeworks/

**Comment by ricardotk** [comment]
> heheh... just found my blog post back when I was at university: http://www.politreco.com/2009/07/11/sharing-some-homeworks/

Nice blog post! Learned some interesting stuff there (:

But it's a pity that the YouTube videos aren't available anymore, I was very excited to see your skills in blender 3D :laughing:

**Comment by jberaud** [comment]
>For a 640x480 image to 64x64 crop its 16.9%
For a 640x480 image to 240x240 crop its 12.2%
For a 640x480 image to 640x480 crop its 2.6%

Oops I misread the dats. Then it is a big improvement.

**Comment by jberaud** [comment]
>instead of going assembly, try enabling the compiler (via CXXFLAGS) to generate optimized instructions and compare to the ones without. For MinnowBoard Max that would be:
-march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2
For ARM I think this would be: -mfpu=neon -ffast-math

I will try both. But let's make it fly well first.

**Comment by jberaud** [comment]
Regarding the crop calculation, I could add the reviewed flag.

**Comment by ricardotk** [comment]
>instead of going assembly, try enabling the compiler (via CXXFLAGS) to generate optimized instructions and compare to the ones without. For MinnowBoard Max that would be:
-march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2

>For ARM I think this would be: -mfpu=neon -ffast-math

@lucasdemarchi we've got even better results with these flags (:

At least for the `yuyv_to_grey()` its very clear the gain in performance.

Without the flags:

Benchmark | Time (ns) | CPU(ns) | Iterations
---------------|--------------|-------------|-------------
BM_Crop8bpp/64/64      |   2655    |   2651    | 218750                                 
BM_Crop8bpp/240/240    |  33617   |   33667    |  20792                                 
BM_Crop8bpp/640/480    | 188022    | 188201   |    3684                                 
BM_YuyvToGrey/4k   |       1714   |    1717   |  403847                                 
BM_YuyvToGrey/75k     |   32148    |  32180   |   21649                                 
BM_YuyvToGrey/300k    |  128647   |  128753    |   5385 

With the flags:

Benchmark | Time (ns) | CPU(ns) | Iterations
---------------|--------------|-------------|-------------
BM_Crop8bpp/64/64     |          2644    |     2643  |   232103                                 
BM_Crop8bpp/240/240   |      33413  |     33346  |     20792                                 
BM_Crop8bpp/640/480    |   174583  |   174154     |    3962                                 
BM_YuyvToGrey/4k      |          1149     |    1150  |   599998                                 
BM_YuyvToGrey/75k      |      22135    |   22146   |    32813                                 
BM_YuyvToGrey/300k      |    85989   |    86140      |   7778

**Comment by ricardotk** [comment]
Since the comments are simple, I'll just force push a new version here.

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
