### PR TITLE
Linux_HAL_Essentials: RC AIO PRU firmware

### PR DESCRIPTION
**Pull request by mirkix**
- PRU firmware for BBB
- Use PRU1 for RC input AND output
- RC input with 5ns accuracy
- 12 PWM RC outputs with better than 1us accuracy
- Written is assembler (pasm include in am335x_pru_package) 
- Testcode `make test`(connect PWM out to RC input). Shows pulse length, pause length, T, jitter, and max program cycle length. 
- LinuxRCInput_AioPRU class for use with ArduPilot
- LinuxRCOutput_AioPRU class for use with ArduPilot
- Comments and reviews are welcome.

### CODE REVIEW

**Comment by proficnc** [comment]
Have you allowed for a pass through mode here? Ie, if the main processor locks up, can you continue in manual?

**Comment by mirkix** [comment]
Pass through is not as easy in the moment and not implemented. This is because all the protocol decoding (spektrum, sbus and PPM SUM) is done by the main cpu. It should be possible to implement something like a rescue system in PRU0 (which is not used with RC AIO firmware) which allow pass through, I have to think about that.

**Comment by tridge** [comment]
very nice work! I think the PXF could also adopt this. I've pushed to master.
How are things coming along with adding a wiki page on how to setup a BBBMINI ?

**Comment by mirkix** [comment]
Hello Andrew,

after the development of the PRU firmware I built a 250 Quad with the BBBMINI. The first test flight was yesterday, all works great, I am using the new AIO PRU firmware already. After the successful first flight I think now its time to start the wiki.

Best regards Mirko
bbbminiquad
bbbmini

**Comment by tridge** [comment]
great! I've assigned this issue to Craig. He can help you get setup with wiki edit privileges.
Congratulations on your successful flight!

**Comment by tridge** [comment]
I love the wiring pictures btw - that's my kind of prototyping :-)

**Pull request closed without merging**
