### PR TITLE
AP_Mount_SoloGimbal merge

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by jschall** [comment]
poke

**Comment by rmackay9** [comment]
I guess you have tested that master plus this set of patches is able to control the gimbal?
When I loaded master plus these changes to my Solo and checked that MNT_TYPE to "2", I wasn't able to control the gimbal.  I saw other problems with my Solo however including being unable to arm from the controller so it's not clear to me where the problem is.

**Comment by jschall** [comment]
Did you set up serial manager params?

**Comment by rmackay9** [comment]
@jschall, ah, yes that is part of it.  When I set SERIAL4_BAUD to 230hz I was able to see the gimbal parameters in the mission planner.  Sadly when I then changed SERIAL1_PROTOCOL to "0" (for console which is what I found in this file: https://github.com/3drobotics/ardupilot-solo/blob/2eecaf54fa1b59700d093036195a335668bc3078/mk/PX4/ROMFS/defaults.parm) I seem to have made it impossible for the Solo controller to connect to the Solo. :-(

**Comment by jschall** [comment]
Protocol 0 is disabled. We are setting serial2 to 0, not serial1. To
recover it you should be able to talk to the Pixhawk over USB either by
physically plugging in to the cube or by setting up the IMX6 gpios to turn
the USB switch on so that it can talk to Pixhawk over USB. You could also
get in through the gimbal port with an ftdi cable.

**Comment by rmackay9** [comment]
Merged, thanks!
I'll discuss with @tridge on Monday to see if he has any additional concerns.
@jschall, it would be great if you could look at using sniff (like in antenna tracker) to simplify the logic of keeping the gimbal and mount library parameters in sync.

**Pull request closed without merging**
