### PR TITLE
ArduPlane: Land disarm delay

### PR DESCRIPTION
**Pull request by magicrub**
After a landing has occur using a LAND waypoint, automatically disarm after (new param) LAND_DISARMDELAY seconds have passed. Use 0 to not disarm after a landing.

### CODE REVIEW

**Comment by magicrub** [comment]
depends on the updated is_flying() https://github.com/diydrones/ardupilot/pull/1888

**Comment by mday299** [comment]
We've got something I've been meaning to submit but haven't got around to yet.  Wait to disarm util all acceleromters calm down 

bool AP_Land::still_vibrating() {
       Vector3f accels = _ins.get_accel();
    
    _x_accel_list[_current_accel_idx] = accels.x;
    _y_accel_list[_current_accel_idx] = accels.y;
    _z_accel_list[_current_accel_idx] = accels.z;
    _current_accel_idx++;
    _current_accel_idx %= AUTO_DISARM_SAMPLE_SIZE;

    //don't do this test if you don't have enough samples
    if (_num_accel_data_points < AUTO_DISARM_SAMPLE_SIZE) {
        _num_accel_data_points++;
        return true;
    } 

    if (variance(_x_accel_list) < 0.001f && variance(_y_accel_list) < 0.001f
            && variance(_z_accel_list) < 0.001f) {
        return false;
    }
}

Of course you'd have to do a "variance" function -- I have that added to AP_Land in my little fork as well if you're interested.

I stick the "still_vibrating" check in the MAV_CMD_NAV_LAND case in the handle_auto_mode function in ArduPlane.pde

**Comment by magicrub** [comment]
0.001g on all axis? Isn't that pretty much impossible? Just sitting here on
my desk I doubt I could achieve that, especially for several continuous
seconds. For a disarm_after_land type thing, wind would trick it. The
threshold would have to be loosened to be of much use. Does it work for you
like that?

**Comment by mday299** [comment]
0.001 has been working for us for close to a year.   Those values should work with your plane on your bench.

However, we use a flying wing with no gear, so when we land we are flat on the ground and less susceptible to wind.  You _may_ have to loosen the tolerance a bit for a light geared plane in wind.

**Comment by magicrub** [comment]
we use a flying wing w/o gear as well - Skywalker X8.

**Comment by magicrub** [comment]
I have not yet flown with this but it works great in SITL.

**Comment by tridge** [comment]
Tom, ping me when you have a chance and I'll teach you to use git interactive rebase to fix patches up. The patches in this PR are a bit of a mess

**Comment by tridge** [comment]
after our mumble discussions I've pushed the new version to master
thanks!

**Comment by magicrub** [comment]
Thank you!

**Pull request closed without merging**
