### PR TITLE
WAF Build System for ardupilot [v2]

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This is the next version of #3242.
Diff:
 - Minor fix on `cmake` finding
 - Remove temporary test code from `Tools/autotest/sim_vehicle.sh`
 - Change travis script so that waf build is done inside the loop over `TRAVIS_BUILD_TARGET`

Best,
Gustavo Sousa

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
And... there's a new commit on top from @cmarcelo so it's easier to support the other Linux boards.

**Comment by tridge** [comment]
I think we should include the wafadmin editable sources in the tree, probably under Tools/build/wafadmin
See this as an example:
https://git.samba.org/?p=samba.git;a=blob;f=buildtools/bin/waf;h=1b0f4662a56d7c44b5bb2215724d7af63a28018e;hb=HEAD
(you can probably just copy that file)
And see wafadmin here:
https://git.samba.org/?p=samba.git;a=tree;f=third_party/waf/wafadmin;h=080028105cd97aadcc084461deb90730ad4df551;hb=HEAD
Alternatively we could create a diydrones/waf git tree and use a git submodule for wafadmin. That will prevent polluting the tree.
The reason for this approach is to avoid the arguments debian has made about including packages using the waf build system. That argument is somewhat silly I think, but it is easiest to just avoid it, and including the editable version of waf in the tree makes it crystal clear that there is no debian policy violation.
It will also make waf a tiny bit faster

**Comment by tridge** [comment]
I'd also like to see a Makefile.waf that will be a prototype of when we switch to waf as primary. It would avoid the need for the alias

**Comment by tridge** [comment]
the libraries search causes issues with stray files:

tridge@blu:~/project/UAV/APM(guludo-pr/waf-build-v2)$ ./waf build
Waf: Entering directory `/home/tridge/project/UAV/APM/build'
Could not find library mav.tlog

the auto-search also provides problems for when you have stray directories:
../libraries/AP_NavigationLegacy/AP_NavigationLegacy.cpp:6:23: fatal error: AP_Common.h: No such file or directory
 #include <AP_Common.h>

I think we do need to have an equivalent of make.inc that lists the library dependencies. Ideally it would parse the existing make.inc to make the transition less painful, though that is not very python-like

**Comment by lucasdemarchi** [comment]
@guludo was @tridge said in the comments above and as talked in the dev call today... we should change this PR to use a git submodule rather than the approach we've got to update our packed waf binary.

This means having to add the Makefile.waf too. Because it's in this wrapper makefile that we actually need to check if we have a checkout of the waf submodule.

@tridge could you add the repository under diydrones/waf so we use it?

**Comment by tridge** [comment]
I've created a branch with the submodule based waf here:
https://github.com/tridge/ardupilot/tree/waf-wip
It also has an initial Makefile.waf

**Comment by guludo** [comment]
@tridge I had already implemented some stuff a while ago hehehe
My version of Makefile.waf has a different approach:
https://github.com/guludo/ardupilot-1/tree/wip/waf-build-v2

**Comment by guludo** [comment]
Headsup: Updated the branch with the addition of the waf submodule and a make wrapper.

Haven't looked at the errors @tridge mentioned yet.

**Comment by lucasdemarchi** [comment]
@guludo thanks.

I think we should create issues in github and add a "waf" label to them in order to track the problems.  Then we could apply the PR. @tridge thoughts?

**Comment by lucasdemarchi** [comment]
@guludo I think this should need a little more testing... particularly for the integration with git submodule init/update. Because it will be the first impression and should at least be able to checkout everything.

I tried here without having the submodule and it didn't work. First issue is the use of realpath. You should use abspath instead.

I'm also not liking how we compile things, doing cd to the subdirectory. Using --target= worked in all tests I did here.

This is the temporary diff I had before having to switch to another task:  https://github.com/lucasdemarchi/ardupilot/commits/wip/waf

**Comment by tridge** [comment]
I'd be happy to apply to master now if both of you are happy to do that. As long as we don't publicise it yet then I think its fine sorting out the issues in a later PR
Gustavo, thanks for the makefile wrappers!

**Comment by lucasdemarchi** [comment]
OK. Let's merge then :)

Thanks.

**Comment by tridge** [comment]
pushed, thanks to both of you for all your work on this!

**Comment by guludo** [comment]
Thanks Tridge! :-)

**Pull request closed without merging**
