### PR TITLE
AP_InertialSensor: disable reset on MPU9250

### PR DESCRIPTION
**Pull request by staroselskii**
Getting rid of the reset as discussed on gitter earlier today. We need that until we figure out the proper fix for the issue.

### CODE REVIEW

**Comment by staroselskii** [comment]
@lucasdemarchi @tridge 

It'd be great to merge as soon as possible. Thanks!

**Comment by lucasdemarchi** [comment]
It'd be good if we put good explanations on the commit messages because it's the only place in which we can easily find the reasoning for a commit. So for this one:

```
AP_InertialSensor: disable reset on MPU9250

The Compass library is initialized before the InertialSensor. AK8963 with
MPU9250 as backend already takes care of resetting MPU9250. The problem with
also resetting it in the MPU9250 initialization code is that if the reset
happens during an internal I2C transaction, the AK8963 may hang. So here we
remove the reset inside MPU9250.  There still a possibility that the first
MPU9250 initialization is not successful and it resets the chip, but it's not
happening in tests.
```

**Comment by lucasdemarchi** [comment]
Tested here starting and stopping ArduCopter 10 times in row and all of them starts successfully. I pushed a branch to my repo with the commit message amended: https://github.com/lucasdemarchi/ardupilot/tree/emlid-mpu9250-reset-revert-fix

**Comment by magicrub** [comment]
The commit format is:

folder_name: simple explanation
<empty line>
more in-depth explanation.

Even simple commits should say something about why this commit is worth
pushing because it may seem obvious now but to everyone else, even your
future self, may not understand it. Personally I believe this should be
strictly enforced. Many open/closed projects enforce various rules to
various degrees. The more strict you are the more it pushes out the casual
committer so generally most open-source projects lack discipline in this
regard. As projects get bigger they generally get more strict. Perhaps with
the flurry of activity this is something we can start enforcing soon. (same
with compiler warnings)

**Comment by staroselskii** [comment]
@lucasdemarchi 

I totally agree. I updated the commit. I also suggest to make an entry in the wiki regarding this kind of behavior (it that's not already there).

**Comment by magicrub** [comment]
Commit log messages are described here
<http://dev.ardupilot.com/wiki/submitting-patches-back-to-master/> in the
dev wiki but it's not very obvious with to it's use of font size and bold.

**Comment by lucasdemarchi** [comment]
@magicrub maybe we could inline the wiki page in the CONTRIBUTING.md?

**Comment by magicrub** [comment]
Sure, why not. Lets start a new thread instead of hijacking this one if we
discuss it any further.

**Comment by mirkix** [comment]
I agree with @staroselskii also get compass failure since #2405 is merged into master.

**Comment by lucasdemarchi** [comment]
just noticed that the first time it executes I always get an "bad DEVICE ID", even with this patch applied.

**Comment by ivereninov** [comment]
@lucasdemarchi  Even after power cycling the board? We have determined a direct connection between this commit and probability of error. With reset it breaks almost every time, without it only on very rare occasions and if you restart firmware multiple times in a row. 

We will do our best to make a proper fix, but it would be really sad if constantly crashing magnetometer will make it in the next rc or even in next copter release.

**Comment by lucasdemarchi** [comment]
@ivereninov I understand that... every time I start it by the first time I get the "bad DEVICE ID".

**Comment by staroselskii** [comment]
@lucasdemarchi 

Had you experienced the same behavior before the latest commits? Could you please revert them and try once more? I don't remember AK8963 failing on the first launch.

**Comment by tridge** [comment]
applied, thanks!
I've also pushed a change to set the SPI bus speed low on startup of the AK8963 driver. That seems to raise the chances of success for me. We've experienced problems in the past with invensense parts trying to configure them at high bus speed

**Pull request merged**
