### PR TITLE
Add LSM9DS0 INS backend

### PR DESCRIPTION
**Pull request by guludo**
Hi all,
This series of commits add INS backend support for LSM9DS0.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
I made some comments on the specific commits, particularly on being able to us runtime options rather than compile time.  Otherwise it looks good to me.  We may want to enable fifo as we are going to do in MPU9250, but just having this driver working is a great step. :+1:

**Comment by guludo** [comment]
Hi @lucasdemarchi, thank you for the comments!
There's just one (https://github.com/guludo/ardupilot-1/commit/e68ef6b5f496da19ed82d185e73c274dcfc14328#commitcomment-11871087) that wasn't totally clear to me. Since two of the changes recommended depend on it, I'll make the changes as soon as we can get that clarified.

**Comment by guludo** [comment]
@lucasdemarchi recommended fixes were done above.

**Comment by tridge** [comment]
applied with a change to make the max offsets be a scaler instead of a vector
thanks!

**Comment by lucasdemarchi** [comment]
Thanks @guludo and @tridge.

@guludo  one thing we want to understand is why it has such a huge offset. Let's try to get a log putting the vehicle in all 6 directions to see if the values from the accel make sense.

**Comment by guludo** [comment]
@lucasdemarchi I've logged the accel values after calibration.

So the output from calibration routine was:
```
AccelRange: 19.2 19.5 19.2
Offsets[0]: -4.19 3.60 -2.12
Scaling[0]: 1.02 1.01 1.02
Calibration successful
Trim OK: roll=0.19 pitch=-0.43
```

I've attached the plots from my test. My test was done by putting the sensor in the following "vehicle" positions (and in that order):
 1. Level
 2. On its left
 3. On its right
 4. Nose pointing down
 5. Nose pointing up
 6. On its back

The first plot shows the three axes values throughout the test. We can picture each of the 6 positions there. The second plot shows the length of the acceleration vector.

lsm9ds0_accel_axes
lsm9ds0_accel_length

**Comment by lucasdemarchi** [comment]
My interpretation matches yours that it looks good. @tridge @rmackay9 any comments?

**Pull request closed without merging**
