### PR TITLE
RFC: support for timesliced timers

### PR DESCRIPTION
**Pull request by jberaud**
This pull request is more intended to get comments on this way of dealing with lower freq timers.
I have noticed using lttng that the main issue I had with scheduling (SCHED_DEBUG long loops) were due to the fact that even if Baro and Compass timers are called with a lower frequency, they are called on the same iteration of the main timer loop. This causes some very long timer loops that also block the main loop for a long time.
This is a way of getting lower freq timers not to run on the same loop iteration.
I must add that the problems I have with the duration of the Baro and Compass reads are due to the fact that on the bebop all of the basic sensors are connected with an i2c bus, which is very slow compared to spi.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
I'm skeptical this will solve the issue :-/. You are giving time slices based on "low frequency" tasks spreading them on loop executions. However we should rather spread based on the execution time, not how frequent the call will be.

We could do that, but measuring the execution time will be very hard to be done correctly for each board. Even more as we increase the number of supported boards.

So... The kernel only offers a sync API. I think a better approach would be to mimic an async API by having a thread per bus (but that would be overkill if we increase too much the number of buses) or by having a thread pool in which we queue the operations.

Another approach that would alleviate our problem is using the kernel driver. Since MS5611 already has one, that would be a good candidate. That can be done only if the I2C bus it's on is not shared with other devices. I'd really love to see this happening and in the long run I think it's more future proof.

Could you share your numbers about the schedule overruns? You may want to apply the patches on #2617 in order to get the distribution of the overruns.

**Comment by jberaud** [comment]
Thanks for the review. You are absolutely right about the fact that it would be better to spread the tasks base on their execution time rather than how frequent the call will be.
The fact that it solves my issues may come from the low number of timesliced timer threads(2).
The number of long loops is lowered from between 6 to 10 to 0 to 1.
I will try these patches to see the distribution, though, having done several lttng traces, I already have the (almost) exact graphs showing each thread's execution time and order. I can share them if you are interested.
I understand your skepticism about the api for a wider use, especially if the number of timers increase, but most boards use only 2 or 3 low freq timers and on the Bebop, it improves the number of missed loops.
Having a thread per i2c bus wouldn't improve as much since both baro and compass devices are on the same bus. It could improve by having the priority of the thread lower than the main loop. So maybe creating a lower priority thread for lower freq sensors could do.

**Comment by jberaud** [comment]
About the kernel drivers. We are probably going this way in the future. The objective here is to port all of the sensor drivers on the iio framework. So at some point we will use kernel drivers.

**Comment by lucasdemarchi** [comment]
> I will try these patches to see the distribution, though, having done several lttng traces, I already have the (almost) exact graphs showing each thread's execution time and order. I can share them if you are interested.

Would be nice to take a look on your graphs indeed.

> I understand your skepticism about the api for a wider use, especially if the number of timers increase, but most boards use only 2 or 3 low freq timers and on the Bebop, it improves the number of missed loops.

Imagine we have a sensor with a long running task taking about 2ms to complete.  There would be nothing we could do to lower the overruns.

> Having a thread per i2c bus wouldn't improve as much since both baro and compass devices are on the same bus.

But then you can work with queuing the commands, mimicking an async API. Then you have the timer thread (or the main thread since there would be really no use for using a timer thread here) to get the data from that thread and enqueue commands.

>  It could improve by having the priority of the thread lower than the main loop. So maybe creating a lower priority thread for lower freq sensors could do.

You may want to increase the main thread priority so it doesn't suffer starvation. We were getting a lot of starvation on the main thread some months ago when we were using **all** sensors + the PCA9685 in a single I2C bus (yep, I know this is crazy ;-)). It was a "DIY drone" with a MinnowBoard Max. In my mind it makes a lot of sense to have the main thread with the highest priority so when it's waiting on sensors it actually boosts the priority of the thread it's waiting for (due to priority inheritance in the Linux kernel). And then it never suffers starvation. I never sent the patch because I stopped using all the sensors on I2C bus and so I couldn't justify with actual data.

**Comment by lucasdemarchi** [comment]
> About the kernel drivers. We are probably going this way in the future. The objective here is to port all of the sensor drivers on the iio framework. So at some point we will use kernel drivers.

Nice... I think the first one I'll try to support is MS5611 since that one has the IIO driver already. There's just one more task on my todo list before going this direction :-).

**Comment by jberaud** [comment]
lttng_trace_timers

What we can see in this loop, is that the baro.read called from the main loop takes 2ms. It is due to the fact that 3 timers are called in a row, and even a fourth one because the timers are getting late. The baro.read function calls suspend_timers, which needs to wait for all the current timers to end.
The baro and compass timers take around 300µs each. 
note : The overall perf are degraded by the use of lttng.

**Comment by jberaud** [comment]
The timeslice method proposed wouldn't solve anything if a timer took 2ms like you said. But in the case of MS5611 and AK8963, the reads take around 300µs, which is enough to have an influence on the main loop and still under 1ms , which is the limit above which the timeslice method wouldn't work.

**Comment by jberaud** [comment]
Regarding the iio drivers, ak8963 and mpu6000 already exist. We have modified the mpu driver in order to use it in fifo mode like we do in the regular bebop software. After implementing the missing features on the Bebop in ardupilot, I will focus on using only iio drivers for the sensors and the motors.

**Comment by tridge** [comment]
I think the correct way to fix this is to have a thread per bus, and use that instead of the global timer thread. We can keep the timer thread for compatibility until all drivers use the per-bus thread, but we should get drivers across to using the per bus threads soon.
This is a good time to be doing this sort or re-organisation I think. 
How about this for an API:
 bool hal.i2c->register_task(uint8_t bus, AP_HAL::MemberProc callback, uint32_t interval_usec);
and the same for hal.spi
we then only do I2C from the main thread during device detection. After a device is detected we do all operations in the per-bus thread. That would include the device initialisation.

**Comment by jberaud** [comment]
Thanks for you answer,
I will try soon to implement that. Even though there are several devices on i2c-1 on the Bebop, I was probably mistaken when I told Lucas that it wouldn't improve things.
Currently, the main thread needs to wait for all the timers to stop (suspend_timer_procs) and with such a callback system, we would only need to have a lock per device in order to insure the coherence of the data.
I will work on that next week to see what performances I get.
Regards,
Julien

**Comment by lucasdemarchi** [comment]
Ok, let's close this since we are going to fix it with the per bus thread.

**Pull request closed without merging**
