### PR TITLE
Vagrant:  Updated Vagrantfile for Vagrant config version 2

### PR DESCRIPTION
**Pull request by eliao**

### CODE REVIEW

**Comment by magicrub** [comment]
Is this still valid? @geeksville , can you take a look?

**Comment by geeksville** [comment]
Hi @magicrub - yes, this looks like a good change to me.

**Comment by magicrub** [comment]
Would you mind giving it a try to confirm?

**Comment by tridge** [comment]
sorry for taking so long on this. Unfortunately it now doesn't rebase on master cleanly, as I don't know enough about vagrant to fix it.
I'll close this, but I'm happy to accept a new PR. I'll make sure I pull it in quickly

**Pull request closed without merging**
