### PR TITLE
Linux UART rework

### PR DESCRIPTION
**Pull request by staroselskii**
The substitute for #2406. I have decided to make a new PR in order not to purge all the comments in the old one. 

@lucasdemarchi @tridge 

I've tried to fix all the issues we discussed earlier.

It'll be terrific to get rid of the petty little bugs in the current implementation by getting this patch merged. I'm looking forward to continue to improve the code at hand as suggested in the last comments from @lucasdemarchi  in #2406 as soon as the PR gets accepted.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
humn... so in the end every caller of recvfrom() and sendto() don't actually use the timeout?  Also the amount of commits fixing previous commits just make it harder to review. Please fix on the commit itself rather than adding commit on the top.  For example:  you remove TCP, then add it back on top, then rename it.  We need to improve our process with big pull requests like this so they don't sit waiting for review for days, weeks or months like this.  Improving commit messages and smartly splitting the commits is a big step towards that goal.

I went through all the commits and they look nice. There's certainly room for improvement, but I think this is a good start.  I'm just worried by the recvfrom() @tridge commented on.

**Comment by staroselskii** [comment]
@lucasdemarchi 

I do like to rebase the changes but there's an issue with github that we've already discussed. The rebase purges all the comments. 

Sorry for the mess with the timeout. I've thought that's clear now.

Yeah, that's been already a month. I would've started to improve the code if the current version hadn't already been extensively flight tested. We'd really like to have these changes in the next release. (Compass inconsistency is another serious issue I've been eager to work on. But I haven't got a feedback on that one, unfortunately). 

Thanks!

**Comment by lucasdemarchi** [comment]
> I do like to rebase the changes but there's an issue with github that we've already discussed. The rebase purges all the comments.
> 

yeah... github is terrible for proper code review. I've been working around that by 1) if there are no comments, just "push -f" since you won't loose anything; otherwise 2) open new pr with a "version suffix". That also gives you a place to mention what changed between the versions and make the review process much easier.

> Sorry for the mess with the timeout. I've thought that's clear now.
> 
> Yeah, that's been already a month. I would've started to improve the code if the current version hadn't already been extensively flight tested. We'd really like to have these changes in the next release. (Compass inconsistency is another serious issue I've been eager to work on. But I haven't got a feedback on that one, unfortunately).

Is this #2397?  It should be improved now after https://github.com/diydrones/ardupilot/commit/0acfcbfa811bb51915e80448e08976b1b603ea8c

But yes, the different offsets among magnetometers bother me as well.

**Comment by staroselskii** [comment]
@lucasdemarchi 

Yes, I was referring to #2397. It's not explicitly related to the commit you've mentioned.

**Comment by tridge** [comment]
I've pushed this to master now, with some re-work.
The main re-work is to make TCP behave as I explained previously. TCP is always a server, and allows multiple connections to be made. So you can disconnect and reconnect in flight without causing ardupilot to exit.
The wait flag just means to block startup until the first connection is made.
I've also fixed up the handling of udp connections when the interface is not available at boot. That is good for systems using 3G links that make take a while to come up

**Comment by staroselskii** [comment]
@tridge Thanks!

**Pull request closed without merging**
