### PR TITLE
Coax differential thrust mixing

### LINKED ISSUE #1467: Copter: coaxial props could potentially be more efficient at different top-bottom throttle ratios
X8 copters may be able to hover longer if the ratio of top-bottom throttle in a hover is modified.

Finding the optimum hover ratio could be done by first making the ratio configurable at runtime and then doing a slow sweep in loiter and observing the hover watts.

### PR DESCRIPTION
**Pull request by chapman**
Rather than a fixed 1:1 relationship between the upper and lower motors in a coax ‘octa-quad’ (a.k.a. X8) setup, this allows modification of that balance for optimal performance, and tuning from CH6

This is a simple scale value for the upper and lower motor outputs, clamped between 0.0 and 1.2 (to prevent vertical flyaways by accidentally entering too high a value).

Not certain the scaling is being applied at the best spot within AP_MotorsMatrix::output_armed_stabilizing(), currently at almost the end, immediately prior to clamping and output.

Test flown successfully.

Fixes #1467

### CODE REVIEW

**Comment by rmackay9** [comment]
It's come up a few times on drones-discuss (and in the forums) whether the difference between upper and lower speed is really important.  The most convincing document I read (which sadly I don't have a link to anymore, sorry!) came from a university study which showed that ideally there should be only a 3% difference between upper and lower motor speeds.  For me that calls into question whether it's worth the extra code complexity.  Do we have any data or information that it's really helpful?  Sorry to be annoying, it's just that we have this KISS principal and part of that is only solving the problems that we know we have, not just that that we think we might have.  I hope that doesn't come off as crappy.

If we do really think/know that it's necessary, instead of having two parameters to control the upper and lower ratio, how about just one and apply half the the upper and half to the lower.. or perhaps apply the percentage to both upper and lower equally.

Also I'm wondering if we need the ratio at all?  Perhaps we should just add a throttle factor similar to the roll, pitch and yaw factors.  Then multiply each motor by it's factor.  For non-coax copters that factor would always be 1.0 but for coax it could be 0.97 for the upper, 1.03 for the lower (or whatever).  Of course we don't have an easy way to update motor factors during flight but that could be added separately 'cuz it's all just held in an array.

**Comment by chapman** [comment]
Thanks for looking Randy.

I actually did initially have this as a single parameter which could tune the balance between upper+lower, but although simpler from a parameter perspective, it is more complex to code and describe how it is working, and different to other platforms.

The other reason I wanted to go for a straight scaling term separately for upper and lower is that it allows you full flexibility for testing things like flying with the upper or lower motors completely off, which I wanted to do recently to investigate vibration issues.

This mixer is a standard thing on other platforms, and I was surprised to see it missing when I moved to a coax rigs recently. 5% doesn't seem like much of a win but it does add a minute or two to a flight when you get up around half an hour, which is significant when you're flying them commercially.

I'm really keen to see this merged in so others can do additional testing with a wider range of vehicles, it could make a big difference in some cases. If everyone comes to the conclusion that it isn't needed we could pull it out again, but I think it is well worth it to be able to test. Until we get an entirely new battery technology, every little bit we can squeeze out helps.

Also, it's not just about efficiency -- the other reason I'm experimenting is noise and vibration. It makes a noticeably different sound as you tune the ratio, which although hasn't shown itself in greatly different vibrations in the logs, it could be enough to change the effect of very fine vibes showing up as 'jello' in recorded video.

**Comment by rmackay9** [comment]
AC, thanks again for the commit.

I hear what you're saying about using the upper and lower for turning off motors but if we want to be able to turn off motors then let's create a separate feature for that that works on all frames.

You know, we use to have this feature but we pulled it out because nobody ever used it and nobody could demonstrate that it added value.  I understand that it seems logical that it could add value... but it's just never been shown to.  Do you think you could do some kind of test that shows some improvement?  Others on drones-discuss or diydrones may also be interested and I guess they can take your patch or we can make a binary available to them.

I think adding a throttle factor is a more flexible solution.

Adding it into the stability patch in the correct place is a bit more complicated than how it's been done here.  In this PR it's done after the thrust curve and volt scaling but I think it should be done before.
The stability patch also assumes the throttle factor is 1.0 for all motors.  If it's not symmetrical (i.e. upper and lower are different distances from 1.0) then the current "best throttle" calcs will be incorrect.  Could you have a chat with Leonard re the stability patch?

Overall it's a good piece of work but I don't think I can pull this into master as it is.

**Comment by rmackay9** [comment]
By the way, I do yield to pressure especially from the dev team... maybe we should get some other people's points of view by discussing on drones-discuss?

**Comment by rmackay9** [comment]
Thinking about this some more.. maybe we could just compromise and simplify it down to one param for the ratio, move the coax multiplication just above the thrust curve and put it in...

**Comment by magicrub** [comment]
@chapman  Is this PR still valid? If so, a rebase on master is needed to keep it alive.

**Comment by magicrub** [comment]
rebase needed. @chapman is this PR still valid?

**Comment by R-Lefebvre** [comment]
I'd be very surprised if this was still valid at all.  My understanding is Leonard is heavily reworking the "stability patch" and it has probably changed significantly.

**Comment by R-Lefebvre** [comment]
Just asked Leonard directly to comment on this.

**Comment by R-Lefebvre** [comment]
Closing this issue after talking with Leonard.  Unfortunately this PR is hopelessly outdated as Leonard has rewritten the Stability Patch for 3.4.

**Pull request closed without merging**
