### PR TITLE
Plane: Make base_mode armed status depend upon the arming library

### PR DESCRIPTION
**Pull request by WickedShell**
Fixes the fact that on plane you can arm without pushing the safety switch.

### CODE REVIEW

**Comment by magicrub** [comment]
That soft armed thing drives me nuts. I always use the direct armed call
like you have.

**Comment by WickedShell** [comment]
It causes a bug because soft arming reflects the state of the safety switch
as well as the arming library. There are 4 possible combinations of FMU
arming and safety switch so without the change its impossible to tell if
the FMU is armed if the safety switch hasn't been pressed. This changes
allows you to tell all  the combinations (safety switch is available in the
SYS_STATUS message)

**Comment by WickedShell** [comment]
Swapped to 3.5.1 as GCS's will handle this correctly by default, and MP show's the safety switch state now.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
