### PR TITLE
Copter: Prevent zero-valued RC inputs on PX4

### PR DESCRIPTION
**Pull request by matthewlloyd**
* Check the channel_count in the ORB rc_input structure,
  since it might be zero, and ignore the RC input if it is.
  This requires radio.pde to call the newly introduced
  RCInput::num_channels method.

* Add additional checks in radio.pde:read_radio so that zero-valued
  RC inputs are ignored and eventually cause radio failsafe.

Tested that RC input still works as normal, at least with SBUS
(which is all I have right now).

These fixes will hopefully prevent a repeat of this crash:

https://groups.google.com/forum/#!topic/drones-discuss/ZBlTgNsK638

The code has changed slightly since the firmware version I was
running when I had that crash (valid_channels in RCInput has
been replaced by the new_input and num_channels methods) but
the underlying issue is still there, which is that if an
ORB rc_input is received with a channel_count of zero,
zero PWM values end up being used as ArduCopter's RC inputs.

### CODE REVIEW

**Comment by hsteinhaus** [comment]
This PR seems to address partially the same issue like my https://github.com/diydrones/ardupilot/pull/1346 . So I am obviously not the only one that got zeros as RC input.

@matthewlloyd How did you feed your RC signal into the Pixhawk? PPMSum?

**Comment by R-Lefebvre** [comment]
Are people still getting zero values?  I struggled with this on a PX4 V1 in fall 2013, but haven't heard much about it since.

**Comment by hsteinhaus** [comment]
I have seen them in August 2014 for the last time - but I have moved to S.Bus in between. I guess they are still there when using PPMSum. However, checking the number of channels in the telegram could be a good idea.

**Comment by rmackay9** [comment]
I know this is an insanely old PR but we're trying to clear the backlog.

I've spent some time looking at this and I can't actually reproduce a case in which we recieve less than a full frame from PX4Firmware.  Here's what I tested:

Test 1 with Futaba TX + PPM sum receiver:
a) before TX is turned on, no frames are received, RC inputs are all zero
b) once TX is turned on, full frames (7channels for me) appear
c) when TX is turned off, full frames (7channels) continue with throttle channel 3 pulled low
d) when receiver is disconnected, frames stop appearing, ardupilot keeps last value

Test 2 with Futaba TX + traditional 7-channel receiver + ppm encoder:
a) before TX is turned on, full frames (8 channels) are recieved with ch3=900, all others 1500
b) once TX is turned on, full frames (8 channels) appear with TX's actual values
c) when TX is turned off or traditional receiver removed, full frames continue, same as (a) above
d) when ppm encoder is disconnected, frames stop appearing, ardupilot keeps last value

So I can't reproduce a problem but theoretically if the receiver sent a reduced number of channels we could have some problems:
i) less than 7/8 could cause an auxiliary function to turn off (i.e. simple mode off, switch out of a flight-mode if initiated from aux channel)
ii) less than 5 could result in a flight mode change
iii) less than 3 sent could result in flight mode change & yaw change

If less than 2 channels are sent, the radio failsafe triggers (assuming it was set up) which causes all Aux switches and pilot input to be ignored so this is safe.

If RCMAP is setup it could change this assessment a bit because throttle could be setup on ch1 or ch2 meaning the radio failsafe wouldn't kick in if just one channel was sent.

..but in general, what's dangerous is when between 3 ~ 6 channels are sent.

I've never seen this situation, has anybody else?

**Comment by rmackay9** [comment]
Ok, I'm going to close this but willing to re-open it if people object.

**Pull request closed without merging**
