### PR TITLE
Fix MS5637 CRC check

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Hi @zehortigoza, separating the logic to read the CRC and calculating it looks good and easier to follow. It also looks better than the previous version, but I'm still not happy with how you are fixing it. We are re-constructing the PROM memory, skipping the read of C1, C2, ..., C6. The fact that the CRC in MS5637 is inside the first "factory defined 16 bits register" only means we don't even have to read the 8th register. For MS5637, `CMD_MS5611_PROM_CRC` makes no sense and we should not be using it.  I'd rather have a separate _check_crc() which reads the right registers, creates the correct data buffer + a separate uint8_t containing the crc and pass down to the common function. This way we wouldn't have to play with mask and index.

**Comment by zehortigoza** [comment]
@lucasdemarchi This was the first approach that I sent to you, so no problem in have a override method?

**Comment by lucasdemarchi** [comment]
@zehortigoza I don't think it's like the first approach. If index was something from a blob we read from the device, it would be ok the way it is. However here **we** are creating the blob ourselves. Why would you need a separate init() function?

**Comment by lucasdemarchi** [comment]
> Why would you need a separate init() function?

answering myself... because you would call it in the constructor :-/. I'll take a closer look later today.

**Comment by zehortigoza** [comment]
Another alternative a little bit ugly is add a parameter to AP_Baro_MS56XX() and call the correcly implementation of crc_check(), @lucasdemarchi what do you think?

**Comment by dgrat** [comment]
This commit does not help to clean up the code.
One needs only one function and not two to compare CRCs.
Is there a single reason to have two functions?
Additionally, I would rather implement the functions like in my project old project :P

    // CRC8 check
    inline unsigned char crc8(const char* data_p, unsigned char length) {
      unsigned char checksum = 0;
      while(length--) {
        checksum = (checksum + *data_p++) << 1;
      }
      return checksum;
    }

    // CRC16 check is enough for 256 character strings ^_^
    inline unsigned short crc16(const char* data_p, unsigned char length, const unsigned short mask = 0xFFFF) {
      unsigned short crc = mask;

      while(length--) {
        unsigned char x = crc >> 8 ^ *data_p++;
        x ^= x >> 4;
        crc = (crc << 8) ^ ((unsigned short)(x << 12)) ^ ((unsigned short)(x << 5)) ^ ((unsigned short)x);
      }
      return crc;
    }

**Comment by lucasdemarchi** [comment]
On Wed, Nov 25, 2015 at 8:25 AM, Daniel Frenzel <notifications@github.com>
wrote:

> This commit does not help to clean up the code.
> One needs only one function and not two to compare CRCs.
> Is there a single reason to have two functions?
> Additionally, I would rather implement the functions like in my project
> old project :P
>
> // CRC8 check
> inline unsigned char crc8(const char* data_p, unsigned char length) {
>   unsigned char checksum = 0;
>   while(length--) {
>     checksum = (checksum + *data_p++) << 1;
>   }
>   return checksum;
> }
>
> // CRC16 check is enough for 256 character strings ^_^
> inline unsigned short crc16(const char* data_p, unsigned char length, const unsigned short mask = 0xFFFF) {
>   unsigned short crc = mask;
>
>   while(length--) {
>     unsigned char x = crc >> 8 ^ *data_p++;
>     x ^= x >> 4;
>     crc = (crc << 8) ^ ((unsigned short)(x << 12)) ^ ((unsigned short)(x << 5)) ^ ((unsigned short)x);
>   }
>   return crc;
> }
>
>
Except that it's CRC-4. The original implementation comes from the
datasheet.

Lucas De Marchi

**Comment by lucasdemarchi** [comment]
> This commit does not help to clean up the code.
> One needs only one function and not two to compare CRCs.

One is to actually read the data stored in the PROM and the CRC. Then
calculate ourselves the crc to check it matches the stored one. In your
function you are just receiving the data as an argument, but we need to get
it from somewhere.

Lucas De Marchi

**Comment by dgrat** [comment]
Reading from the ROM belongs in one function, and calculating the CRC in another function.
This is already started in this commit by removing the ROM access in "calculate_crc". Beside the fact that I think a CRC check function would be a good common function (maybe in APMath.h) and doesn't really belong in the driver, I also don't like this particular implementation of the function (all).
Additionally, the other function _check_crc() is called exactly one time which makes it questionable at all (because its also a small one). 
Why the mask parameter is not a part of the calculate_crc function i also don't understand. One can discuss and discuss, but I wouldn't accept this commit and instead try to clean the driver entirely as I suggested. One could save code and resources.

**Comment by dgrat** [comment]
and btw. one of the functions looks like it can induce an overflow.
is data guaranteed to be at least 16 bytes?

**Comment by zehortigoza** [comment]
@dgrat The implementation of calculate_crc() follow most implementations of CRC-4 that I found, also the manufacturer(Measurement specialties) would not recommend a bad implementation.
About the CRC mask and index it do not belong to _check_crc() because it is different between MS5611 and MS5637, but Lucas had asked to have 2 _check_crc() methods on for each case so this way this guys will be gone.
About the calculate_crc() data parameter it is guarantee that it will have 16bytes if we would move this method to outside of the driver than we should have an additional parameter with the size of the array. But I think we should only move this function to a common place when another library/driver make use of this.

**Comment by lucasdemarchi** [comment]
> Reading from the ROM belongs in one function, and calculating the CRC in another function.
> This is already started in this commit by removing the ROM access in "calculate_crc". Beside the fact that I think a CRC check function would be a good common function (maybe in APMath.h) and doesn't really belong in the driver, I also don't like this particular implementation of the function (all).

so you answered yourself why there are 2 functions instead of one: one to read the prom, one to calculate the crc.

As per making it generic, sure. If it's generic it can be moved to common code elsewhere. As you noticed, to make it generic it would need to check the input < 16. Instead the function here was taken from the datasheet because that is what the manufacturer gave us.  If we decide to have a better/faster/generic version, then I'd say to create also the unit tests to check if it matches the function provided by the manufacturer.  Patches welcome for that.

**Comment by dgrat** [comment]
At least the limits of the array are inside the body of the function..
:D

**Comment by lucasdemarchi** [comment]
@zehortigoza so... I came up with a mix of v1 and v2. The 2-phase constructor is back, but not as a backend method: only MS56XX needs it so the derived classes are responsible to finish the construction.  I think it's cleaner this way.

I also made some renames as the names were not so good IMO, added comments change some visibilities, etc.

Please take a look on this branch: https://github.com/lucasdemarchi/ardupilot/commits/review/pr-3185-fix-ms5637

I didn't test with MS5637, so it still needs proper validation.

**Comment by lucasdemarchi** [comment]
@zehortigoza could you test this branch on your board and report back if it works as expected?

**Comment by zehortigoza** [comment]
@lucasdemarchi Your changes are working, if you want open a PR with this commits or I can do that. Thanks

**Comment by lucasdemarchi** [comment]
Done, thanks.

**Pull request closed without merging**
