### PR TITLE
PIC firmware for RCInput_UART

### PR DESCRIPTION
**Pull request by guludo**
Hi all, 

This PR adds the PIC assembly code for the firmware responsible for reading PWM values from the RC receiver and send them to the serial output. The output is compatible with what is read by RCInput_UART, which was added recently by 20e209120ff7532fa1115a9891e8ac5a2d79c580 "AP_HAL_Linux: add support for RCInput through UART".

Best regards! :)

Gustavo Sousa

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Nice. When we decide about a better name we can rename this one, too.

**Comment by WickedShell** [comment]
What hardware has the PIC 16f690? Is this standalone hardware or integrated on one of the existing supported target boards? (Sorry if I missed the boat on what this runs on).

**Comment by magicrub** [comment]
yeah, and why in assembly? I didn't think anyone actually used 16F boards,
18F are all the rage.

**Comment by lucasdemarchi** [comment]
> What hardware has the PIC 16f690? Is this standalone hardware or integrated on one of the existing supported target boards? (Sorry if I missed the boat on what this runs on).

It's standalone. We are using it with the MinnowBoard Max.

**Comment by lucasdemarchi** [comment]
> yeah, and why in assembly?

Very simple and small code, assembly was chosen. Fabio who started it (first committed) is very familiar with PIC assembly.

> I didn't think anyone actually used 16F boards, 18F are all the rage.

We have plenty of them around here.

**Comment by WickedShell** [comment]
I do some stuff with 12F's still..

Maybe put a comment in the code for the board/design that it's targeting? If it's a completely standalone device that doesn't have anything else documented on it or is openly available, it seems kinda weird to put it's assembly here imo.

**Comment by guludo** [comment]
> Maybe put a comment in the code for the board/design that it's targeting?

If I understand what you mean, this code was provided to allow users to get all PWM signals from the receiver and transmit them as a serial stream of PWM values, which is understood by RCInput_UART. If that addresses your suggestion, I can do that.

**Comment by lucasdemarchi** [comment]
@WickedShell 

> Maybe put a comment in the code for the board/design that it's targeting? If it's a completely standalone device that doesn't have anything else documented on it or is openly available, it seems kinda weird to put it's assembly here imo.

This was a simple standalone PIC with connections already commented in source code. See https://github.com/guludo/ardupilot-1/commit/49a982f641d2850df03aaca7501498c0c7208b46#diff-955a650bfff922f12b36c94c46da0fa5R12

Not sure I understood what you are requesting.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
