### PR TITLE
waf: boards: use classes for boards definition

### PR DESCRIPTION
**Pull request by guludo**
In order to provide board-specific behavior. For example, the incoming PX4
build will require custom build behavior.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@cmarcelo was pretty strong about this approach. He may want to chime in.

**Comment by guludo** [comment]
@lucasdemarchi 

> Humn... not related to this patch, but... how do we enable flags per target rather than per board? Use case: gtests: we need to pass -Wno-undef to it to suppress warnings (see #3530)

As simple as using `cxxflags` in the task generator :-)
Just did it: https://github.com/guludo/ardupilot-1/tree/waf-gtest-Wno-undef

**Comment by guludo** [comment]
I'm closing this in favor of a next version at #3637.

**Comment by cmarcelo** [comment]
> @cmarcelo was pretty strong about this approach. He may want to chime in.

When writing the original code I was aiming to the least amount of features as possible. For example, I wanted to the boards to be objects instead of classes, since there was no reason to do otherwise, the difference of the boards was in the data the objects held, not in functions behaving different.

My experience is that starting to use complex language features (even if we use less lines!) is a slippery slope: it makes build system harder to debug, reducing number of people that can properly fix it.

That said, I defer to @guludo's judgement on where to draw the line. :-)

**Pull request closed without merging**
