### PR TITLE
FrSKY: New serial telemetry support for X-receivers

### PR DESCRIPTION
**Pull request by tomlauzon**
Introduces new XPort support while keeping legacy SPort and DPort. XPort is still based on the Smart.Port protocol (for X-receivers).

### CODE REVIEW

**Comment by magicrub** [comment]
This needs a rebase on master due to the namespace change of HAL to access millis()

**Comment by tomlauzon** [comment]
Hi, can you help with this? We're not sure how to get it unstuck. We are trying to merge this into Copter3.3 not master. Error seems to be:

wget $ARM_TARBALL_URL

--2015-11-16 21:12:42--  http://firmware.diydrones.com/Tools/PX4-tools/gcc-arm-none-eabi-4_7-2014q2-20140408-linux.tar.bz2

Resolving firmware.diydrones.com (firmware.diydrones.com)... 54.235.19.222

Connecting to firmware.diydrones.com (firmware.diydrones.com)|54.235.19.222|:80... connected.

HTTP request sent, awaiting response... 404 Not Found

2015-11-16 21:12:42 ERROR 404: Not Found.

The command "APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/install-travis-env.sh -y && . ~/.profile && popd" failed and exited with 8 during .

**Comment by magicrub** [comment]
It must be rebased on to master to be accepted. Merges into branches are not allowed.

**Comment by gmorph** [comment]
Tom is correct.  It must go into master first and then Randy will decide if he want's it merged into his Copter3.3 release branch.  Especially as it has Plane and Rover changes in it - it must come through master.  It does look interesting so please persist :-)  
Thanks, Grant.

**Comment by kilrah** [comment]
What is this XPort thing? SPort is SPort, there should be no differenciation made there.

**Comment by Johnex** [comment]
Do not merge this, @kilrah says the implementation is not correct and needs to be done differently.
More about it here: https://github.com/diydrones/ardupilot/issues/1587#issuecomment-159840419

**Comment by magicrub** [comment]
rebase is still needed and @Johnex 's comment needs to be addressed

**Comment by tomlauzon** [comment]
Thanks, we are almost done integrating and testing the changes based on the comment above. We will send a new pull request on master shortly.

**Comment by magicrub** [comment]
Great, please post a link to it here

**Comment by govsux** [comment]
Is this project so that FRsky telemetry can be sent directly to the S port on a X8R type RX via one of the serial ports from a pixhawk without the need for a teesny board as is currently needed? Also would this arrangement help mitigate the constant issues / errors occurring with changes to Open TX, Apm code, and teensy FW?

**Comment by tomlauzon** [comment]
@govsux indeed, that's the plan! Some changes to APM are expected as OpenTX evolves, but it will be a lot simpler to keep up to date without having to update a Teensy.

**Comment by govsux** [comment]
@tomlauzon  Great!!!!! Thanks !!!!

**Comment by tomlauzon** [comment]
New pull request here #3434

**Comment by govsux** [comment]
is this gonna be in 3.4 you think?

**Pull request closed without merging**
