### PR TITLE
BMP085 improvements

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Here some improvements to the BMP085 driver.  I was trying to use it while writing these commits, hoping that with the improvements on the sampling we could get to a point in which it would not have only garbage on its data.  From the results I'm seeing it looks like it improved a little bit, but I'm afraid to fly a drone in AltHold with this sensor.

Any opinions if there's anything more that could be tried?

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Below is graph from the sensor using 2 different modes.  This is a bench test:

1) 30s on my desk
2) 30s on the floor
3) 30s on my desk
4) 30s on top of my monitor
5) 30s on my desk

As you can see.... pretty bad results. And it seems OVERSAMPLING=3 is as bad as OVERSAMPLING=2 :(.

**Comment by rmackay9** [comment]
One of the early APM boards (the APM1 to be precise) used the BMP085 baro.  It's not a very good sensor compared to the MS5611.  I personally would just dump the sensor and move to a better one - maybe using an external baro is you've already got boards with this BMP085 baro on it.

**Comment by lucasdemarchi** [comment]
@rmackay9  Yeah... I know it's not as good as the MS5611. I just hoped I could get it to an acceptable level.

I do have an MS5611 for another drone but I still need to write proper support for it "non-standard" I2C bus it is on Linux. That's why I was hoping to get BMP085  in shape for at least being able to turn on AltHold on that drone. And maybe this can be used for later versions of BMP* sensors like BMP180/BMP280.

Do you agree that with this graph it's actually impossible to use it?

**Comment by rmackay9** [comment]
I think it should be possible to make it fly but I think AltHold will move around a lot.  I think we would probably need to adjust the EKF baro noise parameter (I forget the exact name).
Personally, I don't think it's worth the effort to try and get it working but I don't know your goals precisely.  I'd vote for buying a breakout board from ebay and wiring it up to whatever board you're using.

**Comment by lucasdemarchi** [comment]
> I'd vote for buying a breakout board from ebay and wiring it up to whatever board you're using.

except shipping from any ebay vendor to Brazil takes ages :(. I have some of them already on the way. I'm trying to find anything local here, but it's not so easy.  Do you know of any other sensor that gives same or similar accuracy to MS5611? I'm trying to find alternatives here.

**Comment by lucasdemarchi** [comment]
Tested also with BMP180 and the results don't seem to improve much. I'm closing this one.

**Pull request closed without merging**
