### PR TITLE
Filter: conversion to template class 

### PR DESCRIPTION
**Pull request by dgrat**
I think it should be possible to implement the filter classes as template.
What do you think about this suggestion .. 

Signed-off-by: dgrat <dgdanielf@gmail.com>

### CODE REVIEW

**Comment by dgrat** [comment]
Does someone know why isnanf() is not defined for px4 builds?
What would be the correct function?

**Comment by dgrat** [comment]
@tridge @lucasdemarchi 
I think this function (which is unrelated for my commit, but causes a build error) is crap

    float longitude_scale(const struct Location &loc)
    {
        static int32_t last_lat;
        static float scale = 1.0;
        if (labs(last_lat - loc.lat) < 100000) {
            // we are within 0.01 degrees (about 1km) of the
            // same latitude. We can avoid the cos() and return
            // the same scale factor.
            return scale;
        }
        scale = cosf(loc.lat * 1.0e-7f * DEG_TO_RAD);
        scale = constrain_float(scale, 0.01f, 1.0f);
        last_lat = loc.lat;
        return scale;
    }

**Comment by magicrub** [comment]
Fixed, rebase on master

**Comment by tridge** [comment]
hi Daniel, what is the advantage of having this as a template class? It only makes sense for float and double, and we don't want to use double as it is not hw accelerated on stm32. So really it only makes sense for float, which means the template doesn't gain us anything. Have I missed something?

**Comment by magicrub** [comment]
yeah, I'm not seeing the point either. Have we had a need to filter an INT yet?

**Comment by dgrat** [comment]
Because some of these classes have been implemented for float, Vector3f, and Vector2f. 
I thought a general template implementation would save code (which it does).

**Comment by magicrub** [comment]
Personally, I hate templates but have learned to appreciate them a bit. In
this case I don't see why we need it but it but I don't think it's a bad
thing to have it. I have a feeling that the EKF will soon start including
doubles and there are cases where we want to filter INTs so I don't object.

**Comment by dgrat** [comment]
The bad thing about template is that their implementation is not identical for many compilers and platforms.
I don't use them often but sometimes is reasonable and with cxx11 their are some language features which may even improve template support.

**Comment by magicrub** [comment]
It would be nice to somehow know what the type is, is that possible? For
example, for float we may want to do a is_zero() thing but for int we can
just say == 0. I struggled with that when making is_zero in the vector3d
template. I ended up giving up and just treating it like a float every time.

**Comment by dgrat** [comment]
@magicrub 
I have to check this. Would be smart to optimize out some template parameters.

**Comment by lucasdemarchi** [comment]
> I think this function (which is unrelated for my commit, but causes a build error) is crap

Poor compiler not seeing last_lat can be set on next call of `longitude_scale()`. This is one of the reasons not to set Werror.

Unrelated, but it would be good to have an annotation on these functions that are not thread-safe. It seems like this particular one is a potential function to be used wrongly.

**Comment by dgrat** [comment]
The problem is that the first comparison is performed with undefined value of this variable. 
In debug mode it is often zeroed, but with optimization settings mostly not.
Dependent where such things are done, it can become very dangerous.

**Comment by lucasdemarchi** [comment]
> In debug mode it is often zeroed, but with optimization settings mostly not.

a static variable is ***always*** zeroed, independently of the optimization level. If it's not, then there's a bug in the compiler.

The warning here is about "set but not used", not about using uninitialized variable:
```
/home/travis/build/diydrones/ardupilot/libraries/AP_Math/location.cpp: In function 'float longitude_scale(const Location&)':
/home/travis/build/diydrones/ardupilot/libraries/AP_Math/location.cpp:38:20: error: variable 'last_lat' set but not used [-Werror=unused-but-set-variable]
```

**Comment by magicrub** [comment]
I agree that the variable should be set to zero but for clarity and
readability purposes not because it needs to be. The c/c++ language
specifies that all static variables be set to zero. It is the local
variables that use the stack that are not guaranteed to be zero.

**Comment by dgrat** [comment]
My bad then.

**Comment by dgrat** [comment]
@magicrub @lucasdemarchi @tridge 
What do you think about this?

    // Do not do these checks for int types
    if( !std::is_integral<T>::value ) {
        if (isnan(delay_element_0) ) {
            delay_element_0 = sample;
        }
        #if defined (INFINITY)
        if (isinf(delay_element_0) ) {
            delay_element_0 = sample;
        }
        #endif 
    }

**Comment by magicrub** [comment]
That looks fine. I'm no expert in templates, but is the reset and constructor done correctly via = T()?

**Comment by lucasdemarchi** [comment]
> What do you think about this?

in what context?

You need to be careful about using the std:: functions like this std::is_integral() because there's no stdlibc++ for AVR. If it's a header-only definition you may need to copy it removing the namespace, just like I did for `std::remove_reference` in the functor implementation.

**Comment by lucasdemarchi** [comment]
> Regarding the templates: I am atm not so sure whether I can use the std:: standard library. If I really would like to check the template types I may have to use ::type_info and type_id. Would this work on all platforms?

No... AVR don't have those.

**Comment by lucasdemarchi** [comment]
> I thought a general template implementation would save code. 

Just to make clear... it will save "implementation code", not that the resulting `text` section will be any smaller. Under the hood the template code will generate 1 class for each type it's constructed with.

**Comment by dgrat** [comment]
@lucasdemarchi 
> Just to make clear... it will save "implementation code", not that the resulting text section will be any smaller. Under the hood the template code will generate 1 class for each type it's constructed with.

The scope of this small patch is just to enhance the readability and to decrease the size (text) of the implementation. I think it would be good, because it would help newcomers to 
 - read and understand the code
 - reduce the amount of time needed for maintenance the code

Beside this I would like to remove the isinf/isnan checks out of this filter, is this feasible or not?
Does the filter really converge to infinity? Without these functions the commit would be much smaller.

**Comment by tridge** [comment]
The template implementation isn't quite the same as the original. The original passed const referenced for Vector3f, which saves copying the vector onto the stack. That is easily fixable in the template version.
The patch also needs some tidyups, removing the change to the license header, and fixing the commit message to follow the format we use (one line summary, one line break, then longer description)
The big advantage of the template implementation is it saves memory by not having multiple copies of the filter parameters.

**Comment by dgrat** [comment]
I changed: 
 - the removed lines in the license (was probably my text editor)
 - use const references (also for one get function)
 - added some comments: which parts might be removed later, ..
 - Improved the commit description

**Comment by dgrat** [comment]
This code leads to a compiler warning only @Px4. However, it is the only way I know to check for NaN, as isnan(f) was not found at Px4.
Maybe someone has a more elegant solution. Then this commit would free of warnings. 

    static inline bool isnan(const float val) {
      return (val != val) ? true : false;   // is float a nan?
    }

**Comment by magicrub** [comment]
isnan() is used everywhere else in the project, why does it not work just
in this one file?

**Comment by dgrat** [comment]
I  think passing template parameters to macros is the problem.

**Comment by dgrat** [comment]
@tridge @lucasdemarchi @magicrub 
I decided to remove the failsafe functions and to perform some tests on Arduino.
This platform is slow, and the compiler sucks. So if it runs fine there, it should run everywhere. 

Btw.: For unknown reason, the call of "isinff" or "isnanf" lead to an endless loop or crash on Arduino.
One of the reasons to remove these functions ..

plots

**Comment by dgrat** [comment]
Another problem is in Dataflash. If I would include some standard library headers for advanced typechecks, I get compiler errors there. This is likely because of the various macro definitions.
I strongly suggest to move these macro definitions into functions, stored in their own namespace. 
It will become a huge pain, if we further move to linux.

**Comment by magicrub** [comment]
Do you have any template support for doubles? Paul had mentioned wanting to
do performance testing in the ekf with doubles so I imagine filters will
come into play at some point.

**Comment by dgrat** [comment]
filter2

**Comment by tridge** [comment]
hi Daniel, a problem with this patch is it moves a bunch of code from .cpp files to .h. The problem with that is that if the filter is used in two places in the code it will end up being compiled twice. The compiler is not smart enough to make one copy of the function.
Maybe take a look at matrix3.cpp in AP_Math for how to ensure we don't end up with multiple copies of complex functions.

**Comment by dgrat** [comment]
@tridge 
Hi Tridge,
now is is completely split into definition and declaration.
I initially avoided this because of constructor implementation difficulties.
I offered two possibilities in the commits (one is commented out, if changes are desired).
I decided to move ctor impl. into the cpp file and enforced compilation of the code by creating an instance.
This has the advantage that nothing has to be compiled twice, but is less flexible to method two.
Last would force moving the impl. of the ctor to the header .. 

Best, Daniel

**Comment by tridge** [comment]
Thanks for all the improvements! I've pushed this to master now

**Comment by magicrub** [comment]
This is causing compiler warnings due to float to double promotions, please check into it @dgrat.

**Comment by lucasdemarchi** [comment]
@magicrub are you passing any special flag to get the warnings?

**Comment by magicrub** [comment]
Nope. See Travis for this PR which was just rebase don master today
https://travis-ci.org/diydrones/ardupilot/jobs/77856194

search for "warning: implicit conversion from 'float' to 'double'"

**Comment by lucasdemarchi** [comment]
On Sat, Aug 29, 2015 at 7:13 PM, Tom Pittenger <notifications@github.com>
wrote:

> Nope. See Travis for this PR which was just rebase don master today
> https://travis-ci.org/diydrones/ardupilot/jobs/77856194
>
> search for "warning: implicit conversion from 'float' to 'double'"
>

so... it's -Wdouble-promotion that's used in the PX4 build, but does not
happen for the linux boards (
https://travis-ci.org/diydrones/ardupilot/jobs/77856195) because double
precision is not emulated here.

Lucas De Marchi

**Comment by magicrub** [comment]
That's right. In pixhawk we have 32 bit float hardware support but in Linux
class cpus you have a high chance of double hardware support so it's no big
deal.

**Comment by dgrat** [comment]
Hi guys, 
I am more or less aware of this. Unfortunately, the solutions are all not that great, just to fix this warning.
Solution one would be to remove the double typedef for PX4 with a macro.
However, if someone of the linux guys will use exactly this typedef, PX4 will throw a build error.
Method two would be a second typedef for PX4 which corresponds to a float.
This would make the code look shitty. If you are fine, I suggest to ignore this warning.
If not, I could write a fix. But keep in mind, it would just cure the symptoms :D

**Pull request closed without merging**
