### PR TITLE
GPIO: sysfs implementation and support for virtual pins

### PR DESCRIPTION
**Pull request by guludo**
Hi guys!

This PR can be logically separated in the following parts:
- Adding support to virtual GPIO pins:
  - AP_HAL: GPIO: add functions to support virtual pins

- Adding an implementation of `AP_HAL::GPIO` based on sysfs:
  - AP_HAL: add assert_not_reached() macro
  - AP_HAL_Linux: add LinuxGPIO_Sysfs
  - AP_HAL_Linux: make board specific GPIO inclusions last
  - AP_HAL_Linux: add class LinuxDigitalSource_GPIO_Sysfs
  - AP_HAL_Linux: make LinuxGPIO_Sysfs::channel() return a LinuxDigitalSource_GPIO_Sysfs()

- Add a way to test GPIO on Linux
  - AP_HAL_Linux: add test for GPIO
(about this last one, I think it's easy to move it to a generic implementation under AP_HAL... Anyone is welcome to do it :) )

Here goes a [gist](https://gist.github.com/guludo/8103d71ecbd7b82334d7) that shows how to define virtual pins for LinuxGPIO_Sysfs.

### CODE REVIEW

**Comment by guludo** [comment]
Hm... Although it compiles for target linux, it somehow breaks build on travis... I'm looking into that right now!

**Comment by guludo** [comment]
Fixed build

**Comment by guludo** [comment]
We've made some changes and fixes on the branch. I'll update the description.

**Comment by lucasdemarchi** [comment]
LGTM

**Comment by raspilot** [comment]
So when will this PR be applied to master branch?
And would writing to file cost more time than operating the memory directly?

**Comment by lucasdemarchi** [comment]
On Mon, Sep 7, 2015 at 8:34 AM, raspilot <notifications@github.com> wrote:

> So when will this PR be applied to master branch?
>

It's up to @tridge now.


> And would writing to file cost more time than operating the memory
> directly?
>

Yes, not because of the interface per se (fd vs memory) but because by
writing to the memory address itself you are losing the OS protection and
"by-passing" the synchronization to access the hardware that the userspace
<-> kernel space interface provides.

So... I'm not sure you will want to use this since you are already sharing
the code with any RPi board. However this implementation is compatible with
any board supporting Linux and IMO should be the preferred implementation
for any new board (with the exception for those bbb-based or rpi-based).


-- 
Lucas De Marchi

**Comment by lucasdemarchi** [comment]
Let´s close this for now. For MinnowBoard Max there's a simpler implementation in #2947. We can come back to this later.

**Pull request closed without merging**
