### PR TITLE
Add offline aiding feature to UBLOX GPS modules

### PR DESCRIPTION
**Pull request by ziltoid2**
This patch adds the functions needed for offline aiding of UBLOX gps for faster time-to-fix. This includes:
1- aid the receiver with the position of the plane.
2- aid the receiver with AlmanacPlus correction file (downloaded from http://alp.u-blox.com/) via file transfer.
3- aid the receiver with AlmanacPlus correction file via ALPSRV protocol for receivers with no internal flash memory

This functionality is initiated at GPS startup.

### CODE REVIEW

**Comment by magicrub** [comment]
This is a great idea!

**Comment by ziltoid2** [comment]
Thanks, it only lacks the time aiding, which requires access to an RTC on the main controller. This can be added when RTC is available.

**Comment by ziltoid2** [comment]
Sorry for the not-so-tidy commits. The real meat in the first two commits and the rest are cosmetics to fit in with the rest.

**Comment by magicrub** [comment]
How does step 2 work, the file transfer via internet? Can you describe the "work-flow" a bit?

**Comment by magicrub** [comment]
Also, does this have any impact other than a faster time-to fix?

**Comment by ziltoid2** [comment]
You're right, It looks like I have said noting on how it works, by bad.

The process goes like this: On the sd card, under the APM directory, create a directory named "UBLOX_AID". Then do the following:

1- For initial position aiding, write the coordinates in the form lat,lon,alt in a file names pos0.txt under UBLOX_AID. AP_GPS_UBLOX will check for this file at initialisation and send the required messages.

2- Download the file current_1d.alp (from http://alp.u-blox.com/) and place it in UBLOX_AID directory. AP_GPS_UBLOX will try to send this file to the GPS module upon initialisation. If the GPS module supports alp file transfer the aiding process finishes, otherwise (3) will take place

3- If the GPS module doesn't support ALP file transfer, AP_GPS_UBLOX will advertise itself as an ALP server to the GPS module. The GPS module will ask for small chunks of data when it needs it and the server responds accordingly.

The user has to keep in mind that those alp files are valid only for a period of time. For instance the file current_1d.alp is valid for 24 hours. Those files are updated by UBLOX about 3 times a day. However UBLOX strictly claim that this is a standard (free) service and it is not supported nor strictly maintained. Files valid for a longer period of time exist, however they will require more memory as the file is fully read at startup to avoid stalling the processor on IO operations during flight, thus only the smallest file is used.  

The only implication this patch has is a delay for about 2 seconds in the initialisation of the GPS module if whole file transfer is taking place, nothing else I could recall.

Please let me know if I have left anything unclear.

Cheers,

**Comment by magicrub** [comment]
So this 2 second delay occurs only if:
- using a ublox that supports this feature, not the other GPS units?
- the folder/file(s) has been loaded on the SD prior to boot

I think this definitely warrants a wiki entry to publish your above posted
steps.

I understand that this is the initial commit so the focus should be to just
get it working, and that's great - thank you. Later it would be nice to add
support for on-demand uploads via internet-connected GCS via mavlink like
the terrain data does.

-TomP

**Comment by ziltoid2** [comment]
Yes that is right, other GPS modules won't be affected as this is a UBLOX proprietary thing. If no files are loaded in the directory or the directory doesn't exist nothing is different even to UBLOX units.

In addition to the features you've suggested, I also believe that having access to an RTC will benefit the aiding process. but I haven't seen any RTC access APIs in the code. Please let me know if they are hidden somewhere.

Cheers,

**Comment by magicrub** [comment]
There's RTC support hiding in PX4 somewhere via https://github.com/diydrones/ardupilot/pull/1122 and platforms running linux will probably RTC data available

**Comment by ziltoid2** [comment]
Thanks, I'll investigate it when time permits

**Comment by tridge** [comment]
this looks very interesting, thanks!
I think the ideal setup is for us to use MAVLink to fetch the aid information from the GCS. So we'd advertise ourselves as an AID server, then when the uBlox asks for information we send that request to the GCS, the GCS then packages up the information and sends it up to the aircraft, which injects it into the GPS.
That would be less fiddly for the user as it would all happen automatically

**Comment by ziltoid2** [comment]
Hi

Thanks for the input. I agree that managing AID data sources by the GCS is more transparent at the interface level as long as the MAVLink can support it without being too ad-hoc. 

I went through MAVLink messages that could be used for data transfer and I have found the following:

DATA_TRANSMISSION_HANDSHAKE and ENCAPSULATED_DATA which are used to transfer images with a chunk data length of 253 bytes.
TERRAIN_REQUEST and TERRAIN_DATA which are dedicated to transfer Terrain data in chunks of 16 bytes. 

While both are an ad-hoc use of the purpose, the first set seems to be more suitable for the job from the data size point of view. The other issue is that ALP AID client can ask for chunks of data of sizes up to 288 bytes, which would make the onboard code a bit uglier in the case of setting up AID server. Thus I got the impression that the result of using the previously mentioned messages might polish the user interface at the expense of  messing up the internals. 

The other thing would be finding the method by which the position aiding is done from the GCS?

A middle ground would be what magicrub has suggested by employing the GCS to transfer the files to the SD card while using the same aiding logic. This way the process will be almost transparent to the user if the GCS has already the functionality of transferring data files to the SD card.

Please let me know if you envisage another mechanisation of the process.

Cheers,

**Comment by WickedShell** [comment]
Not a reason to not do it, but it's worth noting that as of the M8 series the AID-INI is deprecated and the AID-ALP/ALPSRV had been deleted from the M8 series GPS, which I suspect taken together means that this aiding wouldn't work on a M8. (Although there are some alternate messages available to be used instead).

This document from ublox discusses protocol changes from the 7 to 8 series recievers:
https://www.u-blox.com/sites/default/files/products/documents/ubx7toM8-SWMigrationGuide_AppNote_%28UBX-13003254%29.pdf

Overall though I'm in favor of being able to provide aiding, despite never having a problem with it in the field, it would be a nice feature (particularly when using a new GPS for the first time).

I think it's potentially worth figuring out the MAVLink overhead though, from the user experience perspective.

**Comment by WickedShell** [comment]
My current thought is to pass on this for now.

There are 3 main reasons:
  -This requires a large amount of RAM (a 6144 byte file is held in memory in each instance of the ublox driver) Additionally certain functions need to push a 512 byte local onto the stack as well.
  -This requires reading a file off the SD card when the driver is created. This may happen in flight, which would be a situation we really don't want to get into.
  -The patch is incompatible with ublox 8 or newer ublox units, and I believe the extra data required to make 8's work would compound the memory problem (or we could simply say that the 8's onward aren't supported).

When taking these reasons combined with the difficulty in setting it up, versus the utility offered in flight it doesn't seem to be worth it. For anyone who's willing to go through the effort of pulling the SD card, creating the appropraite files on it, I think would be better served by using the serial inject feature to the GPS and connecting u-center to transfer the data.

Without a better value add I'm hesitant to say that this is worth the extra time at the moment. I like GPS aiding, but have found that it adds a significant boost to value on an unmanned system due to all the clear sky, and time spent in startup allows for fairly fast GPS lock. If people disagree with me please let me know.

**Comment by WickedShell** [comment]
Closing this for the reasons listed above, and since I haven't heard anything back on it.

**Pull request closed without merging**
