### PR TITLE
PR and RFC on reorganizing includes of libraries headers

### PR DESCRIPTION
**Pull request by guludo**
Hi all, this is a pullreq, **but also a RFC** on reorganizing includes of libraries headers.

Currently, [the build system uses `make.inc` to add paths to the include path](https://github.com/diydrones/ardupilot/blob/063faa0383b2774cbf803c76e1f8d08f2b81e31f/mk/sketch_sources.mk#L34) (i.e., compiler option `-I`).

This series of patches makes the build system use only one include path for libraries headers. That way, a library header is included in a source file in two fashions:
 - If the header is in the same directory the source belongs to, then the notation `#include ""` is used with the path relative to the directory containing the source.
 - If the header is outside the directory containing the source, then we use the notation `#include <>` with the path relative to libraries folder.

With that approach, we have the advantage of only one search path for libraries and also a possible performance improvement in lookup time.

Most of the changes were made with a script, so they can be reproduced if necessary.

Another good reason for applying this is that we reduce our dependency on make.inc. IMO, in the future, we should provide a way of not needing to define ALL libraries we want to link to a sketch, because that's prone to errors. For example, let's say several `example/*.cpp` files uses a library X and now X uses a new library Y. In that case **ALL** sketches that use library X must tell the linker (through make.inc) to link library Y as well.

As a RFC, your comments on this subjects are very welcome :)

### CODE REVIEW

**Comment by tridge** [comment]
I like this approach, I think it makes the code more readable too, even if a bit more verbose.
Could you add the script you used to Tools/scripts ? It may be useful when trying to apply existing PRs, and it may also help people trying to rebase on top of this change.
Randy, what do you think about this change? Is it the right time to make this change?

**Comment by rmackay9** [comment]
I'm ok with it as well.  Could we wait until Rob's AC3.3 change is in though?  This is my top priority at the moment so it won' be long.
https://github.com/diydrones/ardupilot/pull/2531

**Comment by guludo** [comment]
@tridge I just added a commit with the script to fix the includes. I've added it as the first commit.

**Comment by guludo** [comment]
There are merge conflicts here, but I think we can wait till the right time to resolve them, right?

I think we'd rather do a clean run, i.e, delete all those intermediate patches (`"*: standardize inclusion of libaries headers"`) and run the script again.

**Comment by tridge** [comment]
yep, makes sense.
Randy, let us know when you are ready to apply this

**Comment by guludo** [comment]
Hi guys,

I've heard we're ready to apply this, so I just ran the script again and did a few manual minor fixes on the includes directives the script couldn't decide what to do.

**Comment by lucasdemarchi** [comment]
> I've heard we're ready to apply this, so I just ran the script again and did a few manual minor fixes on the includes directives the script couldn't decide what to do.

@rmackay9 are we clear now?

**Comment by guludo** [comment]
Heads-up: rebased again.

**Comment by tridge** [comment]
i'm working on applying this now

**Comment by tridge** [comment]
pushed to master. Thanks for your work on this Gustavo, and your patience! Much appreciated

**Pull request closed without merging**
