### PR TITLE
rework of raspilot branch

### PR DESCRIPTION
**Pull request by tridge**
This is a re-work of the raspilot branch by Alex Zhang
Opened here for discussion

### CODE REVIEW

**Comment by raspilot** [comment]
It's great! Thanks for the work.

**Comment by tridge** [comment]
Hi Lucas, I've assigned this to you for review - hope thats OK

**Comment by lucasdemarchi** [comment]
> Hi Lucas, I've assigned this to you for review - hope thats OK

sure, I plan to take a look on it on Monday

**Comment by lucasdemarchi** [comment]
@tridge I went through each commit. Some small things to fix. It looks promising.

I'm particularly worried about changing the period  to 500usec for all boards. I certainly don't want that on all and don't think it's needed for raspilot. May be related it's even relate with the scheduler overruns you are getting.

**Comment by raspilot** [comment]
> On Aug 26, 2015, at 11:54 AM, Lucas De Marchi <notifications@github.com> wrote:
> 
> @tridge <https://github.com/tridge> I went through each commit. Some small things to fix. It looks promising.
> 
> I'm particularly worried about changing the period to 500usec for all boards. I certainly don't want that on all and don't think it's needed for raspilot. May be related it's even relate with the scheduler overruns you are getting.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/diydrones/ardupilot/pull/2720#issuecomment-134814139>.
> 

Hi, Lucas:

If you mean the period of tone alarm task. I change it to 500us because I found some cycles of tone alarm task lost (The pwm0 of raspberry pi is used to drive the tone alarm). It looks like those cycles are disrupted by other higher priority tasks. 

Changing it to 500us will make something better but can’t solve the problem completely. So I suggest keep it the old period time until we find where the problem is.

**Comment by lucasdemarchi** [comment]
> Hi, Lucas:
> 
> If you mean the period of tone alarm task. I change it to 500us because I found some cycles of tone alarm task lost (The pwm0 of raspberry pi is used to drive the tone alarm). It looks like those cycles are disrupted by other higher priority tasks.

As far as I can see it's using the PWM from RPi's hardware, not doing the PWM wave itself via bitbanged gpio. So I fail to see why reducing the period will help. It will actually disturb the other (more important) tasks and cause overruns on timer and main thread.

> 
> Changing it to 500us will make something better but can’t solve the problem completely. So I suggest keep it the old period time until we find where the problem is.

Agreed.

**Comment by lucasdemarchi** [comment]
@tridge @raspilot here is the rebased and reviewed branch to be integrated:
https://github.com/lucasdemarchi/ardupilot/tree/pr-raspilot-support-v2

I did most of the changes in the comments here. Some of them I left as TODO that should be done on top later.

I only build tested these since my HW didn't arrive yet but I checked the diff with the new branch from @raspilot and it appears to be good.  If you could give it a round of testing it would be nice.

There are some conflicts with #2831 and #2698 but they are easy to solve in any order the pull requests go in.

**Comment by tridge** [comment]
Thanks Lucas! I've pushed to master

**Pull request closed without merging**
