### PR TITLE
Add RCOutput using Linux PWM sysfs API [v3]

### PR DESCRIPTION
**Pull request by zehortigoza**
Changes from V2(https://github.com/diydrones/ardupilot/pull/3039):
- replaced PATH_MAX by PWM_PATH_MAX that now is 44 bytes long instead of the default 4K bytes
- moved conversion functions to AP_Math
- improved error messages, now using variadic panic()

### CODE REVIEW

**Comment by tridge** [comment]
@Lucas, what do you think about checking on return values from snprintf()  in HAL_Linux? It seems like it would be prudent.
While looking at this I also noticed that GPIO_Sysfs::_pinMode() isn't using a fd cache in GPIO_Sysfs. I think there is some code in ArduPilot that assumes setting the pin mode is fast. 
I think we need to watch out for this in the Linux HAL. Otherwise code that runs fine on microcontrollers will run v slow on Linux, leading to scheduler delays.

**Comment by lucasdemarchi** [comment]
> @Lucas, what do you think about checking on return values from snprintf() in HAL_Linux? It seems like it would be prudent.

I agree. In some places I'm not so strict since the worst thing that could happen would be failing on open() which is more critical.

> While looking at this I also noticed that GPIO_Sysfs::_pinMode() isn't using a fd cache in GPIO_Sysfs. I think there is some code in ArduPilot that assumes setting the pin mode is fast. 
> I think we need to watch out for this in the Linux HAL. Otherwise code that runs fine on microcontrollers will run v slow on Linux, leading to scheduler delays.

Yep. I just want to measure it before committing. https://github.com/diydrones/ardupilot/pull/3056#issuecomment-151594589

@zehortigoza could you add the table and measure the timings on our board? See comments on the link above.

**Comment by lucas** [comment]
@tridge I think you meant @lucasdemarchi and not @lucas (yes they are different) :disappointed:

**Comment by zehortigoza** [comment]
PR updated with the snprintf() checks.

@lucasdemarchi Sure, I will do that.

**Comment by lucasdemarchi** [comment]
I pushed a branch with a review: https://github.com/lucasdemarchi/ardupilot/commits/pr/rcout_sysfs_v3-r1

Feel free to take it and push -f here when/if we agree to the changes. Most of them were done in "AP_HAL_Linux: rework PWM_Sysfs" as documented in the commit message. I did as a separate commit because it was not only coding style and small changes.
In the last commit I did some some changes, but since they were small I just amended them. Particularly the constructor using a default frequency. This should actually be set in init() to 50, the same value as PCA9685.

While not mandatory, adding documentation on functions for new APIs would be really nice, mainly the non-trivial ones. I added some documentation to the read_file()/write_file() functions to clarify their (slow) behavior and intended use. While at it I also added the scanf/printf format attributes to them, which already caught one bug.

Using uint32_t for usec and nsec is not good (even if in the particular case of PWM they have enough bits).  I'd change them to plain uint64_t but maybe even better is to typedef nsec_t and usec_t, so it also serves for documentation and type checking in places like `uint32_t Linux::PWM_Sysfs::get_period()`. It would be much nicer to have `nsec_t Linux::PWM_Sysfs::get_period()`.

This branch is not tested on real hardware yet.

**Comment by lucasdemarchi** [comment]
Let's continue the discussion in the new version, #3144.

**Pull request closed without merging**
