### PR TITLE
Use method for downcast

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Instead of just doing a static cast to the desired class, use a method
named "from". Pros:

  - When we have data shared on the parent class, the code is cleaner in
    child class when it needs to access this data. Almost all the data
    we use in AP_HAL benefits from this

  - There's a minimal type checking because now we are using a method
    that can only receive the type of the parent class

I saw more casts being while reviewing #2698.  There are probably more cases in the code base. I just selected a few to ask for opinions.

### CODE REVIEW

**Comment by khancyr** [comment]
Hi,

Just a style question : Why not use c++ static_cast<LinuxRCInput *> instead of old c cast ?

**Comment by lucasdemarchi** [comment]
> Just a style question : Why not use c++ static_cast instead of old c cast ?

Just style. I don't see a benefit in using the longer static_cast since both will do the same thing.

**Comment by cmarcelo** [comment]
> Just style. I don't see a benefit in using the longer static_cast since both will do the same thing.

Minor thing: consider using `static_cast`. It is more restrictive than the other cast and does what you want. In the `from()` functions the benefit is small since you does check for the pointer being of the parent type, but still exists, if the inheritance change you get a compilation error.

It also has the network effect of other code (that might not have `from()` check) not considering C-style cast as an option.

**Comment by lucasdemarchi** [comment]
@cmarcelo welcome to the project :)

Still not convinced for this particular case. For both casts you have the same benefits and shortcomings. But I don't really mind. I'll update the PR with a force push when I cover the other users.

**Comment by lucasdemarchi** [comment]
I changed to static_cast and applied it in other places I could find.  It could be improved, making the declaration generic and enforcing that the class is being casted is the parent class. However, I'd need to include type_traits in some headers and that causes a train wreck with other includes (here's the example of what it could be: https://gist.github.com/lucasdemarchi/492b093f21bde064e848

**Comment by dgrat** [comment]
Hi @lucasdemarchi,
1) I already experimented with type traits, when I rewrote the filters.
There are a lot of problems with macro definitions in certain header files, if you include some parts of the standard library. This is why, I think this macro madness must stop. 

2) What is wrong with a dynamic_cast? It inherits a safety check and return NULL/Exception if something is wrong.
Instead, there is a template mixup macro around a static_cast. 
I also think, that such constructs should be only used for code which can be slow. 

Best, Daniel

**Comment by lucasdemarchi** [comment]
> Hi @lucasdemarchi,
> 1) I already experimented with type traits, when I rewrote the filters.
> There are a lot of problems with macro definitions in certain header files, if you include some parts of the standard library. This is why, I think this macro madness must stop.

Nops... the macros here were bad because our includes are still in bad shape.

> 2) What is wrong with a dynamic_cast? It inherits a safety check and return NULL/Exception if something is wrong.
> Instead, there is a template mixup macro around a static_cast. 

When I wrote the gist I was with the wrong impression that if the inheritance changed the static_cast wouldn't warn me so I added the static_assert. However, the static_assert is not really needed. I get a "nice" compiler error if I change the inheritance and don't change the from() method.

Regarding the dynamic_cast... It doesn't do any good here neither. It returns NULL if it can't convert and it does it at runtime. Moreover we never checked the return code so it's pointless. However with the from() method done this way it actually does the check at compile time because now there's only one type that can be converted (or a parent thereof).

**Comment by dgrat** [comment]
> Nops... the macros here were bad because our includes are still in bad shape.

Actually, this is what I meant. If I remember right, the errors were caused because of macro definitions in some headers of AP, but I am not sure anymore.

**Comment by lucasdemarchi** [comment]
@tridge @rmackay9 ?

**Comment by lucasdemarchi** [comment]
Rebased again to fix conflicts

**Comment by tridge** [comment]
I think the from() and static_cast is quite nice, so I've pushed to master
thanks Lucas!

**Pull request closed without merging**
