### PR TITLE
Copter: Pirouette compensation

### PR DESCRIPTION
**Pull request by jolyboy**
This PR addresses the feature request outlined in Issue #1532

### CODE REVIEW

**Comment by rmackay9** [comment]
@R-Lefebvre, didn't pirouette compensation go into master recently?

**Comment by R-Lefebvre** [comment]
No, that was in the last PR targetted for 3.3 that was closed.  I am re-working it that PR, and after it's in 3.3, I will PR it onto Master. (or I guess you could just bring it across).

**Comment by R-Lefebvre** [comment]
To be tested for AC3.3-Heli:

https://github.com/R-Lefebvre/ardupilot/commits/Copter-3.3-Heli-RC13-WIP

**Comment by R-Lefebvre** [comment]
Closing. This has been merged into AC3.3 and Master branches.

**Pull request closed without merging**
