### PR TITLE
Doxygen updates

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
I noticed there was an attempt at using Doxygen previously, but it was very old, and it seemed like no one had touched it in a while.

This is going to take some time and some help from everyone to really flesh out.
But here is a starting point.
I'll be going through some classes and functions documenting what I know, and I hope others will do the same. :-)

see http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#cppblock

for information on proper doxygen documentation syntax.

Here is an example:
screenshot from 2014-06-25 06 48 20

Note: 
this Pull Requests was branched off of my local branch which includes the changes from Pull Request #1148.
Please merge that one first to make the diff here easier to read. It's bad of me that I didn't start from scratch again here, but I just forgot that the A/VTail stuff was in my working branch (I didn't see it until I had already pushed and was looking at the diff for this Pull Request)

### CODE REVIEW

**Comment by gmorph** [comment]
The updated use of Doxygen has been discussed a couple of times at the weekly dev call but with no significant outcome.  What it really needs is someone to champion it and crack the whip on all the developers and ensure updates are done.  

Mr NullVoxPopull - are you that person?  Let us know.

Thanks, Grant

**Comment by NullVoxPopuli** [comment]
If I were still using ardupilot, I'd be interested. But I haven't used it in a while (a may put it on my plane at some point though, idk.)

For right now, I think it just needs to be a requirement for ALL PRs to include documentation on any methods created. 

And if a method is changed by a core contributor, maybe make it a rule for them to add documentation if it isn't there already?

**Comment by magicrub** [comment]
Is it possible to add this check in Travis or github so it inhibits merges?

**Comment by lucasdemarchi** [comment]
@magicrub you could write a script that gets the warnings about non-documented functions and compare with the previous state of warnings. But it doesn't catch 100%: if you move code around or rename them you'd get a warning.

Also, since we don't really run doxygen locally, as @tridge said in the last call we talked about that, it would trigger formatting errors in doxygen that are not easy to track.
That could be fixed if someone decided to be the doxygen maintainer. Maybe if/when they are very well maintained we can try to enforce it.

**Comment by lucasdemarchi** [comment]
Closing this since it's very old, doesn't apply and nobody is working on it.

**Pull request closed without merging**
