### PR TITLE
Replay: flush dataflash log upon getting an FPE

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
should be 2 commits, one on DataFlash, one on Replay
(also waiting for travis retry)

**Comment by peterbarker** [comment]
Interactive rebase fail fixed.

**Comment by tridge** [comment]
would you mind rebasing this on master? thanks!

**Comment by peterbarker** [comment]
Rebased :-)

**Comment by tridge** [comment]
this needs to be reworked for the frontend/backend split
closed for now

**Comment by peterbarker** [comment]
Reworked for frontend/backend split

**Pull request closed without merging**
