### PR TITLE
AP Math new function 3D Distance

### PR DESCRIPTION
**Pull request by lvale**
Returns the distance between 2 points in space defined by Lat, Lon and
Alt

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks good (except for the merge commits but we can get rid of those).
Also "Libraries:" should be replaced with "AP_Math:" in the last commit's subject line.

Only real issue is that the function isn't used yet.  We don't normally add functions that aren't being used because it adds code that we then need to support but is not actually used.

My guess is that you're planning to add a futuer commit that makes use of these functions.  If it's ok, I'd like to close this and then we can revisit it with the future PR.

**Comment by lvale** [comment]
You're right. I've searched all over for a 3D measurement between 2 pos that could also be useful to other actions, so instead of having it inside a larger PR, this way I believed it would be easier.
My only doubt was why the ALT inside the location came in cm, but is not relevant.

**Comment by dgrat** [comment]
I would suggest a overhaul of the location structs.

**Comment by rmackay9** [comment]
Re the location overhaul.  I'm working on a Location_Class as part of adding terrain following to Copter.
https://github.com/rmackay9/rmackay9-ardupilot/blob/terrain4/libraries/AP_Common/Location.h

All feedback welcome.

**Comment by rmackay9** [comment]
By the way, should we close this PR then?  I think we should until the function is actually required.

**Comment by lvale** [comment]
@rmackay9 On the re factoring you're doing and considering the terrain following wouldn't it make sense then to have a "real" distance? i.e. (lat1, lon1, alt1) - (lat2-lon2-alt2) ??

**Pull request closed without merging**
