### PR TITLE
AP_AHRS_DCM: align tilt during initialization

### PR DESCRIPTION
**Pull request by jschall**
addresses #3027

### CODE REVIEW

**Comment by rmackay9** [comment]
I tested this with master copter and it didn't seem to speed up the alignment of the HUD when the pixhawk was held up-side-down.  The HUD still began right-side-up and then spent 5 ~ 10 seconds adjusting itself.

Perhaps it's because this only affects DCM, but my understanding is that the EKF got it's initial alignment from DCM.

**Comment by jschall** [comment]
Interesting, I'll have to confirm. Will look at it today.

**Comment by tridge** [comment]
the problem is that when ahrs.reset() is called the ins is not yet active, and you get a zero accel vector.
We need to do another ahrs.reset() once ins is active

**Comment by tridge** [comment]
i've found the problem. The _dcm_attitude() vector needs to be updated in AP_AHRS_NavEKF.cpp on reset(). I will push once I've done more testing

**Comment by tridge** [comment]
I've pushed it with fixes for both _dcm_attitude and INS_GYR_CAL=0.

**Pull request closed without merging**
