### PR TITLE
AP_GPS: UBX-RXM-RAWX support

### PR DESCRIPTION
**Pull request by WickedShell**
Adds support for logging UBX-RXM-RAWX messages. (Example devices are the Ublox M8T series of devices)

### CODE REVIEW

**Comment by meee1** [comment]
you don't happen to have a sample log with this new data in it? so I can add support to Mission planner?

**Comment by WickedShell** [comment]
Yes! Lots of samples for you, saves me writing a RINEX converter....

**Comment by tridge** [comment]
applied, thanks!

**Comment by WickedShell** [comment]
@meee1 http://files.swiftradioplanes.com/174.BIN It's inside in a poor RF enviorment and short, I don't expect to see a great result with it sitting on my desk, but the data looked valid by inspection. I'm going to start comparing the accuracy versus a reflashed 6H, and a Trimble ProXH as soon as it stops with the inclement weather.

**Comment by ThorstenDP** [comment]
Good news! Thanks!
What about bandwidth/baudrate?
Cheers,
Thorsten

**Comment by WickedShell** [comment]
@ThorstenDP I was using 38400 as the baud rate, same as the default speed that the GPS's from 3DR are at. I didn't seem to be having any problems with excess data.

**Comment by ThorstenDP** [comment]
@WickedShell thanks a lot for the info. Roberto from VR mentioned that he had to change the serial rate in NuttX. So perfect if it works as is. Can you provide the (u-center) settings you are using? Moreover, have you made any tests with RTKLIB so far?

**Comment by WickedShell** [comment]
@ThorstenDP: You will need to raise the baud rate if you have more then ~10 satellites, as well as you need to make sure that the SD card log is not dropping messages, (do you have as many GRXS messages as the GRXH message says you should)

**Comment by ThorstenDP** [comment]
@WickedShell, thanks! I really appreciate your work on this!
I already saw that you made some changes on the baud rate in your latest PR (https://github.com/diydrones/ardupilot/pull/2562). I am also always happy to test new patches. But unfortunately, I had no time to run some test with RAWX data so far, but hope to do so the next weeks on.

**Comment by WickedShell** [comment]
I'm not totally convinced on them yet, the high level idea is good in it, I just want to log a bit more time with it first before we merge it. I think my issues are all related to a combination of difficulties getting an SD card that can actually keep up with logging, and a poor wiring choice on the aircraft (unrelated to the GPS but wasted a bunch of test flights/time on it).

**Pull request closed without merging**
