### PR TITLE
Remove use of APM_BUILD_TYPE() from AP_AHRS

### PR DESCRIPTION
**Pull request by cmarcelo**
The motivation is to move the vehicle specific code to the vehicle folders themselves.

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
Hi, I haven't thoroughly reviewed the code.  But just a comment on the PR in general.

If you would please split out the change to Copter.h and put that in a separate commit from the AP_AHRS library changes as per our convention.

Also, please "squash" the AHRS.h change which is adding some #defines into the other AHRS.h change which is removing them, so the history is clean.

Thanks

**Comment by cmarcelo** [comment]
> If you would please split out the change to Copter.h and put that in a separate commit from the
AP_AHRS library changes as per our convention.

I'll do that. Thanks for pointing this out.

> Also, please "squash" the AHRS.h change which is adding some #defines into the other AHRS.h change which is removing them, so the history is clean.

There are two commits, both removing code from `AP_AHRS.h`, for different reasons. The history seems clean to me. What additions are you referring to?

**Comment by lucasdemarchi** [comment]
Yeah... copter deserves a separate PR, but I don't get the other request from @R-Lefebvre. The 2 separate commits are self-contained.

**Comment by lucasdemarchi** [comment]
Looking at it again. Splitting the commits are "the project's policy". But here it does more harm than actually helps the review :-/ since it would break the build or force us to add one additional commit. @R-Lefebvre maybe that's something to be discussed in the next dev call?

**Comment by R-Lefebvre** [comment]
Ah, sorry I misread that.  Thought one was adding then taking away.  Though I suppose those could both be combined to a single commit? (this is getting nitpicky though).

Lucas: Sure, that discussion is above me, so best to discuss it with Randy and Tridge.  I was just pointing out the existing style.

**Comment by cmarcelo** [comment]
Replaced by #2993.

**Pull request closed without merging**
