### PR TITLE
Overhaul travis configuration

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This changes how we use Travis so to be able to use their container infrastructure rather than VM. The biggest advantage of using the container-based one is the ability to cache a) things we need to download and b) intermediary build steps by using ccache.

I'm not sure why, but this also fixes the problem of the compiler being killed while compiling navio. Maybe they reduced the time allowed for each build. Don't know. The fact is that with this new approach I'm seeing a build time 4 times faster.

### CODE REVIEW

**Comment by magicrub** [comment]
Perhaps were running out of RAM on the current deployment!

**Comment by lucasdemarchi** [comment]
@magicrub unless they lowered the amount of memory, no.

**Comment by lucasdemarchi** [comment]
Btw, it's only **much** faster after the first build since the improvement comes from the cache we create when building.

**Comment by gmorph** [comment]
I tested this in my own repository and it works great.  As Travis is currently causing problems this is the perfect time to change over to this new travis configuration as it fixes the existing issue and is also faster and more flexible.  
Thanks, Grant.

**Comment by tridge** [comment]
great work, thanks Lucas!
pushed

**Pull request closed without merging**
