### PR TITLE
Copter: remove comments that number scheduler table

### PR DESCRIPTION
**Pull request by jschall**
These comments cause merge conflicts and are painful to maintain.

### CODE REVIEW

**Comment by rmackay9** [comment]
maybe we should change the scheduler output so that it outputs the full string instead of the task number?  That risks slowing down the output a bit but might be easier in the end.

**Comment by jschall** [comment]
All I know is that the comments are a merge nightmare :)

**Comment by lucasdemarchi** [comment]
@rmackay9  I'd say the speed is not really a problem here, just the additional storage for the strings.

**Comment by rmackay9** [comment]
Merged.
Although it took a while to decide, I figure that the merge issues that Jon is facing are more severe than the inconvenience for the rest of us when it comes to looking up which scheduler task is slow.
Maybe we can put them back after the merge is complete or find another solution (or just suffer).

**Pull request closed without merging**
