### PR TITLE
Inertial sensors refactoring and fixes

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Here are some fixes and refactors I'm doing for AP_InertialSensor. I left on separate commits the ones that are purely coding style changes.

I couldn't test this on Bebop and it's the one mostly affected. So be aware this is only compile-tested. There are 2 fixes for Bebob ("AP_InertialSensor: MPU6000: fix copying wrong number of bytes" and "AP_InertialSensor: refactor constructors to avoid leak").  And there's one commit to change how the bus and address are chosen.  If we agree on the approach in "AP_InertialSensor: MPU6000: do not care about I2C bus/address" I can do a similar change for AP_Compass that has the same problem.

I have more pending changes for MPU6000 since I need to allow it to talk to other devices on its auxiliar bus.  However I'd like to send these commits earlier so to agree on the approach I'm taking.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@jberaud could you take a look?

**Comment by jberaud** [comment]
Ok,

I will,

Julien

**Comment by jberaud** [comment]
The modifications looks fine to me. Thank you for the code improvements. I don't think it fixes any bus/issue but the code is definitely better this way.
Tested quickly on the bebop. I will fly it later this afternoon to be absolutely sure but everything seems fine.

**Comment by jberaud** [comment]
Flight tested. Ok.

**Comment by lucasdemarchi** [comment]
@jberaud thanks for testing it. I guess you could add a Reviewed tag here?

**Comment by lucasdemarchi** [comment]
Hold on on this, I have some changes and the compass library converted as well. I will push tomorrow.

**Comment by tridge** [comment]
this patch looks very good to me. 
Lucas, do you still have a hold on this?

**Comment by lucasdemarchi** [comment]
> this patch looks very good to me. 
> Lucas, do you still have a hold on this?

yes... I have it done for compass too, but not tested yet. I can push again these commits (I have some typos I did in this pr fixed) and open another pr for compass.

**Comment by tridge** [comment]
ok, I'll wait for you to say its OK to push

**Comment by lucasdemarchi** [comment]
Did github fix their stuff and now we can see the previous version? Or was it because I rebased?

@tridge now it's ok... same commits, just with some typos fixed and reordered.

**Comment by tridge** [comment]
applied, thanks Lucas!

**Pull request closed without merging**
