### PR TITLE
clean up land detector and modify to use desired velocity

### PR DESCRIPTION
**Pull request by jschall**
Also removes the barometer climb rate check.

### CODE REVIEW

**Comment by jschall** [comment]
Untested.

**Comment by jschall** [comment]
Stabilize doesn't check for a land detection, so we don't care :)

**Comment by R-Lefebvre** [comment]
Ok, I wondered if that was the case.  But if that's true, why do we need this part?

!pos_control.is_active_z() 

If it doesn't check in Acro and Stab, then this will always be true?

**Comment by jschall** [comment]
We still do land detection in stabilize - we just don't *use* it. That bit of code covers any case where we might not be using the altitude controller.

**Comment by jschall** [comment]
> We shouldn't remove the baro check. That was specifically added after a false positive due to a very unhappy inertial nav. If we were on EKF only we could remove it but that's not the case for AC3.2.1.

Ok. Can add that back in.

**Comment by rmackay9** [comment]
Merged to master and AC3.2.1 branch.  I added back the baro climb rate check and moved the land_check to it's own file called land_detector.pde.  I've test flown it and I don't see any noticeable change which is good.  I also did some very high speed passes in poshold mode which was the error case, although I think it was very hard to trigger it before even without the new check.

**Pull request closed without merging**
