### PR TITLE
AP_Notify: Add a new RGBLed implementation that works over RCOutput

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@zehortigoza thanks!

@onceme This was the implementation I was telling you for RGB LED on PCA9685. The benefits are:
 - It's more generic allowing any board to re-use it as is - indeed this was how we were using it in minlure
 - Updates to the motors doesn't "conflict" with update to LED. We use rcout->cork() and rcout->push(), meaning it's updated once per mainloop iteration and LED is updated if and only if it changed since last iteration.
 - We correctly take into account changes to the frequency

I think it would be very straightforward for BH to use it. I'll adapt the current PR to use this. Could you test on your hardware to see if it fulfills your needs?

**Comment by onceme** [comment]
@lucasdemarchi @zehortigoza

Thank you. I tried the RCOutput_RGBLed on BH v0.2 board which just I received from our manufacturing partner. The RGBLed works well with it.

Please have a look at the comments of https://github.com/diydrones/ardupilot/pull/3282 for a small patch and a photo I just took.

**Comment by tridge** [comment]
applied, thanks!

**Comment by rmackay9** [comment]
great stuff, it would be good to do a blog post on diydrones or somewhere to show how to use this new feature.

**Comment by lucasdemarchi** [comment]
@rmackay9 It's not for the user, but rather for some board designs we already have. They use the last channels of an PCA9685 to connect an RGB led. Although it could be made to work, we are not really expecting the user to connect the LED to the rcoutput channels.

**Pull request closed without merging**
