### PR TITLE
AP_Eigen

### PR DESCRIPTION
**Pull request by dgrat**
Added a new math backend, based on Eigen (http://eigen.tuxfamily.org/)
Eigen sub module is synced via: https://github.com/RLovelett/eigen.git (as eigen uses mercurial)
I am open for suggestions regardng extensions, function which needs to be included into the new Eigen based types.

  * Performance: I measured between +30 % and +200 % calculation time decrease dependent on the CPU type and whether virtualization was used and which operations are used (typically, best performance gains are observed for vector/matrix multiplications)
  * Memory:  Seems to be comparable with AP_Math
  * Flash: No idea, as I dont use PX4

The interface is yet not feature complete but could be already applied for most tasks and tests. 

Signed-off-by: dgrat <dgdanielf@gmail.com>

### CODE REVIEW

**Comment by dgrat** [comment]
@tridge @lucasdemarchi 
I recently added safe type conversions for all floating point types to all integer types.
There is also a dummy safe if the developer would perform useless type casts. 
Currently, there are a lot of unsafe casts around the library. I want to make these casts simpler and safe. 

Best

**Comment by dgrat** [comment]
Added advanced example: I ported compass learning, because I never liked this particular implementation.

**Comment by lucasdemarchi** [comment]
@dgrat thanks for the new "examples". As @tridge said it's much better to evaluate the impact of the changes by actually changing the existing code rather than just adding examples.

It will take some time for me to be able to review the content of the pull request. Not sure about other maintainers. Meanwhile there are some easy changes you could do to help the review process:

 - We don't use signed-off-by in commit messages

 - The first line of a commit should have a short description of the commit instead of just a "title". Then please let a blank line after the first one, so the several git tools (and github) correctly display them. Example: the last commit should be:

```
AP_Compass: convert compass learning to Eigen

Port compass learning to Eigen ...
```

 - The commits should be split by "library". So in the last commit first add the `constrain_value` in the library and in another commit use it in other places. And IMO this function should be in AP_Math, not AP_Eigen. There are even other places in the code that could use it and it has no relation with Eigen.

 - We are trying to have a common coding style. We are not enforcing it since it would raise the bar too much for newcomers (or make us start to fixup things later).  However it would be good to follow it if possible.  Examples from a quick look in your code: **1.** Add space before parenthesis for **flow control**, i.e. "if", "for", etc.  `if(std::is_floating_point` should be `if (std::is_floating_point`; **2.** remove spaces inside the parenthesis: `static_cast<FloatType>((std::numeric_limits<IntType>::min)()) )` should be `static_cast<FloatType>((std::numeric_limits<IntType>::min)()))`.

 - "Flash: No idea, as I dont use PX4":  this kind of statement doesn't help convincing people to make the switch. Even if we (and I include myself here) don't use it, we should play well with it. For this particular case it's also important in Linux, even if to a less degree. By "flash" we mean the actual binary size. You can easily verify the binary size (and in which section the space is) by using `strip` + `size` tools in the .elf binary. For RPi you actually want "arm-linux-gnueabihf-*" variation of the tools. See https://github.com/diydrones/ardupilot/commit/0daeeb9518c78a37b098c85f94b521d8c255e817 with a detailed example on how to interpret their result.

- IMO we should not track the master branch of Eigen.  We certainly don't want to introduce random bugs in the flight stack because of bugs introduced in the master branch. So... I think we should track the last stable release, which in this case is 3.2.6.  Do we have a git repository with separate branches for stable releases? Otherwise we may want to do a git mirror from "https://bitbucket.org/eigen/eigen/branch/3.2"

Sorry if some of the items above sound as nitpicking. I just want us to have a better/consistent codebase as you also seem to want.

**Comment by dgrat** [comment]
Hi Lucas, 

> we should not track the master branch of Eigen
There is, I think, just one git repo which is always synced with master. 
The problem with Eigen is, that it is using mercury, which makes adding it as submodule tricky. 
At least for me.

Currently, I deal with other problems. I tested building atm only for native linux. I guess, there are definitely problems regarding different compiler versions, which still have to be fixed. I use normally the Travis output for this :) 
Nevertheless, I hope you can test the code.

**Comment by dgrat** [comment]
@lucasdemarchi 

master @ native
dgrat@linux-roz1:~/bin/ardupilot/ArduPlane> size ./ArduPlane.elf 
   text    data     bss     dec     hex filename
 823231     960   47560  871751   d4d47 ./ArduPlane.elf

Eigen @ native
dgrat@linux-roz1:~/ardupilot/ArduPlane> size ArduPlane.elf 
   text    data     bss     dec     hex filename
 826638     996   47752  875386   d5b7a ArduPlane.elf

**Comment by lucasdemarchi** [comment]
@dgrat thanks. Now we know it increases the binary size in 3.5K. We may gain it back when cleaning AP_Math though.  Please also include this kind of information in the commit messages. As you see from the commit I linked above it's very useful for knowing the history of the changes and future evaluation.

**Comment by dgrat** [comment]
@lucasdemarchi 
Do you know how much space currently is available in current NuttX boards?
With AVR it was relatively easy to roughly estimate memory consumption, but I know nearly nothing about PX4 and related.

**Comment by dgrat** [comment]
@tridge @lucasdemarchi 
looks like a macro collision in case of px4 with std::signbit. 
Is there an elegant solution, rather than just undef/delete the macro?

#define signbit(__x) \
	((sizeof(__x) == sizeof(float))  ?  __signbitf(__x) : \
		__signbitd(__x))

**Comment by dgrat** [comment]
I think I may fixed the build problems on PX4. 
I will not shift functions into AP_Math, because I want to remove and replace this part entirely. 
AP_Math will be the past and it is ugly. It is not even template based, nor type safe.

**Comment by dgrat** [comment]
I think I may fixed the build problems on PX4. 
I think, I will not shift functions into AP_Math, because I want to remove and replace this part of the library entirely. 
AP_Math is neither template based, nor type safe, which renders it critical for what I have in mind.

**Comment by dgrat** [comment]
@lucasdemarchi 
The lgamma() function is again compiler dependent. with arm-none-eabi-gcc 4.8.* it works, with 4.9.* not. 
:P the ARM library is a pain ..

**Comment by dgrat** [comment]
@lucasdemarchi @tridge 
I tried to reproduce the build error with a local debian (and https://packages.debian.org/jessie-backports/libstdc++-arm-none-eabi-newlib version 4.9.2)
I was _not_ able to reproduce the build error for px4-v2. Could it be a problem of Travis?

**Comment by lucasdemarchi** [comment]
@dgrat the version used there is the 4.9.3 not 4.9.2. Also it's not using. I'd say to try getting it from the same place as Travis is downloading it and see if you can reproduce it.

**Comment by dgrat** [comment]
Well, it looks like it's either a problem with the installation of the standard library or, the new compiler version is incomplete. 
With 4.8.* it was building with 4.9.2 it was building, and I currently lack time.
I wil

**Comment by dgrat** [comment]
@lucasdemarchi 
Just try to guarantee that at least the standard library is complete with C99 math.
The PX4 flight stack uses GCC ARM 4.8.* and Eigen as far as I know. Maybe just don't use 4.9.
If your setups lacks std:functions and C99 math, I cannot do much even if I can reproduce this particular build error.

Best, Daniel

**Comment by lucasdemarchi** [comment]
@dgrat **my** setup is gcc 5.2 for x86-64 (the minlure we just added support to) ;-). And clang++ in some occasions.

However either we make it to work for everybody or we can't actually make it. And for that we need to understand what's happening and make the right changes for everybody, which may include switching the compiler (as long as everything else continues to work).  There is a reason we are using 4.9.3 for PX4: it produces smaller and faster code. And it is available for every distros.

**Comment by dgrat** [comment]
@lucasdemarchi 
Okay, I have not much time, but I made a test with debian testing 4.9.3.
Looks like, there is a part of the standard library missing. 
Got this error: 

    > home/dgrat/ardupilot/libraries/AP_Eigen/eigen/Eigen/Core:28:19: fatal error: complex: No such file or directory #include <complex>

Asked that at stackoverflow some time ago and got closed-voted (looks probably like an installation mistake ..)
Similar problems here: https://groups.google.com/forum/#!msg/px4users/hHWiqW9lk1U/p8UGfg_tfcwJ

My guess is, it is a packaging error.. compare: 
https://packages.debian.org/jessie/all/libstdc++-arm-none-eabi-newlib/filelist
https://packages.debian.org/stretch/all/libstdc++-arm-none-eabi-newlib/filelist

**Pull request closed without merging**
