### PR TITLE
AP_HAL_Linux: Implement perf API

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by tridge** [comment]
I'm glad to see Linux getting perf counters!
What is the plan for getting the data out of this?

**Comment by lucasdemarchi** [comment]
A separate thread handling d-bus connections. We are trying to ensure the points we talked about during the dev call:
 - the perf events are taken atomically (so you can correlate 2, 3, 4, ...  perf_events)
 - we get them lock-less so we don't have a priority inversion  (actually the priority inversion is not bad, but I don't like the idea of the main thread having to wait the d-bus thread)

**Comment by tridge** [comment]
ok, thanks
pushed to master. I look fwd to the tools to access this!

**Comment by lucasdemarchi** [comment]
@tridge I was thinking to ask @zehortigoza to send first the changes to the scheduler. I think it's ready already.  What do you think?  This would allow us to start adding more meaningful perf events while we iron out how to get them from outside (we can always test them hacking some printfs in the timer thread).

**Pull request closed without merging**
