### PR TITLE
Plane: compiler warnings

### PR DESCRIPTION
**Pull request by magicrub**
- float to double in gcs_send_test (x2)
- float to bool

### CODE REVIEW

**Comment by dgrat** [comment]
Hi @magicrub 
It really looks like it is just not my repo which fails with px4 builds.
The function must be replaced, the comparison is undefined.

**Comment by magicrub** [comment]
Probably just needs a ::

**Comment by magicrub** [comment]
funny, I committed these compiler warnings one-short of when I branched and fixed them. Easy to just add the fix in on this commits while I'm at it

**Comment by dgrat** [comment]
No I think the function needs a revise. 
I think this compiler warning is indeed a nice one.
I just wonder, why it is only for PX4

**Comment by magicrub** [comment]
@dgrat  Are you talking about longitude_scale()?

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
