### PR TITLE
RFC: waf build system

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This is a **request for comments** for the introduction of a new build system for ardupilot based on [waf](https://waf.io/).

Here are some points I'd like to stress:

 - The main advantage of using this build system is the reduction of complexity when compared with the current one.
 - As a consequence, that enabled us to easily do unit test and benchmark integration (Google Test and Google Benchmark, respectively).
 - Clean builds with both build systems yield similar timings, so there isn't performance regression.
 - This is not ready yet. Some of the missing features are:
     - Support building for boards (or targets for the current naming convention) other than `sitl`, `linux` and `minlure`.
     - Add a `make` wrapper for the waf build system.
     - **... and other features that may come up from this RFC.**

Your comments will be appreciated!

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
This is a basic example on how to use it:
If you're in the project's root directory, `./waf configure --board 'linux' build` will trigger the configure and the build command.
You can also call `waf` separately:
```bash
./waf configure --board 'linux'
./waf # command build is the default one
```

An alias or function can be created for convenience:
```bash
alias waf="$PWD/waf"
```

([Here](https://gist.github.com/guludo/87a865f9f93ce6f7531f) is a piece of script I wrote *for myself* in order to create a `waf` function).

For more information you can use `waf --help` and also check out https://waf.io/book/.

**Comment by khancyr** [comment]
Hi, 

I am not a specialist but why use another build system which will need to be maintained update in the project and python dependency ? 
If I had a choice to do, I will choose Cmake instead of waf (I am not knowing it well but I don't see reals advantages, I wil try it ) beaceause it has the same advantages and allow to use of makefiles. ( and compatible with all IDE and ROS)
That my opinion .

By the way, good joob with Gtest ! I think it is a good idea and will allow to track regression more easily !

**Comment by MacDev240** [comment]
Unit Tests , Good work!
Thanks

**Comment by lucasdemarchi** [comment]
Hi @khancyr 

Thanks for the feedback. We had a similar discussion yesterday in the dev call, I will try to summarize it here to broaden the audience:

 - Fact number one: we need something more maintainable than the current build system
 - CMake does the job as well, but has some really annoying points: dealing with it additional DSL is a pain, particularly because of the way you create variables. One typo in the variable name and you will keep wondering why the build system isn't behaving as expected.
 - Since waf is embedded in the repository, there's no additional dependencies to build the project. The only thing you need is python (and you already needed it for other things). Old versions of CMake are pretty terrible to work with; newer ones are better, but it also means additional packages to install. For me it's not a big thing due to the Linux distro I use, but for others (think RHEL, Debian, MacOS, Windows) it may be difficult to keep up with the requirements
 - **We are going to have** integration with makefiles. This is something in the TODO list.  There's nothing special in CMake in this regard and as for IDEs we can integrate it just fine with waf by using the makefiles. For example, waf even generates a clang database that can be used by clang-tools and some IDEs for code completion, refactoring, etc.
 - It's not "another custom build system"  - waf is a build system used in other projects as well, maybe just not the ones you are more familiar with. It's true that CMake is more used than waf, but we don't think that's a strong argument. We are also trying to keep custom things to a minimum and searching on other projects that use waf how they are solving things we need to solve.
 - We really need something maintainers are willing to maintain... @tridge was very against CMake due to its deficiencies so we would need to have a "CMake champ" to keep maintaining the build system. If you look in git log you will see there has already been one attempt to convert it to CMake. However people stop contributing, switch projects, etc and we remain with a half-baked build system.

**Comment by khancyr** [comment]
Hi,

Thanks for the answer, it is more clear for me ! I will take some time to learn about waf !
I agree that the current building need to be update for easier work!

**Comment by lucasdemarchi** [comment]
@guludo for this going on I think we need the following:

 - Remove the commit "AP_Math: remove ROTATION_YAW_293_PITCH_68_ROLL_90": as discussed the fix is not like this and we can discuss it in a separate PR;
 - Add to Travis the compilation of one of the boards (linux, sitl or minlure), so we avoid the build system to bit rot while we finish it

As soon as possible add the other Linux boards and PX4.

@tridge After this I think we can merge it since it doesn't affect the current build system and we will keep improving it on top.

**Comment by khancyr** [comment]
Hi, 
I give a try but it is not working for me.... It throw an error in gbenchmark... but the tool seems promissing,  waf can generate cmakelist so I can load arducopter in Clion ! (I cannot product a build for no but it is less horrible than I expected ! )
I could be interresting to make gtest and gbenchmark optional ( I didn't find how to do it)

**Comment by lucasdemarchi** [comment]
@khancyr they should be optional, yes. gbenchmark is a git submodule, so if you do `git submodule init && git submodule update` it should work

**Comment by khancyr** [comment]
I get 
````
/home/khancyr/Workspace/ardupilot-1/build/gbenchmark/lib/libbenchmark.a(benchmark.cc.o): dans la fonction « benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*) »:
benchmark.cc:(.text+0x3dbe): référence indéfinie vers « pthread_create »
/usr/bin/ld generated: référence indéfinie vers « pthread_create »
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/khancyr/Workspace/ardupilot-1/build'
Build failed
 -> task in 'benchmark_matrix.linux' failed (exit status 1): 
	{task 140236719891792: cxxprogram benchmark_matrix.cpp.1.o -> benchmark_matrix.linux}
['/usr/bin/g++', '-Wl,--gc-sections', 'libraries/AP_Math/benchmarks/benchmark_matrix.cpp.1.o', '-o', '/home/khancyr/Workspace/ardupilot-1/build/libraries/AP_Math/benchmarks/benchmark_matrix.linux', '-Wl,-Bstatic', '-L.', '-lap', '-Wl,-Bdynamic', '-L/home/khancyr/Workspace/ardupilot-1/build/gbenchmark/lib', '-lm', '-lpthread', '-lrt', '-lbenchmark']

````
So in english : benchmark.cc: undefined reference to« pthread_create » , even if -lpthred is here.

but maybe it from my config . I will try later with fresh install.
By the way Ubuntu install-prereqs must be updated with gtest install ( I succeeded to install it on ubuntu but there are no official rules and many way to do it... !)

**Comment by guludo** [comment]
@lucasdemarchi ACK

**Comment by guludo** [comment]
Pull request opened.

**Pull request closed without merging**
