### PR TITLE
Unified delta angle and velocity calculation

### PR DESCRIPTION
**Pull request by guludo**
As @tridge asked in one of the comments in #2796, this PR moves the calculation of delta angle and velocity from the code specific for PX4 to a common place.

I have enabled that for PX4 (the one that was already doing the calculation) and also for MPU9250 and MPU6000 (the IMUs we've been using here).

This passed travis build and I can run ArduCopter with these patches. However I'm not sure on how to validate this. Any idea?

### CODE REVIEW

**Comment by tridge** [comment]
thanks! I'll look at this soon

**Comment by tridge** [comment]
I think this PR looks good, thanks!
we just need a test flight of it on a Pixhawk, with IMUDT logging enabled, then we need to examine the logs to make sure it all looks good

**Comment by rmackay9** [comment]
I attempted to test fly master with these commits added and it didn't go well.  The EKF doesn't seem to be initialising.  Logs are linked below.
https://dl.dropboxusercontent.com/u/3852647/Tridge/randy-benchtest-guludo.bin

**Comment by tridge** [comment]
marked as need-rework as we need to work out why this makes pixhawk crash copters

**Comment by guludo** [comment]
@rmackay9 oh, I hope this didn't cause much damage to your hardware :/ Sorry if so!

I'll take a look.

**Comment by rmackay9** [comment]
@guludo, nah, no problem at all.  It flipped over on takeoff and it's an IRIS so it's pretty durable.  No damage as far as I can tell.

**Comment by guludo** [comment]
@rmackay9 I've reviewed my changes and I found two issues:

 - I'm not verifying wether delta velocity data is really valid before setting it as valid. See https://github.com/guludo/ardupilot-1/commit/5c079edb2131493ce51217b9d9e4fe626a31a939#commitcomment-13754747 . Although that should be fixed in order to make the code safer, I doubt that's the reason for the problem we're facing, since **there will be delta velocity data** when `_publish_accel()` is called by `AP_InertialSensor_PX4`.
 - The new implementation clears the accumulators only when the publishing functions are called whereas the previous PX4 implementation did that whenever `update()` was called. See https://github.com/guludo/ardupilot-1/commit/626124cd14600b9705dee1f9db6f3a49e5312d30#commitcomment-13754645 and https://github.com/guludo/ardupilot-1/commit/ecffd1d1d783b4d877c71066478824783678f41f#commitcomment-13754685 . That could mean delta velocity and delta angle values being too (and/or wrongly) oversampled.

As I said, I doubt the first issue is the cause for the problem with PX4. I'm not sure about the second one though.

Any thoughts, guys?

**Comment by guludo** [comment]
I just added to commits that are to be squashed in a new version of this PR. Those commits address the problem with the accumulators.
I haven't added a patch fixing the "problem" pointed by the first bullet point because I've come to realize that that is not really a problem, since it won't happen if the backends are properly implemented - specifically if they are notifying the raw samples.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
