### PR TITLE
Some suggestions: Compass, AP_Math and Dataflash

### PR DESCRIPTION
**Pull request by dgrat**
I want to add some changes. Some are more, some less important.
I consider two of them as crucial: 

- AP_InertialSensor: One of the sensors uses a wrong macro and is not building under certain conditions, because the definitions are in a header file which is only included for BBB builds.

- AP_PID: I suggest to add support for a standard constructor and to change the handling of floats. There is no reason not to support a standard like constructor and it would allow putting PIDs into an array :). The handling of floats is important in my opinion for UAVs.
Other stuff:

- Rounding in AP_Compass looks not okay

- Dataflash: It would be nice if one could compile Datafaslh with MinGW (but I don't care much if not accepted)

- AP_Math: Added some general purpose functions for (correct) rounding and checks for floats

### CODE REVIEW

**Comment by dgrat** [comment]
The AP_InertialSensor seems to be correct now for Navio. I reverted the change.

**Comment by magicrub** [comment]
This is probably worth while to split up into different PRs. You seem to be fixing/changing multiple unrelated things.

**Comment by dgrat** [comment]
Well,
my intention was to get at least a feedback of which updates are worth to get included prior preparing single PRs.
I personally would like to see the AP_Inertial commit included, because I had to either change or exclude it from build if building for Navio with cmake. I wasn't testing whether there are problems with the regular build system, but if there aren't any I wonder why, because it should cause some. 
The other stuff is less annoying for me, because they do not result in build problems, but may other. 
I think the only controversial patches are Compass and Dataflash. I mean, Compass is not tested and Dataflash is maybe not necessary. I just added this patch, because I once eanted to compile with MinGW for testing purposes.

**Comment by rmackay9** [comment]
Thanks for the contributions!  I've merged in the AC_PID and AP_Math's is_equal changes after a bit of rework:
1. the MI_2_PI macro should probably have brackets around it.  It's possible the order-of-operations would have meant it was fine but in general, for macros like this an extra set of brackets is a good idea.
2. removed some white space changes.  Normally we prefer if formatting changes are done as a separate commit which just changes the format.  In this case, the changes seemed counter to our regular formatting standards so I just removed them.
3. added is_zero to complement is_equal also made both inline after checking their size.
4. use fabsf instead of fabs (note the final "f")
5. pass by value instead of reference
6. there was a missing return in the calc_alpha function.
The above changes were the result of a discussion between Tridge and I (with some additional input from TomP).
7. we like commits to be separated so they don't affected more than one library or vehicle.  So it's ok for a PR to affect more than one lib or vehicle but the individual commits should be separated.

I'm going to close this PR now although we haven't merged all the changes, hopefully the feedback is helpful and we look forward to your next set of patches!
txs again.

**Pull request closed without merging**
