### PR TITLE
Always report primary GPS to GCS and manage switch

### PR DESCRIPTION
**Pull request by emilecastelnuovo**
This addresses issue #1734.

### CODE REVIEW

**Comment by emilecastelnuovo** [comment]
Rebased onto master.

**Comment by emilecastelnuovo** [comment]
Rebased onto master.

**Comment by rmackay9** [comment]
Thanks.  This is a good one that we should get in.

**Comment by tridge** [comment]
this doesn't look right to me. The GPS_RAW_INT message should always be the same GPS (ie. always the first one). The GPS2_RAW is the 2nd GPS.
If we change what GPS is reported in GPS_RAW_INT then it gets very confusing looking at logs, as a graph of a single message type will change between GPS modules. 
The correct fix is to make the GCS understand that there may be multiple GPS modules and display the fix type, number of satellites, hdop and other fields for each GPS separately.
Note that this matches all of our other sensor libraries (compass, baro, IMU etc)

**Comment by rmackay9** [comment]
I misunderstood the change.  I thought that we only had a single GPS message and this change would move the active GPS into that message.  Now that I understand that we have two GPS messages I agree we shouldn' flip them around but instead find a way to tell the GPSs which one to use.

**Pull request closed without merging**
