### PR TITLE
Changes on AP_Sheduler logging

### PR DESCRIPTION
**Pull request by guludo**
Hi guys,

This PR make changes related to AP_Scheduler logging:

1. **New value for SCHED_DEBUG: ShowAll**
    That option makes all tasks execution be logged. That's good to analyze how well the tasks are being scheduled and if tasks are performing in the promised execution time. I've written a script that outputs stats information and a histogram based on the logs from option ShowAll. I'll add that script to Tools/scripts soon in case this PR is accepted.
(*I still don't know what is the procedure to add that information to the CGSs.*)

2.  **Debug messages are print after loop so that they don't interfere in timings**

3. **Makes tasks have a name to provide a easier way to identify tasks in logs**

Regards :)

--
Gustavo Sousa

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Ha! very nice to see these changes finally submitted :-). I already reviewed this privately.

**Comment by lucasdemarchi** [comment]
Recent discussion about the issue this pr fixes: https://github.com/diydrones/ardupilot/pull/2388

@rmackay9 @jschall you may want to take a look on this.

**Comment by guludo** [comment]
Just a heads-up: just added a new commit with the script that process the log messages.

**Comment by lucasdemarchi** [comment]
could you also add an output example?

**Comment by guludo** [comment]
@lucasdemarchi here https://gist.github.com/guludo/e4e797dfc413808396a5

**Comment by dgrat** [comment]
I would like to rewrite the scheduler after this push.
I think the code is not as simple as it could be for this type of scheduler.

**Comment by dgrat** [comment]
@lucasdemarchi This is what I have in mind

    void AP_Scheduler::run(uint16_t time_available) {
        uint32_t run_started_usec  = hal.scheduler->micros();
        uint8_t  log_count         = 0;
        uint8_t  current_log_index = 0;

        for (uint8_t i = 0; i < _num_tasks; i++) {
            Task     cur_task = _tasks[i];
            uint16_t last_run = _last_run[i];

            // this task is due to run. Do we have enough time to run it?
            uint16_t dt             = _tick_counter - last_run;
            uint16_t interval_ticks = pgm_read_word(&cur_task.interval_ticks);
            _task_time_allowed      = pgm_read_word(&cur_task.max_time_micros);
            
            if (interval_ticks > dt || _task_time_allowed > time_available) {
                continue;
            }

            current_log_index = log_count;
            _task_execution_log_buffer[current_log_index].flag = 0;
            
            /* 
             * Finally, run the task 
             */
            _task_time_started = run_started_usec;
            task_fn_t func;
            pgm_read_block(cur_task.function, &func, sizeof(func));
            current_task = i;
            func();
            current_task = -1;
            
            // record the tick counter when we ran. This drives
            // when we next run the event
            last_run = _tick_counter;
            
            // work out how long the event actually took
            run_started_usec = hal.scheduler->micros();
            uint32_t time_taken = run_started_usec - _task_time_started;
            if (time_taken >= time_available) {
                update_ticks();
                out_logs(log_count);
                return;
            }
            time_available -= time_taken;
            
            /*
             * Debug output
             */
             // we've slipped a whole run of this task!
            if (dt >= interval_ticks*2 && _debug > 1) {
                _task_execution_log_buffer[current_log_index].task_id = i;
                _task_execution_log_buffer[current_log_index].flag |= SCHEDULER_TASK_SLIPPED;
                _task_execution_log_buffer[current_log_index].ticks_since_last_run = dt;
                log_count++;
            }

            // if the event overran or _debug set to log all executions
            if ((time_taken > _task_time_allowed && _debug > 2) || _debug > 3) {
                _task_execution_log_buffer[current_log_index].task_id = i;
                _task_execution_log_buffer[current_log_index].time_taken = time_taken;

                _task_execution_log_buffer[current_log_index].flag |= SCHEDULER_TASK_EXECUTED;
                if (time_taken > _task_time_allowed) {
                    _task_execution_log_buffer[current_log_index].flag |= SCHEDULER_TASK_OVERRUN;
                }

                if (current_log_index == log_count) log_count++;
            }
        }

        // update number of spare microseconds
        _spare_micros += time_available;
    }

**Comment by tridge** [comment]
we need to avoid the extra memory allocations on AVR. The _last_run and _task_execution_log_buffer arrays are far too big on AVR.
It also adds about 500 bytes of flash on avr
I do like having the name in there though!
how will we get the statistics out on Pixhawk? I think we may be better using perf counters which has existing infrastructure.
Perhaps we should implement the perf counter interface from px4 on linux?

**Comment by guludo** [comment]
Hi @tridge, does the comment above apply even now that we'll not be supporting AVR on next releases anymore?

**Comment by tridge** [comment]
the AVR restriction no longer applies. This PR was one of the motivations for forking off AVR support
I'd still like to know how this makes sense on Pixhawk though? How would you get the statistics out?
On a Pixhawk the usual mechanism is to add perf counters. Have a look for example at the usage of perf counters in libraries/AP_NavEKF for example.
What I would prefer to see is a port of the PX4 perf counter code to HAL_Linux:
https://github.com/diydrones/PX4Firmware/blob/master/src/modules/systemlib/perf_counter.c
then in AP_HAL_Boards.h we could have a 
#define HAL_HAVE_PERF_COUNTER 1
for both PX4 and Linux. That will immediately get us useful perf counters in lots of places in the code where we only have them for PX4 at the moment. 
In AP_Scheduler we would then allocate an array of perf counters, one per task, named by the task name. On PX4 we could then run "perf" and get performance counters for all tasks (as well as everything else).
I prefer this approach as it would consolidate the APIs between the PX4 port and the Linux port, which would really help reduce duplication, and would give us directly comparable performance numbers
Would you be willing to do the port of perf_counter.c to AP_HAL_Linux? Wrapping it in a C++ class would also be nice, or adding it as a hal method, under hal.util perhaps?

**Comment by lucasdemarchi** [comment]
> I'd still like to know how this makes sense on Pixhawk though? How would you get the statistics out?

Can't you redirect stdout just like we do in Linux?

> On a Pixhawk the usual mechanism is to add perf counters. Have a look for example at the usage of perf counters in libraries/AP_NavEKF for example.
> I prefer this approach as it would consolidate the APIs between the PX4 port and the Linux port, which would really help reduce duplication, and would give us directly comparable performance numbers

I was taking a look on the implementation of perf counters in PX4 yesterday. Note that even if we add perf counters support in Linux, it wouldn't work for **this** case. That's because we just generate the raw events in ardupilot and post-process them later with the python script. Otherwise, how would you generate the histograms? None of the event types have enough room to store all the information we need.

The way I see it PX4's perf is a subset of the tracing utilities available in Linux.

> Would you be willing to do the port of perf_counter.c to AP_HAL_Linux? Wrapping it in a C++ class would also be nice, or adding it as a hal method, under hal.util perhaps?

We could use the same API and in Linux allow to send the events somewhere for post-processing.

**Comment by tridge** [comment]
> Can't you redirect stdout just like we do in Linux?

no, or at least not in a practical way. Stdout goes to a debug uart which most people don't have attached. Even if it is attached there is no useful way to capture that information for post processing

> We could use the same API and in Linux allow to send the events somewhere for post-processing.

yes, that sounds great. So we won't get full histograms on PX4, but we will get a uniform API and get at least min/max/rms on PX4 (which is what you need in most cases).

**Comment by lucasdemarchi** [comment]
@tridge, I was talking to @guludo  today...  I think it makes sense to split this pull request in 2 then. The first part would add the names. The second part changing the scheduler log would be re-implemented later with the perf changes. What do you think?

**Comment by guludo** [comment]
#2789 was applied, thanks @tridge!

I'm closing this one so we don't have zombies PRs.

**Pull request closed without merging**
