### PR TITLE
Introduce AP_HAL functions

### PR DESCRIPTION
**Pull request by cmarcelo**
Introduce functions in the `AP_HAL` that are unlikely to change after link time and would have no benefit from explicit indirection. This includes: `panic()`, `millis()`, `micros()`. The idea is that those basic utility functions should be provided as regular functions instead of virtual functions.

### CODE REVIEW

**Comment by cmarcelo** [comment]
Replaces #3157

Differences:
- Use `AP_HAL` namespace instead of `platform`
- To not use the name `platform`, the implementation code for the HAL is in `system.cpp` file for each HAL, and the header is now called `system.h`. For convenience later, we can split these out.

I've also updated the measurements for the PX4 ArduCopter build, the PR removes 3000 bytes from the code now.

**Comment by cmarcelo** [comment]
@rmackay9 @tridge could you take another look?

**Comment by rmackay9** [comment]
One couple of small problems that I think I can fix as part of the merge:
1. merge conflict with recent change to AC_PosControl
2. commits shouldn't cross vehicle types.  so we should have separate commits for Tracker, Rover, Plane, Copter.
.. anyway, like i said, i can sort that part out but for next time..

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request closed without merging**
