### PR TITLE
AP_Eigen

### PR DESCRIPTION
**Pull request by dgrat**
@cmarcelo 
AP_Eigen commit without compatibility types, but with c style converter functions.

### CODE REVIEW

**Comment by cmarcelo** [comment]
Thanks!

**Comment by cmarcelo** [comment]
@lucasdemarchi @tridge

**Comment by dgrat** [comment]
@lucasdemarchi 
The old commit was rather for comparison, because maybe there is a chance that someone likes the compat classes :) But it looks like the decision has been made

**Comment by dgrat** [comment]
What's the state. After the devcall I wasn't participating, I am curious. 
Will it be included or not?

**Comment by lucasdemarchi** [comment]
I have a rebase of this branch with some fixes. One of the problems is that
it still needs a lot of effort to convert current users. In other words,
replacing Vector3f by Eigen::Vector3f and so on.

This is different from taking some parts and adding examples of the
conversion as has been done. I'll send the branch tomorrow for you to take
a look. Only after the conversion we will actually know if it's worth.

Another thing is as much as you like deprecating AP_Math with similar
methods in AP_Eigen, that's not going to happen, sorry. AP_Eigen should be
a shim to allow the use of Eigen in our codebase. We should focus effort in
making this shim via the add-on mechanism Eigen provides so the conversion
can be done by a simple `using AP_Eigen::Vector3f` in AP_Math or something
like that. This way we can have a big picture of our gains and migrate code
to the new interface if it makes sense. My changes are along these lines...
I'll send them tomorrow for you to take a look.
Em 03/01/2016 5:35 PM, "Daniel Frenzel" <notifications@github.com> escreveu:

**Comment by dgrat** [comment]
AP_Math is 90

**Comment by lucasdemarchi** [comment]
> AP_Math is 90

Improving it in place is the way to improve it. Not on the same commits as
AP_Eigen.

**Pull request closed without merging**
