### PR TITLE
Data flash test

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Did you forget to initialize your git with proper user/email on this machine? The commits are appearing as authored by "unknown":
```
From: unknown <rentt@rentt-G510.(none)>
```

**Comment by peterbarker** [comment]
There are two patches here - one by me and one from rentt (see https://github.com/diydrones/ardupilot/pull/2640); I thought we got a "this PR was referenced from" entry here :/)

In terms of not-working-on-PX4... it was more a matter of "not working at all"!  The code was never adjusted for the frontend/backend split.

Support for APM2 should work.  Sadly, I don't have one to test it on.  Could the change you're looking at be explained by tridge's explanation on that other PR?

Ta!

**Comment by peterbarker** [comment]
.... and I've now sorted make.inc - ta.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
