### PR TITLE
mk: update oreoled.bin

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Any description on what changed?

**Comment by jschall** [comment]
https://github.com/3drobotics/oreo-led/releases
This would be v1.4. v1.5 should go in soon.

**Comment by lucasdemarchi** [comment]
Humn... is that repository not open? I can't access it.  Having a note on the commit message about the version we are using would be good.

**Comment by jschall** [comment]
Uggh, you're right, let me talk to people and get it opened.

**Comment by jschall** [comment]
closing pending #3478

**Pull request closed without merging**
