### PR TITLE
Waf: support Clang

### PR DESCRIPTION
**Pull request by OXINARF**
Following the initial work of @8W9aG and with the precious help from @lucasdemarchi I've made compilation with Clang in Waf possible, not only for native targets but also for cross-compilation.

To use Clang you have two options:
- define the environment variables CC and CXX
- use the flags _--check-c-compiler=clang_ and _--check-cxx-compiler=clang++_ in the configure stage of Waf

The flags take priority over the env vars. These can also be used for GCC but Waf will default to that.

For cross-compiling you need to have:
- somewhere in the system, the GCC toolchain for the board to be build
- have the bin folder of that toolchain in the PATH environment variable

This has only been tested with a specially modified sitltest target in Travis (https://travis-ci.org/OXINARF/ardupilot/builds/114686931), so testing in actual boards is really needed.

I haven't worked much with Python and, although I've been watching the development of the Waf build system here in Ardupilot, I know very very little about Waf. Because of that, input from @guludo is really requested here. Specifically:
- I don't quite like the way of detecting the compiler at the board configure_env but the compiler is only detected after that, so I couldn't see how to do it in another way. I though of changing the order but I'm not sure if that's possible
- the function to help detect the toolchain path isn't bullet proof (for example, a double symlink wouldn't work) but I felt the work to do that would be too high for the reward

Ccache for Clang isn't setup in CI at the moment because it wasn't working properly with it - I'll leave that for future work.

**Clang 3.4.2, at least, is needed, but this was only tested with version 3.7**

### CODE REVIEW

**Comment by guludo** [comment]
Hi @OXINARF, I added some comments above.

**Comment by guludo** [comment]
Btw, thanks for your work on adding support for clang on waf :-)

**Comment by OXINARF** [comment]
@guludo Thanks for your comments. I've responded to them and will start reworking this once you have addressed some of my comments.
It was great working in it and making my first PR to Ardupilot :)

**Comment by guludo** [comment]
@OXINARF thanks, I'll take a look at your response as soon as I can. When sending a new version, I'd recommend either creating a v2 PR (in a v2 branch for example) or pointing the hash to the previous reference of the branch (if using `push -f`). I'm asking that so that we can keep a history of the PR. I'd prefer the first suggestion.

**Comment by guludo** [comment]
@OXINARF @lucasdemarchi 

After reading the current master and this branch I've come to some conclusions:

- Yes, if I don't have g++ but I do have clang, the configuration fails. That is happening because I implemented `toolchain` thinking of g++ (the prefixes) and didn't consider clang. Thus, that is my fault! Sorry...
- I'm not sure if there's an elegant way to fix that, since, as @OXINARF stated previously, Waf doesn't offer builtin support for cross-compilation. A way (again not elegant) I can think of solving that is to detect which compiler would be used ahead of compiler_{c,cxx} for the case of cross-compilation. An approach similar to what @OXINARF is already doing, but with some differences:
   - Use `cfg.environ.get('CXX', '') or cfg.options.check_cxx_compiler or default_compilers()` and loop over it. If 'g++', then add the prefix and do the necessary checks. If 'clang' then do the necessary checks. The first one that pass the checks is selected and the configuration specific for that compiler is done.
   - Do something similar with `CC`.

**Comment by guludo** [comment]
> Use c`fg.environ.get('CXX', '') or cfg.options.check_cxx_compiler or default_compilers()` and loop over it.

Hm, in the calse of `cfg.environ.get('CXX', '')`, we shouldn't iterate :-)

**Comment by lucasdemarchi** [comment]
@guludo I think we should first check what is done for cross-compilation on other build systems:

 1. autotools
 1. cmake
 1. other waf projects
 1. kernel

Of course this can be fixed up on top and I don't mind maintaining the way it is now for a while.

**Comment by OXINARF** [comment]
@guludo I like the option to iterate but to please @lucasdemarchi we shouldn't check CC/CXX env vars. I think Lucas wants that we assume that if the user is setting those vars they know what they are doing - but that means they need to be aware if a board is cross-compiling or not...

@lucasdemarchi I checked autotools and CMake. CMake clearly doesn't know how to how find the toolchain (https://cmake.org/Wiki/CMake_Cross_Compiling) and it depends on the build system to tell him what compiler to use, etc. That's exactly what we are doing with Waf. They do respect CC/CXX but the build system can enforce it (CMAKE_FORCE_C_COMPILER). Actually they say: 

> If your compiler is not able to build a simple program by default without special flags or files (e.g. linker scripts or memory layout files), the toolchain file as shown above doesn't work. Then you have to force the compiler

Clang does need special flags...

Regarding autotools, it can find the toolchain but it relies on the GCC scheme (_prefix_-_compiler_). I found on the source code (sorry but I lost the link and haven't search again) that it gives a warning if you give the flag host (which is actually the target system) and CC/CXX isn't in that scheme because it may not be able to find the toolchain.

**Comment by lucasdemarchi** [comment]
@OXINARF could you rebase this PR on master? Are you still waiting for any reply from me or @guludo ?

**Comment by OXINARF** [comment]
@lucasdemarchi I will be working on this today. The only answer I'm still waiting is regarding the PATH/mavproxy commit (https://github.com/diydrones/ardupilot/pull/3722#commitcomment-16595273)

**Comment by lucasdemarchi** [comment]
> No, they are not related, I just though that the mavproxy change was small enough to not warrant a different commit. I can split if you think it's best.
> Regarding the change to mavproxy, it is not needed for Clang support - it was an initial change because it was needed at the time, but not now.

If they are not needed I'd say to remove it and we can open another PR for that.

> The reason I included it is because I think we should try to migrate to Travis container-builds - and that can't have sudo. Obviously this can be included at any later time.

As odd as it sounds, it didn't give any advantage wrt to speed. We were using the container builds some time ago and switched back to the VM infra. See https://github.com/diydrones/ardupilot/commit/921da676db659714ec2daa725c6a36a3d402fba6

**Comment by OXINARF** [comment]
@lucasdemarchi According to Travis it should be faster to boot (the compile time should be about the same, 1.5 cores vs 2 cores won't make much of a diference). Also it allows to use cache. But it doesn't matter for this PR, so I'll remove the mavproxy part and use it in my future tests with the container-based builds.

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi According to Travis it should be faster to boot (the compile time should be about the same, 1.5 cores vs 2 cores won't make much of a diference). Also it allows to use cache. But it doesn't matter for this PR, so I'll remove the mavproxy part and use it in my future tests with the container-based builds.

yep... we can always try again... We were using container with caches. But it was taking so long to save the caches that it was faster not to use it and timing the complete build with VM vs container was not giving the promised speedup.

The slowness of travis was one of the reasons to add semaphoreci (besides the redundancy we get).  The thing I like about semaphoreci is that it starts the build much faster than travis... maybe because  it's newer and it's still not overloaded.

**Comment by OXINARF** [comment]
@guludo When you wrote

> Use cfg.environ.get('CXX', '') or cfg.options.check_cxx_compiler or default_compilers() and loop over it. If 'g++', then add the prefix and do the necessary checks. If 'clang' then do the necessary checks. The first one that pass the checks is selected and the configuration specific for that compiler is done.

What you mean by doing the necessary checks is basically doing what the compiler_c/cxx does when searching for a compiler right?

**Comment by OXINARF** [comment]
Replaced by #3765

**Comment by guludo** [comment]
> What you mean by doing the necessary checks is basically doing what the compiler_c/cxx does when searching for a compiler right?

@OXINARF 

This is what I have in mind:
  - If we are using native toolchain, then we basically bypass the toolchain configuration.
  - If not:
      - For each of the compilers in the list:
          - If the compiler is clang:
              - We try to find it in the same fashion as waf does (yes, I know this is ugly). If found, we make the checks you wrote in this PR and add the flags.
          - If the compiler is a gnu compiler:
              - We first add the prefix and try to find it in the same fashion as waf does (again, yes, I know this is ugly).
          - Unfortunately, other compilers would be unsupported for cross-compilation.

In this process, if we need to change the environment in order to make the tests we can use [`env.stash()`](https://waf.io/apidocs/ConfigSet.html?highlight=configset#waflib.ConfigSet.ConfigSet.stash) and `env.revert()` to set values transactionally.

**Comment by guludo** [comment]
@OXINARF You closed this PR when I was just about to finish my last comment hahahahaha

**Comment by OXINARF** [comment]
@guludo Eheheh what a timing! I tried the way you are proposing and I ended up ditching it because it indeed wasn't pretty. I think I've achieved the best way but we should discuss that in the new PR.

**Pull request closed without merging**
