### PR TITLE
Plane: Reverse Thrust Steep Landing - REQUEST FOR COMMENT

### PR DESCRIPTION
**Pull request by magicrub**
This is a REQUEST FOR COMMENT for a plane based steep landing approach utilizing an electric motor with reverse thrust.

This is a cleaned-up branch from the work done by Daniel Cironi at Event38 who posted his work on DIYDrones here:
http://diydrones.com/profiles/blogs/instructions-for-using-the-event-38-reverse-throttle-feature-on

landingsequence

There are still a few things I'd like to see changed but want a few more eyes on the code via this Pull-Request too. There are some changes that go beyond reverse thrust for landing that are in here. Some are not very easy to remove so I'm on the fence with regard to splitting this up into several PRs or just fixing this monster. Would be nice to sneak this into Plane v3.5.0 but I'm afraid there's just too much changing and I'd like to get the v3.5 release out sooner rather than leter. Please comment on that.

Please read this wiki before continuing: (keep in mind some of the param names may have been tweaked). The same wiki content is also pending in plane.arduplane.com.
http://droneyard.com/knowledgebase/e386-auto-landing-with-reverse-throttle/

Key changes:
- created new libraries/AP_LAND and moved all LAND_* params to it.
- added a ton of new params (see the wiki)
- added 3 new flight stages: TAKEOFF_WAIT, LAND_APPROACH_STEEP, LAND_FINAL_STEEP
- compensate the throttle for a low battery. As battery voltage drops, delivered thrust scales down. This ensures a, for example, 50% throttle request will produce a reliable thrust at the beginning, middle and end of a long flight. (new PR?)

Potential TODO items:
- remove param LAND_SLOPE and have it computed from the mission
- combine params LAND_THR_PWM and LAND_REV_ON_GND
- try and remove the need to dictate params TECS_A_PIT_MIN and TECS_A_PIT_MAX
- ensure auto-takeoff is safe. There is some code that enabled the motor, all launch types need to be considered.(new PR?)
- decision of when to use stages APPROACH vs APPROACH_STEEP depend on mission, should also consider if reverse thrust will be needed. Not sure how yet.
- some rangefinder code needs to be removed, makes some assumptions on hardware selection.

### CODE REVIEW

**Comment by magicrub** [comment]
Rangefinder code had been removed and flight stage decision is now better.

**Comment by rmackay9** [comment]
Re the compensation for low battery.  Copter has this as well so maybe we could generalize and move i somewhere where we can share it.

**Comment by JamesMasterman** [comment]
Really great work on this. I have one comment  - when transitioning from forward to reverse throttle you should probably ramp up to the desired PWM over about 1 second. If the throttle is going forward fast, putting it straight into reverse could damage the motor or even loosen the prop. I found this with my own reversing code. Maybe you already do this, but I couldn't see it in calculate_approach_throttle.

**Comment by magicrub** [comment]
great observation @JamesMasterman . For this type of application it would probably be a good idea to add a very slow filter to the throttle, perhaps 2 seconds. Approach stage only, not the flare. I can't think of any good reason for it to be agile.

**Comment by iskess** [comment]
Can anyone recommend a good ESC to experiment with this? Are you guys just using RC car ESCs?

**Comment by magicrub** [comment]
@iskess From the diydrones post linked to at the top of the PR:
"We tried a few different ESCs before settling on the Mamba Max Pro. It seemed to work the best for consistent throttle response and the software to adjust the settings was useful and easy to use."

**Comment by JamesMasterman** [comment]
Also most of the blheli ESCs support bidirectional mode. Using blheli suite you can set the midpoint and endpoints. I'm using a cheap rctimer 40a slim.

**Comment by iskess** [comment]
@JamesMasterman 
Would you mind explaining a little better how you set up the BLheli firmware for bi-directional use? I assume you use the BLheli suite to set the throttle end points. How do you define when the throttle is below zero, and motor reversing should begin? Does this create any conflict with the APM throttle failsafe? Thank you for your time.

**Comment by JamesMasterman** [comment]
@iskess using blheli suite, set the direction slider to bidirectional. Then set the Min, Max and centre ppm throttle boxes. I used 1000 for min, 2000 for max and 1150 for centre. You want the reverse side to have the smallest range as resolution is less critical. I think the range just affects resolution, not the power. My ESC can go as low as 900 on the reverse side.

Once you have this working, be very careful how you set up throttle in the autopilot. You want throttle min to be the centre point (1150 in my example). Otherwise if the autopilot can get to the reverse range it could accidentally go into reverse during flight or during a failsafe.

To access the reverse range, that's where your new code comes in. You'll have to allow the user to specify a centre (I prefer neutral) point and the full reverse point.

I imagine the deadband varies by ESC, but in my case it seems to be around 70us wide. I haven't found a way to adjust it with blheli suite, but there may be a way.

**Comment by JamesMasterman** [comment]
Sorry, typo above, the deadband is around 40us wide (about 20us in each direction)

**Comment by iskess** [comment]
@jamesmasterman, thank you for the description on blheli bi-directional throttle. 

Is there a way to set this up to work in FBWA for hand flown approaches? The landing sites that need such radically steep descents are often not the safest  for experimenting with designing creative automatic landing approach paths.  In Manual mode, I could create a mix on the Taranis that reverses and lowers the throttle PWM while the momentary switch is held. Pull back on the "trainer switch" while throttle is at zero, then adding throttle stick sends reverse PWM in the lower range. That will take some fiddling but I'm sure it can be done. I'm not sure if FBWA will be any different than manual, or if it is limited to the throttle min as calibrated to zero. 

It would be nice to have some code to allow an easier setup for reverse thrust in FBWA. Maybe it will require another channel as a signal to reverse the throttle. If channel X is activated, and the throttle is at min, then throttle stick advancement sends inverted PWM below throttle min. If the throttle is not at min when channel X is activated, then the throttle behavior remains normal.

**Comment by JamesMasterman** [comment]
If you don't use auto throttle modes (RTL, Auto etc) then you can set the throttle as you described and use your Tx to control reverse. It's a good way to learn. However, I never figured out a way to allow this to work and still have auto modes behave correctly.

What would be great to see at the end of this is reverse also available through a channel switch so bursts of it can be applied in a manual landing. It would make the code applicable to a much wide range of users. 

For my reversing code, I have a switch on my Tx that I flick to get full reverse throttle. Turning it off restores the forward throttle stick. I just use it in bursts to slow down manual landings. I couldn't live without it now!

**Comment by magicrub** [comment]
closing. Lots of work is still needed on this and support from Event38 dried up. I'll be working on my own version this week which is much simpler..

**Pull request closed without merging**
