### PR TITLE
Added AP_RPM library

### PR DESCRIPTION
**Pull request by tridge**
This allows for logging of an RPM sensor. Currently only via AUX5 on Pixhawk, but hopefully with other backends in the future.
It has been flight tested and works well. Next step is to use this as part of closed loop throttle control for gas helis

### CODE REVIEW

**Comment by magicrub** [comment]
Later this week come in handy for canesc v1.6

**Comment by rmackay9** [comment]
I'm happy with this but the mavlink message only supports 1 rpm sensors.  Maybe that's fine, maybe the GCS doesn't need to know the RPM level of each motor but just wanted to point this out.

**Comment by magicrub** [comment]
I haven't read through this yet but it seems that since it goes through a backend that it should at least support the ability to have multiple copies of the class.

**Comment by tridge** [comment]
Hi Randy, this isn't really meant for ESCs. We have the ESCn messages for that in DF log. 
We could use the RPM message for ESCs if you like, but then we need 8 fields. Do we really want the GCS displaying the RPM of 8 motors for a octa? What would the user do with it?
The RPM for petrol motors and rotors on a heli is important information for a GCS, but I'm less convinced its useful on an electric multicopter

**Comment by rmackay9** [comment]
@Tridge, I think it's fine to send just 2 RPM values.
The GCS displays the PWM for each motor at the moment but once we're on smarter ESCs which accept an RPM input then it would make sense to show that RPM instead of a pwm value but it's not super critical and is almost definitely scope creep for this PR.

**Comment by tridge** [comment]
applied

**Pull request closed without merging**
