### PR TITLE
Plane: detect ground impacts for is_flying to speed up crash detection

### PR DESCRIPTION
**Pull request by magicrub**
Detect X-axis deceleration for probable ground impacts. Limit the max probability that we are flying so it can decay faster if we determine we aren't. This will not change the is_flying state, anything above 0.1 is "true", it just allows it to decay faster once we decide we aren't flying using the normal schemes.

### CODE REVIEW

**Comment by magicrub** [comment]
I've compared it against several logs for behavior but still have not flight tested although there isn't much risk to it. There's still a debounce timer in crash detection for the auto-disarm.

**Comment by WickedShell** [comment]
Looks reasonable to me.

Looking through my logs, I will see that a deep-stall  will cause the confidence to fall fast, but its more then arguable that that isn't flying anyways. Regardless of that it doesn't affect almost any other users, and as long as I leave crash_detection actions to off I won't ever see any negative effects from it.

**Comment by magicrub** [comment]
Thanks for the review, Michael!

Once we get stall detection implemented it will hold off any crash debounce
timers since there is a possibility of stall recovery. That will help in
your case.

**Comment by magicrub** [comment]
Thinking a bit more about this, it actually shouldn't effect you much at
all even right now. You take several seconds to "land" so all the same
crash detect logic will kick in, albeit a second or so earlier.

**Comment by WickedShell** [comment]
The time depends on the altitude its done from, typically its < 15 seconds
(more then 10 normally though). Under some weird circumstances we've spent
over a minute in a stall once. I'm not to worried about it, as I said this
is something most people will never see happen.

**Comment by magicrub** [comment]
Closing, I've merged this into a single PR that was related https://github.com/diydrones/ardupilot/pull/3196

**Pull request closed without merging**
