### PR TITLE
Add support for using SPI devices of the same type.

### PR DESCRIPTION
**Pull request by mirkix**
I am using my BBBMINI in dual MPU-9250 configuration. Until now, it is not possible to access the second MPU-9250 on the SPI bus with the device command. With this PR you can access more than one SPI device of the same type.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
This table is getting way too big, but the solutions looks fine for now.

**Comment by mirkix** [comment]
@lucasdemarchi Thanks for the review Lucas. What do you mean with "This table is getting too big..."?

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi Thanks for the review Lucas. What do you mean with "This table is getting way too big..."?

Just that we should revisit how we define the devices. This single table can't scale as we grow the number of supported boards and is a source of merge conflicts.  We plan to add support for runtime configuration INI files for things like this....  Anyway, I was just thinking out loud.

**Comment by lucasdemarchi** [comment]
@mirkix For easy fixes like this it's preferred to just squash the change on the corresponding commit. Here is the reviewed branch: https://github.com/lucasdemarchi/ardupilot/commits/review/2847

**Comment by mirkix** [comment]
@lucasdemarchi Thanks, never did that before. Agree with the INI files.

**Comment by mirkix** [comment]
@lucasdemarchi Get more and more familiar with Github.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
