### PR TITLE
AP_HAL_Linux:  RCInput_UDP minor fixes

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@zehortigoza please fix these "squash build fix XX". They should not be here.

**Comment by zehortigoza** [comment]
I will as soon as I can fix the build on Travis.

**Comment by zehortigoza** [comment]
Build fixed, sorry for the noise.

**Comment by tridge** [comment]
Hi Jose, the change to use PRIu64 will not work. We use an internal implementation of printf formatting (to give consistency across platforms). The change will remove the compiler warning but will break the code as the internal printf doesn't support that feature.
What we usually do for 64 bit printf is cast to (unsigned long long).

**Comment by lucasdemarchi** [comment]
@tridge why it won't work?  PRIu64 does nothing but to expand to "llu" or "lu" depending on the platform.

**Comment by lucasdemarchi** [comment]
I actually prefer to use PRIu64. It's a macro that expands to the right length modifier for printf so we don't need the cast. @tridge mind revisiting it?  Anyway, adding the reviewed label.

**Comment by zehortigoza** [comment]
For what I read on print_vprintf() is better keep with the 32bits format.

**Comment by tridge** [comment]
I thought it was a format specifier, not a macro. It indeed would work fine.
pushed to master

**Pull request closed without merging**
