### PR TITLE
Copter: add RTL_SPEED parameter

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
I really like the concept of RTL_SPEED, it's a needed feature.  As pointed out, some people may have a really low WP Speed used for specific mapping requirements, and then have an impossibly slow RTL from a long way away.

However, I don't really like the way this is implemented.  I assume it works... but it's hard to check.  It's actually making some existing spaghetti code just a little bit worse.  The problem is we have this function wp_nav.wp_and_spline_init() which already sets the speed based on normal WP Speed.  Then you're over-riding it.  It's not at all clear which speed is in force and when.

I would prefer if wp_and_spline_init was maybe improved to take a parameter for either speed or mode of the caller, and the have the speed set internally to that function.

Also, I don't like adding more parameters at vehicle level.  We should avoid that.  We could put this param in the WP_NAV object.  Then when calling wp_and_spline_init, the speed can be selected by that function based on the argument to the function.

**Comment by jschall** [comment]
I asked Randy if he wanted it reworked into some kind of profile system, where you could have a handful of configuration profiles for different modes. He said I should PR as-is.

**Comment by magicrub** [comment]
Is this missing the kparam value in parameters.h?

**Comment by jschall** [comment]
Nope, it has been reserved for this for months...

**Comment by rmackay9** [comment]
merged, thanks!
Note that I removed the 2nd set_speed_xy that constantly overwrote the speed so that only the one in the start_climb() is called.
I guess the reason that the 2nd set-speed was in there was because the solo companion computer might continue sending set-speed commands even though we're in RTL or perhaps a few set-speed commands will get through as the vehicle switches to RTL (i.e. race condition).

**Comment by jschall** [comment]
@rmackay9 so what's the solution here? Are we going to reject DO_SET_SPEED during RTL?

**Comment by jschall** [comment]
@rmackay9 and what if RTL_SPEED is changed during RTL?

**Comment by magicrub** [comment]
There was some talk today about RTL for plane. There are a few behaviors
that we want different for RTL and I wonder if maybe this is better done in
AP_RTL. Would that be of interest for copter?

**Pull request closed without merging**
