### PR TITLE
Warning related fixes

### PR DESCRIPTION
**Pull request by cmarcelo**
Two minor fixes related to warnings: picking the correct ones for SITL and removing an unused variable warning.

### CODE REVIEW

**Comment by magicrub** [comment]
Hi @cmarcelo,
Thanks for the pull request. Firstly, these are two unrelated things and should be separate pull requests since one is more likely than the other to be accepted.

Second, can you explain your commit a bit? Why do you want  the debug uncommented? When debugging you can just do that on your own build. Also, why loosen the compiler warnings? That seems counter-productive. An ultimate goal would be to make more errors to improve code quality

**Comment by magicrub** [comment]
As is, I vote to close this.

**Comment by cmarcelo** [comment]
@magicrub thanks for reviewing. There are explanations in the commit messages, but I'll explain them here to make it clearer. By your comments I probably wasn't very clear on those messages :-(

The first patch is about fixing a typo when warnings were added to the list. In a Makefile, for multiline lists you need to used `\` to continue a line. That line in the middle was missing it and the other warnings were removed. On top of that, the same flag appears again later, so it's fine to simply remove it. Maybe I misunderstood your concern.

As for the second patch, one alternative would simply removing the unused / commented code. I assumed that those debugging messages were a convenience for the developer, and I myself found it useful how the assignments documented the data being received.

So I wrapped the debug code and the variables (unused in non debug) inside the already existing local define for debugging. That way, if one want to debug, just one place needs to change (turning the flag on), instead of multiple (turning the flag on + uncommenting the Debug()). We get for free a way to remove the warning from non-debug builds. The patch also fixes the commented code, which wasn't really functioning.

**Comment by magicrub** [comment]
My apologies. I see your notes in the commit messages now. The debug makes
sense now that it's using a #define and I didn't notice you were removing a
redundant Werror. These are two good commits.

**Comment by cmarcelo** [comment]
OK, no problem :-)

**Comment by rmackay9** [comment]
merged based on my and @magicrub's review

**Pull request closed without merging**
