### PR TITLE
AP_Baro: Add support to MS5637

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by jberaud** [comment]
Ok for me.

**Comment by tridge** [comment]
Hi Jose, can you explain the 15C comment changes? The code seems to use a 20C threshold throughout, including in the places where your patches change the comments to 15C. Is the MS5637 supposed to use a 15C threshold? If so, can you check the calculations, as it looks like a 20C threshold to me.

**Comment by zehortigoza** [comment]
@tridge Yes, the code of the 3 sensors handles the compensation for temperatures below 20 C but the datasheet have another compensation for temperatures below -15 C, what I have changed was the temperature on the comment saying that the second compensation was not implemented in each sensor.

You can see it here:
http://www.meas-spec.com/downloads/MS5637-02BA03.pdf page 7
http://www.meas-spec.com/downloads/MS5611-01BA03.pdf page 8
http://www.meas-spec.com/downloads/MS5607-02BA03.pdf page 8

**Comment by tridge** [comment]
ok, thanks for the explaination, applied!

**Pull request closed without merging**
