### PR TITLE
RCInput - Navio

### PR DESCRIPTION
**Pull request by dgrat**
Corrected build errors because of pointer to int conversions,
related to a lose in precision (on some platforms).
It means the current implementation will fail on 64 bit systems.

  * Update 1: Replaced signed ptr types with unsigned ptr types
  * Update 2: 
    * Removed two warnings 
    * Removed a problem with the double output of the RPi version number (and redundant code)
    * Added some safety checks in GPIO

Signed-off-by: dgrat <dgdanielf@gmail.com>

### CODE REVIEW

**Comment by dgrat** [comment]
Well, I just got a build error when testing my cmake files.
Beside to this you are right, the RPi is just 32, but it is not entirely correct atm. 
Look at it, as if it is a code clean-up :)

**Comment by dgrat** [comment]
@lucasdemarchi @staroselskii 
Hi Lucas and Georgii,
I added some additional changes via two commits, maybe you can have a look at it. 
In the Emlid forum people wondered about double output of the version number of the RPi.

**Comment by lucasdemarchi** [comment]
> Beside to this you are right, the RPi is just 32, but the code might be more general for upcoming systems.
> Look at it, as if it is a code clean-up :)

doesn't hurt, but this is very board-specific and shouldn't be used in other/new systems. This pokes the system memory via /dev/mem and is only usable for RPi.

**Comment by dgrat** [comment]
Hi Lucas, 
Thanks for discussion. 

> You are getting build errors probably because you are not honoring such checks.

You are right I was not honoring the flags :) 
Building under 64 bit conditions with Flags set lead to build errors. 

> why not an initializer list or in the declaration with c++11?

Are they necessary there? If not forced, I admit, I don't use init-list. 

> Fixed two compiler warnings

I think it was 8 bit 16 bit int conversion.

**Comment by staroselskii** [comment]
@dgrat 

I'd been thinking that it might've been better to move the version detection to ```Util```. I'd actually done that but forgotten to make a PR. Thanks for your fix. 

The RCInput rework itself won't hurt but won't gain us much, either. I don't think it'll ever be run on an another board. 

I also suggest to make meaningful names for commits! 

Sorry, it's taken me so long to reply!

**Comment by dgrat** [comment]
So util or GPIO? 
I guess, Util would fit better to the name.

**Comment by staroselskii** [comment]
@dgrat 
Awesome, Daniel, thanks! I also think that it'd be better to make a subclass like ```Util_Navio``` in order not to bloat the interface for other boards, wouldn't it? Other than that everything seems to be fine. 

I've also seen that the previous commits for Linux had had commit message in the slightly other form. Namely, "AP_HAL_Linux: <the commit description>". I think we should stick to the convention.

**Comment by dgrat** [comment]
@staroselskii 
Okay, applied. 
However, I think that the name spacing and class naming in AP_HAL is semi optimal. 
Linux::Linux* ..

**Comment by lucasdemarchi** [comment]
> However, I think that the name spacing and class naming in AP_HAL is semi optimal. 
> Linux::Linux* ..
> I sticked to the current system and called it LinuxUtilNavio :)

yep, agreed.

**Comment by lucasdemarchi** [comment]
@staroselskii are you ok with the commits?

**Comment by dgrat** [comment]
@lucasdemarchi 
In case the patch gets accepted. 
What do you think about making a small commit removing the Linux* Prefix.
I think the namespace is sufficient and totally fine :)

**Comment by CodeChief** [comment]
+1 on proactively refactoring/cleaning-up the naming.

**Comment by lucasdemarchi** [comment]
I went ahead, rebased the commit and reworded the commit messages as I had asked previously.
https://github.com/lucasdemarchi/ardupilot/tree/review/pr-2698

Some additional changes:
 - Remove trailing whitespaces
 - Follow code convention wrt member names
 - Only navio will build the UtilNavio.cpp file, because it doesn't make sense for other boards
 - Use static cast instead of dynamic_cast. We are not checking the return value so dynamic_cast doesn't help here.

**Comment by dgrat** [comment]
Hi @lucasdemarchi,
thanks for the changes. 

Best, Daniel

**Comment by tridge** [comment]
hi Lucas, the review/pr-2698 branch needs another rebase

**Comment by dgrat** [comment]
@tridge I rebased

**Comment by lucasdemarchi** [comment]
@dgrat could you rather rebase the reviewed branch?

**Comment by dgrat** [comment]
@lucasdemarchi one moment

**Comment by lucasdemarchi** [comment]
Updated version in https://github.com/diydrones/ardupilot/pull/2887

**Pull request closed without merging**
