### PR TITLE
Plane, Copter, Rover: Adding RSSI library to allow for PWM channel value RSSI (and other future methods)

### PR DESCRIPTION
**Pull request by StewLG**
Adding ability and controlling parameters for reading RSSI value from a PWM channel value. This is a feature supported by various radio receivers such as those running OpenLRSng, EzUHF, etc.

Making a new library AP_RSSI to be a uniform place to call read_receiver_rssi. Retains ability to read analog pin for RSSI values, improves flexibility of relevant ranging a bit. Adds ability to read RSSI from a particular channel's PWM channel value.

* RSSI_TYPE: The kind of RSSI to use. Starting set is Disabled, AnalogPin, and RCChannelPwmValue. More can be added readily.
* RSSI_ANA_PIN: This selects an analog pin where the receiver RSSI voltage will be read.        
* RSSI_PIN_LOW: Receiver RSSI voltage low (weak) value.
* RSSI_PIN_HIGH: Receiver RSSI voltage high (strong) value        
* RSSI_CHANNEL: The channel number where RSSI will be output by the radio receiver.
* RSSI_CHAN_LOW: This is the PPM value that the radio receiver will put on the RSSI_CHANNEL when the signal strength is the weakest. Since some radio receivers put out inverted values from what you might otherwise expect, this isn't necessarily a lower value than RSSI_CHAN_HIGH.
* RSSI_CHAN_HIGH: This is the PPM value that the radio receiver will put on the RSSI_CHANNEL when the signal strength is the strongest. Since some radio receivers put out inverted values from what you might otherwise expect, this isn't necessarily a higher value than RSSI_CHAN_LOW.
    
Previous RSSI parameters have been all deprecated in favor of these new ones, and they all have new names. Users will need to re-configure RSSI in order to use these new ones.

Tested on Plane, Copter, and Rover.

Continuation of work started on PR #2731. See also #2721; this PR anticipates the development of other RSSI methods.

### CODE REVIEW

**Comment by tridge** [comment]
I've had a quick look over this and think it looks good. I will do a more detailed review and testing soon.
Many thanks for putting this together!

**Comment by rmackay9** [comment]
The only thing I can see that may need fixing is the use of "int" instead of "int16_t".

**Comment by StewLG** [comment]
Let me know if you want me to change the ints (or anything else). I assume I'd resubmit?

**Comment by rmackay9** [comment]
@StewLG, no need to resubmit even if we want that change (let's hear what Tridge says about it).  All you need to do it put in another commit or force push a fix.

**Comment by tridge** [comment]
Just a few small things:
- the @Values list should be omitted for the voltages I think, so users get a float entry box instead of a drop-down list in the GCS UI. A sensible @Increment should be listed as well (perhaps 0.01 ?), along with an @Range. The GCS should then give a good input box.
- I don't think channels 1 to 4 should be listed in @Values for RSSI_CHANNEL, as they are reserved for pilot input
- the scaling is a bit complicated. I think it should internally work as float in 0.0 to 1.0 range, and then offset a rssi.read_rssi_uint8() interface which just multiplies by 255. The uint8 rssi range is really just an artifact of a particular mavlink API, and I think we'll have other users of the API that would prefer a 0 to 1 float. That should simplify the code a bit too

Thanks!

**Comment by StewLG** [comment]
I have made the requested changes and resubmitted as  #2770.

**Pull request closed without merging**
