### PR TITLE
AP_HAL_Linux: AnalogIIO: Clean up code, add scaling to constructor, enable IIO for BBBMINI V2

### PR DESCRIPTION
**Pull request by mirkix**
Rework of #3550 

* Clean up code
* Add voltage scaling to constructor
* Enable AnalogIIO for BBBMINI
* Add default values for BBBMINI

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
LGTM. @vmayoral could you double check it continues to work on PXF/erleboard?

**Comment by LanderU** [comment]
Hi @mirkix  and @lucasdemarchi,

this is Lander from Erle Robotics.

I've checked in Erle-Brain v1.1 (with PXF) and working properly.

**Comment by lucasdemarchi** [comment]
@LanderU thanks

**Comment by mirkix** [comment]
@lucasdemarchi Thanks Lucas. PR can be closed now?

**Comment by lucasdemarchi** [comment]
Yes, I forgot to close it. Applied, thanks.

**Pull request closed without merging**
