### PR TITLE
RCInput for Navio:

### PR DESCRIPTION
**Pull request by dgrat**
I tried to: 
  - reduce redundancy
  - safety
  - performance
  - readability

Best, Daniel

Signed-off-by: Daniel Frenzel <dgdanielf@gmail.com>

### CODE REVIEW

**Comment by dgrat** [comment]
Was not testing on vehicle so far, but changes are rather simple, should work.
I also made a note. I think it might be possible to avoid a loop by taking care about memory layout.

**Comment by tridge** [comment]
hi Daniel, the build of this change is failing

**Comment by dgrat** [comment]
"make linux" is working

**Comment by ivereninov** [comment]
@dgrat  If you can fix the build we are ready to test your changes.

**Comment by dgrat** [comment]
@ivereninov 
I hope, I made no bigger mistake :)

**Comment by vlad-zakharov** [comment]
@dgrat Hi, thanks for your work. I just tested your code and it seems to be working grate.

**Comment by tridge** [comment]
Thanks Daniel!
I've assigned this to Clouded at the moment, will re-assign to Georgii once he accepts the github issues list invite.
I'd like patches to subsystems where we have a maintainer listed in the maintainer file to be acked by the maintainer, which is Georgii in this case

**Comment by staroselskii** [comment]
@tridge 

Everything seems to be fine. Thanks.

**Comment by tridge** [comment]
applied, thanks!
(with small commit msg change to match style)

**Pull request closed without merging**
