### PR TITLE
Copter: Fix issue with rotor deglitch filter not being static

### PR DESCRIPTION
**Pull request by fhedberg**

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
Hi, what are the implications of this?

**Comment by magicrub** [comment]
Don't you mean problem with it being static instead of not static since you
are removing the static. What is the problem you are trying to fix?

**Comment by fhedberg** [comment]
@R-Lefebvre @magicrub After the pde to cpp conversion, heli-builds doens't link for me as the deglitch filter is defined in the header and ends up in every object file. As the filter isn's really used anywhere else, I figured this was a way to fix it. Not sure why this wasn't an error before however. Or am I misunderstanding something?

**Comment by magicrub** [comment]
Yeah, in the new cpp format the static should be removed. Surprised this
passed travis and Tridge's eyes.

**Comment by magicrub** [comment]
+1

**Comment by fhedberg** [comment]
Closing as @tridge fixed this in https://github.com/diydrones/ardupilot/commit/e5e21ddcceb808d85e4c3d97ecba060f51479469

**Pull request closed without merging**
