### PR TITLE
DataFlash and ArduPlane: Log landing variables

### PR DESCRIPTION
**Pull request by magicrub**
When performing a LAND waypoint in mode AUTO, lots of local variables are calculated in real-time to maintain a desired decent profile. These are now logged as LND1 and LND2. There were so many params that it had to be broken into two log entries due to a 64char limit. However, only a single bit of the mask is needed 1<<17 (131072, 0x0002FFFF) to generate both log entries. The two log entries look like so:

LND1
    int32_t land_bearing_cd;
    float sink_rate;
    float sink_time;
    float sink_height;
    float total_distance;

LND2
    float aim_height;
    float flare_time;
    float flare_distance;
    float land_slope;
    int32_t land_wp_alt;
    int32_t target_altitude_offset_cm;
    float land_proportion;

### CODE REVIEW

**Comment by magicrub** [comment]
Some of these variables are not very useful to look at, I can probably reduce this down to a single log entry named LAND

**Comment by magicrub** [comment]
@tridge , please advise

**Comment by magicrub** [comment]
I'm tempted to close this PR. I stopped using it on my own fork because it's not as useful as I thought it would be. What do you think @tridge

**Comment by gmorph** [comment]
Hi Tom.  You are the person most likely to need this functionality so I'd suggest if you have stopped using it then others probably won't find it very useful either.  I suggest you close it.  Thanks.

**Comment by magicrub** [comment]
It's not that I've stopped using it forever, I'm just finding that when powering on the lidar in mid-flight that I occasionally get a shorter range like 15m and, rarely, it doesn't boot up at all. I suspect it is a hardware bug in the lidar. I am investigating it.

**Comment by magicrub** [comment]
Whoops, my last comment was wrong - I thought we were talking about the lidar snooze PR. I'm OK closing this, it was @tridge that initially recommend I create it because he felt it had a good use. Let's get his vote before we close it. Either way it should get re-worked (and reduced) before it goes into master.

**Comment by magicrub** [comment]
This has sort of fizzled out, I log it on my fork but haven't cared to look at the data much beyond issue testing. Needs a re-think (and new PR/issue)

**Pull request closed without merging**
