### PR TITLE
AP_Notify: Added LAND_BEEP to ArduPlane for chirping after a land

### PR DESCRIPTION
**Pull request by magicrub**
When landing Arduplane in tall grass it is sometimes hard to find the aircraft. With this newly added LAND_BEEP set to 1 (enable) it will make a chirp sound once per second.

### CODE REVIEW

**Comment by tridge** [comment]
nice idea!
I think we need a way for the beeping to stop though. Maybe on mode change?

**Comment by magicrub** [comment]
I considered that but decided not to because if you have a crash while in auto you should immediately go to manual/stab with throttle down to ensure the motor is off. Hence, crash detection and auto-disarm is a handy thing to have!

**Comment by magicrub** [comment]
However @tridge , I suppose we could build disable-beep methods into LAND_BEEP instead of just boolean. 0: disabled, 1:enabled with reboot or another flight or mission reset to mute, 2: enabled and flight mode change to mute. Sounds like an enum without an AP_Land home!

**Comment by rmackay9** [comment]
FYI, we have a similar request on copter. https://github.com/diydrones/ardupilot/issues/1023

I'm not a plane user but for copter, personally I would rather mavlink-enable the beeper so that a ground station can make it play a tune whenever the user wants.  So the user can push a button on a tablet (or whatever GCS) to invoke a sound.

**Comment by magicrub** [comment]
I see a new mavlink command to trigger this being a separate feature. Basically, that's a noise-maker button. Can be triggered on/off at any time to trigger presumably any sound we wanted. However, I surely welcome a MAVLink msg to (at least) turn off the beep. It would be yet another way to avoid annoying beeps while keeping the aircraft powered after a flight

**Comment by magicrub** [comment]
after some thought I decided to go ahead and add an enum to multiple LAND_BEEP modes:
enum LandingBeepMode {
    DISABLED,
    ENABLED,
    ENABLED_MUTE_VIA_MODE_CHANGE,
};

this will need some memory added to ap_notify

**Comment by magicrub** [comment]
I've updated this to use 4 modes, an "always on" to test with soyou know what sound to listen for
0:Off,1:On,2:On_After_Land,3:On_After_Land_MuteViaModeChange

I rebased and then it merged back onto itself. I may need a little help to clean that up but it is otherwise ready to be merged.

**Pull request closed without merging**
