### PR TITLE
Added brackets on line 545,552

### PR DESCRIPTION
**Pull request by ashwinvasudevan**
Syntax errors on line 545,552. Added brackets.

### CODE REVIEW

**Comment by rmackay9** [comment]
merged!  nice catch!

**Comment by lucasdemarchi** [comment]
@ashwinvasudevan thanks and sorry for introducing this bug. It's not used by any board so this is why my build tests didn't catch it.  What board are you using?

**Comment by ashwinvasudevan** [comment]
@lucasdemarchi  I am using the Beaglebone black. I wanted to understand Ardupilot and contribute to the code and hence I bought a cheap ADXL345 sensor and try to build for it.

**Comment by lucasdemarchi** [comment]
@ashwinvasudevan ok, thanks.  Just make sure you read the comment in the top of the file to support L3G4200D:

```
  This is an INS driver for the combination L3G4200D gyro and ADXL345 accelerometer.
  This combination is available as a cheap 10DOF sensor on ebay

  This sensor driver is an example only - it should not be used in any
  serious autopilot as the latencies on I2C prevent good timing at
  high sample rates. It is useful when doing an initial port of
  ardupilot to a board where only I2C is available, and a cheap sensor
  can be used.
```

We flew with it with a minnowboard max ~1 year ago. So it can be done.  Main problem with this is actually that you are putting all the sensors in a single I2C bus (besides the mag not being that good). I2C has very little bandwidth for handling all of that.

**Comment by ashwinvasudevan** [comment]
@lucasdemarchi Yes, I am just using it for testing until my IMU and Baro arrives for the BBBmini. 
Thank you for the brief explanation.

**Pull request closed without merging**
