### PR TITLE
AC_WPNav: stop gradually in loiter

### PR DESCRIPTION
**Pull request by jschall**
addresses #3025

### CODE REVIEW

**Comment by rmackay9** [comment]
@jschall, so it already stops gradually in loiter so there must be some edge case which we're not handling quite right.  Can you describe the case where this change helps?

**Comment by jschall** [comment]
No, it is a fundamental problem with the minimum acceleration. It steps to 0 when the copter comes to a stop.

**Comment by rmackay9** [comment]
After discussing on the dev call it seems the best way to reproduce the issue is something like:
1. set the WPNAV_LOIT_MINA to be higher than default (like 250)
2. speed the vehicle up and then let it slow down towards zero.  As the vehicle slows to near zero it will suddenly stop (leading to a twitch)?
This change smoothes the stop.

**Comment by R-Lefebvre** [comment]
It's not a twitch, really.  It's that the desired acceleration changes from 250 m/s/s at one instant, to 0 at the next instant.  So the required tilt angle for the deceleration goes from ~12 deg to 0 deg in 0.0025mSec which is not possible.  So there is a quick snap from 12deg to 0deg.  Also, the copter usually "bounces" off it's desired target position since it's can't actually move that fast.  The Loiter controller then tries to fix this position error, so there's usually a little bounce.

**Comment by jschall** [comment]
ping

**Comment by rmackay9** [comment]
yes, this is top of my list now.

**Comment by lthall** [comment]
Hi all,
The problem here is WPNAV_LOIT_MINA has been set to large in an attempt to provide a braking effect. This variable shouldn't be set larger than would cause a 3 degree roll or pitch, ie 50. The purpose of this variable is to provide very subtle feedback to the pilot to show the copter has come to a complete halt. At 25 it is barely noticeable, at 50 it is obvious if you know what you are looking at. Both provide a positive reassuring communication back to the pilot.

This patch attempts to add breaking to loiter and in doing so introduces a significant angle discontinuity if the sticks are returned to centre when the additional braking angle doesn't exceed the maximum angle of the copter. If the acceleration is limited by the lean angle then I suspect there will be a velocity error build up.

We may be able to add a function like this into loiter but people must understand that any breaking like this will result in a large discontinuity when ever the sticks go to zero and also damage low speed positioning.

The other option we may consider is changing the drag curve. Real drag is A.v^2, we use A.v to make the breaking more pronounced at low speeds. We could also consider something like A.x^(1/2). But I would need to consider how the input would scale and feel to the pilot.

**Comment by R-Lefebvre** [comment]
I have not looked at this specific implementation.  But I strongly support any move in the direction of making Loiter stop faster, and better, when the sticks are released.  Loiter generally works really well for a positioning controller.  However, the low MinA setup that is common, makes it not work well for many applications where it could be useful.

If we could have accommodated people who wanted it to stop fast, we could have avoided the need for the creation of the Pos Hold flight mode.

Currently, I use Loiter with a high MinA, and like it very much.  I have never used PosHold, and don't plan to. My only problem with a high MinA Loiter, is the snap at the end when the controller goes from 250 m/s/s deceleration to 0.

**Comment by jschall** [comment]
Real drag is not A.v^2 - it depends on Reynolds number. The fact that linear drag seems to work best for loiter seems to suggest that linear drag is dominant on multicopters.

This patch fixes a significant discontinuity when the vehicle stops. It does not add any discontinuity - the discontinuity you are describing exists whether or not this patch is applied.

**Comment by jschall** [comment]
I strongly suspect that leonard may be misreading the code - leonard, note that the max() of 2 negative numbers is the number that is smaller in magnitude.

**Comment by rmackay9** [comment]
merged!

**Pull request closed without merging**
