### PR TITLE
AP_HAL_PX4: fix passing callback to member function

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Details on commit message.

### CODE REVIEW

**Comment by magicrub** [comment]
Thanks @lucasdemarchi

**Comment by lucasdemarchi** [comment]
and again travis is failing where it shouldn't

**Comment by lucasdemarchi** [comment]
@magicrub does this deserve a Reviewed flag? I had totally forgotten about this PR and was surprised to see these warnings today in a PX4 build.

**Comment by magicrub** [comment]
I have no idea what's going on with it, but sure. If the warnings are gone and your happy with it then I'm happy with it.

**Comment by lucasdemarchi** [comment]
@magicrub thanks, adding the Reviewed flag myself then.

**Comment by magicrub** [comment]
I already did

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
