### PR TITLE
AP_Math: Move simple math function implementations to header for better compile time optimization

### PR DESCRIPTION
**Pull request by walmis**
Functions like sq() are better moved to the header file as inline.
Compiler can then optimize these out when used in code, this saves cpu
cycles with stack push, pop during function calls.

Also it significantly reduced code size (Cortex-M3 build with NavEKF enabled)

Before:
```
 text	   data	    bss	    dec	    hex	
 450272	   3492	  28784	 482548	  75cf4
```
After:
```
text	   data	    bss	    dec	    hex	
410552	   3492	  28780	 442824	  6c1c8
```

### CODE REVIEW

**Comment by tridge** [comment]
unfortunately this makes the build 4k bigger on AVR2560, which takes it over the limit for plane on APM2
We may need some ifdefs for AVR

**Comment by magicrub** [comment]
Would Travis have caught that?

**Comment by tridge** [comment]
if we do add ifdefs, we should protocol use the inline fns for HAL_CPU_CLASS_150 and above (as that assumes hw floating point).
Would you be willing to rework this with the ifdefs?

**Comment by walmis** [comment]
I think we can safely inline these functions on non-AVR (32bit) hardware. I have commited an update which checks for AVR define and marks these functions with attribute((noinline)).

**Comment by tridge** [comment]
We'll need to have them in a .cpp file on CPUs without floating pt hardware. Otherwise the functions get duplicated when called from multiple contexts. The current PR adds 2k to flash on APM2. That is still too much (we are very close to the limit)
I'd also prefer to use  HAL_CPU_CLASS_75 as the conditional, as 75 and below are for CPUs without floating pt acceleration.

**Comment by gmorph** [comment]
Hi, Travis is fixed however this PR is not passing the Travis build.  Can you have a look please?
Interestingly its failing with a stack frame error inside the EKF which you haven't changed so somehow the inlining of the functions is increasing the amount of stack used.  Probably related to Tridge's observation above regarding the duplication of functions.

**Comment by magicrub** [comment]
Looks like Travis DID catch that :)

**Comment by walmis** [comment]
Okay, another shot at this. If HAL_CPU_CLASS is less than 75 then everything works the old way, else the functions are included as inline in the header file. Compiler will then automatically choose whether it's better to inline them or not. Since these are declared only with *inline* keyword, they should have external linkage, so non-inlined functions will have the same address in the whole program and not be duplicated.

**Comment by tridge** [comment]
hi again, we've now branched AVR support into master-AVR, so I'd now be happy to accept these changes without ifdefs, and gain the smaller flash size and better CPU performance for stm32 and better.
would you be able to rebase and update this PR ready for master?

**Comment by tridge** [comment]
i've applied this without the AVR specific changes now, as we no longer need AVR support for master
thanks for the patch!

**Pull request closed without merging**
