### PR TITLE
Tradheli onion pr

### PR DESCRIPTION
**Pull request by R-Lefebvre**

### CODE REVIEW

**Comment by magicrub** [comment]
That's a lot of commits!

**Comment by fhedberg** [comment]
:+1:

**Comment by lucasdemarchi** [comment]
> No description provided.

:(

**Comment by fhedberg** [comment]
The following summarize my changes, but I think it's better if @R-Lefebvre adds comments about the new RSC mode and the RSC state machine/output changes:

* Abstracts traditional helicopter code by moving the single rotor swash calculations and tail-rotor yaw control into AP_MotorsHeli_Single.
* Abstracts rotor control (run-up/ramp-up) into AP_MotorsHeli_RSC which is used both for main rotors and direct-drive variable pitch tail-rotors.

These two changes are prerequisites for adding support for new helicopter frames, which is provided separately in #1860.

**Comment by rmackay9** [comment]
In general it looks ok.  There are a lot of commits but they're nicely broken up into individual changes so each one is not too difficult to review.

I haven't checked every line looking for bugs but Rob's the TradHeli maintainer so I've just looked for C++ and style issues and trust Rob's done the necessary testing.

If you want to address those issues I've raised above then I'll pull into master

**Comment by R-Lefebvre** [comment]
re: AP_MOTORS_HELI_SINGLE  actually I was also slightly concerned about that.  Actually, found the name not descriptive enough. I just didn't want to change it as I concerned it would cause more merge conflicts for Frederick. 

But we should probably solve this now, as it will cause problems later. The problem is if we ever did code for a single rotor fixed pitch heli for example.

Instead of HELI_SINGLE, we called it SINGLE_ROTOR_COLLECTIVE_PITCH, or just SRCP for short?

Any other ideas?

**Comment by R-Lefebvre** [comment]
re: Number of commits.  I did that so I could keep things straight in my head as I went through it.  The only thing I could have done is merge them all into super-commits after the fact, and then what is the point of that?

**Comment by fhedberg** [comment]
@R-Lefebvre @rmackay9 Renaming it is totally fine with me, I was just out of good ideas ;)

I'm would vote for shorter alternatives in general, and preferably not any abbreviations... But I'll defer to you native speakers for some better options.

**Comment by rmackay9** [comment]
_Trad? _Traditional?

I agree with @fhedberg that SingleRotorCollectivePitch is too long and acronyms will be difficult to guess.

**Comment by fhedberg** [comment]
AP_MotorsHeli_Single also goes very nicely with AP_MotorsHeli_Dual (for tandem and transverse), but happy for suggestions on that one too.

**Comment by rmackay9** [comment]
There seems to be duplication of rotor control mode definitions:
ROTOR_CONTROL_MODE_DISABLED vs AP_MOTORS_HELI_RSC_MODE_DISABLED

**Comment by rmackay9** [comment]
I've taken a go at updating this branch to master and resolving the enum issue.
https://github.com/rmackay9/rmackay9-ardupilot/commits/rob-onion1

@R-Lefebvre, @fhedberg, can you have a look and confirm you're ok with these fixes?

**Comment by fhedberg** [comment]
@rmackay9 :+1:

**Comment by rmackay9** [comment]
Merged!
@fhedberg, @R-Lefebvre, it would be really good if you could thoroughly check that master is ok for all the various combinations of rotor control, tail-control, etc.

**Pull request closed without merging**
