### PR TITLE
Support BH HAT for ardupilot

### PR DESCRIPTION
**Pull request by onceme**
Hi maintainers of ardupilot, this is Aaron again.

As we talked in the [drone discuss loop](https://groups.google.com/forum/#!topic/drones-discuss/oE1alXaXNzM), this is the pull request I launched for the purpose of supporting BH HAT.

Please helping me take a look, thanks a lot.

Cheers,
Aaron

### CODE REVIEW

**Comment by tridge** [comment]
hi Aaron,
Generally looks good, thanks! Some issues though:
* I think we should use the make target "bhat" instead of "bh" due to the lame way we detect build types in our build system. We look for the substring, and if we use "bh" then it will preclude any future build targets with the letters "bh" in the name. Using "bhat" makes it a bit more unique.
* For coping with the two versions of the bhat, it may be better to just try to instantiate each of the sensor types. The HAL_INS_DEFAULT defines assume a single type, but you can just ignore that and instead just try detect() on each type in AP_InertialSensor.
* There is quite a lot of unnecessary whitespace changes in the patches. Not a major problem, but it does make merges a bit harder and the commits untidy. Have you tried using "git add -p" to avoid these side effects of editors?
* the RCInput_BH code doesn't seem right. It looks like you are trying to decode PPMSUM data inside RCInput_BH::_timer_tick(). Why not just pass all pulses to RCInput::_process_rc_pulse() ? That way you get PPMSUM, but also get SBUS and DSM for free.

Lucas de Marchi will also have to take a look

**Comment by fhedberg** [comment]
@onceme Also, looks like RCOutput_BH is just an old copy of RCOutput_PCA9685. Better to just use the existing implementation instead of adding a new one.

**Comment by lucasdemarchi** [comment]
My high level comments are mostly the same as the above. Just to emphasize:
 - There seems to be no difference in RCInput and RCOutput to deserve new classes.
 - RCInput_RPI can be used as is as far as I see.
 - RCOutput_PCA9685 needs a little bit of changing, but not that much. This is the one most of the Linux boards use.  Since you have an LED in the last channels you need to define a maximum number of channels to be used so you leave 3 for the LED. For the LED itself, see below
 - LED: I didn't check your hardware schematics (do we have them available?), but make sure you have a common cathode LED there, otherwise it will be default on when OE in PCA9685 is disabled. I know that because we did that very same mistake and for the first version of our [board](http://wiki.minnowboard.org/Drone_Lure) we ended up removing the LED.  Also I think we can leave this a little bit more generic so the LED actually reserves the channels on PCA9685 and hence we wouldn't need to limit the number of channels.  We implemented that some weeks ago, but didn't send to upstream since we temporarily removed the LED. I think @zehortigoza  still has the code for that. @zehortigoza mind sharing your branch with that?
 - Does it make sense for you to support both of the boards or is the second one already going to replace the first?  If it makes sense, then I'm with @tridge and you should just try-and-fail the INS instantiation.  Just make sure the init() method is reading the WHOAMI register

Lastly we don't do git merges and we have one in your PR. My advice here is to take the complete diff, remove the unnecessary whitespace changes and re-split the PR.  Let me know if you need help, I'm available most of the time in gitter, skype and mailing list.

I'm marking the PR as "need-rework" for us to be able to track the pending commits that still needs review.

**Comment by onceme** [comment]
@tridge 

Hi Tridge,

Thanks for the comments, being on a trip these days, sorry for the late response.

- "bhat" sounds good, I'll take that, thanks.
- Let me check the the detect() mechanism a bit more, it is great if this can coping with the two versions
- My editor will highlight the tailing spaces/tabs, it didn't remove them automatically. Usually I would delete them manually if I see any. I thought this is everybody want, but it does make the patch untidy, so I agree, it better be in a separate commit.
- Actually RCInput_BH doesn't try to decode PPMSUM, It now reads 8 standalone GPIO pins through pigpiod, so we can get the 8 PWMs directly from receiver. Frankly speaking, it works and I didn't see exists code could be a reference. Is there a better way to read PWMs from 8 or more GPIO pins?

**Comment by onceme** [comment]
@fhedberg 

Hi fhedberg,

Thanks for the information, I didn't know there's a RCOutput_PCA9685 in master. Originally we added these code based on Copter-3.3 release, and referred the code from NAVIO. This part shall be revised.

**Comment by onceme** [comment]
@lucasdemarchi 

Hi Lucas,

Thanks for more comments:)

- Seems RCIuput_RPI is reading PPMSUM from GPIO4? Because we want to support [FS-R8B](http://www.myrcmart.com/flysky-fsr8b-24ghz-8ch-receiver-for-fsth9x-fsth9b-radio-p-4717.html) RX without extra PPM encoder hardware, so there are 8 GPIOs on RPI is reserved for the 8 separate PWM input. Many people around me using fs-th9x and fs-r8b, so I think support it is reasonable. However I'd like to know if there's a better way to support it, we definitely want to keep improving this part.
- Regarding RCOutput_PCA9685, first time heard from @fhedberg, indeed, it can replace RCOutput_BH
- About LEDs, BH hardware schematic is not available yet, it's now still under active changing, after the whole thing is stable, it will be. Anyway, thanks for telling me about the cathode LED, luckily we have time to change them before producing BH samples in the end of this month. And "Drone Lure" looks lovely;-)
- We would like to support both of the boards for now, since BH is a HAT of RPI2, some of my friends prefer MPU6050 to MPU9250, because their already exists lab project (not ardupilot) is using 6050. In future, if 6050 has no more users, I shall launch another pull request to remove this part from ardupilot, is this make sense? And yes, as in the answer to @tridge, I will try detect() first.

Lastly, I accidentally deleted my remote/origin/master this morning, so this PR was closed. A new one will be launched after the code is prepared again. I hope it won't cause any inconvenience.

**Pull request closed without merging**
