### PR TITLE
Wundef (v2)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
v2 of https://github.com/diydrones/ardupilot/pull/3530

@peterbarker I added some commits on top and changed the waf integration (we need to disable -Wundef for tests using gtest lib)

@vmayoral there were some leftovers for erleboard, could you take a look?

@guludo is the waf integration ok now?

### CODE REVIEW

**Comment by guludo** [comment]
> @guludo is the waf integration ok now?

Hm, just a minor comment above. I just noticed that now, sorry. I think we can fix that on top (if we fix it).
Other than that, looks good to me.

**Comment by lucasdemarchi** [comment]
yeah.... we need to fix it. Overriding cxxflags is not what we should be doing.

**Comment by lucasdemarchi** [comment]
Previous HEAD, so comments are not lost: https://github.com/diydrones/ardupilot/pull/3639/commits

I'm rebasing and pushing -f.

**Comment by lucasdemarchi** [comment]
@peterbarker Looking at this PR again my changes on top of yours looked very trivial so I went ahead and applied it. @peterbarker @vmayoral let me know of any problems.

Thanks.

**Pull request closed without merging**
