### PR TITLE
Adding RSSI library to allow for PWM channel value RSSI - rework #1

### PR DESCRIPTION
**Pull request by StewLG**
This is a resubmit of #2765 after changes requested by @tridge. 

Adding ability and controlling parameters for reading RSSI value from a PWM channel value. This is a feature supported by various radio receivers such as those running OpenLRSng, EzUHF, etc.

Making a new library AP_RSSI to be a uniform place to call read_receiver_rssi. 
    
Retains ability to read analog pin for RSSI values, improves flexibility of relevant ranging a bit.
    
Adds ability to read RSSI from a particular channel's PWM channel value.

    RSSI_TYPE: The kind of RSSI to use. Starting set is Disabled, AnalogPin, and RCChannelPwmValue. More can be added readily.
    RSSI_ANA_PIN: This selects an analog pin where the receiver RSSI voltage will be read.        
    RSSI_PIN_LOW: Receiver RSSI voltage low (weak) value
    RSSI_PIN_HIGH: Receiver RSSI voltage high (strong) value        
    RSSI_CHANNEL: The channel number where RSSI will be output by the radio receiver.
    RSSI_CHAN_LOW: This is the PWM value that the radio receiver will put on the RSSI_CHANNEL when the signal strength is the weakest. Since some radio receivers put out inverted values from what you might otherwise expect, this isn't necessarily a lower value than RSSI_CHAN_HIGH.
    RSSI_CHAN_HIGH: This is the PPM value that the radio receiver will put on the RSSI_CHANNEL when the signal strength is the strongest. Since some radio receivers put out inverted values from what you might otherwise expect, this isn't necessarily a higher value than RSSI_CHAN_LOW.
    
Previous RSSI parameters have been all deprecated in favor of these new ones, and they all have new names. Users will need to re-configure RSSI in order to use these new ones.

Tested on Plane, Copter, and Rover.

Continuation of work started on PR #2731. See also #2721; this PR anticipates the development of other RSSI methods.

### CODE REVIEW

**Comment by tridge** [comment]
thanks for a great implementation! I've pushed it to master

**Comment by StewLG** [comment]
Will this make it into Plane 3.4.0? Or just subsequent releases?

**Comment by gmorph** [comment]
It will make Plane 3.4.0. Thanks!

**Comment by nicbk117** [comment]
What about Copter? :)

**Comment by rmackay9** [comment]
@nicbk117, I'm afraid it won't make it into AC3.3 but it'll be in AC3.4.

**Comment by StewLG** [comment]
I've left comments on issues/PRs where appropriate, but I believe the following should be closed by this PR:

#1377 - MAX and MIN RX RSSI value 
#1061 - Copter: add min RSSI voltage
#503  - Feature request: PWM RSSI support on PWM input channel 8
#1827 - RXRSSI bottom end calibration

The rest (see references above) aren't 100% satisfied by this PR or are already closed.

**Pull request closed without merging**
