### PR TITLE
Parm log defaults

### PR DESCRIPTION
**Pull request by peterbarker**
Common cause of UAV failure is people playing with parameters and getting something not-quite-right.

Nice to know which parameters have been modified from their defaults, so these patches add the defaults to the PARM message.

### CODE REVIEW

**Comment by magicrub** [comment]
This is a great feature that I am surprised that we never implemented from
the beginning. I think I've seen an issue for this floating around but can
say for sure.

Thank you Peter!

**Comment by tridge** [comment]
unfortunately get_default_value() doesn't actually get the default value from the users point of view. For example, consider RATE_RLL_D for copter. If you use get_default_value() it will return 0 because that is what is in the table in the AC_PID library. The actual default is 0.004, as that is set in the constructor of the pid_rate_roll variable in Parameters.h. That means these defaults will be right for most things in plane, but will be wrong for a lot of variables in copter due to the extensive use of constructor overrides for parameters.
I don't know of any way to retrieve the constructor value unfortunately.

**Comment by peterbarker** [comment]
The code is quite free to ignore any values that go into params entirely, 'though.  Code knowledge is required to interpret how the parameters are used anyway, and the real benefit to the change is to know what the user has overridden, not in what values are actually used.  I contend that even if we could look into the code to pull out a "true" default value, we shouldn't - the PARM message (IMHO) should just be about what's in the parameter definitions.

Also - is gradually moving stuff out of constructors a possibility?

**Comment by magicrub** [comment]
Depends what is in the constructor. Most stuff should be moved to the
header via c11. Other items that must init pragmatically in the Constructor
should be called from an init() or defaults() type of thing so other
functions can access them for cases like this

**Comment by rmackay9** [comment]
The constructor overrides in Copter are mostly for the PIDs.  I guess I'd be intereted to see a list of parameters from a clean install of copter on a pixhawk to see what others turn up.

**Comment by tridge** [comment]
Peter, the problem is common classes, such as AC_PID. The class uses a single parameter table, but there are several instances of the class, each with different defaults.
Try resetting parms on a copter, then compare the defaults to what your patch gives. You'll find quite a few parms are incorrect. That could be very misleading. If a user "reset to defaults" their copter likely wouldn't fly anything like the true defaults

**Comment by tridge** [comment]
I will close this for now, as I think the results will be too misleading. It would be very nice if we could do this, but I suspect it will require quite a bit of development to get right

**Pull request closed without merging**
