### PR TITLE
AP_GPS: save configuration to non-volatile memory in UBlox GPS

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by WickedShell** [comment]
Looks reasonable, haven't tested it yet here but looks good, and solo has been using it. Will try to test sometime this evening.

**Comment by lvale** [comment]
Does this apply to other uBlox units (I was looking at https://www.u-blox.com/sites/default/files/products/documents/u-bloxM8_ReceiverDescrProtSpec_(UBX-13003221)_Public.pdf

Also on this doc there is a reference that configuration changes do require either a power cycle or software controlled reset to be effective.

**Comment by WickedShell** [comment]
It should apply to all the u-blox's although I haven't checked all the data
sheets for compatibility yet I think that message has not changed.

Power cycle with config change is only made with regards to loading a
permanently saved config, and that's only if you don't want to send a
CFG-CFG/Load. "The receiver will change its Current Configuration
immediately after receiving the configuration message." Page 2 of the
document you linked,

**Comment by lvale** [comment]
@WickedShell Regarding the reset that I mention and you point to the doc, I didn't see on the commit the reset command being applied, but I'm known for missing obvious things :) :) :)

**Comment by rmackay9** [comment]
@WickedShell, if/when you're happy can you add a Reviewed tag?

**Comment by WickedShell** [comment]
Wilco, just haven't gotten to it yet. Hoping for this evening.

**Comment by WickedShell** [comment]
Works as it says on the tin. I really should have saved my config before running that patch as I wanted the stuff it turned off as on by default. But that's easily fixed and matched the expected behavior. Tested  against APM:Plane with a M8T.

Out of curiosity why does solo need this?

**Comment by jschall** [comment]
We don't configure them in he factory as we did with the DIY products and
IRIS/IRIS+

**Comment by WickedShell** [comment]
I would have thought it would be fine to reconfig on the fly, although I guess that means in rare cases you run a slightly higher chance of having a config that you need not make it to the GPS. Anyways was just curious :)

**Comment by jschall** [comment]
Reconfiguring seems to cause intermittent failure.

**Comment by tridge** [comment]
this needs a timer to prevent _save_cfg() being called too fast. It will call it at the read rate (ie. 50Hz) till the device acks it. This will completely flood the serial link. As we typically don't have flow control it could end up sending the msg in a loop forever as the msgs will be corrupted due to serial overruns.
It shouldn't try a save_cfg more than once every 5 seconds I think
It would also be nice to have at least a bit of a comment explaining what new functions do. An empty comment block isn't much use.

**Comment by bugobliterator** [comment]
@WickedShell @tridge Rework done to solve concerns.

**Comment by tridge** [comment]
Another potential issue just occurred to me. Each request to save config on uBlox receivers that use EEPROM will mean another write cycle on the GPS EEPROM. If the ACK isn't recognised by ArduPilot for some reason then we will end up continually sending it at 1Hz (down from 50Hz before the fixes). So if we were powered on long enough the EEPROM will get totally worn out, potentially making the GPS unserviceable.
I think we should send at most every 5 seconds, and after 5 failures give up and stop sending the request.
My principle concern is older uBlox models which may have slightly different protocol formats. It could also happen is the tx wire on the uart was broken.
In general we need to be careful not to ask a peripheral to continuously do an operation that may shorten the life of the device

**Comment by bugobliterator** [comment]
@tridge agreed, I will make the change.

**Comment by bugobliterator** [comment]
@tridge Rework done to solve concerns.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
