### PR TITLE
HAL_Linux: use hard-disk storage by default on PXF

### PR DESCRIPTION
**Pull request by khancyr**
Last PR to make Erle and Dyidrone Master the same!

### CODE REVIEW

**Comment by khancyr** [comment]
@lucasdemarchi I update the PR but it removes your comments.
Now all linux board will use hard drive by default

**Comment by tridge** [comment]
why don't we want to use FRAM on the PXF? The FRAM should be a lot less prone to corruption than a microSD filesystem.

**Comment by khancyr** [comment]
I don't know... it is better asking to @vmayoral 
I not sure what is FRAM ... Is it a flash memory on pxf cape ? But to handle which data?

**Comment by vmayoral** [comment]
I don't have a strong opinion on this matter. I used hard-disk storage for dev. purposes but if @tridge assures that FRAM is more secure i'd say we should keep it that way.

**Comment by tridge** [comment]
The FRAM holds parameters, waypoints, fence points and rally points. I think it would be a backward step to move to using the filesystem for a board that has an FRAM chip.
FRAM is extremely fast, and supports a massive number of write cycles. It is interfaced over SPI

**Comment by tridge** [comment]
I'll close this as I think the Erle repo should instead adopt FRAM again

**Pull request closed without merging**
