### PR TITLE
Fix build in travis

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Let's get our builds rolling... example of a build: https://travis-ci.org/lucasdemarchi/ardupilot/builds/66464377

### CODE REVIEW

**Comment by gmorph** [comment]
Interesting Lucas.  So it would just make APM2 for Plane as the first test and then build the other targets.  
I have just noticed it appears we don't build APM2 at all for Rover or AntennaTracker.  I think this is an oversite and needs to be put in.  Thoughts?
Thanks, Grant.

**Comment by lucasdemarchi** [comment]
Indeed. But it's not that I removed them, they were not there already, right?

**Comment by lucasdemarchi** [comment]
@gmorph Now I added a commit so we build APMrover2 and AntennaTracker for apm2 and also changed the script a little bit to be simpler. Thoughts?

**Comment by lucasdemarchi** [comment]
Also worth noting travis shows the sum of all build times in its "builds view". However since the builds are started in parallel (but not always at the same time) this is not really the time it takes to run all of them. 

From what I've seen while testing we are down from ~30-40min to build everything to ~20-25.  Not awesome, but at least it doesn't go as high as 50min breaking the build due to timeout.

**Comment by magicrub** [comment]
We have a lot of cleans in there that take time. Is it be possible to
remove them or optimize them some way?

-TomP

**Comment by magicrub** [comment]
Do we know the cpu-count limit of Travis? Does it ever change depending on Travis's global load? Would setting some of the builds to -j16 make any difference?

**Comment by magicrub** [comment]
Also, I see that Travis offers a caching option for paid accounts. Food for thought.
http://docs.travis-ci.com/user/caching/

**Comment by lucasdemarchi** [comment]
> We have a lot of cleans in there that take time. Is it be possible to remove them or optimize them some way?

For me "make clean" is way too fast to be something to optimize. But... instead of splitting the build for each vehicle we could split it for each arch. Then we don't have to run "make clean".... maybe only the px4-depclean, I'm not sure.

**Comment by lucasdemarchi** [comment]
> Do we know the cpu-count limit of Travis? Does it ever change depending on Travis's global load? Would setting some of the builds to -j16 make any difference?

1.5 cores.  I'm not sure why there were changes in our history from j2 to j3 to j4 to j2.  I just left as it was.  Relevant link: http://docs.travis-ci.com/user/speeding-up-the-build/  - I did the first suggestion in that link.

**Comment by lucasdemarchi** [comment]
> Also, I see that Travis offers a caching option for paid accounts. Food for thought.
http://docs.travis-ci.com/user/caching/

That doesn't work if you build with VMs rather than containers. We need to use VM because we install things with apt-get. That's not supported by containers.

**Comment by lucasdemarchi** [comment]
> That doesn't work if you build with VMs rather than containers. We need to use VM because we install things with apt-get. That's not supported by containers.

Answering myself now :-)... that's what this commit fixed: https://github.com/diydrones/ardupilot/commit/b4718f69434ed924a43cb3d167e8b61f2de29b3e

**Comment by lucasdemarchi** [comment]
> Also, I see that Travis offers a caching option for paid accounts. Food for thought.
http://docs.travis-ci.com/user/caching/

And before considering paying for... We might want to consider other options.  In [kmod](https://github.com/lucasdemarchi/kmod)  I'm using both travis-ci and semaphoreci. I'm liking semaphoreci, but I'm not sure if it will fit our needs here.

**Comment by lucasdemarchi** [comment]
> Intel® C++ Compiler is highly compatible with the GNU Compiler. With a small
> wrapper script and a limited number of temporary source patches, we’ve successfully
> compiled Linux kernels 2.4.21, 2.6.9, 2.6.18 and 2.6.32 with the Intel C++ Compilers
> on IA-32, Intel® 64 and IA-64. Since newer Linux kernels may have fewer source
> compatibility issues, we recommend that you build newer Linux kernels with the latest
> Intel C++ Compiler

^ from https://software.intel.com/sites/default/files/article/146679/linuxkernelbuildwhitepaper.pdf

**Comment by lucasdemarchi** [comment]
@tridge  New version, now the build is split by target, using 2 VMs: 1 for PX4 and another for all the others. Example build: https://travis-ci.org/lucasdemarchi/ardupilot/builds/66975061
I added one commit on top to change the way the split is done because it actually "needed" the use associative arrays (or at least it was much simpler by having it)

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
