### PR TITLE
Device interface (v3)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
New version of #3544 

 - I added the changes requested by @jberaud 
 - I didn't make the changes to compile on qurt, since I guess it's broken in more places (see https://github.com/diydrones/ardupilot/pull/3544#issuecomment-183552838)

I'm already adding the Reviewed flag @jberaud added on the previous version.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
so... not sure what happened to the PX4 build, it was compiling last time. it looks like we are now including `modules/PX4Firmware/Build/px4fmu-v2_APM.build/nuttx-export/include/cxx/cstddef` which doesn't contain the typedef for nullptr_t. Although it does contain in the arm-none toolchain.

**Comment by lucasdemarchi** [comment]
I pushed a new version with 2 commits to workaround toolchains with missing parts. This can also be used in other places as well (though it wasn't done in this  PR). @tridge, comments?

**Comment by tridge** [comment]
thanks to some help from Lucas this branch fixes the issues for qurt and qflight:
https://github.com/tridge/ardupilot/commits/hexagon-fix

**Comment by tridge** [comment]
we need one more patch so we don't break the px4 build too:
https://github.com/tridge/ardupilot/commit/8ace731fe55aad3a412a9b3eac642cb8721f62d3

**Comment by lucasdemarchi** [comment]
Some more fixes to get it actually compiling and running on qurt/qflight - thanks @tridge for testing it.

There was another fix pointed out by @guludo on the `I2CDevice::read_registers_multiple()` implementation. I also rebased and cleaned the tree a little bit.

Everything is now applied to master! Thanks all for the help with this PR.

**Pull request closed without merging**
