### PR TITLE
Copter 3.3 heli rc13 pr

### PR DESCRIPTION
**Pull request by R-Lefebvre**
PR for helicopter changes to be released as Copter 3.3 RC13 for Tradheli.

Changes/additions as described in 9/29/15 Dev Call.

### CODE REVIEW

**Comment by magicrub** [comment]
Hit me up if you'd like some help folding those commits in an interactive rebase

**Comment by R-Lefebvre** [comment]
Thanks, but I'm not really sure why we would?  Each commit is a unitized functional change.  Why would we want to collapse them down which will make change tracking more difficult, particularly if we had to find a problem in the future?  "Looks like the problem occurred somewhere in this one giant omnibus commit."

The reason I have these hugs slugs of commits, is because I can't push them to master as I go.  I take a selection of work over a time period, and do a massive PR.  I don't think crushing them down helps Randy analyze them?

**Comment by magicrub** [comment]
Twas just offering since I saw a dozen commits in the same folder(s). If they are better not folded then so be it.

**Comment by rmackay9** [comment]
BTW, overall this PR is not nearly as scary as it first appeared because most of the changes are already in Master (as Rob clarified on the call) also as per usual for Rob's changes, the commits are broken into understandable pieces, styling is just like our existing code, etc.

As TomP suggested some of the final few commits should be combined.  In particular the "Copter heli stab col" commits add variables and flags but then remove them later.

**Comment by R-Lefebvre** [comment]
Yeah, the effort for a squash on that didn't seem worth it to me, but I can do it.

**Comment by R-Lefebvre** [comment]
To be reworked and resubmitted.

**Pull request closed without merging**
