### PR TITLE
Heli: fixed external tail gyro with no flybar

### PR DESCRIPTION
**Pull request by tridge**
this fixes acro mode for ext gyro with no flybar
without this change you can't move the tail at all in acro mode

### CODE REVIEW

**Comment by jschall** [comment]
Why would we support external gyros at all? Have we failed in some way?

**Comment by R-Lefebvre** [comment]
Reviewed.

I don't like the further complexity this adds for very small use-case, but there's no hard technical reason to stop it.

**Comment by rmackay9** [comment]
merged based on Rob's review.

**Comment by rmackay9** [comment]
@jschall, I agree.  My argument against supporting external gyros has always been that if we don't have good yaw control we should put our efforts into improving it rather than adding support for an external gyro.

What I've heard in response however is:
1. yaw control as good as an external gyro is extremely difficult and until we achieve that we need this
2. that this allows a manual bail-out.  Multicopter fliers are accustomed to having no backup but for those coming from the plane world, this is a hard pill to swallow.

**Pull request closed without merging**
