### PR TITLE
Compile warnings

### PR DESCRIPTION
**Pull request by magicrub**
First of many commits/PRs to clean up warnings. I'm doing this in chunks so I can get a fresh Travis-CI report.

### CODE REVIEW

**Comment by dgrat** [comment]
I fixed the AP_Camera regression. Best Daniel

**Comment by magicrub** [comment]
why isn't Travis testing this?

**Comment by dgrat** [comment]
You commit failed.
I added a small commit today.
Travis now compiles fine.


2015-04-22 17:04 GMT+02:00 Tom Pittenger <notifications@github.com>:

**Comment by magicrub** [comment]
Daniel, I squashed your regression commit back into the first commit so that it's less confusing. I recently fell in love with rebase interactive and can show you how to do it if you'd like. Makes the commits SOOOO much easier to look at in cases just like this

**Comment by magicrub** [comment]
Daniel, please look me up on gitter (magicrub) or skype or hangout or mumble so we can work together on this without spamming everyone with email.

**Comment by dgrat** [comment]
Thanks, I will accept the offer :)
This WE I am out.  
My skype is dgrat87. Let's have a chat then.

**Comment by rmackay9** [comment]
merged, thanks!
I had to do a fair bit of chopping to break the commits into individual commits that only affected a single library or vehicle.  If you could make sure to do that for your future commits that would be greatly appreciated.
Also note how we normally like the subject line written.
Finally I removed a couple of commits which I thought affected generated mavlink .h files.

**Comment by magicrub** [comment]
Randy,
Sorry for the mess, I really didn't intend for it to get pushed yet as this is sort of a work in progress as mentioned in the first comment that I'll be pushing many commits and have this open PR so I could see the Travis output. Oh well, it's just as well that it's in merged in. Is planning on doing a rebase interactive on the whole thing to clean it up but was waiting for other major warnings to get addressed first.

Regarding generated MAVLink files. Of they generate earnings then we must either fix them on every regeneration or never treat warnings as errors.

**Comment by rmackay9** [comment]
no troubles.
You know it's possible to run Travis on your own branch as well.  I forget how I did it but it involved poking some buttons on a web page with a mouse I think.. nothing too complex.

**Comment by magicrub** [comment]
I have it running on my own fork but I'm doing these fixes from Daniels
fork so there's an extra layer of complexity that o didn't want to deal
with.

**Pull request closed without merging**
