### PR TITLE
Fix MS5637 CRC check [v2]

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This is the review of #3185

### CODE REVIEW

**Comment by dgrat** [comment]
Looks much better :)

**Comment by lucasdemarchi** [comment]
> instead of 16 or 24 bit I would name them *"byte" because I think the unit size is byte not bit

where? PROM is a bank of 8 16-bit registers.

**Comment by dgrat** [comment]
@lucasdemarchi 
Ah okay, then you are right, seems I was confused because its saved in a uint16 array.

**Comment by tridge** [comment]
this breaks my NavIO+ with "Can't read PROM" at boot

**Comment by lucasdemarchi** [comment]
@tridge sorry, there was a wrong copy and paste in the last commit (using register 0 rather than 7) and a mask problem in the first commit. Should be fixed now.

**Comment by tridge** [comment]
thanks! pushed to master

**Pull request closed without merging**
