### PR TITLE
Plane: CONTINUE_AND_CHANGE_ALT behavior change

### PR DESCRIPTION
**Pull request by magicrub**
Instead of trying to hold a navigation bearing with two waypoints, hold a steering heading like takeoff. This allows it to work the same way but without depending on previous and next waypoints. Please review @mday299 .

### CODE REVIEW

**Comment by mday299** [comment]
I'm not a fan of the idea of ceasing to use the L1 controller's idea of sticking on a line between two points during landing.  Heading hold is insufficient to stay lined up with a runway in our experience -- you need the crosstrack corrections.

**Comment by iskess** [comment]
I agree with Michael. Can we just use something like Cruise mode that always places a fictitious WP 1 KM ahead?

**Comment by magicrub** [comment]
The reason I changed it in the first place is I could not get it to work right for auto-land. It would always take a hard turn and fly east instead of hold a straight line when switching from auto->fbwa->auto on approach to simulate an aborted land.

When you change modes the plane's prev_WP_loc and next_WP_loc get set to current_loc so the waypoint info is lost and thus wp based bearing is trash.

Perhaps a better solution is to use wp bearing when prev!=next, else use yaw hold. Yeah, that sounds much better. Best of both worlds.

**Comment by magicrub** [comment]
updated the commit to check for a valid waypoint, and thus a valid bearing, else if good GPS uses ground course else sensor yaw

**Comment by magicrub** [comment]
Just flew https://github.com/diydrones/ardupilot/pull/2747 which is a branch based on this PR. Works great.

**Comment by magicrub** [comment]
Rebased on master because https://github.com/diydrones/ardupilot/pull/2269 was merged

**Comment by magicrub** [comment]
flight tested, works great

**Comment by magicrub** [comment]
@tridge This is a bug fix, can we please get it into beta?

**Comment by tridge** [comment]
I finally got a chance to look at this properly, sorry for the delay
I've pushed to master, and it will be in the 3.4 release

**Pull request closed without merging**
