### PR TITLE
AP_Eigen

### PR DESCRIPTION
**Pull request by dgrat**
Added a new sub module, with example. The "interface" adds some of the known functions for length, and error checks.
If AP_Math would be removed, one only needs to remove two conversion operators and everything is fine.
It is smart to derive from Eigen anyway if one wants to add more functionality later, so I don't share @lucasdemarchi concerns, as I only implemented some of the useful functions (not everything in AP_Math is bad).
I tweaked the size. So the objects for matrices and vectors are all the same (AP_Math and Eigen and my Class).
@tridge  Memory fragmentation shouldn't happen (no dynamic allocation, 1d array). The performance is better and theoretically there shouldn't be bugs in the current implementation.
I guess everyone should test this module and compare flash sizes and behavior. In best case the size of the executable increases just a bit, memory consumptions stays the same and performance is ~30% better :D 
@tridge regarding the code quality, I think there is no doubt that the current math backend has disadvantages, because the interface is not complete. The implementation is partially also not smart.  

Signed-off-by: dgrat <dgdanielf@gmail.com>

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@dgrat even in the case "let's go with a wrapper", I don't think this is the proper way to it.

We should add a submodule for **Eigen**.  AP_Eigen then would live in the ardupilot repository, not elsewhere. This way it's very easy to manage our dependency of the original project and even contribute back.

**Comment by dgrat** [comment]
I don't really understand. If we use Eigen, we anyway have to define a derived class.

**Comment by lucasdemarchi** [comment]
@dgrat but here I'm complaining on the way you did the submodule, not anything else.

**Comment by dgrat** [comment]
@lucasdemarchi 
I will change this till monday :)

**Comment by dgrat** [comment]
@lucasdemarchi 
I forgot, Eigen is using mercurial. I am not a git pro, but I guess, it will be not that easy to add a submodule without creating a git fork, which I did.

**Pull request closed without merging**
