### PR TITLE
Enable external LEDs

### PR DESCRIPTION
**Pull request by rotcehdnih**
Set notify.init to true 

Tried and tested

### CODE REVIEW

**Comment by tridge** [comment]
I'd like to know a bit more about exactly what pins are enabled with this change, and make sure it doesn't conflict with anything else (eg. airspeed sensor)

**Comment by rotcehdnih** [comment]
4,5,6 i think , the defaults for arducopter

**Comment by gmorph** [comment]
This page describes how it operates:
http://copter.ardupilot.com/wiki/common-optional-hardware/nav-leds/
It affects pins A4, A5, A6 and A7.  I would assume you can no longer use those pins for anything else once this is enabled.  Could be bad if existing users are doing this as there is no way to turn it off.
The change is only relevant for APM2.  It has no effect on Pixhawk.

**Comment by gmorph** [comment]
Hi Hector.  I just had a quick chat with Tridge about this.  We are worried that if someone is using those pins for something else this will break them as there is no way to turn it off.  Our preferred approach is to create a new BRD_ parameter for this (perhaps BRD_EXT_LEDBUZZ).  So in Plane and Rover it would default to "false" as it does now but if someone enables that BRD_ parameter then it would work.  Would you be able to write the code for a new parameter to enable/disable this setting and have it in both Rover and Plane?  We won't touch copter as there is no more copter releases for APMs.
Looking forward to hearing from you.
Thanks, Grant.

**Comment by magicrub** [comment]
Closing to to inactivity and a rebase is required. Please reopen or resubmit if you still want this merged in!

**Pull request closed without merging**
