### PR TITLE
Linux_HAL_Essentials: Add PRU firmware files. Prevent user to install…

### PR DESCRIPTION
**Pull request by mirkix**
Add PRU firmware files. Prevent user to install PRU compiler.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@mirkix I don't really like to commit prebuilt files to the tree like this. Developers having the tools installed is a necessary step and after this is done they can forget about it... Maybe list dependencies in a "requirements" file?

**Comment by mirkix** [comment]
@lucasdemarchi I agree with you, I had only seen that already are binary files for the PXF in the repo.

https://github.com/diydrones/ardupilot/blob/master/Tools/Linux_HAL_Essentials/pwmpru1
https://github.com/diydrones/ardupilot/blob/master/Tools/Linux_HAL_Essentials/rcinpru0

So we can close the PR and I will write a README.md how to build the firmware and how to install the necessary tools / compiler.

**Comment by lucasdemarchi** [comment]
@mirkix I didn't know we had already a binary file like this. IMO we should remove it. @tridge?

**Comment by tridge** [comment]
At the time the PRU C compiler was hard to get - you had to ask for a copy especially from the author. It wasn't generally available. I think it is more generally available now.
Either way, I actually don't mind having small binaries like this in the tree. We already have that for the px4 bootloader for example (see mk/PX4/ROMFS/bootloader). We did that as we really want one "blessed" bootloader for px4. Building that bootloader with the wrong tools can brick your board.
For this particular case (BBBMINI PRU fw) I'm happy to go with whatever Mirkix prefers. If he wants to include the small fw in the tree I'm happy with that, or if he prefers to have build rules to build it as part of "make bbbmini" that is fine too. I don't think a blanket ban on fw binaries in the tree is a good idea, as there are counter examples like the px4 bootloader

**Comment by lucasdemarchi** [comment]
@mirkix so it's your call...

**Comment by mirkix** [comment]
@lucasdemarchi 
Hello Lucas, please merge the firmware files into master. Thanks.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
