### PR TITLE
Hostname resolution for IP based connections on Linux

### PR DESCRIPTION
**Pull request by staroselskii**
The intent is to make it possible to connect by hostname rather than by IP. It'll make our lives way easier. There's a bunch of users who use NoIP services and they desperately need this change.

Now one can launch APM like this:

**sudo ArduCopter.elf -A udp:\<hostname\>:\<port\>**

Along the way I've tried to break dependency on IPv4. This has yielded a couple of changes:
- ```sockaddr_storage``` is used instead of ```sockaddr_in```
- ```getaddrinfo()/getnameinfo()``` is used instead of making ```sockaddr_in``` (IPv4-specific structure) by hand and using ```inet_ntoa()```
- ```last_recv_address()``` slightly changed to take a pointer rather than a reference to pointer (I find it very confusing)
- added ```const``` specifier to a couple of methods

There's a handful of little issues, though:
- This code still works with IPv4 only, though. In order to overcome this limitation we need to change the logic a bit, i.e. call ```socket()``` after ```getaddrinfo()```
- ```select_address()``` method limits the usage to IPv4 for now

There's a serious code duplication issue that should also be eliminated. I'd be delighted if anyone pointed out a way to solve this problem.

### CODE REVIEW

**Comment by tridge** [comment]
My main concern with this change is it opens up the possibility of trying to do address resolution in the main thread while flying. That would be bad, as address resolution can take many seconds.
At the very least I'd like to only use the name lookups if the address is not in a numeric form. I'd also want us to audit the code and ensure no name resolution can happen in flight via any series of calls.

**Comment by staroselskii** [comment]
@tridge 

The address resolution delay had also been bugging me for a while. But I've been under impression that the ```UARTDriver``` related code is called only from the ```uart_thread```, though. Am I missing something?

The audition is very well welcome. The current state is a bit raw. I'm also eager to hear your opinion on the issues I'd layout out in the PR description.

I also think UDP and TCP sockets should be separated. Maybe that's time to consider a full-fledged socket library rather than trying to get everything by ourselves. But I can't recall one that could satisfy our needs without bringing the significant overhead. @lucasdemarchi Do you have a library in mind?

**Comment by magicrub** [comment]
I'm just guessing here, but if we're in the context of Linux doesn't it
sort of come for free somewhere out of the ether? If not, LwIP
<http://savannah.nongnu.org/projects/lwip/> is a good choice but I'm not
sure how well it manages security. I've implemented the basics into a
ST32F1xxx chip before with all the usual protocols like DHCP and was able
to push 50Mbps out of the Ethernet port (UDP) while running it's normal
app. And that wasn't even using select!

**Comment by staroselskii** [comment]
@magicrub 

There's no need for a custom TCP/IP stack implementation. There's one in Linux kernel and we're pretty happy with that! I'm more interested in a socket library on top the socket API. Although, the latter is nice by its own means, the SocketAPM class is getting bigger and bigger. Once day we might find ourselves having yet another socket abstraction layer. There's a chance I'm being too dramatic, though.

**Comment by dgrat** [comment]
Sorry, I am not sure, because I don't know the implementation details, 
but is getaddrinfo allocating memory for address_info? If not it looks like a mistake.

Best, Daniel

+    struct addrinfo *address_info;
+
+    memset(&hints, 0, sizeof(hints));
+    hints.ai_family = AF_UNSPEC;
+    hints.ai_socktype = datagram? SOCK_DGRAM: SOCK_STREAM;
+
+    ret = getaddrinfo(hostname, service, &hints, &address_info);
+    if (ret < 0) {
+        return NULL;
+    }
+
+    return address_info;

**Comment by staroselskii** [comment]
@dgrat

Yes, ```getaddrinfo()``` allocates memory dynamically. That's why we need to call ```freeaddrinfo()```. Actually, the frequent dynamic allocation is indeed might be not a good thing to do. I understand your concern.

**Comment by staroselskii** [comment]
@lucasdemarchi @tridge 

I'm looking forward to your feedback, guys! The Navio community craves for this feature.

**Comment by tridge** [comment]
We definately don't want to do a reverse lookup in UDPDevice::read(). That is deliberately trying to connect to the specific IP the packet came from. A reverse lookup is both fragile and creates ambiguity, as well as being much slower than getting the address from the kernel. Please remove the changes to last_recv_address().
For the forward lookups we need a cache. DNS lookups can be very slow (I've seen them take many seconds and even up to a minute in a bad environment). We can't do a lookup on every packet send while not yet connected, and we don't want to rely on the system name cache. I think we need the caller to cache the IP the first time it manages to resolve it.

**Comment by staroselskii** [comment]
@tridge 

Thanks for the comments!

I was wondering what is the preferred way to deal with a sudden IP change that might happen? Do we need to poll it once in a while once we detect the GCS connection loss. Are we able to spot that, actually?

**Pull request closed without merging**
