### PR TITLE
AP_Motors: Add manual servo override to center swash-plate for set-up.

### PR DESCRIPTION
**Pull request by fhedberg**
Add manual servo override mode to center swash-plate for set-up.

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
Hi Fredrik, what is the intent of this?  Why not just maintain the existing manual pass-through and instruct users to leave the sticks centered?  The only advantage I see here is to ensure the collective is at center?

**Comment by Jman841** [comment]
I think the best way to handle this for setup is to have a button in mission planner that sets the swash to exactly what it thinks is level. From there you should be able to adjust the subtrims to get all servo horns exactly at 90 degree's and, after this leave it in this mode to setup the linkages for the swash plate exactly.

Also, a button to set the swash to full positive and negative collective for adjusting max and min travel points of each servo, and, max and min pitch. 

Relying on the Tx is a PITA due to getting it exactly 0 is much more difficult than simply pushing a button.

**Comment by R-Lefebvre** [comment]
To be tested for AC3.3:

https://github.com/R-Lefebvre/ardupilot/commits/Copter-3.3-Heli-RC13-WIP

**Comment by fhedberg** [comment]
Hi @R-Lefebvre! The intent with this was pretty much what @Jman841 described, to make it easier to setup the helicopter without the transmitter. I'm working on some GCS things for this but realized as @Jman841 suggested, that we would need full positive and full negative collective as well. Thoughts?

**Comment by R-Lefebvre** [comment]
I would prefer to instruct users to put it in H_SV_MAN = 1 Mode, then put the collective full up and full down, rather than make the H_SV_MAN function more complicated.  The seems the easiest solution.

**Comment by R-Lefebvre** [comment]
Though I suppose in the future we will need to eventually have up/down as modes, if we actually do get rid of the requirement to use an RC Tx with the system.  :\

**Comment by fhedberg** [comment]
@R-Lefebvre @Jman841 Yeah. I agree that we should either close this or do full up/down as well, but don't have a strong opinion on it. If full up/down is the way to do, I can take care of it.

**Comment by R-Lefebvre** [comment]
Making extra modes for full up/down should be trivial.  I'm just not sure if we should bother doing it now, or just put it off to 3.4?

I do have one issue with these mode changes though.  They will cause the servos to jump very fast.  If they are unloaded that is fine.  But if the user were to, say, have the blades installed, and not straight in the grips, the servos will be under heavy load.  They could strip if they change modes.

In the past, I've suggested that we should have an LPF on the servo movement while disarmed.  Originally, this was to prevent "buzzing" as occurs sometimes on the servos while the heli is sitting on the bench.  I was going to close that issue, doesn't seem to be much of a problem anymore.  But maybe we should reconsider?  It would help buzzing, as well as slowing servo movements?

I dunno, this is getting more complicated now.

Maybe take this PR in as it is now, then for 3.4, we can do full up/down switching, and LPF while disarmed?

**Comment by fhedberg** [comment]
@R-Lefebvre I'm all for waiting with this - better to get it right than out the door ;)

**Comment by R-Lefebvre** [comment]
You don't think this should go into AC3.3 as it is?  I was going to be testing it.  It was just the expansion of to up/down functionality I wasn't sure about.

Any time user changes H_SV_MAN to 1, the servos will jump.  2 is not that much different.

**Comment by fhedberg** [comment]
@R-Lefebvre In that case I think we should have min and max as well ;) https://github.com/fhedberg/ardupilot/commit/9ec34d5c29140cbd71a9c799ed39d34a26f88a66

**Comment by R-Lefebvre** [comment]
@fhedberg I have pulled this into my AC3.3-Heli RC13 WIP branch.  There was a merge conflict with something I had worked on last week.  I fixed it up, please check:

https://github.com/R-Lefebvre/ardupilot/commit/ab39b66876faae38c247c905a6c935ffc34db6f8

**Comment by fhedberg** [comment]
@R-Lefebvre :+1: Closing this, assume we pull patches from AC3.3-Heli into master later?

**Comment by R-Lefebvre** [comment]
I'm not sure what the convention is in this case. But whatever is in my branch should end up in master.

**Comment by fhedberg** [comment]
@R-Lefebvre Not sure what the convention is for APM, but typically, I think that stuff that's supposed to end up in master should be pushed to master first, and then back-ported/pulled-into older release branches if possible, as it makes is easier for the rest of us to always have the latest and greatest on master - perhaps @tridge and/or @rmackay9 have suggestions on how we best can handle the branching?

**Comment by rmackay9** [comment]
Yes, in general stuff should go into master first and then be put into the older branches.

@fhedberg I'm not sure if the best approach is for @R-Lefebvre to combine your changes in with his and merge them all in at once (to Copter-3.3. and master).  That's not generally how I handle multicopter changes.  I suspect @R-Lefebvre is doing this because it makes flight testing easier.

**Comment by R-Lefebvre** [comment]
I'm doing it this way as his PR had merge conflicts with another change I made.  So I fixed it up and pushed it into my branch, keeping his name on the commit.  This is all getting flight tested as a batch.  It would be inefficient to test pre-PR code, then merge in the PR, flight test that.  Then flight test after more of my own commits I've made.

The part that I had a question about, was if he should close his PR, open another using the conflict-fixed commit?  Or I'll just PR the whole batch of changes when it's ready?

**Comment by rmackay9** [comment]
Ok, if you're combining @fhedberg's commits into your PR then probably no need to keep his original open.

**Comment by R-Lefebvre** [comment]
Ok, so 3 PR's?  Mine before his changes, then his, then mine after his change?

**Comment by rmackay9** [comment]
either 1 PR or 3 PRs is fine.  I'd prefer smaller and if it's really huge then it's pretty much guaranteed that I'll find thing that will stop the whole PR from going in.  if it's done incrementally then it's more likely that some will get in while some will not.  Anyway.. whatever works for you..

**Pull request closed without merging**
