### PR TITLE
MPU6000 minor fixes

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by magicrub** [comment]
You have two changes:
A spelling good which is good to merge and a functional change that I think should not go in. The reason the set speed function accepts an enum is that in the future more sites may be added. Hard coding it go gay or slow is not useful.

**Comment by lucasdemarchi** [comment]
I agree with @magicrub... and setting the speed on I2C should not be done at all (we also don't support AVR anymore).

**Comment by lucasdemarchi** [comment]
@zehortigoza please send only the typo changes for this pull request.

**Comment by magicrub** [comment]
Please forgive my horrible auto correct fail on the post. I've corrected my comment.

**Comment by lucasdemarchi** [comment]
@magicrub It was understandable it was an auto correct mistake.

**Comment by zehortigoza** [comment]
Done, new version without the functional change.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
