### PR TITLE
EKF2: Reduce Roll and Pitch Errors Due To Magnetic Field Disturbances

### PR DESCRIPTION
**Pull request by priseborough**
**Background**

Magnetic heading fusion is the method that the filter uses when on the ground, or in flight when EK2_MAG_CAL = 2. It does not use the magnetic field states and was originally added to provide a computationally efficient yaw observation method that was less susceptible to magnetic field disturbances causing disturbances in roll and pitch, than the 3-axis fusion method that is the default for up and away flight.

This was implemented previously by using a measurement that represented the azimuth angle of the measured magnetic field projected onto the horizontal. Although this method did not require the use of magnetic field states and did not suffer from singularities when the pitch angle was around +-90 deg, it did however still allow disturbances in the magnetic field around the vehicle to affect the roll and pitch.

**This Change**

A new magnetic heading fusion method has been devised that significantly reduces the roll and pitch errors caused by external magnetic field disturbances. The observation is now an Euler yaw heading that switches between a 321 and 312 rotation sequence calculation to avoid regions of singularity.
Using Euler yaw decouples the observation from the roll and pitch states and prevents magnetic disturbances from affecting roll and pitch via the magnetometer fusion process.

**Bench Test Results**

The copter (3DR Iris+) was stationary on a level surface and powered via usb with GPS disabled (GPS_TYPE = 0). A strong magnet was moved around the copter. This test was perfomred before and after the patch was applied. The plots show the magnetic field vector and the roll and pitch for EKF2 and DCM (AHR2)

Before the patch was applied the EKF2 experienced large roll and pitch errors due to the strong magnetic disturbance.

mag disturbance - before
rp comparison - before

After the patch was applied, the disturbances in roll and pitch were effectively eliminated:

mag disturbance after
rp comparison after

**Flight Test Results**

An indoor flight test with GPS disabled (GPS_TYPE = 0) and heading fusion forced on for in-flight (EK2_MAG_CAL = 2) was completed. Plots from the flight test are shown below. The EKF2 and DCM angles were in good agreement and innovations remained low

rp comparison
mag yaw innov
pos innov

### CODE REVIEW

**Comment by rmackay9** [comment]
No chance of t13 or t6 being zero I guess?  I just want to make sure a div-by-zero isn't possible.

**Comment by priseborough** [comment]
In theory not because of the way we switch between fusion methods to ensure we always use a method that is properly conditioned, however rearranging the checks to look after this scenario is easy to do, so i will add a patch that looks after it.

**Comment by rmackay9** [comment]
Sorry @priseborough but could you rebase on master?  I'm getting conflicts and don't trust myself to resolve them.

**Comment by lucasdemarchi** [comment]
The conflict was only due to the M_PI_F rename that went in last week as part of the AP_Math rework.

Applied.

**Pull request closed without merging**
