### PR TITLE
AP_GPS: Ublox select GNSS constellation

### PR DESCRIPTION
**Pull request by WickedShell**
Allows selecting what constellations to track for ublox GPS's. Only supported on the 7 and 8 series (has no effect on the 6). Also allows you to ensure usage of SBAS correctly on a 7 or 8 series if it came from the factory configure incorrectly.

Channel assignments are calculated automatically (all constellations except sbas evenly reserve half of the available channels, and are then allowed to use upto all remaining channels).

Due to a difference in documentation between 7 and 8 series (and the 8 not responding in accordance with the data sheet on the flags, no flags except for enable are changed. This should only be a potential weakness if using QZSS and desiring to differentiate between L1CA and L1SAIF.

### CODE REVIEW

**Comment by WickedShell** [comment]
I'd wait to merge this. Just did a test flight, and got a lot of weird data with CAM's not being triggered reliably and not seeing expected behavior on GPS2. Theres a lot of changes outside of just code though that were in the plane so I need to narrow down what happened before saying this is good. (Although it all looked really good in a pixhawk on the table)

**Comment by WickedShell** [comment]
So this works great on the ground. Haven't had a problem with it yet under those cicrumstances. Unfortunately when actually flying it stops logging RAWX information (which is what I'm trying to get out of this), but it never loses the gps signal (and logs GPS2 messages). There is no time gap when the raw information stops, so the GPS hasn't been lost, but it stops providing the raw stuff (at least according to the log).

Interestingly I can't recreate this on the ground yet, even if the plane is in auto/moving around, and in flight it seems to be happening randomly. I'm inclined to dismiss it as intermittent connection as the normal GPS solution keeps coming from the receiver without ever missing an update. (Flown as a dual GPS system with a 3DR Ublox 6 as the primary, and a M8T as the secondary with no auto switch, and raw logging turned on, tracking GPS, GLONASS, SBAS).

I'd be intrested to see what someone else gets with this patch?

**Comment by WickedShell** [comment]
It should be good now due to 5d9219e it was dropping any messages that had more then 15 satellites, which would happen when I went out to fly, but not inside a building when I was testing on the ground.

I'll get this flight tested tomorrow.

**Comment by magicrub** [comment]
Nice find. To be consistent, shouldn't you use ARRAY_SIZE(_buffer)?

**Comment by WickedShell** [comment]
@magicrub Not really. _buffer is actually a union of all the messages we know how to parse, and an array within it (which is just to let you look at arbitrary bytes). Take a look at libraries/AP_GPS/AP_GPS_UBLOX.h#L279

**Comment by magicrub** [comment]
fair enough

**Comment by ThorstenDP** [comment]
Perfect! Can't wait to test it!

**Comment by WickedShell** [comment]
It should be, I'm only using a dual GPS at the moment as I want to plot the positions from the ublox 6 flying the plane, the 8's computed position, and then the corrected position from the raw data on the 8.

**Comment by WickedShell** [comment]
Flight tested, worked great. The only continuing caveat is that you just need to ensure that your SD card can keep up with the data stream. If it does then you should be fine and it works well. The GPS I'm using is needing to go through almost the entire auto configuration process and is working well. (It's starting on the wrong baud, with the wrong messages, and the wrong constellations, and its being configured correctly every time).

**Comment by tridge** [comment]
applied, thanks so much for your work on this Michael!
btw, do you want to be listed as uBlox driver maintainer now?

**Comment by WickedShell** [comment]
Sure, there's definitely some more patches I want to do with it. (More
robust handling of configuration, adding better support for dual GPS with
different configurations, and figure out a better system to use to enable
SBAS constellation selection. (And there's some more stuff way out there
that'd be interesting).

**Comment by krolladam** [comment]
Hi Michael,

Thanks very much for writing the ublox raw data patch.  I'm waiting on my m8t to be delivered before I can test it.  How to you geotag with the post processed data though?  Has anything been written for the mission planner tagging?  I can't see anything on github.Thanks, Adam.

**Comment by WickedShell** [comment]
This is possibly a repeat email, I just found this in my drafts folder, so
I'm assuming I hadn't already sent this email, if it's a repeat please
ignore it.

I did some tests with a python script, but it was never very flexible. It
should be possible to tag with this:
https://github.com/metadirective/gpicsync although you have the 1 second
data resolution problem still. Mission planner can convert you're M8T's raw
data to the relevant .obs that you then process elsewhere. Unfortunately as
far as I know there isn't a standard solution to retagging the data yet.
Ideally you want something that can tag off the CAM messages with the post
processed log, but at this point I don't know of anything that is available
and supports that. (I'm still looking to get better results from the
tagging then I am currently seeing).

**Comment by Yups1337** [comment]
@WickedShell 
Are there any changes regarding the tagging of the images? It would be a very big milestone to postprocess the ublox raw data of the flight and tag the images precisely, maybe with the new TRIG message from the camera hotshoe?

**Comment by WickedShell** [comment]
@Yups1337 I haven't done further work with the postprocessed GPS and tagging. To beable to use this well you need to integrate the tagging process directly with the post processing/correction process which I haven't put much time into. The recent camera/trig message changes are a good step forward for helping to improve the timing accuracy, but its most straightforward to use those with a RTK gps rather then post processing.

**Comment by Yups1337** [comment]
@WickedShell 
I would do it a different way. The RAW logging with ardupilot works, so we get a *.obs file wich can be converted to RINEX. With the free software RTKLIB (RTKPOST) we can postprocess the RINEX file and get the flight path with high precison. Maybe around 5cm accuracy. 
The Ublox M8T is a cheap receiver and ist able to log at 10Hz. 
Because we have the TRIG MSG from the hotshoe adapter, the exact time when the picture was taken can be recorded exactly. 
Now we can align the TRIG MSG timestamps with the processed log file by time and do a linear interpolation between the 10Hz log points (should be precise enough).

In my opinon the goal is to create high precison 3D-Data without additonal GCPs. 

RTK is another option, but it is more expensive, less reliable (because of the needed telemetry system) and needs more time to setup.

**Comment by sudhavana** [comment]
Hi @WickedShell I tried to flash the latest sw on pixhawk to record the raw GPS measurements. pixhawk 3DR has the u-blox M8N version I understood. I am still unable to record the raw measurements. I have enabled the GPS_RAW_DATA.
image
Can you help?

**Comment by WickedShell** [comment]
@sudhavana M8N does not support raw data logging, you need a M8T or M8P GPS. (In general any u-blox P or T series GPS has raw data logging enabled)

**Comment by sudhavana** [comment]
How do I find out which version of u-blox I have on my pixhawk? Sorry for the dumb question.

**Pull request closed without merging**
