### PR TITLE
Plane: Reverse Thrust

### PR DESCRIPTION
**Pull request by magicrub**
Ever wanted to have a steep landing slope but you can't because you come in too fast? Well now you can! With Reverse Thrust you can dictate whatever airspeed you want and the motor will spin up backwards to maintain that. Depending on the mass of your aircraft and the thrust force of your motor+prop, you can have a glide slope very very steep. This is not throttle based, it's airspeed based so it works with full and empty batteries the same way. I definitely recommend an airspeed sensor for this feature.

I'll be writing something up on the wiki soon. but here's a summary:

The TECS controller can now calculate a negative throttle demand. If you're too steep you gain speed and TECS says to slow down and with reverse thrust ESC you can actually do that! If you have a rangefinder then you have accurate height and with an airspeed sensor you have a very accurate airspeed. The beauty of this is we now have a very repeatable total energy/momentum at the moment we flare so its much easier to fine-tune a soft perfect landing even with a large baro offset causing the lidar to bump us up. It's magic!

I was using a BLHeli ESC but any bi-directional ESC will work. Does not need to be symmetric. 

Configuration
Step 1: set THR_MIN (Throttle min) to something negative, probably whatever you have for THR_MAX but negative.

Step 2: set RC3_TRIM to your ESC's neutral positon. That is, the PWM that is throttle-off. Does not need to be symmetric (1500).

Step 3: set TECS_APPR_SMAX (optional) approach sink max. Normal sink max is a couple m/s but in a steep approach you may want this around 10m/s depending on how steep you're willing to push the aircraft. If you leave this as zero then it uses the normal TECS_SINK_MAX.

Step 4: set LAND_PF_ALT (Pre-flare altitude) to a non-zero value. This triggers the pre-flare flight stage which is before the LAND_FLARE stage. Try values between 7m - 15m.

Step 5: set LAND_PF_ARSPD (pre-flare airspeed) The airspeed demand you want during pre-flare. This should be just above your stall speed. While sinking from LAND_PF_ALT to LAND_FLARE_ALT it'll put the brakes on to try to achieve this airspeed.

Step 5: tweak the other existing flare params to smooth out the touchdown.

Special thanks to the folks at Event 38 to help get this going. Shout out to Daniel Cironi and Jeff Taylor. See:
http://diydrones.com/profiles/blogs/introducing-the-e386-mapping-drone?xg_source=activity
and
http://diydrones.com/profiles/blogs/instructions-for-using-the-event-38-reverse-throttle-feature-on?xg_source=activity

I worked with Daniel to bring their design to master for a Pull-request but I ended up just starting over and going with a totally different approach.

This fixes https://github.com/diydrones/ardupilot/issues/2087

### CODE REVIEW

**Comment by magicrub** [comment]
I added LAND_PF_SEC to go along with LAND_PF_ALT just like there's a LAND_FLARE_ALT/SEC

**Comment by magicrub** [comment]
Here's the first draft of the Reverse-Thrust wiki, I'm sure I'll be tweaking it a little more.
http://plane.ardupilot.com/wiki/automatic-landing/#reverse-thrust_landing

**Comment by magicrub** [comment]
There was a problem with allowing reverse thrust in any non-auto mode (ie, LOITER). Added bitmasks options for all auto_throttle modes and force pushed. I see lots of PRs that have a zillion commits to the same file so I guess I'll stop force pushing to keep it clean from now on since it's a pain to manage on my end.

**Comment by iskess** [comment]
Is there any way to utilize the reverse thrust in FBW mode? What if I don't have an Autolanding set up because I'm not familiar enough with the steep terrain to trust the google map and build an approach. I would want to have the ability to fly the approach in FBWA and dive the plane without picking up speed. Could there be a parameter to not allow the plane to accelerate beyond trim speed (or trim+ X% or X m/s) when diving in FBW with the throttle at zero?

**Comment by magicrub** [comment]
@iskess yes, bitmask for FBWB is here:
https://github.com/diydrones/ardupilot/pull/3567/files#diff-e322ec9c243771bc0e3f6c7fb72991cdR208

FBWA is not an auto-throttle mode so throttle just passes through. I have my ranges set to 1000-1500-2000 and my transmitter throttle set to only output a range of 1500-2000. if you set your transmitter to go below 1500 (or whatever threshold your ESC is set for) then you can do it in FBWA. otherwise, FBWB will do it automatically.

**Comment by magicrub** [comment]
To be clear, the reverse-thrust system is baked into TECS so if TECS demands negative thrust to maintain the normal cruise speed, then your ESC will go in reverse to maintain that. Then after that I have a bitmask to inhibit reverse for given modes and also specific mission items within AUTO.

here's the bitmask:
enum {
     USE_REVERSE_THRUST_NEVER                    = 0,
     USE_REVERSE_THRUST_AUTO_ALWAYS              = (1<<0),
     USE_REVERSE_THRUST_AUTO_LAND_APPROACH       = (1<<1),
     USE_REVERSE_THRUST_AUTO_LOITER_TO_ALT       = (1<<2),
     USE_REVERSE_THRUST_AUTO_LOITER_ALL          = (1<<3),
     USE_REVERSE_THRUST_AUTO_WAYPOINT            = (1<<4),
     USE_REVERSE_THRUST_LOITER                   = (1<<5),
     USE_REVERSE_THRUST_RTL                      = (1<<6),
     USE_REVERSE_THRUST_CIRCLE                   = (1<<7),
     USE_REVERSE_THRUST_CRUISE                   = (1<<8),
     USE_REVERSE_THRUST_FBWB                     = (1<<9),
     USE_REVERSE_THRUST_GUIDED                   = (1<<10),
 };

This is set by USE_REV_THRUST and the default is 2 (USE_REVERSE_THRUST_AUTO_LAND_APPROACH only).

I was having problems where I would be doing landing testing and temporarily put it into loiter and it was a windy day so at the with-with to against-wind (or vice versa?) transition the ESC would spin up backwards for a moment. So this bitmask now allows/blocks that type of behavior for all auto_throttle modes.

**Comment by iskess** [comment]
Yes of course it would have to be FBWB, sorry for my error. The bitmask looks great. 
Have you had any issues with throttle failsafe? Do you still have it set to something like 950? I'm concerned about the possibility of a sudden burst of max reverse throttle on the bench if the Tx is turned off. It should skip from throttle_min to failsafe without touching the reverse range. I just wanted to know if you had any experience or thoughts on this.

**Comment by magicrub** [comment]
Never had a problem, but you have to make sure to configure this with the
motor powered off. When disabled or when in auto and not taken off yet the
throttle is forced to zero (1500us). Chance of the throttle going in
reverse unexpectantly is same as the risk throttle going forward
unexpectantly once its been configured.

The risk is when setting THR_MIN = -100 and RC3_TRIM = 1500 when your ESC
is not configured yet. Autopilot will send 1500 which is normally 50%
forward throttle.

**Comment by magicrub** [comment]
merged, thanks @tridge!

**Comment by iskess** [comment]
When will 3.51 beta be released, I'm all set to test the reverse thrust on a 3DR Aero. Everything is working well on the bench, except the Throttle % being reported wrong. It would be nice to have ARMING_REQUIRE set to RC3_TRIM so it doesn't go to max reverse when disarmed. Using 2 results in that incessant beeping. 
I set up my ESC using BLHeli and set neutral to 1250 to give enough resolution in the forward range. However this only gives me like 50% reverse throttle, which might not be enough, we shall see. Can't wait to try this over those damn powerlines on final approach at the local flying field.

**Comment by magicrub** [comment]
This is in master so you can grab the latest daily build to try it out
right away! The idle throttle is fixed in master too using rc-trim.

The wiki needs an update cuz I have a few new tweaks in there.

I'm excited about you testing it!

**Comment by iskess** [comment]
Sorry for my ignorance, I haven't tried a latest build before. I went to firmware.diydrones.com/Plane/latest/PX4 and I see ArduPlane-v1.px4. I also see v2.px4 and v4.px4. All have the same date and time. Just pick v4?

**Comment by WickedShell** [comment]
V1 is for the PX4FMU/IO combo that was originally available.
V2 is for Pixhawk/clones
V4 is for the Pixracer boards

**Comment by magicrub** [comment]
Thanks Michael. We should relabel those somehow

**Comment by iskess** [comment]
Downloaded the latest build. THR_MIN won't take a neg value, it resets back to 0. 
Throttle still shows 20% at neutral (1200). 
To have reverse thrust available in all modes, do I set the USE_REVERSE_THRUST  to 1? I'm not clear on the convention (1<<0)

**Comment by magicrub** [comment]
I'll post a link to a master binary in a few minutes.

**Comment by magicrub** [comment]
Here you go Iam:
https://drive.google.com/open?id=0B6RPB3yIS_0MLUhyQ21tNUVSOVk

-TomP

**Comment by iskess** [comment]
Tom, I uploaded the firmware from that link and it's still showing 3.5.0. I cannot change THR_MIN to a negative number, and I don't see BATT_WATT_MAX

**Comment by magicrub** [comment]
The WATT_MAX thing is a pending PR, not yet in master. I can include that if you'd like.
I don't see how your THR_MIN is limited, it never has been limited. Keep in mind that the descriptions in Mission Planner are only a snaps from th elatets release so my descriptions aren't shown in there but the binary file I sent you will work. Just set it to -100.

**Comment by magicrub** [comment]
oOOoOoo You must be using the silly sliders in Mission Planner. Go to Full Parameter List and search "THR_MIN" and you can put in whatever you want. I never use the other std/adv menus. Not worth using: can't search, can't exceed bounds.

**Comment by iskess** [comment]
I never use the Silly Sliders, Full Params Lost only. If I change THR_MIN to -100, write, then refresh, it showed 0....but now it's working! So sorry for the false alarm,

**Comment by iskess** [comment]
With RC3_TRIM set to 1200 I'm seeing the Throttle as 57% at neutral. As I add forward throttle that number decreases until PWM 1500 where it shows 0% Throttle, then as I continue to advance the throttle increases up to 100%. Reverse throttle shows 57% then increases upward to 100% at full reverse which is a range of 1200-1000 PWM.

**Comment by magicrub** [comment]
Hmm, thats odd. Ok I'll check into it. For now can you try a TRIM of 1500
to test the other stuff?

**Comment by iskess** [comment]
Ok, I reprogrammed the ESC for a 1500 center and it all works as you said it should. 
I don't understand the bitmask values. What does (1<<0) mean? I set anything between 1 and 0? This is not like any other bit masks in this project.

**Comment by magicrub** [comment]
<< is the shift operation in C/C++ so it s a 1 shifted once, or twice, ect. The result is described here:
http://plane.ardupilot.com/wiki/arduplane-parameters/#bitmask_for_when_to_allow_negative_reverse_thrust_arduplaneuse_rev_thrust

**Comment by iskess** [comment]
Testing went well. Using a 3DR Aero in FBWA, I could put the nose down -30 degrees and get an 8 m/s descent (1600 fpm), that's a 50% gradient, without gaining any speed. 

I had no problems on a steep approach. However during normal waypoint navigation the autopilot wouldn't use enough reverse throttle to maintain the target path. 
See tlog 74.18% (13:09:38) plane is 10m high and 1 m/s fast, but it is only applying 23% reverse throttle. 
not enough reverse
 Also see 72.99% (13:08:48)
[2016-02-25 12-19-31.zip](https://github.com/diydrones/ardupilot/files/149784/2016-02-25.12-19-31.zip)

Using FBW

**Comment by magicrub** [comment]
Any way you can get a bin file?

**Comment by magicrub** [comment]
The throttle on mission planner may not represent actual throttle on the
sw/fw versions you have.

**Comment by iskess** [comment]
I was also monitoring the reverse throttle by watching the RC3 PWM, since I couldn't see whether the Throttle was + or -. 

Here is the .BIN. sorry its so huge. I never power cycled the airplane that day. 

https://www.dropbox.com/s/a4w7d08ky0nxf3j/BIN%206.zip?dl=0

**Comment by magicrub** [comment]
Iam,

Full-disclosure: I've never flown FBW with reverse, only AUTO. After
looking at your log, seems to be working well though.

couple observations on your log:
- your pitch demand vs actual is pretty bad. You could benefit from some
tuning. Roll looks good.
- you have USE_REV_THRUST=1 which means to allow it all the time
<http://plane.ardupilot.com/wiki/arduplane-parameters/#bitmask_for_when_to_allow_negative_reverse_thrust_arduplaneuse_rev_thrust>.
I noticed your motor went in reverse a few times during normal flight. I
fly with it set to 2. Just an fyi.
- during approach of your aborted land I see ch3 PWM lingering around 1200
to 1150, then backs off once it reaches it's target airspeed. Keep in mind,
the algorithm isn't "full reverse", but intead it tries to maintain a
target airspeed. High throttle to decelerate, medium to low to maintain it
depending on the slope. Another landing I see the throttle lower. Seems to
be working fine.
- an easy way to convert PWM to % in mission planner datalog viewer, double
click on RCO-ch3 and type in "-1500,/5" and that will subtract 1500 from
every ample then divide by 5 (in that order). That turns 1000-2000 into
-100 to +100 scale.
- per your "problem" with it not doing enough reverse in normal flight.
Being over by just 1 m/s is relatively good considering I see when climbing
you're hitting 12.9m/s where 15 is your cruise. That means the reverse is
working better than your forward! :)

**Comment by iskess** [comment]
Thanks Tom. I see now that since my problem was with maintaining target altitude in the dive, this is indeed poor pitch tuning. Throttle is modulated by airspeed target only, and it did a good job of this. I will tighten up the pitch PIDs and try again. I just used the autotune function and it seems to have tuned much tighter in roll than pitch. 
I'm a little confused as to why it did such a good job of pitching the nose down to stay on path during landing, but not at other times. Is it possible that the pitch/power weighting is different during the two phases? 

In general I don't want reverse thrust to come on intermittently in normal flight due to windshear or other small airspeed deviations. However I do want reverse thrust to engage went the vertical flight path is steeper than the glide angle of the airplane. Maybe it shouldn't be purely airspeed dependent? 

Thanks again for a fantastic feature! I have a bunch more esc's to flash now.

**Comment by magicrub** [comment]
Your settings are:
TECS_SPDWEIGHT
<http://plane.ardupilot.com/wiki/arduplane-parameters/#weighting_applied_to_speed_control_tecs_spdweight>
== 1
TECS_LAND_SPDWGT
<http://plane.ardupilot.com/wiki/arduplane-parameters/#weighting_applied_to_speed_control_during_landing_tecs_land_spdwgt>
== -1

and I use

TECS_LAND_SPDWGT == 0
TECS_SPDWEIGHT == 0
(to decouple pitch and throttle in my flying wing)

**Comment by iskess** [comment]
Thanks Tom. I see that having TEC_LAND_SPDWEIGHT set to -1 will increase my height accuracy as the approach progresses. This explains why the plane was more aggressive with reverse thrust in landing. As SPDWEIGHT approaches zero, the TECS will pitch harder to maintain path and accept a larger airspeed error. That airspeed error allows the Reverse Throttle to be utilized more which helps the whole loop. So I'm guessing that I can conclude that when using Reverse Throttle, the TECS_SPDWEIGHT can be lowered a bit. Even if this holds true for descends, there may be increased risk of stall in climbs if the TECS has less weight on airspeed?
I remember you stalled your wing using TECS_LAND_SPDWEIGHT = 0, how did you mitigate that risk?

**Comment by magicrub** [comment]
By reducing roll max

**Comment by Chavalcoy** [comment]
Hi!
Very intresting things here!

I would like to get some clarification from you guys. 
As Iskess, I would like to do a manual approach in FBWA or B? (whatever is easiest method-wise) 
take the plane down to 3-5m above ground, into the wind,  and then apply reverse thrust to make a stall landing
pretty much what the ebee seems to be doing. but only in manual mode instead. 
As for how much reverse thrust, either by flipping a switch on the radio and appying enough reverse manually to slow down the wing. This will of course require some testing to get the feel.

Alt (better) to flip a switch and make just the reversing-into-stall-ebee-style just when I want to land.


-I understand i need to reprogram the ESC. Any wiki on how? not the whole thing just the specific parameters.

-Are any of the above methods (manual or semi-auto) possible then?

/John

**Comment by magicrub** [comment]
This is mainly designed for high accuracy near-stall auto-landing like the
ebee you refer to. For reverse thrust in manual you just push the throttle
lower when you feel like it. Cuz, it's manual. Same with FBW, its all about
setting your throttle trims on the transmitter compared to however you set
your ESC. Different ESCs get programmed differently, refer to your ESC mfgr
and/or google for programming them. There are many aftermarket ESC
firmwares if your ESC doesn't already support reverse.

**Comment by Chavalcoy** [comment]
Ok. I dont know if I understand this right. I want the wing to basically free fall from 3-5m in order to spare the hardware. 
Take LAND_PF_ARSPD. I would put this to 1-2 m/s and the wing would in theory free fall into the ground? 

I have only seen the EVENT38 video where the plane did a 40deg tuchdown in slow speed and that is not what im looking for.

As for the manual reverse. I assume you could program a hot/switch on the transmitter that activates a different trim level. for ex. hotkey on=Throttlestick at bottom means throttle -100?

**Comment by magicrub** [comment]
>>I have only seen the EVENT38 video where the plane did a 40deg touchdown
in slow speed and that is not what im looking for
its essentially the same as the Event38 one but you're slowing it down
more. Sure, go to 2m/s during pre-flare and give it enough time to slow
down and you'll for-sure stall. You'll need to figure out what your sink
rate will be so you know at a given slope angle that you'll hit your stall
speed at 3-5m up. But a stall fall from 5m is not pretty.

You have to consider *HOW* your plane goes from 15m/s down to stall
(10m/s?) because that action takes time and you'll be flying downward
during that process. That is all scripted in the pre-flare alt.

**Comment by Chavalcoy** [comment]
I understand it will not be pretty, as long as the wing has some forward momentum and the ailerons are stabilizing the wing, It should work.

[https://www.youtube.com/watch?v=UyzuUYA2vHg](url)

Got the inspiration from this video and shows pretty much what i would like to do. 
My thinking is that the approach will be hard to plan in MP if the area is small och has obstacles.
That is why i rather fly manually during the approach. Then I would like to activate a semi-manual landing. 

It could be manual, but I would like to have all the timing (reverse time and %) programmed maybe with a target airspeed (1-2m/s) then freefall as the video. Whith the help of the Autopilot to stabilize the descent.

**Comment by magicrub** [comment]
>> ... as long as ... the ailerons are stabilizing the wing.
By definition, that is not a stall.

That's a good video, thanks for sharing. I had never seen it pitch up on
the ebee.

To achieve that on APM do your pre-flare to just above stall then flare at
alt 2 or so the set tecs-land-src crazy low like -10 to ramp up your pitch
or simply set your land pitch min and Max to be high like 45. The max so
need to be set high with way.

**Comment by Chavalcoy** [comment]
Ok. We are still talking using a reverse thrust config for that  right? Will do some testing when I get a suitable esc.

**Comment by magicrub** [comment]
yes, reverse thrust. All you're trying to do is lower your airspeed then
pitch up at the end.

- approach steep-ish
- pre-flare high enough that you can slow down to your desired airspeed in
time which is not 2 m/s, that's silly. Try 10 or whatever is around your
stall speed. Once you stall your wing will drop and you won't be able to
pitch up so make sure not to slow down too much.
- flare low, like 2m
- pitch up like crazy by either changing your sink rate to negative (climb)
via TECS_LAND_SRC and it will climb, or a high positive LAND_PITCH_CD so
that you're not allowing it to pitch down, only up.

I've never to pitch up like crazy so make sure you've got room for a crazy
landing!

**Comment by Chavalcoy** [comment]
Great.
Actually I fount the ebee manual online and it describes the landing pretty much as your description above.

I would like to make the final brake at FLARE, Point 7. Is it possible the add it in the procedure?

[http://s30.postimg.org/um7irif35/Landing.png](http://s30.postimg.org/um7irif35/Landing.png)

**Pull request closed without merging**
