### PR TITLE
All: rssi from sbus

### PR DESCRIPTION
**Pull request by multigcs**
calculates an RSSI value based on the SBUS drop-bit

### CODE REVIEW

**Comment by gmorph** [comment]
Hi Oliver.  This looks good.  Our policy is separate patches per directory
http://dev.ardupilot.com/wiki/submitting-patches-back-to-master/
We will handle this one for you :-) New branch is here
https://github.com/gmorph/ardupilot/commits/multigcs-sbus-rssi
However its not building for APM2 and other platforms.  Any chance you could have a look and fix it up?  Thanks.

**Comment by multigcs** [comment]
is it ok if i give you a diff against your repository ?

http://www.multixmedia.org/test/rssi-gmorph-changes.diff

**Comment by tridge** [comment]
can you update this PR to address the portability and code style issues?
Also, it would be better to put the logic in one plane - perhaps in libraries/RC_Channel, rather than duplicating it in each vehicle type

**Comment by magicrub** [comment]
is this PR still valid?

**Comment by StewLG** [comment]
Tom, this PR was done before the RSSI library changes. I'm accomplishing the very same thing with https://github.com/diydrones/ardupilot/pull/3274. This appears to be the source of the original idea for SBUS packet drop counted RSSI, at least in the AP ecosystem.

So I'd say this is superceded by #3274, but I do want to give credit where it is due.

**Comment by magicrub** [comment]
Ok, thanks

**Pull request closed without merging**
