### PR TITLE
AP_HAL_Linux: Fix BBBmini IIO scaling

### PR DESCRIPTION
**Pull request by mirkix**
Fix BBBmini IIO scaling

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@mirkix in your case what's the output of the `scale_available` and `scale` in the sensor directory?  Also, what's the FSR there? The output of the sensor should be in mV so these numbers look a little bit weird to me... do you have any resistor divider?

**Comment by mirkix** [comment]
@lucasdemarchi Hi Lucas, there is no `scale_available`and `scale`:
```
debian@beaglebone:/sys/bus/iio/devices/iio:device0$ ls -la
total 0
drwxr-xr-x 5 root root    0 Feb 17 18:32 .
drwxr-xr-x 4 root root    0 Feb 17 18:32 ..
drwxr-xr-x 2 root root    0 Feb 17 18:32 buffer
-r--r--r-- 1 root root 4096 Feb 17 18:32 dev
-rw-r--r-- 1 root root 4096 Feb 17 18:32 in_voltage0_raw
-rw-r--r-- 1 root root 4096 Feb 17 18:32 in_voltage1_raw
-rw-r--r-- 1 root root 4096 Feb 17 18:32 in_voltage2_raw
-rw-r--r-- 1 root root 4096 Feb 17 18:32 in_voltage3_raw
-rw-r--r-- 1 root root 4096 Feb 17 18:32 in_voltage4_raw
-rw-r--r-- 1 root root 4096 Feb 17 18:32 in_voltage5_raw
-rw-r--r-- 1 root root 4096 Feb 17 18:32 in_voltage6_raw
-r--r--r-- 1 root root 4096 Feb 17 18:32 name
lrwxrwxrwx 1 root root    0 Feb 17 18:32 of_node -> ../../../../../../firmware/devicetree/base/ocp/tscadc@44e0d000/adc
drwxr-xr-x 2 root root    0 Feb 17 18:32 power
drwxr-xr-x 2 root root    0 Feb 17 18:32 scan_elements
lrwxrwxrwx 1 root root    0 Feb 17 18:32 subsystem -> ../../../../../../bus/iio
-rw-r--r-- 1 root root 4096 Feb 17 18:32 uevent
debian@beaglebone:/sys/bus/iio/devices/iio:device0$ 
```

You get raw ADC values (0 ... 4095) if you read `in_voltageX_raw`.
Voltage divider: 20kOhm / 10 kOhm 
Voltage: 0 ... 1.8V
Resolution: 12 bit (0 ... 4095)

Result = #define IIO_VOLTAGE_SCALING 3.0*1.8/4095.0

Regards
Mirko

**Comment by lucasdemarchi** [comment]
Hi @mirkix 

yeah, it looks like your driver doesn't have the scale information. Usually there is a in_voltageX_scale (or omitting the X if it's always the same). Then you know the voltage scale for the ADC peripheral (but would still have to add the scale for the voltage divider you added in your board).

**Comment by lucasdemarchi** [comment]
> Result = #define IIO_VOLTAGE_SCALING 3.0*1.8/4095.0

this should be 4096.0 because you have 4096 numbers in a [0,4095] interval.

**Comment by lucasdemarchi** [comment]
Oh, no... you are right. Applied.

**Pull request closed without merging**
