### PR TITLE
GCS_MAVLink: Suggest new class structure and clean up

### PR DESCRIPTION
**Pull request by dgrat**
I sorted the functions of GCS_MAVLink dependent on their purpose and moved one function out of the member space. 
Wanted to use this as a starting point for future shifts of the vehicle code into the library. 
I just used derivation for shifting the member variables out of the now specialized classes.  

Signed-off-by: dgrat <dgdanielf@gmail.com>

### CODE REVIEW

**Comment by magicrub** [comment]
Github can not merge. Please rebase on master

**Comment by dgrat** [comment]
Do you think the commit is okay? The change is heavy, even when I was not touching the functions itself. I intended to use this as a starting point for shifting further functions into the library. However, I am not sure whether other developers like the current draft.

**Comment by magicrub** [comment]
well, regardless if other devs like it or not, github can not merge it so it needs a rebase to master before it can even be considered. I haven't looked at it in detail yet so I'm neutral about.

**Comment by dgrat** [comment]
Well rebasing is not easy, if there are constant additions and I think I will not recheck every function for changes. 
I close the commit.

**Pull request closed without merging**
