### PR TITLE
Remove unused libs

### PR DESCRIPTION
**Pull request by lucasdemarchi**
From a quick look these are very old implementations that are not used anymore.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@rmackay9 @tridge any objection on removing these?

**Comment by tridge** [comment]
I think they can be removed, but I'd like Randy to comment on perfmon and PI

**Comment by rmackay9** [comment]
I'm happy with them being removed, thanks!
Copter uses AC_PID now.
PerfMon I haven't used in a long time and we have better tools now.
We stopped using AP_Curve with the latest copter release (Copter-3.3) and instead now use a smooth curve for the thrust->pwm curve.

**Comment by lucasdemarchi** [comment]
@tridge @rmackay9  thanks, applied.

**Pull request closed without merging**
