### PR TITLE
refactor of AC_AttitudeControl to use radians, rationalize naming conventions, and rewrite comments

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by jschall** [comment]
@lthall @rmackay9 Next I will begin working on functional changes that go on top of this.

**Comment by jschall** [comment]
@rmackay9 I think I'm going to let this PR stand as-is for now.

**Comment by rmackay9** [comment]
I think we need to discuss the rename of "frame_conversion_ef_to_bf" to "ang_vel_to_euler_derivative".  The new name implies that it always converts an rotation rates but it is also used to convert angles.

**Comment by jschall** [comment]
I think it's great that the new name reveals that the computation of angle error is a linearization. That fact was obfuscated by the poor naming before.

**Comment by jschall** [comment]
I think we could also name the input functions to input_, so input_euler_angle_roll_pitch_euler_rate_yaw_smooth

**Comment by jschall** [comment]
Resolved your concerns in commit cf68476

**Comment by jschall** [comment]
Added a change to prefix the input shaper functions with input_

e.g. input_euler_angle_roll_pitch_euler_rate_yaw_smooth

**Comment by rmackay9** [comment]
@jschall, before you ask, i haven't forgotten about this PR.  It's still high on my list.

**Comment by priseborough** [comment]
I have been reviewing the final AC_AttitudeControl files and have a few comments in relation to documentation in the header file.

1) All rotations, and vector should include frame of reference and units in the header documentation. We should not be relying on the variable name to capture the required information, however variable names do need to be descriptive and not misleading. Some examples:

Is _att_error_rot_vec_rad in the vehicle body frame or is it in the reference frame? This has
Is _ang_vel_target_rads in the body frame?

2) Lines 514 to 516 in AC_AttitudeControl.cpp don't make sense given the frame of reference. The comment states that this correction is for precession, however this is clearly not a compensation for gyroscopic precession, so it must be a correction for rotating reference frames. However if _att_error_rot_vec_rad is in body frame and already compensated for the change in vehicle orientation, then no further correction should be necessary.

**Comment by rmackay9** [comment]
We seem stuck on the renaming.
In an attempt to make some limited progress, here's a branch with just the first two commits in it that I'm happy to push to master.  Normally we don't push just parts of a PR because it's a potentially untested piece of code but if Jon wants to give his ok on this I'll push it.
     https://github.com/rmackay9/rmackay9-ardupilot/commits/jon-refac1

I'm also keen to get the quaternion acro controller included but because the patch is after all the renaming I ran into troubles.  Jon, if you want to fix up the last commit in this branch so that it works we can add this patch as well.
https://github.com/rmackay9/rmackay9-ardupilot/commits/jon-refac3

Please have mercy and don't give me a pile of complaints about why this or that isn't going in.  I'm stuck in the middle here.  Let's try and come to an agreement so we can proceed on getting the important bits in master.

**Comment by jschall** [comment]
@rmackay9 Who exactly is stuck on the renaming?

**Comment by rmackay9** [comment]
@jschall, see @priseborough's comments above.  I think @lthall also has concerns about the new names.  Personally, I don't think the new name for the frame_conversion_bf_to_ef (i.e. "ang_vel_to_euler_derivative") although I'm happy to go along with it if Leonard and Paul are happy.

Instead of arguing about these names though, I think we should put aside the naming for a moment and focus on the bits that we can agree on which, at the moment, are the two bits I've mentioned above.

**Comment by jschall** [comment]
@rmackay9, based on my discussions with @priseborough, he is in total agreement with making these changes. Don't let me speak for him though.

Not certain about @lthall.

Regardless of your personal opinions on that name, it describes what the function mathematically represents, whereas the existing name simply does not and can be terrifically misleading. The fact that we are misusing the function is irrelevant - it should be named descriptively. If you would like a deeper mathematical explanation I can put that together tomorrow. The point of these patches is to refactor the code such that someone qualified can read it and understand what it is doing without having intimate knowledge of the code. Per @priseborough, that goal had been accomplished. He stated on a skype call that he can now read the code and understand what it is doing.

**Comment by rmackay9** [comment]
@jschall, I see @priseborough's comments above, after your last commits and it doesn't seem he's satisfied yet.  I've asked Paul if he can reply here if he's happy.
Even with @priseborough consent, I don't think @lthall is happy with the new names.

So looks like you're going for the all or nothing on this PR.  wonderful.

**Comment by priseborough** [comment]
Jon has addressed my comments on naming with a patch, so i am now happy with naming. I had a query regarding some existing functionality, but that is outside the scope of this PR. I am happy for it to go in as is. It's not perfect and it never will be as we do not have a standard lexicon and naming convention for the project, however its better than what we have before, so provided it passes functional testing (ie had not changed the behaviour of the control loops), then I think it should go in.

We could spin this particular wheel ad-infinitum.

**Comment by jschall** [comment]
@rmackay9, if @lthall wants to make constructive suggestions, he may and we can discuss them and incorporate them if they are an improvement. So far he has participated minimally, but if you read our email thread he seems amenable to everything that has been discussed. So where is this perception of a disagreement coming from? All I see is a fairly remarkable lack of disagreement between everyone involved except perhaps you.

**Comment by jschall** [comment]
> @jschall, I see @priseborough's comments above, after your last commits and it doesn't seem he's satisfied yet. I've asked Paul if he can reply here if he's happy.

The commit that addresses Paul's concerns was pushed immediately before he posted his review comment - we discussed on Skype.

**Comment by rmackay9** [comment]
I'm pretty certain that @lthall is not happy with the names so we're going to have to get through that before it can go in.

**Comment by rmackay9** [comment]
@jschall, can you resolve the merge conflicts with master?

**Comment by jschall** [comment]
@rmackay9 done.

**Comment by jschall** [comment]
Pushed changes in response to @rmackay9's review, fixing the regressions found by Randy, fixing heli build, and renaming the getters for attitude target and attitude error.

**Comment by rmackay9** [comment]
merged, thanks!

**Pull request closed without merging**
