### PR TITLE
Add support to MPU9250 over I2C

### PR DESCRIPTION
**Pull request by zehortigoza**
The main reason of this PR is add I2C support to MPU9250, but several changes was need before do that.
This changes makes MPU9250 API and part of the implementation equal to MPU6000, now we have a bus abstraction and the implementation of SPI auxiliary bus. In a future PR we can even share some methods between those 2 sensors.
For I2C it don't use the auxiliary bus, it just connect the I2C auxiliary bus of MPU9250 to the main I2C bus e let the MCU/CPU talk to all devices(AK8963 and others) directly.

The SPI connection was tested on the MinnowBoard Max + minlure(https://github.com/diydrones/ardupilot/pull/2947), on another version of the minlure that had a MPU9250 instead of a MPU6000 + HMC5843.

As GitHub order commits by date, here is correctly order(starting from bottom):
6924705 AP_InertialSensor: Add HAL_COMPASS_AK8963_MPU9250_I2C to _detect_backends()
fb6ef5c AP_HAL: HAL_COMPASS_AK8963_MPU9250_I2C to the supported list
069236b AP_Compass: AK8963: Add support to use a AK8963 behind of a MPU9250 over I2C
60ce215 AP_InertialSensor: Make detect_backends() public
b305c82 AP_InertialSensor: MPU9250 I2C: Connect the auxiliary I2C bus to the main bus
8c4d6d0 AP_InertialSensor: Add MPU9250 over I2C to detect_backends()
e206a0e AP_HAL: Add MPU9250 over I2C
2ce731c AP_InertialSensor: MPU9250: Add I2C support
db25780 AP_InertialSensor: MPU9250: Remove methods not used anymore
5c5b4a6 AP_Compass: AK8963: Use MPU9250 auxiliary bus
cf87c22 AP_InertialSensor: Add support to get auxiliary bus of multiple instances of the same sensor
2124cf2 AP_InertialSensor: MPU9250: Export auxiliary bus
20ea555 AP_InertialSensor: MPU9250: Add BusDriver abstraction

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
LGTM.

I don't really like how you are defining a "POINTER" constant and passing the instance number rather than de device... but we can change that on top.

I also tested on navio to make sure it continues to work.

**Comment by lucasdemarchi** [comment]
Later we also have to start removing the duplicate code between MPU6000 and MPU9250, but I think that could wait the new AP_HAL::Device interface I'm going to propose soon.

**Comment by lucasdemarchi** [comment]
@zehortigoza what was the update? Just a rebase?

**Comment by zehortigoza** [comment]
@lucasdemarchi I just rebase to fix conflicts.

**Comment by lucasdemarchi** [comment]
@tridge @rmackay9 this is reviewed, could you take a look?

**Comment by tridge** [comment]
looks good, thanks!
I've pushed to master

**Pull request closed without merging**
