### PR TITLE
AP_Motors: Circular swash-plate limits for AP_MotorsHeli

### PR DESCRIPTION
**Pull request by fhedberg**
This is a rebase of @jolyboy's #1754 on master.

@jolyboy: Comments?

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
Nice work, I'll have a look at this and try to include it in 3.3

**Comment by jolyboy** [comment]
Very nice work, thank you for taking the time to get this done.

**Comment by R-Lefebvre** [comment]
I'll be testing this patch for inclusion with AC3.3-Heli

https://github.com/R-Lefebvre/ardupilot/commits/Copter-3.3-Heli-RC13-WIP

**Comment by fhedberg** [comment]
@r-lefebvre Assume all your 3.3 changes are going into master so closing this.

**Comment by R-Lefebvre** [comment]
Yep, will try to PR it today.

**Comment by fhedberg** [comment]
@R-Lefebvre :+1:

**Pull request closed without merging**
