### PR TITLE
Copter: remove decimator from get_roi_yaw

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by rmackay9** [comment]
this is running at 400hz.  Is it really helpful to run the angle calcs at that speed?
I just worry about the performance impact at a time when the Pixhawk is not running smoothy

**Comment by jschall** [comment]
Once we've decoupled the angular position loop from the angular rate loop and run it at 100hz, it should run at 100hz. Maybe for now we should decimate it to 100hz instead of 40hz?

**Comment by rmackay9** [comment]
Jon, ok sounds good.  So I'll reduce the decimator to a quatrimator.

**Comment by rmackay9** [comment]
merged our modified agreement.

**Pull request closed without merging**
