### PR TITLE
AP_GPS: Read actual hDOP value from UBLOX messages.

### PR DESCRIPTION
**Pull request by andyp1per**
Before we were reading the position DOP and calling it hDOP. Since the
other drivers actualy read hDOP it seem best to do the same.
Fixes issue https://github.com/diydrones/ardupilot/issues/462.

### CODE REVIEW

**Comment by andyp1per** [comment]
Any opinion on this? I think it's the right fix and it closes a couple of issues. Any reason it can't go in?

**Comment by magicrub** [comment]
My opinion is yes, hDop would be useful!

**Comment by tridge** [comment]
hi Andy, my main concern with this change is the call in ArduCopter/motors.cpp in the arming checks. This will change the threshold for the vast majority of copter users who use a uBlox
I'll assign this to Randy so he can decide if he is happy with the change, or wants a change in the defaults hdop threshold to go along with it

**Comment by ThorstenDP** [comment]
Maybe a first step should be just renaming the HDOP in PDOP and then introduce HDOP as an additional  value.

**Comment by andyp1per** [comment]
The problem is the other drivers record HDOP, so if you rename PDOP then they are all wrong. The only reason we record PDOP is because its easy to get from the existing data in UBLOX. I would prefer that we do the Right Thing. IMO that should be HDOP.

**Comment by taedla01** [comment]
Hello everyone,
I am with Andy, we should read the real HDOP.

Regards from Spain,
Dario.

**Comment by andyp1per** [comment]
Randy? Any opinions?

**Comment by rmackay9** [comment]
Looks like there's a compile error because there's a duplicate "case 8:" in send_next_rate_update.

**Comment by rmackay9** [comment]
So in my quick tests the hdop value is about 62% of the pdop value.  So assuming that ratio is generally constant we should reduce our GPS_HDOP_GOOD parameter default from 230 to 140.

One slight concern is that it reads a new GPS message which is 18bytes long.  I hope this doesn't cause any bandwidth issues or missed messages (I will check to see if Tridge has an opinion on this).

**Comment by andyp1per** [comment]
The original commit was clean - something underlying must have changed, do you want me to update the PR?
Re: bandwith I think the update rate for this message is fairly low (1Hz maybe?) so hopefully should be ok.

**Comment by WickedShell** [comment]
Guessing that the RXM-RAWX stuff that went in for the M8T message stole the
case from you.

**Comment by andyp1per** [comment]
OK, I think I fixed both the compile and the setting of  GPS_HDOP_GOOD

**Comment by rmackay9** [comment]
merged, thanks!

**Comment by andyp1per** [comment]
Thanks Randy!

**Pull request closed without merging**
