### PR TITLE
Fix milligauss codes in AP_Compass_LSM303D Driver.

### PR DESCRIPTION
**Pull request by raspilot**
Add set_milligauss_ratio() to AP_Compass_LSM303D.cpp, and modify some related codes.
There is a "Prearm:Compass not calibrated" warning  now because of missing of the milligauss related codes.

### CODE REVIEW

**Comment by rmackay9** [comment]
we're seeing similar problems on the Bebop so perhaps the ak8963 has similar issues.

**Comment by lucasdemarchi** [comment]
@rmackay9 here it was just missing the function so no conversion from sensor unit to milligauss was happening.

In AK8963 the function is already there, converting from µT to milligauss so it must be another bug.

**Comment by rmackay9** [comment]
merged based on Lucas's review.
I simply changed the subject on the commit a bit to make it fit in better with our regular style.

**Comment by raspilot** [comment]
@rmackay9 Thanks!

**Pull request closed without merging**
