### PR TITLE
AP_HAL_Linux: Add init checks

### PR DESCRIPTION
**Pull request by dgrat**
I think this may enhance the starting time and adds some additional checks.

Signed-off-by: dgrat <dgdanielf@gmail.com>

### CODE REVIEW

**Comment by dgrat** [comment]
.. travis

**Comment by tridge** [comment]
I'd like Mikhael to have a look at this one, I'll try and add him to the PR

**Comment by dgrat** [comment]
@lucasdemarchi 
I think you are right. I personally use monit for process monitoring and it would be better to do it on the operating system level.
I would suggest a simple check whether the daemon is alive. On the other side I see the intention to restart it with the firmware, which is not good at the operating system level. 
Moreover, it would be super risky if the program does not create a *.pid file. 
So I was just removing the sleep() functions and added a few checks, as the program should be blocked anyway by a call of system(). 
.. At least I hope so.

**Comment by lucasdemarchi** [comment]
Should we close this in face of #2456 ?

**Comment by tridge** [comment]
yes, I think so.
closed ...

**Comment by dgrat** [comment]
the other patch is much better

**Pull request closed without merging**
