### PR TITLE
Plane: Beep/Chirp after a land to help find in tall grass

### PR DESCRIPTION
**Pull request by magicrub**
ArduPlane: added LAND_BEEP

- Helpful for landing in tall grass and can not see aircraft directly, this is an audible beep/chirp
- Has 4 modes: 0:Off,1:On (always),2:On_After_Land,3:On_After_Land_MuteViaModeChange

The #1 "On" option means the beep is on, always. That mean it beeps allll the time. Useful to hear the beep when testing so you know what to listen for, but otherwise this option should be set to 2 or 3.

Also, it will auto-mute after you pick up the aircraft.. or kick it.

### CODE REVIEW

**Comment by jmachuca77** [comment]
This is also useful for copter. The new racer quads are a pain to find when they crash. I would add an option for activating it after a crash. And if possible to activate it with a switch on the transmitter. As sometimes the crash detection fails

**Comment by magicrub** [comment]
this is a little buggy so please don't merge until I've had time to fix it.

**Comment by gmorph** [comment]
Hi Tom. Travis has been fixed and now this isn't passing the Travis build. Can you have a look please? Thanks.

**Comment by magicrub** [comment]
I have no idea what that error is. Anyone got any ideas?

**Comment by R-Lefebvre** [comment]
Sign of the beast?

**Comment by magicrub** [comment]
I've decided to nuke this.

**Pull request closed without merging**
