### PR TITLE
semaphore: add another option for CI

### PR DESCRIPTION
**Pull request by ricardotk**
This PR adds support for [SemaphoreCI](https://semaphoreci.com/) as another option for continuous integration.

You can [check the builds from my branch](https://semaphoreci.com/ricardotk/ardupilot).

### CODE REVIEW

**Comment by ricardotk** [comment]
@lucasdemarchi could you take a look?

**Comment by lucasdemarchi** [comment]
I added some comments above. Do you have a link to a semaphoreci build in your repo?

**Comment by lucasdemarchi** [comment]
It would be good to add in a comment here the configuration you put there

**Comment by lucasdemarchi** [comment]
> I added some comments above. Do you have a link to a semaphoreci build in your repo?

Just found it: https://semaphoreci.com/ricardotk/ardupilot/branches/semaphoreci/builds/24

**Comment by lucasdemarchi** [comment]
> This means we would stop using the container infra in Travis. Have you measured the build times? I think we could keep installing the packages the way we currently are.

So... This is current master:
https://travis-ci.org/diydrones/ardupilot/builds/103443335

This is your branch:
https://travis-ci.org/diydrones/ardupilot/builds/103410043

So same time.

**Comment by lucasdemarchi** [comment]
@ricardotk here's the reviewed branch: https://github.com/lucasdemarchi/ardupilot/commits/review/pr-3526

And here its current build:
https://semaphoreci.com/lucasdemarchi/ardupilot/branches/review-pr-3526/builds/3

**Comment by lucasdemarchi** [comment]
new build, now passing: https://semaphoreci.com/lucasdemarchi/ardupilot/branches/review-pr-3526/builds/5

**Comment by ricardotk** [comment]
> new build, now passing: https://semaphoreci.com/lucasdemarchi/ardupilot/branches/review-pr-3526/builds/5

Cool, this branch LGTM

**Comment by lucasdemarchi** [comment]
Applied. Thanks.

**Pull request closed without merging**
