### PR TITLE
Copter: don't accept disarm commands in stabilize and acro unless als…

### PR DESCRIPTION
**Pull request by jschall**
…o landed

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
What's the impetus for this?

**Comment by squilter** [comment]
We can probably remove the 21196 while we're at it.  We decided to use `	MAV_CMD_DO_FLIGHTTERMINATION` instead of 21196.

**Comment by jschall** [comment]
@R-Lefebvre, Solo controller used to send disarms in some cases. I think this is unneeded now with MAV_CMD_SOLO_BTN_PAUSE_CLICK, and like @squilter said, we have the flighttermination thing now if you really want to disarm while flying.

**Comment by rmackay9** [comment]
merged, thanks!
I haven't removed the 21196 thing.  I'm not against removing it although it then makes the disarm just like the kill switch.

**Pull request closed without merging**
