### PR TITLE
AP_InertialSensor: use rotate_inverse in calibrate_accel and _init_gyro

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by jschall** [comment]
Tested rotate_inverse, have not tested AP_InertialSensor changes.

**Comment by tridge** [comment]
looks good! Just needs a test suite in AP_Math/examples

**Comment by lucasdemarchi** [comment]
@jschall are you going to work on a test as @tridge requested?

**Comment by rmackay9** [comment]
@jschall, I'm going to close this 'cuz no response and I think your subsequent work on the accel calibrator that's in Solo means this won't go in.

**Pull request closed without merging**
