### PR TITLE
Adding RSSI to logging

### LINKED ISSUE #2021: RFE: log rxrsssi
Last I needed it for debugging, my pixhawk didn't log the value of rxrssi to sd. It was being shown on my OSD, but not saved for later review.
Assuming it hasn't been added recently
http://diydrones.com/forum/topics/is-rxrssi-not-being-logged-by-apm-at-all-1
could it be added in a future build?

Thanks.

### LINKED ISSUE #2245: enhancement: log rssi to TF/DataFlash
Please, consider logging of receiver RSSI. Possibly in the RCIN message...

### PR DESCRIPTION
**Pull request by StewLG**
Adding RSSI value to logging using new RSSI library.

Closes #2021. Closes  #2245. See also http://diydrones.com/forum/topics/is-rxrssi-not-being-logged-by-apm-at-all-1, and #2798, where @tridge asks for a log with rssi.

rssidemo

### CODE REVIEW

**Comment by rmackay9** [comment]
The RSSI is the signal strength of the RC input right?  Maybe we could just add it to the end of the RCIN message instead?

**Comment by magicrub** [comment]
RSSI is a bit vague too, needs a better label like RxRSSI. otherwise
there's no way of telling if it's GPS, 900/433MHz, video, or WiFi RSSI.

**Comment by StewLG** [comment]
> The RSSI is the signal strength of the RC input right? Maybe we could just add it to the end of the > RCIN message instead?

I tried it that way first, but when I tried something like this (in DataFlash.h, line 706);

    { LOG_RCIN_MSG, sizeof(log_RCIN), \
      "RCIN",  "Qhhhhhhhhhhhhhhf",     "TimeUS,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,rssi2;" }, \

I get an error 

        c:/Ardupilot-NewStewBuild/ardupilot/ArduPlane/Log.cpp:499:1: error: initializer-string for array of chars is too long [-fpermissive]
    compilation terminated due to -Wfatal-errors.

To get past it I'd believe I'd have to change sizes in 

    struct PACKED log_Format {
        LOG_PACKET_HEADER;
        uint8_t type;
        uint8_t length;
        char name[4];
        char format[16];
        char labels[64];
    };

Which looked suspiciously word aligned to me, so I opted for putting it in its own structure. 

> RSSI is a bit vague too, needs a better label like RxRSSI. otherwise there's no way of telling if it's 
> GPS, 900/433MHz, video, or WiFi RSSI.

Happy to call it "rxrssi" throughout. I'll make that change after I hear about what to do about the size issue for RCIN.

**Comment by magicrub** [comment]
Log->RCIN->RSSI (if it fits) is fine, but RxRSSI everywhere else would be
preferred.

**Comment by rmackay9** [comment]
@StewLG,
thanks for this by the way!
So the issue is actually the length of the field names in Dataflash.h (around line 706).  So we don't have enough space to add "rssi2".  you may find that it works ifyou make it really short like "RS" or even just "R".  We've had this issue in a number of messages like the IMU one where you'll see the final parameter is just "U".  I wanted to make it "Use" but it wouldn't fit.
Maybe you can check how many characters we can fit into RCIN?  It may be none in which case a new message is the only solution and what you've done is then fine!

**Comment by rmackay9** [comment]
If we think that we will put the RSSI values of all known links to the GCS in this message then maybe the field could be "RC" for radio control?  If we get the info from the 3DR radio in there we could have another field called "Telem" eventually.

**Comment by StewLG** [comment]
> Maybe you can check how many characters we can fit into RCIN? It may be none in which case a new 
> message is the only solution and what you've done is then fine!

This fails to compile:

    { LOG_RCIN_MSG, sizeof(log_RCIN), \
      "RCIN",  "Qhhhhhhhhhhhhhhf",     "TimeUS,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,R" }, \

So, I believe I cannot add a field to RCIN, period. 

> If we think that we will put the RSSI values of all known links to the GCS in this message then maybe the 
> field could be "RC" for radio control? If we get the info from the 3DR radio in there we could have another 
> field called "Telem" eventually.

I think I'm with Tom here that I'd be expecting rxrssi for the name so that it will line up with the rest of the UI, in particular the status panel:

rxrssi

I could have it go RXRSSI -> RXRSSI, but that forecloses this ever being expanded to other kinds of RSSI. So I prefer RSSI->RXRSSI, which is the original PR, as submitted.

**Comment by WickedShell** [comment]
You have to many fields being logged at once (more accurately you are
having a problem that your format descriptor is a catering and thus null
terminated and thus 17 characters long. Someone feel d free to correct me
if I'm wrong or if a macro is fixing it behind the scenes.

Also all the status stuff in mission planner simply requires it to be a
mavlink message in order to see it while flying. (Which I agree if feeding
worthwhile)

Maybe you can check how many characters we can fit into RCIN? It may be
none in which case a new
message is the only solution and what you've done is then fine!

This fails to compile:

{ LOG_RCIN_MSG, sizeof(log_RCIN), \
  "RCIN",  "Qhhhhhhhhhhhhhhf",
"TimeUS,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,R" }, \

So, I believe I cannot add a field to RCIN, period.

If we think that we will put the RSSI values of all known links to the GCS
in this message then maybe the
field could be "RC" for radio control? If we get the info from the 3DR
radio in there we could have another
field called "Telem" eventually.

I think I'm with Tom here that I'd be expecting rxrssi for the name so that
it will line up with the rest of the UI, in particular the status panel:

[image: rxrssi]
<https://cloud.githubusercontent.com/assets/7128339/9719673/7bb2b5cc-553b-11e5-87bc-c4860582085d.png>

I could have it go RXRSSI -> RXRSSI, but that forecloses this ever being
expanded to other kinds of RSSI. So I prefer RSSI->RXRSSI, which is the
original PR, as submitted.

—
Reply to this email directly or view it on GitHub
<https://github.com/diydrones/ardupilot/pull/2804#issuecomment-138326867>.

**Comment by StewLG** [comment]
I was hoping this PR would be uncontroversial and therefore a quick merge, but it seems to have stalled out. So I'm going to give it a nudge.

If I can summarize the conversation so far:

- There's no debate that logging RXRSSI is warranted.
- We agree the new logging won't fit in RCIN.
- There is some mild debate about exactly where it goes.

I would say that logging RXRSSI somewhere, even if we can't all agree it is the exact best and right place, would be better than the current situation of not logging it at all. 

If I can get a clear guidance and agreement about how to alter this PR to make it more acceptable I would be glad for it. Otherwise I'm hoping the original PR can be accepted as-is.

**Comment by rmackay9** [comment]
I'm going to test and then merge this to master, hopefully today

**Comment by rmackay9** [comment]
merged, thanks!

**Comment by StewLG** [comment]
Awesome. Thanks!

**Comment by Nik-Lz** [comment]
So this is RSSI on dataflash logging? Because i can't find it on my dataflash logs with my newly bought Quanum Nova Pro.. Do i need to update the software, or something?

**Comment by magicrub** [comment]
Yes, on df logs. New catagory called RSSI. What version is the Quanum Nova Pro running? Perhaps they forked before this was implemented?

**Comment by StewLG** [comment]
I'm not 100% sure about the Pro, but the Quanum Nova was 2.5.2 was Pre-ARM - Apm v2.5.2:

https://github.com/jlnaudin/x-VTOLdrone/wiki/Inside-the-Cheerson-CX-20-Auto-pathfinder-(or-called-the-Quanum-Nova)

This means that Magicrub is right - none of my RSSI stuff did made it into the final Arduino APM build. This still makes me sad, as there were (and obviously still are) a lot of APM 2.5.2 pilots out there.

**Comment by magicrub** [comment]
Stew, the program space was beyond full. If that was back ported, what would you have suggested we remove to make it fit?

**Comment by StewLG** [comment]
Oh, please don't take that as a serious criticism. I know APM was bursting at the seams. I was just hoping it would make it on the last train out of town is all. 

If I was seriously grouching, I would have made up a custom build that removed something else in its favor. I never did.

**Comment by magicrub** [comment]
>please don't take that as a serious criticism

Sorry, we get a lot of people asking "oh just add this, just add that" to the old system. Hard to tell serious vs not-so-serious grouching sometimes :)

**Pull request closed without merging**
