### PR TITLE
Added support for TeraRanger One sensor

### PR DESCRIPTION
**Pull request by lfrodrigues**
Added support for TeraRanger One ranging sensor (only for PX4)

### CODE REVIEW

**Comment by gmorph** [comment]
Thanks for the contribution.  There doesn't appear to be a proper probe routine for this device.  Is there a datasheet for the device?  We want to add a more robust probe process to more accurately check for this device in case another device is using address 0x30 - for example a WHOAMI register.  Be great if you could advise us on this or even implement the probe process.  Thanks!

**Comment by lfrodrigues** [comment]
I just implemented the driver code for PX4 copying from mb12xx and added the necessary bits into apm to support it. 

We didn't implement a WHOAMI register in our sensor firmware but we can easily do it. Which register/return value should we use? 

Would you be able to change directly PX4 source to add support for it or do I need to submit a pull request (last time it took a few months).

**Comment by tridge** [comment]
ahh, ok, you are the developer of the hardware as well as the device driver?
If you are the hardware developer then to add a WHOAMI register, just pick a register number and make it return a distinctive value. If you are not the hardware developer then just check the datasheet and see if there is a way to check more reliably if it really is the right device. We can accept the driver without that, but given it is always better to have a good probe() function as there are a lot more I2C devices in the world then there are addresses.
If you do a PR to diydrones/PX4Firmware we can get it included upstream.

**Comment by lfrodrigues** [comment]
Yes I did the driver and also the firmware for the sensor so I can change everything. Ok I'll make a PR to diydrones/PX4Firmware with the correct WHOAMI register.

**Comment by tridge** [comment]
I've pushed this into master now. It would be nice to fix the WHOAMI, but that can come later.
Do you have time to add the driver to our wiki? Adding it here would be nice:
http://plane.ardupilot.com/wiki/common-rangefinder-landingpage/
if you do have time then ping Craig Elder on skype and he can give you access
Thanks!

**Comment by lfrodrigues** [comment]
Yes I can update the wiki, how can I find Craig's contact?

**Comment by tridge** [comment]
email craig@3drobotics.com, or catch him on gitter https://gitter.im/diydrones/ardupilot
Thanks!

**Pull request closed without merging**
