### PR TITLE
AP_Mount: Fixed a bug with wrapping of panning angles.

### PR DESCRIPTION
**Pull request by gmorph**

### CODE REVIEW

**Comment by rmackay9** [comment]
merged!

**Comment by R-Lefebvre** [comment]
Grant, could you briefly explain what this bug did?

**Comment by gmorph** [comment]
I linked it to an issue the user had above.
The code needs to remember the angle that the panning servo is at as its just a dumb servo.  So an operator would move a joystick to the left to pan a bit, then the joystick would re-center leaving the servo at that angle.  Then the operator might pan a bit more in the same way.  So the code tracks what angle the servo is at.  However because we weren't constraining the angle the code would go to if the servo stopped at 45 degress the code would keep going so an operator might hold down left pan and the code would think the servo is at 120 degress for instance.  Then if the user panned in the other direction nothing would happen as the code would be panning back from 120, 119, 118, 117 but wouldn't be moving the servo until it got back to 45.  Make sense?

**Comment by R-Lefebvre** [comment]
Ok, thanks.  I saw the linked issue about RC7_Out stop working, but didn't realize it was being used for the pan, which was the real culprit, not just a random channel going dead.

I was wondering if the pan bug could cause other channels to go dead, but I guess not.

**Pull request closed without merging**
