### PR TITLE
fix issue #3074 No vehicle state after starting Vagrant SITL instance

### PR DESCRIPTION
**Pull request by derekxm**
Fix issue issue #3074. For some reason I have to do this to make SITL work in vagrant and my linux box. This fix undoes commit 596cac58d04749c7e5575342e08055cfdd30e26b made by @tridge.

### CODE REVIEW

**Comment by tridge** [comment]
this may break windows SITL I think
have you worked out why this change breaks vagrant SITL?

**Comment by derekxm** [comment]
I do not know why it breaks vagrant, seems the ArduCopter.elf does not run.

**Comment by lucasdemarchi** [comment]
I suggest adding `set -x` to the script to see why it's not working. For me it doesn't make much sense to have this wrapper script.

**Comment by lucasdemarchi** [comment]
Also, it's weird we are starting the commands and putting some of them in background and some of them we are running as foreground. I think all of them should actually replace the shell script with something like "exec $cmd".

**Comment by lucasdemarchi** [comment]
Fixed in #3325

**Pull request closed without merging**
